Repository hmcts/civil-citizen-ui, pull requests merged in 2022-06, with the labels that each got.

#491 Feature/civ 2517 financial details 1
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/common/utils/currencyFormat.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswersService.ts
  src/test/unit/services/features/response/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-491

#498 Refactor mockClaim so that functions added to claim class don't need …
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-498

#489 Civ 2504 claim summart part 2
  src/main/assets/scss/main.scss
  src/main/common/form/models/claimSummarySection.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/views/features/dashboard/claim-summary-content.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/response/repaymentPlan/repaymentPlanService.test.ts
  src/test/utils/mocks/civilClaimResponseApplicanIndividualMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-489

#494 Civ 2701 using expert small claims
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/expertGuidanceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/expert-guidance.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/directionsQuestionnaire/expertGuidanceController.test.ts
  src/test/unit/views/directionsQuestionnaire/expert-guidance.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-494

#499 Feature/civ 2518 financial details 2
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswersService.ts
  src/test/unit/services/features/response/checkAnswersService.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-499

#502 feature/CIV-2799/Part admit payment option
  src/main/common/form/models/admission/fullAdmission/paymentOption/paymentDate.ts
  src/main/common/form/models/admission/partialAdmission/paymentIntention.ts
  src/main/common/form/models/admission/paymentOption/paymentOption.ts
  src/main/common/form/models/admission/paymentOption/paymentOptionType.ts
  src/main/common/models/claim.ts
  src/main/common/models/partialAdmission.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/admission/fullAdmission/paymentOption/paymentOptionController.ts
  src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/admission/fullAdmission/paymentOption/paymentOptionService.ts
  src/main/services/features/response/admission/paymentOptionService.ts
  src/main/services/features/response/checkAnswersService.ts
  src/main/views/features/response/admission/payment-option.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/admission/paymentOption.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.test.ts
  src/test/unit/services/features/response/admission/fullAdmission/paymentOption/paymentOptionService.test.ts
  src/test/unit/services/features/response/admission/paymentOptionService.test.ts
  src/test/unit/services/features/response/checkAnswersService.test.ts
  src/test/unit/views/features/response/admission/payment-option.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseFullAdmissionMock.json
  src/test/utils/mocks/civilClaimResponseNoAdmittedPaymentAmountMock.json
  src/test/utils/mocks/civilClaimResponseWithAdmittedPaymentAmountMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-502

#514 Feature/civ 3012 dashboard model
  src/main/common/models/dashboard/dashboardItem.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-514

#515 Hide financial details on check answers if pay immediately is selected
  src/main/services/features/response/checkAnswersService.ts
  src/test/unit/services/features/response/checkAnswersService.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-515

#516 Civ 3042 fix translation with unexpected data
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/feeRange.ts
  src/main/routes/features/response/eligibility/sendYourResponseByEmailController.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/utils/mocks/feeRangesMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-516

#517 Check your answers - Financial details 3
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswersService.ts
  src/test/unit/services/features/response/checkAnswersService.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-517

#529 fix(vulnerabilities): add got to resolutions list
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-529

#534 Dependencies bump
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-534

#530 Fix CIV-3070 - Prevent paymentIntention from resetting partialAdmission
  src/main/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.ts
  src/test/unit/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-530

#541 fix translation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/main/views/features/response/statementOfMeans/otherDependants/other-dependants.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-541

#547 CIV-3120 add constant to point to claim store for civil_serfice image
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-547

#551 build(fix): add config for judicial ref data
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-551

#544 Techdebt - CIV-1530 - Accessibility tests
  package.json
  src/test/a11y/a11y.test.ts
  src/test/a11y/action-urls.ts
  src/test/a11y/dummy.test.ts
  src/test/a11y/ignored-urls.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-544

#526 add translations
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/response/admission/payment-date.njk
  src/main/views/features/response/statementOfMeans/are-you-severely-disabled.njk
  src/main/views/features/response/statementOfMeans/disability.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-526

#542 Civ 2700 dq support
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/supportRequired.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/views/features/directionsQuestionnaire/support-required.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/supportRequiredController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/otherDependants/severelyDisabledDefendantMock.json
  src/test/unit/services/features/directionsQuestionnaire/supportRequiredService.test.ts
  src/test/unit/views/directionsQuestionnaire/support-required.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-542

#533 Civ 809 task list part admit
  src/main/common/form/models/mediation/mediationIndividualPhoneNumber.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/checkAndSubmitYourResponse.ts
  src/main/common/utils/taskList/tasks/chooseAResponse.ts
  src/main/common/utils/taskList/tasks/confirmYourDetails.ts
  src/main/common/utils/taskList/tasks/decideHowYouPay.ts
  src/main/common/utils/taskList/tasks/freeTelephoneMediation.ts
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/common/utils/taskList/tasks/howMuchHaveYouPaid.ts
  src/main/common/utils/taskList/tasks/howMuchMoneyAdmitOwe.ts
  src/main/common/utils/taskList/tasks/repaymentPlan.ts
  src/main/common/utils/taskList/tasks/shareFinancialDetails.ts
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/common/utils/taskList/tasks/whenWillYouPay.ts
  src/main/common/utils/taskList/tasks/whyDisagreeWithAmountClaimed.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/routes/features/response/incompleteSubmissionController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/urls.ts
  src/main/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.ts
  src/main/services/features/response/taskListService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/common/utils/taskList/tasks/freeTelephoneMediation.test.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/common/utils/taskList/tasks/howMuchHaveYouPaid.test.ts
  src/test/unit/common/utils/taskList/tasks/howMuchMoneyAdmitOwe.test.ts
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/common/utils/taskList/tasks/whenWillYouPay.test.ts
  src/test/unit/common/utils/taskList/tasks/whyDisagreeWithAmountClaimed.test.ts
  src/test/unit/routes/features/mediation/mediationIndividualPhoneController.test.ts
  src/test/unit/routes/features/response/taskListController.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/unit/views/features/mediation/can-we-use.test.ts
  src/test/unit/views/features/response/task-list.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-533

#553 Fix: delete duplicate url
  src/main/routes/urls.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-553

#525 CIV-3057 fix incorrect mock data
  src/main/common/models/claim.ts
  src/main/modules/draft-store/redisData.json
  src/main/views/features/response/financialDetails/financial-details.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-525

#554 Dependencies bump
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-554

#543 Feature/CIV-2476/Download sealed claim
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/app/client/dmStoreClient.ts
  src/main/app/client/errorMessageContants.ts
  src/main/common/models/claim.ts
  src/main/common/models/document/caseDocument.ts
  src/main/common/models/document/document.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/document/systemGeneratedCaseDocuments.ts
  src/main/common/utils/documentTypeConverter.ts
  src/main/common/utils/downloadUtils.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/document/documentDownloadController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/dashboard/dashboard.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/documentTypeConverter.test.ts
  src/test/unit/routes/features/document/documentDownloadController.test.ts
  src/test/unit/views/features/response/claim-details.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/civilClaimResponseMock.json
  src/test/utils/mocks/civilClaimResponsePDFTimelineMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-543
