Repository hmcts/civil-citizen-ui, pull requests merged in 2022-01, with the labels that each got.

#91 Feature/i18n poc
  package.json
  sonar-project.properties
  src/integration-test/smoke-test.js
  src/main/app.ts
  src/main/modules/i18n/index.ts
  src/main/modules/i18n/locales/cy/translation.json
  src/main/modules/nunjucks/index.ts
  src/main/views/home.njk
  src/main/views/webpack/js.njk
  src/test/unit/modules/i18n/i18n.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-91

#94 Feature/civ 694 adjust dashboard UI to call civil api
  docker-compose.yml
  package.json
  src/main/app.ts
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claim.ts
  src/main/common/utils/currencyFormat.ts
  src/main/modules/health/index.ts
  src/main/modules/i18n/locales/cy/translation.json
  src/main/routes/features/dashboard/index.ts
  src/main/routes/home.ts
  src/main/routes/routes.ts
  src/main/views/features/dashboard/dashboard.njk
  src/main/views/template.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/modules/i18n/i18n.test.ts
  src/test/unit/routes/home.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-94

#104 Fix vulnerabilities
  .gitignore
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-104

#97 Add codecept config for functional and crossbrowser tests
  Jenkinsfile_nightly
  README.md
  package.json
  src/main/app.ts
  src/test/config.ts
  src/test/cross-browser/codecept.conf.js
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/features/homepage.feature
  src/test/e2e/pages/homepage.ts
  src/test/e2e/step_definitions/steps.ts
  src/test/functional/codecept.conf.js
  src/test/functional/codecept.conf.ts
  src/test/functional/features/homepage.feature
  src/test/tsconfig.json
  src/test/types/steps.d.ts
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-97

#109 Refactor/switch config format to yaml
  Dockerfile
  README.md
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.json
  config/custom-environment-variables.yaml
  config/default.json
  config/default.yaml
  config/dev.json
  config/dev.yaml
  config/production.json
  config/production.yaml
  config/test.json
  config/test.yaml
  docker-compose.yml
  src/main/app.ts
  src/main/routes/features/dashboard/index.ts
  src/main/server.ts
  src/test/e2e/pages/homepage.ts
  src/test/unit/routes/home.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-109

#110 Moving all dependabot version upgrades into one pr
  .eslintrc.js
  package.json
  src/main/modules/nunjucks/index.ts
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-110

#108 Feature/civ 807 view claim screen v2
  bin/init.sh
  nodemon.json
  src/main/app.ts
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claim.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/img/favicon.ico
  src/main/routes/features/response/index.ts
  src/main/routes/routes.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/error.njk
  src/main/views/features/response/claim-details.njk
  src/main/views/home.njk
  src/main/views/not-found.njk
  src/main/views/template.njk
  src/test/a11y/a11y.ts
  src/test/unit/features/response/routes/claim-details.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-108
