Repository hmcts/civil-citizen-ui, pull requests merged in 2022-09, with the labels that each got.

#786 CIV-4335 - FIX - Partial Admission Repayment Amount
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/services/features/response/repaymentPlan/repaymentPlanService.ts
  src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/services/features/response/repaymentPlan/repaymentPlanService.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-786

#785 bugfix/CVI-4447/language toggle
  src/main/assets/js/language-toggle.js
  src/main/views/claim-details-tpl.njk
  src/test/unit/views/features/public/eligibility/help-with-fees-reference.test.ts
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
  src/test/unit/views/features/response/dashboard/claim-summary.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-785

#808 CIV-260: Respond to money claim - Enter claim number
  src/main/common/form/validators/claimReferenceValidator.ts
  src/main/common/models/firstContact/claimReference.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/claimReferenceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/firstContact/claim-reference.njk
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
  src/test/unit/views/features/public/firstContact/claim-reference.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-808

#809 CIV-262 - Feature - Claim Details Summary
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/macro/evidence-summary.njk
  src/main/views/macro/timeline-summary.njk
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/views/features/public/firstContact/claim-summary.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-809

#806 CIV-4407 Not authorised to view the claim
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/accessDeniedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/firstContact/access-denied.njk
  src/test/unit/routes/features/public/firstContact/accessDeniedController.test.ts
  src/test/unit/views/features/public/firstContact/access-denied.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-806

#811 Dependencies bump
  package.json
  src/main/common/form/models/bankAndSavings/bankAccount.ts
  src/main/common/form/models/statementOfMeans/courtOrders/courtOrder.ts
  src/main/common/form/models/statementOfMeans/debts/debtItems.ts
  src/main/common/form/models/timeLineOfEvents/timelineRow.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-811

#822 Civ 4567 transform response to ccd
  Jenkinsfile_CNP
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccdResponse/ccdPayBySetDate.ts
  src/main/common/models/ccdResponse/ccdPaymentOption.ts
  src/main/common/models/ccdResponse/ccdRepaymentPlan.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/models/events/eventDto.ts
  src/main/routes/features/response/checkAnswersController.ts
  src/main/routes/features/response/responseDeadline/responseDeadlineOptionsController.ts
  src/main/routes/guards/deadLineGuard.ts
  src/main/services/features/response/submission/submitResponse.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/ccdResponse/ccdPaymentOption.test.ts
  src/test/unit/common/models/ccdResponse/ccdRepaymentPlan.test.ts
  src/test/unit/routes/features/response/checkAnswersController.test.ts
  src/test/unit/services/features/response/responseDeadlineService.test.ts
  src/test/unit/services/features/response/submission/submitReponse.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-822

#810 Feature/civ 259 respond to moneyclaim
  src/main/assets/scss/main.scss
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/signpostingController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/external-urls.njk
  src/main/views/features/public/firstContact/signposting.njk
  src/test/unit/routes/features/public/firstContact/signpostingController.test.ts
  src/test/unit/views/features/public/firstContact/signposting.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-810

#821 Civ 261 security code
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/firstContact/pin.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/claimReferenceController.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/firstContact/pin.njk
  src/main/views/macro/error-summary.njk
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
  src/test/unit/views/features/public/firstContact/pin.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-821

#812 feature/CIV-2676/response submission FA pay immediately
  src/main/common/models/claim.ts
  src/main/common/models/claimResponseStatus.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/pinController.ts
  src/main/routes/features/response/submitComfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/fullDefenceConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationService.ts
  src/main/views/external-urls.njk
  src/main/views/features/dashboard/item-content.njk
  src/main/views/features/response/submit-confirmation.njk
  src/main/views/macro/contact-us-for-help.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/unit/views/features/response/submit-confirmation.test.ts
  src/test/utils/externalURLs.ts
  src/test/utils/mocks/civilClaimResponseFullAdmissionMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-812

#823 CIV-4219 Get the details right
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/completingClaimController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/completing-claim.njk
  src/test/unit/routes/features/claim/completingClaimController.test.ts
  src/test/unit/views/features/claim/completing-claim.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-823

#838 Build(deps): bump ioredis from 4.28.5 to 5.1.0
  package.json
  src/main/modules/draft-store/index.ts
  src/main/modules/health/index.ts
  src/main/routes/features/directionsQuestionnaire/vulnerabilityController.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-838

#824 CIV-4209 | add new resolve dispute screen and related urls and tests
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/resolvingThisDisputeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/resolving-this-dispute.njk
  src/test/unit/routes/features/claim/resolvingThisDisputeController.test.ts
  src/test/unit/views/features/claim/resolving-this-dispute.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-824

#840 Hotfix - Refactor test to work with cookie banner
  src/test/unit/views/features/claim/resolving-this-dispute.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-840

#839 bugfixes/CIV-3438-welsh-translations
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-839

#827 Feature/civ 4220 about you and claim
  src/main/common/form/models/claim/claimantPartyTypeSelection.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/claim/claimantPartyTypeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/claim/claimant-party-type.njk
  src/test/unit/routes/features/public/claim/claimantPartyTypeController.test.ts
  src/test/unit/views/features/public/claim/claimant-party-type.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-827

#837 CIV-3787, 3786, 3766 - You can use this service screens
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/determinationWithoutHearingController.ts
  src/main/routes/features/public/eligibility/applyForHelpWithFeesController.ts
  src/main/routes/features/public/eligibility/claimantOver18EligibilityController.ts
  src/main/routes/features/public/eligibility/eligibleController.ts
  src/main/routes/features/public/eligibility/helpWithFeesReferenceController.ts
  src/main/routes/features/public/eligibility/someUsefulInfoFeesController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/eligibility/eligibleService.ts
  src/main/views/external-urls.njk
  src/main/views/features/public/eligibility/apply-for-help-with-fees.njk
  src/main/views/features/public/eligibility/eligible.njk
  src/main/views/features/public/eligibility/help-with-fees-reference.njk
  src/test/unit/routes/features/public/eligibility/applyForHelpWithFeesController.test.ts
  src/test/unit/routes/features/public/eligibility/claimantOver18EligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/eligibleController.test.ts
  src/test/unit/routes/features/public/eligibility/helpWithFeesReferenceController.test.ts
  src/test/unit/routes/features/public/eligibility/someUsefulInfoFeesController.test.ts
  src/test/unit/views/features/public/eligibility/apply-for-help-with-fees.test.ts
  src/test/unit/views/features/public/eligibility/eligible.test.ts
  src/test/unit/views/features/public/eligibility/help-with-fees-reference.test.ts
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-837

#829 feature/CIV-3816-cookie-preferences-page
  src/main/common/form/models/cookies.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/public/cookiesController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/external-urls.njk
  src/main/views/features/public/cookies/cookies-content.njk
  src/main/views/features/public/cookies/cookies-view.njk
  src/test/unit/routes/features/public/cookiesController.test.ts
  src/test/unit/views/features/public/cookies-view.test.ts
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-829

#842 tech-debts/CIV-3856-test-with-dynamic-dates
  src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/utils/dateUtils.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-842

#841 CIV-4290 -TechDebt - GenericYesNo Model Refactor
  src/main/common/form/models/admission/partialAdmission/alreadyPaid.ts
  src/main/common/form/models/genericYesNo.ts
  src/main/common/form/models/mediation/freeMediation.ts
  src/main/common/form/models/statementOfMeans/carer.ts
  src/main/common/form/models/statementOfMeans/debts/debtItems.ts
  src/main/common/form/models/statementOfMeans/debts/debts.ts
  src/main/common/form/models/statementOfMeans/dependants/childrenDisability.ts
  src/main/common/form/models/statementOfMeans/partner/cohabiting.ts
  src/main/common/form/models/statementOfMeans/partner/partnerAge.ts
  src/main/common/form/models/statementOfMeans/partner/partnerDisability.ts
  src/main/common/form/models/statementOfMeans/partner/partnerPension.ts
  src/main/common/form/models/statementOfMeans/partner/partnerSevereDisability.ts
  src/main/common/form/models/statementOfMeans/severeDisability.ts
  src/main/common/models/mediation/mediation.ts
  src/main/common/models/partialAdmission.ts
  src/main/common/models/statementOfMeans.ts
  src/main/routes/features/mediation/companyTelephoneNumberController.ts
  src/main/routes/features/mediation/mediationDisagreementController.ts
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/routes/features/response/admission/partialAdmission/alreadyPaidController.ts
  src/main/routes/features/response/statementOfMeans/carerController.ts
  src/main/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/severeDisabilityController.ts
  src/main/services/features/response/admission/partialAdmission/partialAdmissionService.ts
  src/main/services/features/response/statementOfMeans/carerService.ts
  src/main/services/features/response/statementOfMeans/dependants/childrenDisabilityService.ts
  src/main/services/features/response/statementOfMeans/partner/cohabitingService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerAgeService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerDisabilityService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerPensionService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerSevereDisabilityService.ts
  src/main/services/features/response/statementOfMeans/severeDisabilityService.ts
  src/test/unit/common/form/models/partner.test.ts
  src/test/unit/common/form/models/statementOfMeans/carer.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
  src/test/unit/services/features/response/statementOfMeans/carerService.test.ts
  src/test/unit/services/features/response/statementOfMeans/dependants/childrenDisabilityService.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/unit/views/features/public/eligibility/claim-against-government.test.ts
  src/test/unit/views/features/public/eligibility/claimant-address-eligibility.test.ts
  src/test/unit/views/features/public/eligibility/defendant-address-eligibility.test.ts
  src/test/unit/views/features/public/eligibility/help-with-fees-eligibility.test.ts
  src/test/unit/views/features/public/eligibility/help-with-fees-reference.test.ts
  src/test/unit/views/features/public/eligibility/over-18.test.ts
  src/test/unit/views/features/public/eligibility/single-defendant.test.ts
  src/test/unit/views/features/public/eligibility/some-useful-info-fees.test.ts
  src/test/unit/views/features/public/eligibility/tenancy-deposit.test.ts
  src/test/unit/views/features/response/admission/partialAdmission/already-paid.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-841

#835 Civ 3737 initiate response event
  Jenkinsfile_CNP
  bin/variables/load-preview-environment-variables.sh
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-835

#843 CIV-4810 - TechDebt - Change respond days to 28
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-843

#761 CIV-4308: Welsh Translations 15
  src/main/common/form/models/mediation/mediationIndividualPhoneNumber.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/routes/features/response/requestMoreTimeController.ts
  src/main/views/features/mediation/can-we-use.njk
  src/main/views/features/mediation/mediation-disagreement.njk
  src/test/unit/routes/features/response/statementOfMeans/residenceController.test.ts
  src/test/unit/views/features/mediation/can-we-use.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-761

#849 changing the service url to http
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-849

#846 CIV-4658 - Features - DQ - Tried to Settle the Claim
  src/main/common/form/models/genericYesNo.ts
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/triedToSettleController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/triedToSettleService.ts
  src/main/views/features/directionsQuestionnaire/tried-to-settle-claim.njk
  src/test/unit/routes/features/directionsQuestionnaire/triedToSettleController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/triedToSettleService.test.ts
  src/test/unit/views/directionsQuestionnaire/tried-to-settle-claim.test.ts
  src/test/unit/views/features/public/eligibility/defendant-age-eligibility.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-846

#848 Civ 3737 initiate response event
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claim.ts
  src/main/common/models/responseDeadline.ts
  src/main/common/utils/taskList/tasks/viewOptionsBeforeDeadline.ts
  src/main/routes/features/response/responseDeadline/agreedResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/newResponseDeadlineController.ts
  src/main/routes/guards/deadLineGuard.ts
  src/main/services/features/response/responseDeadline/extendResponseDeadlineService.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/response/responseDeadline/newResponseDeadlineController.test.ts
  src/test/unit/routes/guards/deadLineGuard.test.ts
  src/test/unit/services/features/response/responseDeadline/extendResponseDeadlineService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-848

#857 CIV-4662: DQ - Consider claimant documents (Re-create)
  src/main/common/models/directionsQuestionnaire/considerClaimantDocuments.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/considerClaimantDocumentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/considerClaimantDocumentsService.ts
  src/main/views/features/directionsQuestionnaire/consider-claimant-documents.njk
  src/test/unit/routes/features/directionsQuestionnaire/considerClaimantDocumentsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/considerClaimantDocumentService.test.ts
  src/test/unit/views/directionsQuestionnaire/consider-claimant-documents.test.ts
  src/test/unit/views/directionsQuestionnaire/request-extra-4weeks.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-857

#863 Civ 4664 dq evidence yourself
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/defendant-yourself-evidence.njk
  src/test/unit/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/views/directionsQuestionnaire/defendant-yourself-evidence.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-863

#861 CIV-4717 - TechDebt - Change Navigation Path
  src/main/routes/features/directionsQuestionnaire/determinationWithoutHearingController.ts
  src/main/routes/features/directionsQuestionnaire/triedToSettleController.ts
  src/test/unit/routes/features/directionsQuestionnaire/determinationWithoutHearingController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/triedToSettleController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-861

#862 Civ 4754 dq expert can still examine
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/expertCanStillExamine.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/expertCanStillExamineController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/defendant-expert-can-still-examine.njk
  src/test/unit/routes/features/directionsQuestionnaire/expertCanStillExamineController.test.ts
  src/test/unit/views/directionsQuestionnaire/defendant-expert-can-still-examine.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-862

#855 CIV-4749 - Features - Permission For Expert
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/permissionForExpertController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/permissionForExpertService.ts
  src/main/views/features/directionsQuestionnaire/permission-for-expert.njk
  src/test/unit/routes/features/directionsQuestionnaire/permissionForExpertController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/permissionForExpertService.test.ts
  src/test/unit/views/directionsQuestionnaire/permission-for-expert.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-855

#864 CIV-4901 - Bugfix - Company Details Welsh Translations
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-864

#860 Features/civ 4523 response submission reject and paid
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/rejectClaimConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-860

#866 Feature/civ 2432 claim summary more time requested
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-866

#873 CIV-4974 - add robotics recipient for spec secret
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-873

#850 Civ 4488 response submission pa not paid
  sonar-project.properties
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-850

#858 CIV-4742: Defendant Response - DQ - Small Claims - Using an expert
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/considerClaimantDocumentsController.ts
  src/main/routes/features/directionsQuestionnaire/defendantExpertEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/expertCanStillExamineController.ts
  src/main/routes/features/directionsQuestionnaire/expertSmallClaimsController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/expert-small-claims.njk
  src/test/unit/routes/features/directionsQuestionnaire/considerClaimantDocumentsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/defendantExpertEvidenceController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/expertCanStillExamineController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/expertSmallClaimsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/requestExtra4WeeksController.test.ts
  src/test/unit/views/directionsQuestionnaire/consider-claimant-documents.test.ts
  src/test/unit/views/directionsQuestionnaire/defendant-yourself-evidence.test.ts
  src/test/unit/views/directionsQuestionnaire/expert-small-claims.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-858

#872 CIV-4398 - TechDebt - Deprecated Form
  src/main/common/form/models/form.ts
  src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
  src/main/common/form/validators/formValidator.ts
  src/main/routes/features/mediation/mediationDisagreementController.ts
  src/main/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.ts
  src/main/views/features/mediation/mediation-disagreement.njk
  src/main/views/features/response/statementOfMeans/dependants/children-disability.njk
  src/test/unit/common/form/models/form.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-872

#868 CIV-5005 - TechDebt - DQ Services Refactor
  src/main/common/form/models/directionQuestionnaireErrorMessages.ts
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/routes/features/directionsQuestionnaire/defendantExpertEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/determinationWithoutHearingController.ts
  src/main/routes/features/directionsQuestionnaire/expertCanStillExamineController.ts
  src/main/routes/features/directionsQuestionnaire/expertGuidanceController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/features/directionsQuestionnaire/sharedExpertController.ts
  src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
  src/main/routes/features/directionsQuestionnaire/triedToSettleController.ts
  src/main/routes/features/directionsQuestionnaire/vulnerabilityController.ts
  src/main/services/features/directionsQuestionnaire/determinationWithoutHearingService.ts
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
  src/main/services/features/directionsQuestionnaire/requestExtra4WeeksService.ts
  src/main/services/features/directionsQuestionnaire/sharedExpertService.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/services/features/directionsQuestionnaire/triedToSettleService.ts
  src/main/services/features/directionsQuestionnaire/vulnerabilityService.ts
  src/main/views/features/directionsQuestionnaire/defendant-expert-can-still-examine.njk
  src/main/views/features/directionsQuestionnaire/determination-without-hearing.njk
  src/main/views/features/directionsQuestionnaire/expert-guidance.njk
  src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
  src/main/views/features/directionsQuestionnaire/tried-to-settle-claim.njk
  src/main/views/features/directionsQuestionnaire/vulnerability.njk
  src/test/unit/services/features/directionsQuestionnaire/determinationWithoutHearingService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/requestExtra4WeeksService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/sharedExpertService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/supportRequiredService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/triedToSettleService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/vulnerabilityService.test.ts
  src/test/unit/services/features/response/yourDefenceService.test.ts
  src/test/unit/views/directionsQuestionnaire/vulnerability.test.ts
  src/test/unit/views/features/response/submit-confirmation.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-868

#845 Features/civ 4522 response submission part admit paid
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-845

#869 Nested ternaries refactored
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/test/unit/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.test.ts
  src/test/unit/views/features/response/submit-confirmation.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-869

#874 CIV-4489: Response Submission - Dispute
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/fullDefenceConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/unit/views/features/response/submit-confirmation.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-874

#877 features/CIV-4746-expert report details
  src/main/common/form/validators/validationConstraints.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/experts/expertReportDetails/expertReportDetails.ts
  src/main/common/models/directionsQuestionnaire/experts/expertReportDetails/reportDetail.ts
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/expertReportDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/expertReportDetailsService.ts
  src/main/views/features/directionsQuestionnaire/expert-report-details.njk
  src/main/views/macro/report-detail.njk
  src/test/unit/routes/features/directionsQuestionnaire/expertReportDetailsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/views/directionsQuestionnaire/expert-report-details.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-877

#887 Update: add new roles
  bin/add-roles.sh
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-887

#883 CIV-5062 - TechDebt - Accessibility Tests
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/admission/partialAdmission/how-much-do-you-owe.njk
  src/main/views/features/response/admission/payment-date.njk
  src/main/views/features/response/citizenDob/citizen-dob.njk
  src/main/views/features/response/citizenPhoneNumber/citizen-phone.njk
  src/main/views/features/response/statementOfMeans/courtOrders/court-order.njk
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/features/response/statementOfMeans/employment/who-employs-you.njk
  src/main/views/features/response/timelineOfEvents/defendant-timeline.njk
  src/main/views/macro/employer.njk
  src/main/views/macro/timeline-row.njk
  src/test/a11y/ignored-urls.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-883

#871 Feat/civ 4225
  src/main/assets/js/postcode-lookup.js
  src/main/common/form/models/citizenAddress.ts
  src/main/common/form/models/citizenCorrespondenceAddress.ts
  src/main/common/form/models/partyDetails.ts
  src/main/common/models/claim.ts
  src/main/common/models/correspondenceAddress.ts
  src/main/common/models/primaryAddress.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/claimantIndividualDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/claimantDetailsService.ts
  src/main/views/features/claim/claimant-individual-details.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/macro/address.njk
  src/test/unit/routes/features/claim/claimantIndividualDetailsController.test.ts
  src/test/unit/services/features/claim/claimantDetailsService.test.ts
  src/test/unit/views/features/claim/claimant-individual-details.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-871

#894 fix ccd definition import on preview
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-894

#844 CIV-4571: Contact details change LR email notification
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/services/translation/response/ccdTranslation.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-844

#885 Features/civ 4668 dq other witnesses
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/witnesses/otherWitnessItems.ts
  src/main/common/models/directionsQuestionnaire/witnesses/otherWitnesses.ts
  src/main/common/models/directionsQuestionnaire/witnesses/witnesses.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/otherWitnessesController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/otherWitnesses/other-witness.njk
  src/main/views/features/directionsQuestionnaire/otherWitnesses/other-witnesses.njk
  src/test/unit/routes/features/directionsQuestionnaire/otherWitnessesController.test.ts
  src/test/unit/views/directionsQuestionnaire/other-witnesses.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-885
