Repository hmcts/civil-citizen-ui, pull requests merged in 2022-10, with the labels that each got.

#893 Civ 4667 dq enter expert details
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/experts/expertDetails.ts
  src/main/common/models/directionsQuestionnaire/experts/expertDetailsList.ts
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/experts/expertDetailsController.ts
  src/main/routes/routes.ts
  src/main/services/features/directionsQuestionnaire/expertDetailsService.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-details.njk
  src/main/views/macro/expert-details-row.njk
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertDetailsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/experts/expertDetailsService.test.ts
  src/test/unit/views/directionsQuestionnaire/experts/expert-details.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-893

#813 Cui functional tests
  .gitignore
  Jenkinsfile_CNP
  package.json
  src/integration-test/smoke-test.ts
  src/test/config.ts
  src/test/cross-browser/codecept.conf.ts
  src/test/cross-browser/features/homepage.feature
  src/test/e2e/pages/homepage.ts
  src/test/e2e/pages/phonenumber.ts
  src/test/e2e/step_definitions/steps.ts
  src/test/functional/codecept.conf.js
  src/test/functional/codecept.conf.ts
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/codecept.conf.ts
  src/test/functionalTests/features/dashboard/pages/dashboard.ts
  src/test/functionalTests/features/dashboard/steps/dashboard.ts
  src/test/functionalTests/features/home/pages/login.ts
  src/test/functionalTests/features/home/steps/login.ts
  src/test/functionalTests/features/response/pages/bankAccountsDetails.ts
  src/test/functionalTests/features/response/pages/carerDetails.ts
  src/test/functionalTests/features/response/pages/checkYourAnswers.ts
  src/test/functionalTests/features/response/pages/courtOrders.ts
  src/test/functionalTests/features/response/pages/dateToPayOn.ts
  src/test/functionalTests/features/response/pages/debts.ts
  src/test/functionalTests/features/response/pages/dependantDetails.ts
  src/test/functionalTests/features/response/pages/disabilityDetails.ts
  src/test/functionalTests/features/response/pages/employerDetails.ts
  src/test/functionalTests/features/response/pages/employment.ts
  src/test/functionalTests/features/response/pages/enterContactNumberDetails.ts
  src/test/functionalTests/features/response/pages/enterDateOfBirthDetails.ts
  src/test/functionalTests/features/response/pages/enterNameAndAddressDetails.ts
  src/test/functionalTests/features/response/pages/explanation.ts
  src/test/functionalTests/features/response/pages/monthlyExpenses.ts
  src/test/functionalTests/features/response/pages/monthlyIncome.ts
  src/test/functionalTests/features/response/pages/otherDependantDetails.ts
  src/test/functionalTests/features/response/pages/partAdmitAlreadyPaid.ts
  src/test/functionalTests/features/response/pages/partnerAgeDetails.ts
  src/test/functionalTests/features/response/pages/partnerDetails.ts
  src/test/functionalTests/features/response/pages/partnerDisabilityDetails.ts
  src/test/functionalTests/features/response/pages/partnerPensionDetails.ts
  src/test/functionalTests/features/response/pages/paymentOption.ts
  src/test/functionalTests/features/response/pages/priorityDebtsDetails.ts
  src/test/functionalTests/features/response/pages/rejectAllOfClaim.ts
  src/test/functionalTests/features/response/pages/repaymentPlan.ts
  src/test/functionalTests/features/response/pages/residenceDetails.ts
  src/test/functionalTests/features/response/pages/respondType.ts
  src/test/functionalTests/features/response/pages/selfEmploymentDetails.ts
  src/test/functionalTests/features/response/pages/selfEmploymentTaxDetails.ts
  src/test/functionalTests/features/response/pages/severeDisabilityDetails.ts
  src/test/functionalTests/features/response/pages/shareYouFinancialDetailsIntro.ts
  src/test/functionalTests/features/response/pages/taskList.ts
  src/test/functionalTests/features/response/steps/commonSteps.ts
  src/test/functionalTests/features/response/steps/prepareYourResponseSteps.ts
  src/test/functionalTests/tests/dashboard_tests.ts
  src/test/functionalTests/tests/response_admitAll_tests.ts
  src/test/functionalTests/tests/response_partAdmit_tests.ts
  src/test/functionalTests/tests/response_rejectAll_tests.ts
  src/test/types/steps.d.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-813

#920 disabled both smoke and functional tests
  package.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-920

#891 Civ 5074 add new generic services to dq
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/experts/expertCanStillExamine.ts
  src/main/common/models/directionsQuestionnaire/experts/expertReportDetails/expertReportDetails.ts
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/common/models/directionsQuestionnaire/experts/sentExpertReports.ts
  src/main/common/models/directionsQuestionnaire/hearing/considerClaimantDocuments.ts
  src/main/common/models/directionsQuestionnaire/hearing/determinationWithoutHearing.ts
  src/main/common/models/directionsQuestionnaire/hearing/hearing.ts
  src/main/common/models/directionsQuestionnaire/vulnerabilityQuestions/vulnerability.ts
  src/main/common/models/directionsQuestionnaire/vulnerabilityQuestions/vulnerabilityQuestions.ts
  src/main/routes/features/directionsQuestionnaire/considerClaimantDocumentsController.ts
  src/main/routes/features/directionsQuestionnaire/defendantExpertEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/determinationWithoutHearingController.ts
  src/main/routes/features/directionsQuestionnaire/expertCanStillExamineController.ts
  src/main/routes/features/directionsQuestionnaire/expertReportDetailsController.ts
  src/main/routes/features/directionsQuestionnaire/otherWitnessesController.ts
  src/main/routes/features/directionsQuestionnaire/permissionForExpertController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/features/directionsQuestionnaire/sentExpertReportsController.ts
  src/main/routes/features/directionsQuestionnaire/sharedExpertController.ts
  src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
  src/main/routes/features/directionsQuestionnaire/triedToSettleController.ts
  src/main/routes/features/directionsQuestionnaire/vulnerabilityController.ts
  src/main/services/features/directionsQuestionnaire/considerClaimantDocumentsService.ts
  src/main/services/features/directionsQuestionnaire/determinationWithoutHearingService.ts
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
  src/main/services/features/directionsQuestionnaire/expertReportDetailsService.ts
  src/main/services/features/directionsQuestionnaire/otherWitnessesService.ts
  src/main/services/features/directionsQuestionnaire/permissionForExpertService.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/services/features/directionsQuestionnaire/vulnerabilityService.ts
  src/main/views/features/directionsQuestionnaire/determination-without-hearing.njk
  src/main/views/features/directionsQuestionnaire/expert-report-details.njk
  src/main/views/features/directionsQuestionnaire/vulnerability.njk
  src/test/unit/routes/features/directionsQuestionnaire/determinationWithoutHearingController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/expertReportDetailsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/otherWitnessesController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/vulnerabilityController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/considerClaimantDocumentService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/determinationWithoutHearingService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/permissionForExpertService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/supportRequiredService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/vulnerabilityService.test.ts
  src/test/unit/views/directionsQuestionnaire/determination-without-hearing.test.ts
  src/test/unit/views/directionsQuestionnaire/expert-report-details.test.ts
  src/test/unit/views/directionsQuestionnaire/vulnerability.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-891

#889 tech-debts/CIV-4773-response-submit-date
  src/main/common/models/claim.ts
  src/main/common/utils/dateUtils.ts
  src/main/routes/features/response/submitComfirmationController.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/views/features/response/submit-confirmation.njk
  src/test/a11y/a11y.test.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/views/features/response/submit-confirmation.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-889

#886 CIV-4690: DQ - Do you want to ask for a telephone or video hearing
  src/main/common/models/directionsQuestionnaire/hearing/hearing.ts
  src/main/common/models/directionsQuestionnaire/hearing/phoneOrVideoHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/phoneOrVideoHearingController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/phone-or-video-hearing.njk
  src/test/unit/routes/features/directionsQuestionnaire/phoneOrVideoHearingController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/views/directionsQuestionnaire/phone-or-video-hearing.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-886

#890 CIV-4226 - Feature - Claimant Date of Birth
  src/main/common/form/models/claim/claimantDoB.ts
  src/main/common/form/models/evidence/evidenceItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/claim/claimantDoBController.ts
  src/main/routes/features/response/citizenDob/citizenDobController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/citizenDob/citizen-dob.njk
  src/test/unit/routes/features/public/claim/claimantDoBController.test.ts
  src/test/unit/views/features/public/claim/claimant-dob.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-890

#923 Dependencies bump
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-923

#880 CIV-4599: Defendant Response - Claimant LR email notifications
  src/main/common/form/models/yesNo.ts
  src/main/common/models/ccdResponse/ccdAgreedMediation.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/test/unit/common/models/ccdResponse/ccdAgreedMediation.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-880

#931 Remove cmc-s2s-secret secret
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
Labels: enableHelm

#921 CIV-4683: Defendant Response - DQ - Why are you, your experts or witnesses unavailable for a hearing for <<xx>> days?
  src/main/common/models/directionsQuestionnaire/hearing/hearing.ts
  src/main/common/models/directionsQuestionnaire/hearing/whyUnavailableForHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/whyUnavailableForHearingService.ts
  src/main/views/features/directionsQuestionnaire/why-unavailable-for-hearing.njk
  src/test/unit/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.test.ts
  src/test/unit/views/directionsQuestionnaire/why-unavailable-for-hearing.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-921

#916 CIV-4229 Enter a phone number (optional)
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/claim/claimantPhoneController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/claimantPhoneService.ts
  src/main/views/features/public/claim/claimant-phone.njk
  src/test/unit/routes/features/claim/claimantPhoneController.test.ts
  src/test/unit/services/features/public/claim/claimantPhoneService.test.ts
  src/test/unit/views/features/public/claim/claimant-phone.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-916

#934 Removing duplicate testing step
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  jest.a11y.config.js
  jest.config.js
  src/main/routes/features/claim/completingClaimController.ts
  src/main/routes/features/claim/resolvingThisDisputeController.ts
  src/main/views/features/claim/claimant-individual-details.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-934

#942 Temporarily removing coverage and accessibility tests in master
  package.json
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-942

#922 new next 12 month can not hearing screen
  src/main/common/form/models/directionQuestionnaireErrorMessages.ts
  src/main/common/models/directionsQuestionnaire/hearing/hearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/cantAttendHearingInNext12MonthsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/cant-Attend-Hearing-In-Next-12Months.njk
  src/test/unit/routes/features/directionsQuestionnaire/cantAttendHearingInNext12MonthsController.test.ts
  src/test/unit/views/directionsQuestionnaire/cant-Attend-Hearing-In-Next-12Months.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-922

#919 Civ 4716 dq welsh language
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/languageOptions.ts
  src/main/common/models/directionsQuestionnaire/welshLanguageRequirements/language.ts
  src/main/common/models/directionsQuestionnaire/welshLanguageRequirements/welshLanguageRequirements.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/directionsQuestionnaire/welshLanguageController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/welsh-language.njk
  src/test/unit/routes/features/directionsQuestionnaire/welshLanguageController.test.ts
  src/test/unit/views/directionsQuestionnaire/welsh-language.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-919

#947 adding a bot to close stale PRs
  .github/workflows/stale.yml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-947

#953 Civ 4321 claim amount
  src/main/common/form/models/claim/amount/amountBreakdown.ts
  src/main/common/form/models/claim/amount/claimAmountRow.ts
  src/main/common/form/models/claim/claimant/claimantDoB.ts
  src/main/common/form/models/claim/claimant/claimantPartyTypeSelection.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/amount/claimAmountBreakdownController.ts
  src/main/routes/features/public/claim/claimantDoBController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/amount/claimAmountBreakdownService.ts
  src/main/views/features/claim/amount/claim-amount-breakdown.njk
  src/main/views/macro/claim-amount.njk
  src/test/unit/routes/features/claim/amount/claimAmountBreakdownController.test.ts
  src/test/unit/services/features/claim/amount/claimAmountBreakdownService.test.ts
  src/test/unit/views/features/claim/amount/claim-amount-breakdown.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-953

#949 features/CIV-4322-claim-interest-page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/interest/claimInterestController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/interest/claimInterestService.ts
  src/main/views/features/claim/help-with-interest-rates.njk
  src/main/views/features/claim/interest/claim-interest.njk
  src/test/unit/routes/features/claim/interest/claimInterestController.test.ts
  src/test/unit/services/features/claim/interest/claimInterestService.test.ts
  src/test/unit/views/features/claim/interest/claim-interest.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-949

#950 Civ 4899 modified address
  compose/draft-store.yml
  config/default.yaml
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/services/features/response/submission/compareAddress.ts
  src/main/services/features/response/submission/submitResponse.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/test/unit/services/features/response/submission/compareAddress.test.ts
  src/test/unit/services/features/response/submission/submitReponse.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-950

#954 Civ 4336 date claim interest from
  src/main/common/form/models/interest/interest.ts
  src/main/common/form/models/interest/interestStartDate.ts
  src/main/common/form/validators/validationConstraints.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/interest/claimInterestController.ts
  src/main/routes/features/claim/interest/interestStartDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/interest/interestService.ts
  src/main/views/features/claim/interest/interest-start-date.njk
  src/test/unit/routes/features/claim/interest/claimInterestController.test.ts
  src/test/unit/routes/features/claim/interest/interestStartDateController.test.ts
  src/test/unit/services/features/claim/interest/interestService.test.ts
  src/test/unit/views/features/claim/interest/claim-interest.test.ts
  src/test/unit/views/features/claim/interest/interest-start-date.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-954

#956 CIV-4323: How do you want to claim interest?
  compose/draft-store.yml
  src/main/common/form/models/claim/interest/interestClaimOption.ts
  src/main/common/form/models/claim/interest/interestClaimOptionsType.ts
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claim/claimantDoBController.ts
  src/main/routes/features/claim/claimantPartyTypeController.ts
  src/main/routes/features/claim/claimantPhoneController.ts
  src/main/routes/features/claim/defendantPartyTypeController.ts
  src/main/routes/features/claim/interest/claimInterestController.ts
  src/main/routes/features/claim/interest/interestTypeController.ts
  src/main/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/interest/interestTypeService.ts
  src/main/views/features/claim/claimant-party-type.njk
  src/main/views/features/claim/claimant-phone.njk
  src/main/views/features/claim/defendant-party-type.njk
  src/main/views/features/claim/interest/interest-type.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/interestUtils.test.ts
  src/test/unit/routes/features/claim/claimantDoBController.test.ts
  src/test/unit/routes/features/claim/claimantPartyTypeController.test.ts
  src/test/unit/routes/features/claim/defendantPartyTypeController.test.ts
  src/test/unit/routes/features/claim/interest/claimInterestController.test.ts
  src/test/unit/routes/features/claim/interest/interestTypeController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/whyUnavailableForHearingController.test.ts
  src/test/unit/services/features/claim/claimantPhoneService.test.ts
  src/test/unit/services/features/claim/interest/interestTypeService.test.ts
  src/test/unit/views/directionsQuestionnaire/why-unavailable-for-hearing.test.ts
  src/test/unit/views/features/claim/claimant-dob.test.ts
  src/test/unit/views/features/claim/claimant-party-type.test.ts
  src/test/unit/views/features/claim/claimant-phone.test.ts
  src/test/unit/views/features/claim/defendant-party-type.test.ts
  src/test/unit/views/features/claim/interest-type.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-956

#964 Dependencies bump
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-964

#937 CIV-4320 - Features - Their Details (Organisation)
  src/main/common/form/models/address.ts
  src/main/common/form/models/companyOrOrganisationPartyDetails.ts
  src/main/common/form/validators/postcodeValidator.ts
  src/main/common/models/claim.ts
  src/main/common/models/primaryAddress.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/claimantIndividualDetailsController.ts
  src/main/routes/features/claim/defendant/defendantDetailsController.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/claimantDetailsService.ts
  src/main/services/features/claim/claimantOrDefendantTypeService.ts
  src/main/services/features/claim/defendantDetailsService.ts
  src/main/services/features/claim/partyTypeService.ts
  src/main/services/features/response/citizenDetails/citizenDetailsService.ts
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
  src/test/unit/routes/features/claim/claimantIndividualDetailsController.test.ts
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/routes/features/claim/defendantPartyTypeController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/views/features/claim/claimant-individual-details.test.ts
  src/test/unit/views/features/claim/defendant/defendant-details-company-or-organisation.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockForm.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-937

#932 CIV-4288: Their email address (optional)
  src/main/common/form/models/claim/yourDetails/defendantEmail.ts
  src/main/common/models/respondent.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/yourDetails/defendantEmailController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/yourDetails/defendantEmailService.ts
  src/main/views/features/claim/yourDetails/defendant-email.njk
  src/test/unit/routes/features/claim/defendantEmailController.test.ts
  src/test/unit/services/features/claim/defendantEmailService.test.ts
  src/test/unit/views/features/public/claim/defendant-email.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-932

#967 Hotfix - Correct url
  src/main/routes/urls.ts
  src/main/services/features/claim/partyTypeService.ts
  src/test/unit/routes/features/claim/claimantIndividualDetailsController.test.ts
  src/test/unit/routes/features/claim/claimantPartyTypeController.test.ts
  src/test/unit/views/features/claim/claimant-individual-details.test.ts
Labels: enableHelm, fullDeploy

#961 CIV-4300 - Features - Their details (Company)
  package.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/defendant/defendantDetailsController.ts
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-961

#979 Civ 5292 pip api
  src/main/app/client/civilServiceClient.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-979

#977 CIV-5108 | add continue claiming interest page and tests
  src/main/common/form/models/interest/interest.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/interest/continueClaimingInterestController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/interest/continue-claiming-interest.njk
  src/test/unit/routes/features/claim/interest/continueClaimingInterestController.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-977

#968 CIV-4283: Your details - Company page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/yourDetails/claimantOrganisationDetailsController.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/yourDetails/claimant-organisation-details.njk
  src/test/unit/routes/features/claim/yourDetails/claimantOrganisationDetailsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-968

#970 Features/civ 5038 calculate total
  sonar-project.properties
  src/main/assets/js/append-row.js
  src/main/assets/js/calculate-amount.js
  src/main/assets/js/calculate-total-amount.js
  src/main/common/form/models/claim/amount/amountBreakdown.ts
  src/main/common/form/validators/validationConstraints.ts
  src/main/index.js
  src/main/routes/features/claim/amount/claimAmountBreakdownController.ts
  src/main/views/features/claim/amount/claim-amount-breakdown.njk
  src/main/views/macro/claim-amount.njk
  src/test/unit/routes/features/claim/amount/claimAmountBreakdownController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-970

#985 Stale Branches: Action to delete stale branches
  .github/workflows/stale-branches.yml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-985

#987 CIV-4393: Briefly explain your claim
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/common/form/models/claim/details/reason.ts
  src/main/common/models/claim.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/utilityService.ts
  src/main/routes/features/claim/details/reasonController.ts
  src/main/routes/features/claim/interest/interestStartDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/details/claimDetailsService.ts
  src/main/services/features/claim/interest/interestService.ts
  src/main/views/features/claim/details/reason.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/main/views/features/response/your-defence.njk
  src/test/unit/routes/features/claim/details/reasonController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/routes/features/response/financial-details/claimIndividualMock.json
  src/test/unit/routes/features/response/financial-details/claimIndividualMockNoType.json
  src/test/unit/routes/features/response/financial-details/claimOrganisationMock.json
  src/test/unit/services/features/claim/details/claimDetailsService.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/civilClaimResponseExpertAndWitnessMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
  src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-987

#976 bugfix/CIV-5149/save-other-witnesses
  src/main/routes/features/directionsQuestionnaire/experts/expertDetailsController.ts
  src/main/routes/features/directionsQuestionnaire/witnesses/otherWitnessesController.ts
  src/main/services/features/directionsQuestionnaire/expertDetailsService.ts
  src/main/services/features/directionsQuestionnaire/otherWitnessesService.ts
  src/main/views/features/directionsQuestionnaire/support-required-list.njk
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/experts/expertDetailsService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/otherWitnessesService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-976

#981 CIV-4338: When do you want to stop claiming interest?
  src/main/common/form/models/claimDetails.ts
  src/main/common/form/models/interest/interest.ts
  src/main/common/form/models/interest/interestEndDate.ts
  src/main/common/models/claim.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claim/interest/interestEndDateController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/interest/interestService.ts
  src/main/views/features/claim/interest/interest-end-date.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/claim/interest/interestEndDateController.test.ts
  src/test/unit/services/features/claim/interest/interestService.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/civilClaimResponseExpertAndWitnessMock.json
  src/test/utils/mocks/civilClaimResponseFullAdmissionMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
  src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-981

#990 CIV-4394 - Features - Claim Timeline
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/common/form/models/timeLineOfEvents/claimantTimeline.ts
  src/main/common/models/claim.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/yourDetails/timelineController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/yourDetails/timelineService.ts
  src/main/views/features/claim/yourDetails/timeline.njk
  src/test/unit/routes/features/claim/yourDetails/timelineController.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-990

#1001 CIV-2809 - Bugfix - Set API key
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/default.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1001

#991 Tech debt/civ 5040 regular expenses missing translations
  src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
  src/main/common/utils/priorityDebts/priorityDebtsConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/financialSection/answers/addMonthlyExpenses.ts
  src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
  src/test/unit/routes/features/response/statementOfMeans/expenses/regularExpensesController.test.ts
  src/test/unit/services/features/response/checkAnswers/financialDetails/addMonthlyExpenses.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-991

#1005 New: add minimatch to resolutions
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1005

#1003 Civ 4346 help with fees reference
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/common/form/models/claim/details/helpWithFees.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/details/helpWithFeesController.ts
  src/main/routes/features/public/eligibility/helpWithFeesReferenceEligibilityController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/details/help-with-fees.njk
  src/test/unit/routes/features/claim/details/helpWithFeesController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1003

#1000 Feat/civ 4343 | How much do you want to continue claiming?
  src/main/common/form/models/interest/howMuchContinueClaiming.ts
  src/main/common/form/models/interest/interest.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/interest/howMuchContinueClaimingController.ts
  src/main/routes/routes.ts
  src/main/views/features/claim/interest/how-much-continue-claiming.njk
  src/test/unit/routes/features/claim/interest/howMuchContinueClaimingController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1000

#1010 CIV-5043 | add missing welsh translations and set key value pairs
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/reject-all-of-claim.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1010

#1009 features/CIV-5144-defendant details
  src/main/assets/js/postcode-lookup.js
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/party.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
  src/main/services/features/claim/yourDetails/claimantAndDefendantPhoneService.ts
  src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/main/services/features/response/citizenDetails/citizenDetailsService.ts
  src/main/services/features/response/mediation/companyTelephoneNumberService.ts
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/macro/citizen-telephone.njk
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/services/features/claim/claimantAndDefendantPhoneService.test.ts
  src/test/unit/services/features/claim/defendantEmailService.test.ts
  src/test/unit/services/features/response/citizenDetails/citizenDetailsService.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mockForm.ts
  src/test/utils/mocks/civilClaimResponseFullAdmissionMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
  src/test/utils/mocks/civilClaimResponseUnemploymentOtherMock.json
  src/test/utils/mocks/civilClaimResponseUnemploymentRetiredMock.json
  src/test/utils/mocks/civilClaimResponseWithAdmittedPaymentAmountMock.json
  src/test/utils/mocks/noRespondentTelephoneMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1009

#1002 techdebts/CIV-5192-refactor-claim-details
  src/main/routes/features/claim/yourDetails/claimantDoBController.ts
  src/main/routes/features/claim/yourDetails/claimantPartyTypeController.ts
  src/main/services/features/claim/yourDetails/claimantDetailsService.ts
  src/test/unit/routes/features/claim/claimantPartyTypeController.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1002

#1007 DefectFix : CIV-5350: addDaysTranslated Nunjucks function not working.
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/test/unit/modules/nunjucks/filters/dateFilter.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1007

#1012 CIV-5455 - Bug Fix - Save individual and sole trader details
  src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
  src/main/services/features/claim/yourDetails/claimantDetailsService.ts
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1012

#1008 techdebts/CIV-5289-refactor-party-type
  src/main/routes/features/claim/defendant/defendantDetailsController.ts
  src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
  src/main/services/features/claim/claimantOrDefendantTypeService.ts
  src/main/services/features/claim/yourDetails/claimantDetailsService.ts
  src/main/services/features/claim/yourDetails/defendantDetailsService.ts
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/routes/features/claim/defendantPartyTypeController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantOrganisationDetailsController.test.ts
  src/test/unit/services/features/claim/yourDetails/claimantDetailsService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1008

#1016 CIV-5021 remove whitespace from time
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1016

#1015 CIV-4281: Confirm your details - Navigation
  src/main/modules/draft-store/redisData.json
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/citizenDob/citizenDobController.ts
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/routes/features/response/citizenDob/citizenDobController.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseRespondentIndividualWithPhoneNumberMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1015

#1018 Tech debt/civ 5110 defendant response postcode lookup
  src/main/assets/js/postcode-lookup.js
  src/main/common/form/models/address.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
  src/main/views/features/claim/yourDetails/claimant-organisation-details.njk
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/macro/postcode-address-form.njk
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1018

#1025 CIV-5483 - Tech debt - Common Translations
  src/main/common/form/models/statementOfMeans/employment/employer.ts
  src/main/common/utils/priorityDebts/priorityDebtsConstants.ts
  src/main/common/utils/taskList/tasks/confirmYourDetails.ts
  src/main/common/utils/taskList/tasks/freeTelephoneMediation.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addBankAccounts.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addCarer.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addCourtOrders.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addDependants.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addDisability.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addEmploymentDetails.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addLoansOrCreditCardDebts.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addMonthlyExpenses.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addMonthlyIncome.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addOtherDependants.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addPartner.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addPriorityDebts.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addResidence.ts
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponsePaymentSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseToClaimSection.ts
  src/main/views/features/claim/yourDetails/claimant-organisation-details.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/dashboard/dashboard.njk
  src/main/views/features/directionsQuestionnaire/experts/sent-expert-reports.njk
  src/main/views/features/mediation/free-telephone-mediation.njk
  src/main/views/features/public/eligibility/defendant-age.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/main/views/features/response/eligibility/send-your-response-by-email.njk
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/main/views/features/response/responseDeadline/agreed-response-deadline.njk
  src/main/views/features/response/statementOfMeans/are-you-severely-disabled.njk
  src/main/views/features/response/statementOfMeans/citizenBankAndSavings/citizen-bank-accounts.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
  src/main/views/features/response/statementOfMeans/explanation.njk
  src/main/views/features/response/timelineOfEvents/defendant-timeline.njk
  src/main/views/macro/contact-us-for-help.njk
  src/main/views/macro/employer.njk
  src/main/views/macro/evidence-summary.njk
  src/main/views/macro/evidence.njk
  src/main/views/macro/report-detail.njk
  src/main/views/macro/statement-of-truth.njk
  src/main/views/macro/timeline-row.njk
  src/main/views/macro/timeline-summary.njk
  src/main/views/macro/transaction-details.njk
  src/test/unit/common/utils/taskList/tasks/freeTelephoneMediation.test.ts
  src/test/unit/services/features/response/checkAnswers/financialDetails/addPriorityDebts.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/utils/checkAnswersConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1025

#1021 CIV-5252: Welsh Translations 18
  src/main/common/models/directionsQuestionnaire/hearing/determinationWithoutHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/directionsQuestionnaire/experts/defendant-expert-evidence.njk
  src/main/views/features/directionsQuestionnaire/hearing/determination-without-hearing.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1021

#1019 CIV-5254: Welsh UI Translations 20
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/directionsQuestionnaire/experts/expert-report-details.njk
  src/main/views/features/directionsQuestionnaire/experts/shared-expert.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1019

#1020 Refactor translation t function
  src/main/app.ts
  src/main/modules/nunjucks/index.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1020

#1034 CIV-5249: CUI Welsh UI Translations 17
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/directionsQuestionnaire/consider-claimant-documents.njk
  src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witness.njk
  src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1034
