Repository hmcts/civil-citizen-ui, pull requests merged in 2022-07, with the labels that each got.

#583 Fix the PRs
  Jenkinsfile_CNP
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-583

#580 Dependencies bump
  .gitignore
  package-lock.json
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-580

#582 Civ 2988 welsh translation error messages
  src/main/modules/i18n/locales/cy.json
  src/main/modules/nunjucks/index.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-582

#591 hotfix(vulnerability): add moment to transitive resolution list
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-591

#594 Civ 2747 claimant case data
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/views/features/response/dashboard/dashboard.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/claimantClaimsMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-594

#575 Civ 3071 why do you disagree reject all
  src/main/common/form/models/rejectAllOfClaim.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/admission/fullRejection/howMuchHaveYouPaidController.ts
  src/main/routes/features/response/admission/fullRejection/whyDoYouDisagreeFullRejectionController.ts
  src/main/routes/features/response/admission/fullRejection/youHavePaidLessController.ts
  src/main/routes/features/response/admission/partialAdmission/whyDoYouDisagreeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/admission/partialAdmission/whyDoYouDisagreeService.ts
  src/main/services/features/response/admission/whyDoYouDisagreeService.ts
  src/main/views/features/directionsQuestionnaire/expert-guidance.njk
  src/main/views/features/response/admission/fullRejection/you-have-paid-less.njk
  src/main/views/features/response/admission/why-do-you-disagree.njk
  src/test/unit/routes/features/response/admission/fullRejection/whyDoYouDisagreeControllerFullRejection.test.ts
  src/test/unit/services/features/response/admission/partialAdmission/whyDoYouDisagreeService.test.ts
  src/test/unit/services/features/response/admission/whyDoYouDisagreeService.test.ts
  src/test/unit/views/features/response/admission/fullRejection/you-have-paid-less.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-575

#556 Civ 3011 client for claims against you
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
  src/test/utils/mocks/defendantClaimsMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-556

#597 Civ 2908 check your answers part 3
  src/main/common/form/models/yesNo.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/mediation/companyTelephoneNumberController.ts
  src/main/routes/features/mediation/mediationDisagreementController.ts
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/views/features/mediation/can-we-use.njk
  src/main/views/macro/telephone.njk
  src/test/unit/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.test.ts
  src/test/utils/checkAnswersConstants.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-597

#600 Tech debt - CIV-2607 Missing Mediation View Unit Tests
  src/main/views/features/mediation/mediation-disagreement.njk
  src/test/unit/views/features/mediation/i-dont-want-free-mediation.test.ts
  src/test/unit/views/features/mediation/mediation-disagreement.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-600

#599 Civ 2824 client to submit event
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/models/events/eventDto.ts
  src/main/routes/features/response/checkAnswersController.ts
  src/test/unit/app/client/civilServiceClient.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-599

#555 Citizen UI add function tests
  .gitignore
  Jenkinsfile_CNP
  package.json
  src/test/config.ts
  src/test/e2e/pages/homepage.ts
  src/test/e2e/pages/phonenumber.ts
  src/test/e2e/step_definitions/steps.ts
  src/test/functional/codecept.conf.ts
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/codecept.conf.ts
  src/test/functionalTests/features/dashboard/pages/dashboard.ts
  src/test/functionalTests/features/dashboard/steps/dashboard.ts
  src/test/functionalTests/features/home/pages/login.ts
  src/test/functionalTests/features/home/steps/login.ts
  src/test/functionalTests/features/response/pages/bankAccountsDetails.ts
  src/test/functionalTests/features/response/pages/carerDetails.ts
  src/test/functionalTests/features/response/pages/checkYourAnswers.ts
  src/test/functionalTests/features/response/pages/courtOrders.ts
  src/test/functionalTests/features/response/pages/dateToPayOn.ts
  src/test/functionalTests/features/response/pages/debts.ts
  src/test/functionalTests/features/response/pages/dependantDetails.ts
  src/test/functionalTests/features/response/pages/disabilityDetails.ts
  src/test/functionalTests/features/response/pages/employerDetails.ts
  src/test/functionalTests/features/response/pages/employment.ts
  src/test/functionalTests/features/response/pages/enterContactNumberDetails.ts
  src/test/functionalTests/features/response/pages/enterDateOfBirthDetails.ts
  src/test/functionalTests/features/response/pages/enterNameAndAddressDetails.ts
  src/test/functionalTests/features/response/pages/explanation.ts
  src/test/functionalTests/features/response/pages/monthlyExpenses.ts
  src/test/functionalTests/features/response/pages/monthlyIncome.ts
  src/test/functionalTests/features/response/pages/otherDependantDetails.ts
  src/test/functionalTests/features/response/pages/partAdmitAlreadyPaid.ts
  src/test/functionalTests/features/response/pages/partnerAgeDetails.ts
  src/test/functionalTests/features/response/pages/partnerDetails.ts
  src/test/functionalTests/features/response/pages/partnerDisabilityDetails.ts
  src/test/functionalTests/features/response/pages/partnerPensionDetails.ts
  src/test/functionalTests/features/response/pages/paymentOption.ts
  src/test/functionalTests/features/response/pages/priorityDebtsDetails.ts
  src/test/functionalTests/features/response/pages/rejectAllOfClaim.ts
  src/test/functionalTests/features/response/pages/repaymentPlan.ts
  src/test/functionalTests/features/response/pages/residenceDetails.ts
  src/test/functionalTests/features/response/pages/respondType.ts
  src/test/functionalTests/features/response/pages/selfEmploymentDetails.ts
  src/test/functionalTests/features/response/pages/selfEmploymentTaxDetails.ts
  src/test/functionalTests/features/response/pages/severeDisabilityDetails.ts
  src/test/functionalTests/features/response/pages/shareYouFinancialDetailsIntro.ts
  src/test/functionalTests/features/response/pages/taskList.ts
  src/test/functionalTests/features/response/steps/commonSteps.ts
  src/test/functionalTests/features/response/steps/prepareYourResponseSteps.ts
  src/test/functionalTests/tests/dashboard_tests.ts
  src/test/functionalTests/tests/response_admitAll_tests.ts
  src/test/functionalTests/tests/response_partAdmit_tests.ts
  src/test/functionalTests/tests/response_rejectAll_tests.ts
  src/test/types/steps.d.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-555

#606 Revert "Citizen UI add function tests"
  .gitignore
  Jenkinsfile_CNP
  package.json
  src/test/config.ts
  src/test/e2e/pages/homepage.ts
  src/test/e2e/pages/phonenumber.ts
  src/test/e2e/step_definitions/steps.ts
  src/test/functional/codecept.conf.js
  src/test/functional/codecept.conf.ts
  src/test/functionalTests/codecept.conf.ts
  src/test/functionalTests/features/dashboard/pages/dashboard.ts
  src/test/functionalTests/features/dashboard/steps/dashboard.ts
  src/test/functionalTests/features/home/pages/login.ts
  src/test/functionalTests/features/home/steps/login.ts
  src/test/functionalTests/features/response/pages/bankAccountsDetails.ts
  src/test/functionalTests/features/response/pages/carerDetails.ts
  src/test/functionalTests/features/response/pages/checkYourAnswers.ts
  src/test/functionalTests/features/response/pages/courtOrders.ts
  src/test/functionalTests/features/response/pages/dateToPayOn.ts
  src/test/functionalTests/features/response/pages/debts.ts
  src/test/functionalTests/features/response/pages/dependantDetails.ts
  src/test/functionalTests/features/response/pages/disabilityDetails.ts
  src/test/functionalTests/features/response/pages/employerDetails.ts
  src/test/functionalTests/features/response/pages/employment.ts
  src/test/functionalTests/features/response/pages/enterContactNumberDetails.ts
  src/test/functionalTests/features/response/pages/enterDateOfBirthDetails.ts
  src/test/functionalTests/features/response/pages/enterNameAndAddressDetails.ts
  src/test/functionalTests/features/response/pages/explanation.ts
  src/test/functionalTests/features/response/pages/monthlyExpenses.ts
  src/test/functionalTests/features/response/pages/monthlyIncome.ts
  src/test/functionalTests/features/response/pages/otherDependantDetails.ts
  src/test/functionalTests/features/response/pages/partAdmitAlreadyPaid.ts
  src/test/functionalTests/features/response/pages/partnerAgeDetails.ts
  src/test/functionalTests/features/response/pages/partnerDetails.ts
  src/test/functionalTests/features/response/pages/partnerDisabilityDetails.ts
  src/test/functionalTests/features/response/pages/partnerPensionDetails.ts
  src/test/functionalTests/features/response/pages/paymentOption.ts
  src/test/functionalTests/features/response/pages/priorityDebtsDetails.ts
  src/test/functionalTests/features/response/pages/rejectAllOfClaim.ts
  src/test/functionalTests/features/response/pages/repaymentPlan.ts
  src/test/functionalTests/features/response/pages/residenceDetails.ts
  src/test/functionalTests/features/response/pages/respondType.ts
  src/test/functionalTests/features/response/pages/selfEmploymentDetails.ts
  src/test/functionalTests/features/response/pages/selfEmploymentTaxDetails.ts
  src/test/functionalTests/features/response/pages/severeDisabilityDetails.ts
  src/test/functionalTests/features/response/pages/shareYouFinancialDetailsIntro.ts
  src/test/functionalTests/features/response/pages/taskList.ts
  src/test/functionalTests/features/response/steps/commonSteps.ts
  src/test/functionalTests/features/response/steps/prepareYourResponseSteps.ts
  src/test/functionalTests/tests/dashboard_tests.ts
  src/test/functionalTests/tests/response_admitAll_tests.ts
  src/test/functionalTests/tests/response_partAdmit_tests.ts
  src/test/functionalTests/tests/response_rejectAll_tests.ts
  src/test/types/steps.d.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-606

#611 TechDebt - CIV-3453 - Remove NumberOfDays
  src/main/common/form/models/numberOfDays.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-611

#612 Civ 3376 enable elastic search in preview
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-612

#614 Civ 3376 enable elastic search in preview
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-614

#615 build(vulnerability fix): add glob-parent to resolutions
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-615

#603 CIV-915 - Response Deadline Options
  src/main/common/form/models/responseDeadline.ts
  src/main/common/models/claim.ts
  src/main/common/models/responseDeadline.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/needMoreTime.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/responseDeadlineOptionsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/responseDeadlineService.ts
  src/main/views/features/response/response-deadline-options.njk
  src/test/unit/routes/features/response/responseDeadlineOptionsController.test.ts
  src/test/unit/services/features/response/responseDeadlineService.test.ts
  src/test/unit/views/features/response/response-deadline-options.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-603

#609 Switch from Wiremock instance to actual legacy draft store instance
  config/default.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-609

#608 feature/CIV-3436/Include case state to case data
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/test/a11y/a11y.test.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/views/features/response/dashboard/claim-summary.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-608

#618 Tech Debt - CIV-2784 - Refactor getClaimantName function
  src/main/routes/features/response/admission/fullRejection/youHavePaidLessController.ts
  src/main/routes/features/response/rejectAllOfClaimController.ts
  src/main/routes/features/response/yourDefenceController.ts
  src/main/services/features/response/rejectAllOfClaimService.ts
  src/test/unit/routes/features/response/rejectAllOfClaimController.test.ts
  src/test/unit/routes/features/response/yourDefenceController.test.ts
  src/test/unit/services/features/response/rejectAllOfClaimService.test.ts
  src/test/utils/mocks/civilClaimResponseUnemploymentRetiredMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-618

#619 TechDebt - CIV-1277 - Error Summary Macro
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/features/response/citizenResponseType/citizen-response-type.njk
  src/main/views/features/response/response-deadline-options.njk
  src/main/views/features/response/statementOfMeans/citizenBankAndSavings/citizen-bank-accounts.njk
  src/main/views/macro/error-summary.njk
  src/main/views/question-template.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-619

#620 Civ 3570
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/routes/features/response/checkAnswersController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/guards/allResponseTasksCompletedGuard.ts
  src/main/services/features/response/taskListService.ts
  src/test/unit/routes/guards/allResponseTasksCompleteGuard.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-620

#616 Civ 3067 task list reject
  src/main/common/models/claim.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/common/utils/taskList/tasks/tellUsHowMuchYouHavePaid.ts
  src/main/common/utils/taskList/tasks/tellUsWhyDisagreeWithClaim.ts
  src/main/common/utils/taskList/tasks/whyDisagreeWithAmountClaimed.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/evidence/evidenceController.ts
  src/main/routes/urls.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/common/utils/taskList/tasks/tellUsHowMuchYouHavePaid.test.ts
  src/test/unit/common/utils/taskList/tasks/tellUsWhyDisagreeWithClaim.test.ts
  src/test/unit/common/utils/taskList/tasks/whyDisagreeWithAmountClaimed.test.ts
  src/test/unit/routes/features/response/evidence/evidenceController.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-616

#605 add repayment plan for partAdmission
  src/main/common/form/models/repaymentPlan/repaymentPlanForm.ts
  src/main/common/models/claim.ts
  src/main/common/utils/taskList/tasks/repaymentPlan.ts
  src/main/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/repaymentPlan/repaymentPlanController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponsePaymentSection.ts
  src/main/services/features/response/repaymentPlan/repaymentPlanService.ts
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/services/features/response/repaymentPlan/repaymentPlanService.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/unit/views/features/response/repaymentPlan/repaymentPlan.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-605

#610 CIV-3118 - Request More Time
  src/main/common/form/models/additionalTime.ts
  src/main/common/form/models/responseDeadline.ts
  src/main/common/models/responseDeadline.ts
  src/main/common/utils/taskList/tasks/needMoreTime.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/requestMoreTimeController.ts
  src/main/routes/routes.ts
  src/main/services/features/response/responseDeadlineService.ts
  src/main/views/features/response/request-more-time.njk
  src/test/unit/routes/features/response/requestMoreTimeController.test.ts
  src/test/unit/services/features/response/responseDeadlineService.test.ts
  src/test/unit/views/features/response/request-more-time.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-610

#604 Civ 2749 translate dashboard data and display
  src/main/app/client/legacyDraftStoreClient.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/common/models/legacyDraftClaim/draftClaim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/app/client/legacyDraftStoreClient.test.ts
  src/test/unit/common/models/legacyDraftClaim/draftClaim.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
  src/test/utils/mocks/ocmcDraftDataMock.json
Labels: enhancement, ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-604

#624 Feature/civ 3305 reject and paid part 1
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseToClaimSection.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseToClaimSection.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-624

#626 feature/CIV-1343/Agreed response deadline
  src/main/common/form/models/agreedResponseDeadline.ts
  src/main/common/form/validators/dateNotBeforeReferenceDate.ts
  src/main/common/form/validators/dateNotMoreThanDurationValidator.ts
  src/main/common/models/responseDeadline.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/responseDeadline/agreedResponseDeadlineController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/responseDeadlineService.ts
  src/main/views/features/response/responseDeadline/agreed-response-deadline.njk
  src/test/unit/routes/features/response/responseDeadline/agreedResponseDeadlineController.test.ts
  src/test/unit/services/features/response/responseDeadlineService.test.ts
  src/test/unit/views/features/response/responseDeadline/agreed-response-deadline.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-626

#634 Vulnerability Fix - @widio/sauce-service Transitive Dependency
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-634

#632 Feature/civ 3379 part admit no paid part 2
  src/main/common/models/claim.ts
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponsePaymentSection.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponsePaymentSection.test.ts
  src/test/utils/checkAnswersConstants.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-632

#622 Civ 916 deadline extension page
  config/default.yaml
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/responseDeadline/newResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/responseDeadlineOptionsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/test/a11y/a11y.test.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/response/responseDeadline/newResponseDeadlineController.test.ts
  src/test/unit/views/features/response/responseDeadline/new-response-deadline.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-622

#621 Civ 3596 refactor how much do you owe
  src/main/common/form/models/admission/partialAdmission/howMuchDoYouOwe.ts
  src/main/routes/features/response/admission/partialAdmission/howMuchDoYouOweController.ts
  src/main/services/features/response/admission/partialAdmission/howMuchDoYouOweService.ts
  src/main/views/features/response/admission/partialAdmission/how-much-do-you-owe.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-621

#640 feature/CIV-3714/Update validation for agreed response dead line
  src/main/common/form/models/agreedResponseDeadline.ts
  src/main/common/form/validators/optionalDateInPastValidator.ts
  src/main/common/utils/dateConverter.ts
  src/main/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/services/features/response/repaymentPlan/repaymentPlanService.ts
  src/test/unit/common/utils/dateConverter.test.ts
  src/test/unit/services/features/response/admission/partialAdmission/howMuchHaveYouPaidService.test.ts
  src/test/unit/services/features/response/repaymentPlan/repaymentPlanService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-640

#631 Civ 3304 check your answers part4
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponsePaymentSection.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseToClaimSection.test.ts
  src/test/utils/checkAnswersConstants.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-631

#639 update add roles script
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-639

#636 Civ 2694 download claim
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claim.ts
  src/main/common/utils/documentSizeDisplayFormatter.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/test/unit/common/utils/documentDisplaySizeFormatter.test.ts
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-636

#643 adding new access-profile GS_profile into add-roles.sh
  bin/add-roles.sh
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-643

#625 Civ 3416 bug confirm your details task list
  src/main/common/models/respondent.ts
  src/main/common/utils/taskList/tasks/confirmYourDetails.ts
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/services/features/response/citizenDetails/citizenDetailsService.ts
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/services/features/response/citizenDetails/citizenDetailsService.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-625

#629 CIV-3417 - Bank account error
  src/main/common/form/models/bankAndSavings/bankAccount.ts
  src/main/common/form/models/bankAndSavings/bankAccounts.ts
  src/main/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.ts
  src/main/views/features/response/statementOfMeans/citizenBankAndSavings/citizen-bank-accounts.njk
  src/main/views/macro/bank-account.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/ bankAccountAndSavings/bankAccounts.test.ts
  src/test/unit/views/features/response/statementOfMeans/citizen-bank-accounts.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-629

#657 Fix - add nameOverride for elasticsearch
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-657
