Repository hmcts/civil-citizen-ui, pull requests merged in 2022-11, with the labels that each got.

#1028 Civ 4396 check your answer part1
  src/main/common/models/party.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/defendant/defendantDetailsController.ts
  src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
  src/main/routes/features/claim/yourDetails/defendantEmailController.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/services/features/claim/checkAnswers/financialSection/addClaimAmounts.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildClaimAmountSection.ts
  src/main/services/features/claim/yourDetails/claimantDetailsService.ts
  src/main/services/features/claim/yourDetails/defendantDetailsService.ts
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/services/features/claim/checkAnswers/claimAmountSection/addClaimAmounts.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1028

#1057 CIV-4772 - Tech Debt - Response Submit Guard
  src/main/common/models/claim.ts
  src/main/routes/features/response/submitConfirmationController.ts
  src/main/routes/guards/responseSubmitDateGuard.ts
  src/main/routes/routes.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/routes/guards/responseSubmitDateGuard.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1057

#1058 Dependencies bump
  package.json
  src/test/unit/modules/health/health-down.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1058

#1004 access profile "payment-access" added
  bin/add-roles.sh
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1004

#1030 CIV-4832 - translation added
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1030

#999 CIV-3601 point to civil service pr
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-999

#1023 CIV-5036 - fix translation for under 18 page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/ageEligibility/under-18.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1023

#1027 Feat/civ 5253
  src/main/modules/i18n/locales/cy.json
  src/main/views/features/directionsQuestionnaire/defendant-yourself-evidence.njk
  src/main/views/features/directionsQuestionnaire/experts/sent-expert-reports.njk
  src/main/views/features/directionsQuestionnaire/tried-to-settle-claim.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1027

#1070 Reverting back master push
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
  src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1070

#1062 CIV-5450 | remove || new Claim()
  src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/services/features/claim/yourDetails/defendantDetailsService.ts
  src/main/services/features/response/statementOfMeans/dependants/childrenDisabilityService.ts
  src/main/services/features/response/statementOfMeans/disabilityService.ts
  src/main/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
  src/main/services/features/response/statementOfMeans/employment/selfEmployed/selfEmployedAsService.ts
  src/main/services/features/response/statementOfMeans/partner/cohabitingService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerAgeService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerDisabilityService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerPensionService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerSevereDisabilityService.ts
  src/main/services/features/response/statementOfMeans/severeDisabilityService.ts
  src/test/unit/routes/features/response/citizenResponseType/citizenResponseTypeController.test.ts
  src/test/unit/services/features/claim/yourDetails/defendantDetailsService.test.ts
  src/test/unit/services/features/response/statementOfMeans/dependants/childrenDisabilityService.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/selfEmployedAsService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1062

#1059 CIV-2811: ResidenceType refactor
  src/main/common/form/models/statementOfMeans/residence/residence.ts
  src/main/common/form/models/statementOfMeans/residence/residenceType.ts
  src/main/common/form/models/statementOfMeans/residenceType.ts
  src/main/common/models/statementOfMeans.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/response/statementOfMeans/residenceController.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addResidence.ts
  src/main/services/features/response/statementOfMeans/residence/residenceService.ts
  src/main/views/features/response/statementOfMeans/residence.njk
  src/test/unit/services/features/response/checkAnswers/financialDetails/addResidence.test.ts
  src/test/unit/services/features/response/statementOfMeans/residence/residenceService.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1059

#1077 Re-create - Claimant Response Model
  package.json
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1077

#1080 Tech debt/civ 4631 part admit guard
  src/main/routes/features/response/admission/partialAdmission/howMuchDoYouOweController.ts
  src/main/routes/features/response/admission/partialAdmission/howMuchHaveYouPaidController.ts
  src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
  src/main/routes/features/response/admission/partialAdmission/paymentDateController.ts
  src/main/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/admission/partialAdmission/whyDoYouDisagreeController.ts
  src/main/routes/guards/partAdmitGuard.ts
  src/main/routes/guards/partAdmitHowMuchHaveYouPaidGuard.ts
  src/test/unit/routes/features/response/admission/partialAdmission/howMuchDoYouOweController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/howMuchHaveYouPaidController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/paymentDateController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/whyDoYouDisagreeController.test.ts
  src/test/unit/routes/guards/paidAdmitGurad.test.ts
  src/test/unit/routes/guards/partAdmitHowMuchHaveYouPaidGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1080

#1022 Civ 5037
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/eligibility/send-your-response-by-email.njk
  src/main/views/macro/contact-us.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1022

#1073 CIV-1350-TechDebt:configure test with non-relative module imports.
  jest.a11y.config.js
  jest.config.js
  src/main/routes/features/claim/amount/claimAmountBreakdownController.ts
  src/main/routes/features/claim/details/helpWithFeesController.ts
  src/main/routes/features/claim/details/reasonController.ts
  src/main/services/features/claim/checkAnswers/financialSection/addClaimAmounts.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
  src/main/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.ts
  src/test/unit/routes/features/claim/amount/claimAmountBreakdownController.test.ts
  src/test/unit/routes/features/claim/details/helpWithFeesController.test.ts
  src/test/unit/routes/features/claim/details/reasonController.test.ts
  src/test/unit/services/features/claim/checkAnswers/claimAmountSection/addClaimAmounts.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.test.ts
  tsconfig.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1073

#1072 CIV-5520: BUG - Refactor interest pages
  src/main/common/form/models/interest/interest.ts
  src/main/common/models/claim.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/draft-store/redisData.json
  src/main/routes/features/claim/interest/claimantInterestFromController.ts
  src/main/routes/features/claim/interest/claimantInterestRateController.ts
  src/main/routes/features/claim/interest/continueClaimingInterestController.ts
  src/main/routes/features/claim/interest/howMuchContinueClaimingController.ts
  src/main/routes/features/claim/interest/interestTypeController.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildClaimAmountSection.ts
  src/main/services/features/claim/interest/claimantInterestFromService.ts
  src/main/services/features/claim/interest/claimantInterestRateService.ts
  src/main/services/features/claim/interest/interestTypeService.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/interestUtils.test.ts
  src/test/unit/services/features/claim/interest/claimantInterestFromService.test.ts
  src/test/unit/services/features/claim/interest/claimantInterestRateService.test.ts
  src/test/unit/services/features/claim/interest/interestService.test.ts
  src/test/unit/services/features/claim/interest/interestTypeService.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mocks/civilClaimResponseExpertAndWitnessMock.json
  src/test/utils/mocks/civilClaimResponseFullAdmissionMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1072

#1076 features/CIV-5494-check your answers-PT4-clone
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/supportRequired.ts
  src/main/common/utils/checkYourAnswer/changeButton.ts
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/addSupportRequiredList.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/services/features/directionsQuestionnaire/supportRequiredService.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/addSupportRequiredList.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
  src/test/utils/mocks/civilClaimResponseExpertAndWitnessMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1076

#1091 features/CVI-5667-ccj defendant dob
  src/main/common/models/claimantResponse.ts
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/common/models/claimantResponse/ccj/dateOfBirth.ts
  src/main/common/models/claimantResponse/ccj/defendantDOB.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/main/routes/features/claimantResponse/ccj/defendantDOBController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/views/features/claimantResponse/ccj/defendant-dob.njk
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/modules/nunjucks/filters/dateFilter.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/defendantDOBController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1091

#1075 features/CIV-5478-proceed against full dispute-clone
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantIntentionToProceedController.ts
  src/main/routes/routes.ts
  src/main/views/features/claimant-response/claimant-intention-to-proceed.njk
  src/test/unit/routes/features/claimantResponse/claimantIntentionToProceedController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1075

#1074 CIV-5477: Has the defendant paid you
  src/main/common/form/models/claimantResponse/claimantResponseErrorMessages.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/partPaymentReceivedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/genericForm/genericFormService.ts
  src/main/views/features/claimantResponse/part-payment-received.njk
  src/test/unit/routes/features/claimantResponse/partPaymentReceivedController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1074

#1035 CIV-5479 - Feature - Check Answers Hearing Requirements Section
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1035

#1060 CIV-314-Tech Debt - Resetting redis data with changing response type.
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/services/features/response/responseType/citizenResponseTypeService.ts
  src/test/unit/services/features/response/responseType/citizenResponseTypeService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1060

#1104 CIV-5960: BUG - Refactor CCD Translator
  src/main/services/translation/response/convertToCCDAddress.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1104

#1103 Adding Breathing Space Model and Service
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/common/models/breathingSpace.ts
  src/main/common/models/breathingSpace/debtRespiteOption.ts
  src/main/common/models/breathingSpace/debtRespiteOptionType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/breathingSpace/breathingSpaceService.ts
  src/test/unit/services/features/breathingSpace/breathingSpaceService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1103

#1069 Features/civ 5492 experts hearing reports
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/experts/expertReportDetails/expertReportDetails.ts
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/hearingExportsReportBuilderSection.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/hearingRequirementsSection.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/hearingExportsReportBuiderSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1069

#1095 Accessibility
  package.json
  src/main/assets/scss/main.scss
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertGuidanceController.ts
  src/main/routes/features/mediation/freeTelephoneMediationController.ts
  src/main/routes/features/mediation/iDontWantFreeMediationController.ts
  src/main/views/features/claim/details/reason.njk
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
  src/main/views/macro/postcode-address-form.njk
  src/test/a11y/a11y.test.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/dashboard/contactThemController.test.ts
  src/test/unit/routes/features/mediation/freeTelephoneMediationController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1095

#1088 CIV-5609 part admit settle claim
  src/main/common/models/claimantResponse.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/settleClaimController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/settle-claim.njk
  src/main/views/macro/yesNoGenericForm.njk
  src/test/unit/routes/features/claimantResponse/settleClaimController.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1088

#1105 CIV-5484 - TechDebt - Remove PoC and Example Files
  src/main/assets/scss/task-list.scss
  src/main/common/form/models/claim/claimant/claimantPartyTypeSelection.ts
  src/main/common/models/evidence/evidenceDetails.ts
  src/main/common/models/respondent.ts
  src/main/common/utils/languageToggleUtils.ts
  src/main/common/utils/numberConverter.ts
  src/main/modules/nunjucks/index.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/exampleSectionOne.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/exampleSectionTwo.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdateService.ts
  src/main/services/features/directionsQuestionnaire/expertDetailsService.ts
  src/main/services/features/directionsQuestionnaire/expertReportDetailsService.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/services/features/response/admission/partialAdmission/howMuchDoYouOweService.ts
  src/main/views/features/response/eligibility/send-your-response-by-email.njk
  src/main/views/macro/buttons.njk
  src/main/views/macro/telephone.njk
  src/main/views/macro/yesNoForm.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1105

#1089 CIV-5662 : Part admit + already paid- Rejection reason.
  src/main/common/form/models/claimantResponse/rejectionReason.ts
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/rejectionReasonController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/rejection-reason.njk
  src/test/unit/routes/features/claimantResponse/rejectionReasonController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1089

#1112 Fix: delete duplicated url
  src/main/routes/urls.ts
  src/test/a11y/ignored-urls.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1112

#1114 Features/civ 4715 specific court
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/courts/courtLocations.ts
  src/main/common/models/directionsQuestionnaire/hearing/hearing.ts
  src/main/common/models/directionsQuestionnaire/hearing/specificCourtLocation.ts
  src/main/modules/draft-store/courtLocationCache.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/hearing/specificCourtController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/hearing/specificCourtLocationService.ts
  src/main/views/features/claimantResponse/rejection-reason.njk
  src/main/views/features/directionsQuestionnaire/hearing/specific-court.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/directionQuestionnaire/hearing/specificCourtlocation.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/hearing/specificCourtLocationController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/hearing/specificCourtLocationService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1114

#1081 CIV-5558 | Claimant Intent – Full admit pay by set date + How they want to pay
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/fullAdmitSetDatePaymentService.ts
  src/main/services/features/response/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/views/features/claimantResponse/full-admit-set-date-payment.njk
  src/test/unit/routes/features/claimantResponse/fullAdmitSetDatePaymentController.test.ts
  src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1081

#1101 CIV-5257 - Features - Welsh Translations 23
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/directionsQuestionnaire/experts/defendant-expert-can-still-examine.njk
  src/main/views/features/directionsQuestionnaire/vulnerabilityQuestions/vulnerability.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1101

#1097 CIV-5256 - Features - Welsh 22
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/directionsQuestionnaire/hearing/cantAttendHearingInNext12MonthsController.ts
  src/main/routes/urls.ts
  src/main/views/features/directionsQuestionnaire/experts/permission-for-expert.njk
  src/main/views/features/directionsQuestionnaire/hearing/cant-attend-hearing-in-next-12-months.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1097

#1090 Bringing back Welsh Translation for CIV-5255
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1090

#1093 CIV-5570: Claimant Intent –Debt Respite - When did it start?
  src/main/common/models/breathingSpace.ts
  src/main/common/models/breathingSpace/debtRespiteStartDate.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/breathingSpace/debtRespiteStartDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/breathingSpace/respite-start.njk
  src/test/unit/routes/features/breathingSpace/debtRespiteStartDateController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1093

#1110 Feat/civ 5573 | Debt Respite - Expected end date
  src/main/common/models/breathingSpace.ts
  src/main/common/models/breathingSpace/debtRespiteEndDate.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/breathingSpace/debtRespiteEndDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/breathingSpace/debt-respite-end-date.njk
  src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1110

#1108 CIV-5571: Debt Respite - What type is it?
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/breathingSpace/debtRespiteOptionController.ts
  src/main/routes/routes.ts
  src/main/views/features/breathingSpace/respite-type.njk
  src/test/unit/routes/features/breathingSpace/debtRespiteOptionsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1108

#1117 re-create-CIV-5563-Defendant's response-full dispute
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/claim.ts
  src/main/common/models/summaryList/summaryList.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/fullAdmissinionDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addBankAccounts.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addDependants.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addEmploymentDetails.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addLoansOrCreditCardDebts.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addOtherDependants.ts
  src/main/services/genericService.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/main/views/features/dashboard/item-content.njk
  src/main/views/features/response/statementOfMeans/citizenBankAndSavings/citizen-bank-accounts.njk
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/main/views/features/response/statementOfMeans/otherDependants/other-dependants.njk
  src/main/views/features/response/statementOfMeans/unemployment.njk
  src/main/views/macro/employer.njk
  src/main/views/macro/their-financial-details.njk
  src/test/unit/routes/features/claimantResponse/reviewDefendantsResponseController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/unit/services/features/response/checkAnswers/financialDetails/addOtherDependants.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponsePaymentSection.test.ts
  src/test/unit/services/genericService.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
  src/test/utils/checkAnswersConstants.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1117

#1128 Enable CUI FTs
  Jenkinsfile_CNP
  package.json
  src/test/config.js
  src/test/functionalTests/features/response/pages/checkYourAnswers.js
  src/test/functionalTests/features/response/pages/enterNameAndAddressDetails.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpec.js
  src/test/functionalTests/tests/response_admitAll_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, Testing, rel:civil-citizen-ui-pr-1128

#1132 update staging environment variables
  Jenkinsfile_CNP
  charts/civil-citizen-ui/values.aat.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1132

#1133 Fixing few timeout issues
  jest.config.js
  package.json
  src/test/unit/services/features/breathingSpace/breathingSpaceService.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1133

#1143 CIV-6106 - Remove the dependency on User Profile
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1143

#1123 re-recreate:CIV-5567: Breathing Space - Debt Respite Scheme
  src/main/common/models/breathingSpace.ts
  src/main/common/models/breathingSpace/debtRespiteReferenceNumber.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/breathingSpace/debtRespiteReferenceNumberController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/breathingSpace/debt-respite-reference-number.njk
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteReferenceNumberController.test.ts
  src/test/unit/services/features/breathingSpace/breathingSpaceService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1123

#1124 CIV-5451 - CIV-6094: TechDebt getFullName
  src/main/common/models/ccdResponse/ccdAddress.ts
  src/main/common/models/ccdResponse/ccdParty.ts
  src/main/common/models/claim.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/oidc/index.ts
  src/main/routes/features/response/admission/fullRejection/youHavePaidLessController.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/citizenDob/citizenDobController.ts
  src/main/routes/features/response/rejectAllOfClaimController.ts
  src/main/routes/features/response/requestMoreTimeController.ts
  src/main/routes/features/response/responseDeadline/agreedResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/newResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/responseDeadlineOptionsController.ts
  src/main/routes/features/response/yourDefenceController.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/fullDefenceConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/rejectClaimConfirmationContent.ts
  src/main/services/translation/response/convertToCCDAddress.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/mediation/can-we-use.njk
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/features/response/financialDetails/financial-details.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/response/financial-details/claimIndividualMock.json
  src/test/unit/routes/features/response/financial-details/claimIndividualMockNoType.json
  src/test/unit/routes/features/response/financial-details/claimOrganisationMock.json
  src/test/unit/routes/features/response/responseDeadline/newResponseDeadlineController.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1124

#1121 CIV-5670: Request a CCJ - Payment options
  src/main/common/form/models/claimantResponse/ccj/ccjPaymentOption.ts
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/ccjPaymentOptionController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/ccj/ccj-payment-options.njk
  src/test/unit/routes/features/claimantResponse/ccj/ccjPaymentOptionController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1121

#1118 Civ 4392 total amount claiming
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/assets/scss/main.scss
  src/main/common/form/models/claim/interest/claimantInterestRate.ts
  src/main/common/models/claim.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/interest/claimantInterestRateController.ts
  src/main/routes/features/claim/totalAmountController.ts
  src/main/routes/features/public/eligibility/totalAmountController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/amount/claimAmountBreakdownService.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/views/features/claim/interest/claimant-interest-rate.njk
  src/main/views/features/claim/total-amount.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/test/unit/common/utils/interestUtils.test.ts
  src/test/unit/routes/features/claim/iterest/claimantInterestRateController.test.ts
  src/test/unit/routes/features/claim/totalAmountController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, rel:civil-citizen-ui-pr-1118

#1113 Civ 5493 hearing requirement witnesses
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/main/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, rel:civil-citizen-ui-pr-1113

#1119 CIV_5677 :Claimant Intent - Request a CCJ - Payment options - Pay by …
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/defendantPaymentDateController.ts
  src/main/routes/features/response/admission/fullAdmission/paymentOption/paymentDateController.ts
  src/main/routes/features/response/admission/partialAdmission/paymentDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/admission/payment-date.njk
  src/test/unit/routes/features/claimantResponse/ccj/defendantPaymentDateController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, rel:civil-citizen-ui-pr-1119

#1130 re-create-CIV-5682-CCJ confirmation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/ccjConfirmationController.ts
  src/main/routes/features/claimantResponse/claimantIntentionToProceedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/external-urls.njk
  src/main/views/features/claimantResponse/ccj/ccj-confirmation.njk
  src/main/views/features/claimantResponse/claimant-intention-to-proceed.njk
  src/test/unit/routes/features/claimantResponse/ccj/ccjConfirmationController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1130

#1142 Add admit all scenarios
  package.json
  src/test/config.js
  src/test/functionalTests/tests/response_admitAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, Testing, rel:civil-citizen-ui-pr-1142
