Repository hmcts/civil-citizen-ui, pull requests merged in 2022-12, with the labels that each got.

#1155 CIV_5706 : Remove claim from redis once response has been submitted.
  src/main/modules/draft-store/draftStoreService.ts
  src/main/routes/features/response/checkAnswersController.ts
  src/test/unit/modules/draft-store/draftStoreService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1155

#1154 Remove dependencies
  .gitignore
  Jenkinsfile_CNP
  bin/variables/load-preview-environment-variables.sh
  bin/variables/load-staging-environment-variables.sh
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1154

#1098 Re-create - CIV-5540
  src/main/modules/draft-store/redisData.json
  src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
  src/main/routes/urls.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1098

#1191 adding ccd field limit
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1191

#1180 Tech debt/civ 5541 refactor payment
  src/main/common/form/models/admission/partialAdmission/paymentIntention.ts
  src/main/common/form/models/admission/paymentIntention.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/fullAdmission.ts
  src/main/common/models/partialAdmission.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/repaymentPlan.ts
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/services/features/claimantResponse/defendantResponse/fullAdmissinionDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/fullAdmitSetDatePaymentService.ts
  src/main/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.ts
  src/main/services/features/response/admission/paymentOptionService.ts
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponsePaymentSection.ts
  src/main/services/features/response/repaymentPlan/repaymentPlanService.ts
  src/main/services/features/response/responseType/citizenResponseTypeService.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/common/utils/taskList/tasks/whenWillYouPay.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
  src/test/unit/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.test.ts
  src/test/unit/services/features/response/admission/paymentOptionService.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseToClaimSection.test.ts
  src/test/unit/services/features/response/repaymentPlan/repaymentPlanService.test.ts
  src/test/unit/services/features/response/responseType/citizenResponseTypeService.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1180

#1201 ignoring some tests for pipeline to work
  jest.config.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1201

#1153 Fix: response submit guard
  src/main/common/models/claim.ts
  src/main/routes/guards/responseSubmitDateGuard.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/routes/guards/responseSubmitDateGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1153

#1152 CIV-2061 Refactor priority debts page
  src/main/common/form/models/statementOfMeans/expensesAndIncome/expenseType.ts
  src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
  src/main/common/form/models/statementOfMeans/priorityDebtDetails.ts
  src/main/common/form/models/statementOfMeans/priorityDebts.ts
  src/main/common/utils/priorityDebts/priorityDebtsConstants.ts
  src/main/common/utils/priorityDebts/priorityDebtsConvertors.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/statementOfMeans/priorityDebtsController.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addPriorityDebts.ts
  src/main/services/features/response/statementOfMeans/priorityDebtsService.ts
  src/main/views/features/response/statementOfMeans/priority-debts.njk
  src/main/views/macro/conditional-checkBoxHTML.njk
  src/test/config.js
  src/test/functionalTests/features/response/pages/checkYourAnswers.js
  src/test/functionalTests/features/response/pages/priorityDebtsDetails.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpec.js
  src/test/unit/routes/features/response/statementOfMeans/priorityDebtsController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/response/statementOfMeans/priorityDebtsService.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1152

#1192 Civ 5614 launch darkly
  config/default.yaml
  package.json
  sonar-project.properties
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1192

#1209 Feat/civ 5680
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/common/models/claimantResponse/ccj/instalmentFirstPaymentDate.ts
  src/main/common/models/claimantResponse/ccj/repaymentPlanInstalments.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/repaymentPlanInstalmentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/ccj/repayment-plan-instalments.njk
  src/test/unit/routes/features/claimantResponse/ccj/repaymentPlanInstalmentsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1209

#1196 Features/civ 2444 welsh bilingual language preference
  src/main/common/models/claim.ts
  src/main/common/models/claimBilingualLanguagePreference.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/response/bilingualLangPreferenceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/response/bilingualLangPreferenceService.ts
  src/main/views/features/response/bilingual-language-preference.njk
  src/test/unit/routes/features/response/bilingualLangPreferenceController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/response/bilingualLangPreferenceService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1196

#1212 CIV-5967 - Remove Bitnami Dependency
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  jest.config.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1212

#1214 CIV-5967 - remove bitnami dependency
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1214

#1210 Bug/civ 6258 mediation number
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1210

#1215 added code to exclude the submission in AAT environment
  src/test/functionalTests/features/response/pages/checkYourAnswers.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1215

#1144 Features/civ 5611 submit lip claim
  bin/import-ccd-definition.sh
  bin/pull-latest-camunda-files.sh
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/events/caseEvent.ts
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/response/convertToCUI/convertToCUIParty.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/submission/submitClaim.test.ts
  src/test/unit/routes/features/public/eligibility/helpWithFeesEligibilityController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/howMuchDoYouOweController.test.ts
  src/test/unit/routes/features/response/checkAnswersController.test.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIParty.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1144

#1178 Bump dependencies
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1178
