Repository hmcts/civil-citizen-ui, pull requests merged in 2022-08, with the labels that each got.

#628 CIV-3603 Refactor deprecated form 2
  src/main/common/form/models/citizenTelephoneNumber.ts
  src/main/common/form/models/repaymentPlan/repaymentPlanForm.ts
  src/main/common/form/models/statementOfMeans/carer.ts
  src/main/common/form/models/statementOfMeans/debts/debtItems.ts
  src/main/common/form/models/statementOfMeans/debts/debts.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.ts
  src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
  src/main/routes/features/response/statementOfMeans/carerController.ts
  src/main/routes/features/response/statementOfMeans/debts/debtsController.ts
  src/main/views/features/response/citizenPhoneNumber/citizen-phone.njk
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/main/views/features/response/statementOfMeans/carer.njk
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/macro/yesNoGenericForm.njk
  src/test/unit/common/form/models/statementOfMeans/carer.test.ts
  src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/debts/debtsController.test.ts
  src/test/unit/views/features/response/citizenPhoneNumber/citizen-phone.test.ts
  src/test/unit/views/features/response/repaymentPlan/repaymentPlan.test.ts
  src/test/unit/views/features/response/statementOfMeans/carer.test.ts
  src/test/unit/views/features/response/statementOfMeans/debts/debts.test.ts
  src/test/utils/mockForm.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-628

#677 fix - move dates to the future
  src/test/unit/routes/features/response/admission/fullAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-677

#678 Dependencies bump
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-678

#652 Civ 3516 check ya reject dispute all
  src/main/common/form/models/rejectAllOfClaim.ts
  src/main/common/models/claim.ts
  src/main/common/utils/taskList/tasks/tellUsWhyDisagreeWithClaim.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/rejectAllOfClaimController.ts
  src/main/routes/features/response/yourDefenceController.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/rejectAllOfClaimService.ts
  src/main/services/features/response/yourDefenceService.ts
  src/main/views/features/response/your-defence.njk
  src/test/unit/common/utils/taskList/tasks/tellUsWhyDisagreeWithClaim.test.ts
  src/test/unit/routes/features/response/yourDefenceController.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
  src/test/unit/services/features/response/yourDefenceService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-652

#685 Dependencies bump
  charts/civil-citizen-ui/Chart.yaml
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-685

#656 CIV 3602 Refactor Deprecated Form 1
  src/main/common/form/models/citizenAddress.ts
  src/main/common/form/models/citizenCorrespondenceAddress.ts
  src/main/common/form/models/citizenDob.ts
  src/main/common/form/models/citizenResponseType.ts
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/citizenDob/citizenDobController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/services/features/response/citizenDetails/citizenDetailsService.ts
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/features/response/citizenDob/citizen-dob.njk
  src/main/views/features/response/citizenResponseType/citizen-response-type.njk
  src/main/views/macro/address.njk
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/services/features/response/citizenDetails/citizenDetailsService.test.ts
  src/test/utils/mockForm.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-656

#699 Dependencies bump
  charts/civil-citizen-ui/Chart.yaml
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-699

#702 CIV-3454 - Re-create PR
  src/main/common/form/models/statementOfMeans/partner/cohabiting.ts
  src/main/common/form/models/statementOfMeans/partner/partnerAge.ts
  src/main/common/form/models/statementOfMeans/partner/partnerDisability.ts
  src/main/common/form/models/statementOfMeans/partner/partnerSevereDisability.ts
  src/main/modules/i18n/locales/cy.json
  src/main/views/features/response/statementOfMeans/partner/partner-age.njk
  src/main/views/features/response/statementOfMeans/partner/partner-disability.njk
  src/main/views/features/response/statementOfMeans/partner/partner-severe-disability.njk
  src/main/views/features/response/statementOfMeans/partner/partner.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-702

#698 Civ 3720 add call to get case from ccd
  src/main/modules/utilityService.ts
  src/main/routes/features/document/documentDownloadController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/features/response/taskListController.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-698

#655 CIV-3172 - Welsh UI translations 7
  src/main/common/form/models/statementOfMeans/employment/employer.ts
  src/main/common/form/models/statementOfMeans/employment/employers.ts
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/selfEmployedAsForm.ts
  src/main/common/form/models/statementOfMeans/expensesAndIncome/incomeType.ts
  src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/financialDetails/financial-details.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/main/views/features/response/statementOfMeans/employment/who-employs-you.njk
  src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
  src/main/views/features/response/statementOfMeans/income/regular-income.njk
  src/main/views/macro/employer.njk
  src/main/views/macro/transaction-details.njk
  src/test/unit/common/form/models/statementOfMeans/expensesAndIncome/regularIncome.test.ts
  src/test/unit/common/form/models/statementOfMeans/expensesAndIncome/transaction.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployedAsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/whoEmploysYouController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/income/regularIncomeController.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-655

#706 remove lang from service and controller
  src/main/common/form/models/claimSummarySection.ts
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/exampleSectionOne.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/exampleSectionTwo.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdateService.ts
  src/main/views/features/dashboard/claim-summary-content.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdateService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-706

#711 Update: redisData
  src/main/modules/draft-store/redisData.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-711

#703 CIV-2900 - Re-create PR
  src/main/common/form/models/admission/paymentOption/paymentOption.ts
  src/main/common/form/models/citizenTelephoneNumber.ts
  src/main/common/form/models/statementOfMeans/dependants/dependants.ts
  src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
  src/main/common/form/models/statementOfMeans/residence.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/statementOfMeans/residenceController.ts
  src/main/views/features/response/admission/payment-option.njk
  src/main/views/features/response/citizenPhoneNumber/citizen-phone.njk
  src/main/views/features/response/statementOfMeans/dependants/dependants.njk
  src/main/views/features/response/statementOfMeans/residence.njk
  src/test/unit/common/form/models/admission/paymentOption.test.ts
  src/test/unit/routes/features/response/admission/fullAdmission/paymentOption/paymentOptionController.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.test.ts
  src/test/unit/routes/features/response/citizenPhoneDetails/citizenPhoneController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/dependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/residenceController.test.ts
  src/test/unit/services/features/response/statementOfMeans/dependants/dependantsService.test.ts
  src/test/unit/views/features/response/admission/payment-option.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-703

#713 CIV-3467 - Re-create PR
  src/main/common/form/models/admission/partialAdmission/howMuchDoYouOwe.ts
  src/main/common/form/models/admission/partialAdmission/whyDoYouDisagree.ts
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
  src/main/common/form/models/statementOfMeans/otherDependants.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
  src/main/common/form/validators/numberOfPeopleValidator.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/views/features/response/admission/partialAdmission/how-much-do-you-owe.njk
  src/main/views/features/response/admission/why-do-you-disagree.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/main/views/features/response/statementOfMeans/otherDependants/other-dependants.njk
  src/test/unit/common/form/models/admission/partialAdmission/howMuchDoYouOwe.test.ts
  src/test/unit/common/form/models/statementOfMeans/admission/partialAdmission/whyDoYouDisagree.test.ts
  src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-713

#692 feature/CIV-918/Make a new money claim
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/views/features/response/dashboard/dashboard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-692

#709 Feature/civ 3468 welsh tran error msg 5
  src/main/common/form/models/citizenDob.ts
  src/main/common/form/models/statementOfMeans/employment/employmentForm.ts
  src/main/common/form/models/statementOfMeans/partner/partnerPension.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/currencyValidator.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/features/response/statementOfMeans/employment/employment-status.njk
  src/main/views/features/response/statementOfMeans/partner/partner-pension.njk
  src/main/views/macro/yesNoForm.njk
  src/main/views/macro/yesNoGenericForm.njk
  src/test/unit/routes/features/response/citizenDob/citizenDobController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/debts/debtsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/employmentStatusController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerPensionController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-709

#716 Civ 3394 task list deadline
  sonar-project.properties
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/needMoreTime.ts
  src/main/common/utils/taskList/tasks/viewOptionsBeforeDeadline.ts
  src/main/routes/features/response/requestMoreTimeController.ts
  src/main/routes/features/response/responseDeadline/agreedResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/newResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/responseDeadlineOptionsController.ts
  src/main/routes/features/response/understandingYourOptionsController.ts
  src/main/routes/guards/deadLineGuard.ts
  src/main/routes/urls.ts
  src/main/services/features/response/responseDeadlineService.ts
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/test/unit/routes/features/response/requestMoreTimeController.test.ts
  src/test/unit/routes/features/response/responseDeadline/agreedResponseDeadlineController.test.ts
  src/test/unit/routes/features/response/responseDeadline/newResponseDeadlineController.test.ts
  src/test/unit/routes/features/response/responseDeadlineOptionsController.test.ts
  src/test/unit/routes/features/response/taskListController.test.ts
  src/test/unit/routes/features/response/understandingYourOptionsController.test.ts
  src/test/unit/routes/guards/deadLineGuard.test.ts
  src/test/unit/views/features/response/dashboard/claim-summary.test.ts
  src/test/unit/views/features/response/request-more-time.test.ts
  src/test/unit/views/features/response/response-deadline-options.test.ts
  src/test/unit/views/features/response/responseDeadline/agreed-response-deadline.test.ts
  src/test/unit/views/features/response/understanding-your-options.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/civilClaimResponseMock.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-716

#715 CIV 3451 CUI Welsh UI Translations 8
  src/main/common/form/models/admission/partialAdmission/alreadyPaid.ts
  src/main/common/form/models/timeLineOfEvents/timelineRow.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/main/modules/nunjucks/index.ts
  src/main/views/features/response/admission/partialAdmission/already-paid.njk
  src/main/views/features/response/timelineOfEvents/defendant-timeline.njk
  src/main/views/macro/timeline-row.njk
  src/test/unit/common/form/models/timelineOfEvents/defendantTimeline.test.ts
  src/test/unit/common/form/models/timelineOfEvents/timelineRow.test.ts
  src/test/unit/views/features/response/admission/partialAdmission/already-paid.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-715

#704 Feat/caseworker ras validation civ3585
  bin/add-roles.sh
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-704

#717 CIV-3824 - Fix - Set previous selection values
  src/main/views/features/response/response-deadline-options.njk
  src/test/a11y/ignored-urls.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-717

#732 CIV-3698
  src/main/common/form/models/statementOfMeans/dependants/betweenSixteenAndNineteenDependants.ts
  src/main/common/form/models/statementOfMeans/disability.ts
  src/main/common/form/models/statementOfMeans/employment/employmentForm.ts
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.ts
  src/main/routes/features/response/statementOfMeans/disabilityController.ts
  src/main/routes/features/response/statementOfMeans/employment/employmentStatusController.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.ts
  src/main/routes/features/response/statementOfMeans/employment/whoEmploysYouController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
  src/main/services/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
  src/main/services/features/response/statementOfMeans/disabilityService.ts
  src/main/services/features/response/statementOfMeans/employment/employmentConverter.ts
  src/main/services/features/response/statementOfMeans/employment/employmentService.ts
  src/main/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
  src/main/views/features/response/statementOfMeans/dependants/between_16_and_19.njk
  src/main/views/features/response/statementOfMeans/disability.njk
  src/main/views/features/response/statementOfMeans/employment/employment-status.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/test/unit/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/dependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
  src/test/unit/services/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenService.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/employmentService.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-732

#725 CIV-3698 - TechDebt Refactor Deprecated Form
  src/main/common/form/models/statementOfMeans/dependants/betweenSixteenAndNineteenDependants.ts
  src/main/common/form/models/statementOfMeans/disability.ts
  src/main/common/form/models/statementOfMeans/employment/employmentForm.ts
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.ts
  src/main/routes/features/response/statementOfMeans/disabilityController.ts
  src/main/routes/features/response/statementOfMeans/employment/employmentStatusController.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.ts
  src/main/routes/features/response/statementOfMeans/employment/whoEmploysYouController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
  src/main/services/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
  src/main/services/features/response/statementOfMeans/disabilityService.ts
  src/main/services/features/response/statementOfMeans/employment/employmentConverter.ts
  src/main/services/features/response/statementOfMeans/employment/employmentService.ts
  src/main/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
  src/main/views/features/response/statementOfMeans/dependants/between_16_and_19.njk
  src/main/views/features/response/statementOfMeans/disability.njk
  src/main/views/features/response/statementOfMeans/employment/employment-status.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/test/unit/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/dependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
  src/test/unit/services/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenService.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/employmentService.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-725

#730 CIV-3700 - TechDebt Refactor Deprecated Form
  src/main/common/form/models/statementOfMeans/partner/partnerDisability.ts
  src/main/common/form/models/statementOfMeans/partner/partnerPension.ts
  src/main/common/form/models/statementOfMeans/partner/partnerSevereDisability.ts
  src/main/common/form/models/statementOfMeans/priorityDebts.ts
  src/main/common/form/models/statementOfMeans/severeDisability.ts
  src/main/common/utils/priorityDebts/priorityDebtsConvertors.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/priorityDebtsController.ts
  src/main/routes/features/response/statementOfMeans/severeDisabilityController.ts
  src/main/services/features/response/statementOfMeans/partner/partnerDisabilityService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerPensionService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerSevereDisabilityService.ts
  src/main/services/features/response/statementOfMeans/priorityDebtsService.ts
  src/main/services/features/response/statementOfMeans/severeDisabilityService.ts
  src/main/views/features/response/admission/partialAdmission/already-paid.njk
  src/main/views/features/response/statementOfMeans/are-you-severely-disabled.njk
  src/main/views/features/response/statementOfMeans/partner/partner-disability.njk
  src/main/views/features/response/statementOfMeans/partner/partner-pension.njk
  src/main/views/features/response/statementOfMeans/partner/partner-severe-disability.njk
  src/main/views/features/response/statementOfMeans/priority-debts.njk
  src/test/unit/common/form/models/statementOfMeans/priorityDebts/priorityDebts.test.ts
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerDisabilityController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/severeDisabilityController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-730

#728 CIV-3699 - TechDebt Refactor Deprecated Form
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/selfEmployedAsForm.ts
  src/main/common/form/models/statementOfMeans/otherDependants.ts
  src/main/common/form/models/statementOfMeans/partner/cohabiting.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/selfEmployedAsController.ts
  src/main/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerController.ts
  src/main/services/features/response/statementOfMeans/employment/selfEmployed/selfEmployedAsService.ts
  src/main/services/features/response/statementOfMeans/otherDependants/otherDependantsService.ts
  src/main/services/features/response/statementOfMeans/partner/cohabitingService.ts
  src/main/services/features/response/statementOfMeans/partner/partnerAgeService.ts
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/main/views/features/response/statementOfMeans/otherDependants/other-dependants.njk
  src/main/views/features/response/statementOfMeans/partner/partner-age.njk
  src/main/views/features/response/statementOfMeans/partner/partner.njk
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerAgeController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerController.test.ts
  src/test/unit/services/features/response/statementOfMeans/employment/selfEmployedAsService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-728

#727 CIV-4222 - Fix: add next claim summary
  src/main/routes/features/dashboard/claimSummaryController.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-727

#734 CIV-3620 : CUI Welsh UI Translations 9
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/mediation/free-telephone-mediation.njk
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/test/unit/views/features/mediation/free-telephone-mediation.test.ts
  src/test/unit/views/features/response/repaymentPlan/repaymentPlan.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-734

#718 CIV-3851 : CUI Welsh UI Translations 10
  src/main/common/form/models/admission/howMuchHaveYouPaid.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/response/admission/partialAdmission/howMuchHaveYouPaidController.ts
  src/main/views/features/response/admission/how-much-have-you-paid.njk
  src/main/views/features/response/evidence/evidence.njk
  src/main/views/features/response/evidence/evidences.njk
  src/main/views/macro/error-summary.njk
  src/test/unit/common/form/models/admission/partialAdmission/howMuchHaveYouPaid.test.ts
  src/test/unit/services/features/response/admission/partialAdmission/howMuchHaveYouPaidService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-718

#737 change to https services related to ccd and civil service
  Jenkinsfile_CNP
  bin/variables/load-preview-environment-variables.sh
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-737

#741 3826 yet again
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/auth/user/oidc.ts
  src/main/assets/scss/main.scss
  src/main/common/models/AppRequest.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/oidc/index.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/main/views/home.njk
  src/main/views/macro/header.njk
  src/main/views/question-template.njk
  src/test/unit/app/auth/user/oidc.test.ts
  src/test/unit/modules/i18n/i18n.test.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/views/directionsQuestionnaire/expert-guidance.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-741

#733 CIV-3826 - Re-create - Log Out Functionality
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/auth/user/oidc.ts
  src/main/assets/scss/main.scss
  src/main/common/models/AppRequest.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/oidc/index.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/main/views/home.njk
  src/main/views/macro/header.njk
  src/main/views/question-template.njk
  src/test/unit/app/auth/user/oidc.test.ts
  src/test/unit/modules/i18n/i18n.test.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/views/directionsQuestionnaire/expert-guidance.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-733

#743 CIV-4080 - Welsh Translations #13
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/response/responseDeadline/agreedResponseDeadlineController.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-743

#723 CIV 3852 CUI Welsh UI Translations 11
  src/main/common/form/models/mediation/freeMediation.ts
  src/main/common/form/models/mediation/noMediationReason.ts
  src/main/common/form/models/mediation/noMediationReasonOptions.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/mediation/i-dont-want-free-mediation.njk
  src/main/views/features/mediation/mediation-disagreement.njk
  src/test/unit/routes/features/mediation/mediationDisagreementController.test.ts
  src/test/unit/views/features/mediation/i-dont-want-free-mediation.test.ts
  src/test/unit/views/features/mediation/mediation-disagreement.test.ts
  src/test/unit/views/features/response/responseDeadline/agreed-response-deadline.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-723

#701 Feature/Welsh translation error message 3
  src/main/common/form/models/admission/fullAdmission/paymentOption/paymentDate.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/admission/payment-date.njk
  src/test/unit/services/features/response/admission/fullAdmission/paymentOption/paymentDateService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-701

#742 CIV-4350 - Tech Debt - Cuiuser sign in
  src/main/app/auth/user/oidc.ts
  src/main/common/models/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/test/unit/app/auth/user/oidc.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-742

#724 Bug/civ 3908 repayment schedule translation
  src/main/assets/js/calculate-length-repayment.js
  src/main/assets/scss/main.scss
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-724

#748 CIV-4440 - Bugfix - Elivs operator on schedule container children
  src/main/assets/js/calculate-length-repayment.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-748

#746 feature/CIV-3614/not eligible to use this service page
  src/main/common/form/models/eligibility/NotEligibleReason.ts
  src/main/common/utils/notEligibleReasonConvertor.ts
  src/main/common/utils/urlFormatter.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/eligibility/notEligibleController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/external-urls.njk
  src/main/views/features/eligibility/not-eligible-includes/claim-value-not-known.njk
  src/main/views/features/eligibility/not-eligible-includes/claim-value-over-25000.njk
  src/main/views/features/eligibility/not-eligible.njk
  src/main/views/macro/external-link.njk
  src/main/views/macro/header.njk
  src/main/views/macro/paper-form-address.njk
  src/test/unit/common/utils/notEligibleReasonConvertor.test.ts
  src/test/unit/routes/features/eligibility/notEligibleController.test.ts
  src/test/unit/views/features/eligibility/not-eligible.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-746

#739 bugfix/CIV-3944/data-persisted-on-selection-change
  src/main/assets/js/calculate-length-repayment.js
  src/main/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/test/unit/services/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-739

#738 CIV-3935 - Fix - Clear Data On Selection Change
  src/main/services/features/response/statementOfMeans/otherDependants/otherDependantsService.ts
  src/test/unit/services/features/response/statementOfMeans/otherDependants/otherDependants.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-738

#750 Features/civ 3628 have postal address
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/defendantAddressEligibilityController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/defendant-eligible-address.njk
  src/test/unit/routes/features/public/eligibility/defendantAddressEligibilityController.test.ts
  src/test/unit/views/features/public/eligibility/defendant-address-eligibility.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-750

#749 CIV-3604: Try the new online service
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/notEligibleController.ts
  src/main/routes/features/public/eligibility/tryNewServiceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/not-eligible-includes/claim-value-not-known.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-value-over-25000.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/main/views/features/public/eligibility/try-new-service.njk
  src/test/unit/routes/features/public/eligibility/notEligibleController.test.ts
  src/test/unit/routes/features/public/eligibility/tryNewServiceController.test.ts
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
  src/test/unit/views/features/public/eligibility/try-new-service.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-749

#754 feature/CIV-3740/Claim for tenancy deposit
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/tenancyDepositController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/tenancy-deposit.njk
  src/test/unit/routes/features/public/eligibility/notEligibleController.test.ts
  src/test/unit/routes/features/public/eligibility/tenancyDepositController.test.ts
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
  src/test/unit/views/features/public/eligibility/tenancy-deposit.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-754

#756 CIV-3626: You can’t use this service if this claim is against more than one person or organisation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/not-eligible-includes/multiple-defendants.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-756

#766 fix tests
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-766

#759 CIV-3633: You can't use this service - This service is currently for claimants representing themselves
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/not-eligible-includes/claim-on-behalf.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-759

#753 New: reason defendant address
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/not-eligible-includes/defendant-address.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-753

#771 re-feature/CIV-3741/not eligible for tenancy deposit
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/not-eligible-includes/claim-for-tenancy-deposit.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-771

#774 CIV-3763: Are you 18 or over?
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/claimantOver18EligibilityController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/over-18.njk
  src/test/unit/routes/features/public/eligibility/claimantOver18EligibilityController.test.ts
  src/test/unit/views/features/public/eligibility/over-18.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-774

#779 CIV-3765: Do you need help paying your court fee?
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/helpWithFeesEligibilityController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/help-with-fees.njk
  src/test/unit/routes/features/public/eligibility/helpWithFeesEligibilityController.test.ts
  src/test/unit/views/features/public/eligibility/help-with-fees-eligibility.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-779

#778 CIV-3753 : You cant use this service. You cant use this service , defendant under 18
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/external-urls.njk
  src/main/views/features/public/eligibility/not-eligible-includes/under-18-defendant.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-778

#769 CIV-3630 who are you making the claim for
  src/main/common/models/eligibility/claimType.ts
  src/main/common/models/eligibility/claimTypeOptions.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/public/eligibility/claimTypeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/claim-type.njk
  src/test/unit/routes/features/public/eligibility/claimTypeController.test.ts
  src/test/unit/views/features/public/eligibility/claim-type.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-769

#777 CIV-3764 cant use this service 18 or over
  src/main/common/form/models/eligibility/NotEligibleReason.ts
  src/main/common/utils/notEligibleReasonConvertor.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/claimantOver18EligibilityController.ts
  src/main/views/features/public/eligibility/not-eligible-includes/claimant-under-18.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/common/utils/notEligibleReasonConvertor.test.ts
  src/test/unit/routes/features/public/eligibility/claimantOver18EligibilityController.test.ts
  src/test/unit/views/features/public/eligibility/claim-against-government.test.ts
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-777

#767 CIV-3739: You need to have an address in the UK to make a money claim
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/not-eligible-includes/claimant-address.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-767

#781 CIV-3785: Do you have a Help With Fees reference number?
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/helpWithFeesReferenceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/help-with-fees-reference.njk
  src/test/unit/routes/features/public/eligibility/helpWithFeesReferenceController.test.ts
  src/test/unit/views/features/public/eligibility/help-with-fees-reference.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-781

#780 Civ 3768 some useful info about help fees
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/someUsefulInfoFeesController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/eligibility/some-useful-info-fees.njk
  src/test/unit/routes/features/public/eligibility/someUsefulInfoFeesController.test.ts
  src/test/unit/views/features/public/eligibility/some-useful-info-fees.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-780

#763 CIV-4039/consolidate-nunjucks-templates
  src/main/modules/draft-store/redisData.json
  src/main/views/features/response/statementOfMeans/priority-debts.njk
  src/main/views/macro/buttons.njk
  src/main/views/question-template.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-763

#783 CIV-3743 | add not eligible screen changes for government departments
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/not-eligible-includes/government-department.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/test/unit/views/features/public/eligibility/not-eligible.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-783
