Repository hmcts/civil-citizen-ui, pull requests merged in 2022-04, with the labels that each got.

#277 Refactor/CIV-1711-Use optional chaining
  src/main/assets/js/append-row.js
  src/main/common/form/models/bankAndSavings/bankAccounts.ts
  src/main/common/form/models/statementOfMeans/employment/employmentForm.ts
  src/main/common/form/models/statementOfMeans/residence.ts
  src/main/common/form/validators/arrayAtLeastOneSelectedValidator.ts
  src/main/common/form/validators/formValidator.ts
  src/main/modules/admission/fullAdmission/paymentOption/paymentOptionService.ts
  src/main/modules/citizenDetails/citizenDetailsService.ts
  src/main/modules/statementOfMeans/bankAccounts/bankAccountConverter.ts
  src/main/modules/statementOfMeans/bankAccounts/bankAccountService.ts
  src/main/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
  src/main/modules/statementOfMeans/dependants/dependantsService.ts
  src/main/modules/statementOfMeans/disabilityService.ts
  src/main/modules/statementOfMeans/employment/employmentService.ts
  src/main/modules/statementOfMeans/partner/cohabitingService.ts
  src/main/modules/statementOfMeans/partner/partnerAgeService.ts
  src/main/modules/statementOfMeans/partner/partnerDisabilityService.ts
  src/main/modules/statementOfMeans/partner/partnerPensionService.ts
  src/main/modules/statementOfMeans/partner/partnerSevereDisabilityService.ts
  src/main/modules/statementOfMeans/residence/residenceService.ts
  src/main/modules/statementOfMeans/severeDisabilityService.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/citizenDob/citizenDobController.ts
  src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/routes/features/response/statementOfMeans/disabilityController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/residenceController.ts
  src/main/routes/features/response/statementOfMeans/severeDisabilityController.ts
  src/main/views/features/response/statementOfMeans/residence.njk
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-277

#271 Refactor/civ 1740 remove code smells
  src/main/modules/statementOfMeans/disabilityService.ts
  src/main/modules/statementOfMeans/partner/cohabitingService.ts
  src/main/modules/statementOfMeans/partner/partnerDisabilityService.ts
  src/main/modules/statementOfMeans/partner/partnerPensionService.ts
  src/main/modules/statementOfMeans/partner/partnerSevereDisabilityService.ts
  src/main/modules/statementOfMeans/severeDisabilityService.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/routes/features/response/ageEligibility/ageEligibilityController.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/routes/features/response/citizenDob/citizenDobController.ts
  src/main/routes/features/response/citizenPhoneNumber/citizenPhoneController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/features/response/financialDetails/financialDetailsController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.ts
  src/main/routes/features/response/statementOfMeans/disabilityController.ts
  src/main/routes/features/response/statementOfMeans/employment/employmentStatusController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerAgeController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerPensionController.ts
  src/main/routes/features/response/statementOfMeans/partner/partnerSevereDisabilityController.ts
  src/main/routes/features/response/statementOfMeans/severeDisabilityController.ts
  src/main/routes/home.ts
  src/main/routes/homeController.ts
  src/main/routes/routes.ts
  src/main/routes/unauthorised.ts
  src/main/routes/unauthorisedController.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-271

#285 Civ 1374 are you behind on tax payments
  config/default.yaml
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/validationConstraints.ts
  src/main/common/models/statementOfMeans.ts
  src/main/common/models/taxPayments.ts
  src/main/common/utils/yesNoOptionConverter.ts
  src/main/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.ts
  src/main/modules/statementOfMeans/employment/employmentConverter.ts
  src/main/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
  src/test/unit/common/utils/yesNoOptionConverter.test.ts
  src/test/unit/modules/statementOfMeans/employment/selfEmployed/onTaxPaymentsService.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-285

#269 Civ 1456 how do you respond
  src/main/common/form/models/numberOfDays.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/claim.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/modules/draft-store/index.ts
  src/main/modules/draft-store/redisData.json
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/modules/draft-store/draftStoreService.test.ts
  src/test/unit/routes/features/response/citizenResponseType/citizenResponseTypeController.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-269

#295 Civ 1490 are you unemployer or retired
  src/main/common/form/models/statementOfMeans/unemployment/otherDetails.ts
  src/main/common/form/models/statementOfMeans/unemployment/unemployment.ts
  src/main/common/form/models/statementOfMeans/unemployment/unemploymentCategory.ts
  src/main/common/form/models/statementOfMeans/unemployment/unemploymentDetails.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/claim.ts
  src/main/common/models/statementOfMeans.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/statementOfMeans/unemployment/unemploymentService.ts
  src/main/routes/features/response/statementOfMeans/employment/employmentStatusController.ts
  src/main/routes/features/response/statementOfMeans/unemployment/unemploymentController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/statementOfMeans/unemployment.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/employmentStatusController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/unemployment/unemploymentController.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-295

#294 Feature/civ 1365 self employed as
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/selfEmployedAsForm.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/selfEmployedAs.ts
  src/main/common/models/statementOfMeans.ts
  src/main/modules/statementOfMeans/employment/selfEmployed/selfEmployedAsService.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/selfEmployedAsController.ts
  src/main/routes/routes.ts
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/test/unit/modules/statementOfMeans/employment/selfEmployedAsService.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployedAsController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-294

#298 Civ 1364 who employs you
  bin/generate-ssl-options.sh
  src/main/common/form/models/statementOfMeans/employment/employer.ts
  src/main/common/form/models/statementOfMeans/employment/employers.ts
  src/main/common/form/models/statementOfMeans/employment/employmentForm.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/atLeastOneEmployerValidator.ts
  src/main/common/form/validators/formValidator.ts
  src/main/common/models/statementOfMeans.ts
  src/main/modules/statementOfMeans/employment/employerService.ts
  src/main/routes/features/response/statementOfMeans/employment/employmentStatusController.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/selfEmployedAsController.ts
  src/main/routes/features/response/statementOfMeans/employment/whoEmploysYouController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/server.ts
  src/main/views/features/response/statementOfMeans/employment/who-employs-you.njk
  src/main/views/macro/employer.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/employmentStatusController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployedAsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/whoEmploysYouController.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-298

#308 Fix: bug loading main-dev.js
  src/main/views/webpack/js-template.njk
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-308

#309 Upgrade Packages
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-309

#297 Feature/civ 1469/debts you are behind
  src/main/common/form/models/statementOfMeans/priorityDebtDetails.ts
  src/main/common/form/models/statementOfMeans/priorityDebts.ts
  src/main/common/models/statementOfMeans.ts
  src/main/common/utils/priorityDebts/priorityDebtsConstants.ts
  src/main/common/utils/priorityDebts/priorityDebtsConvertors.ts
  src/main/modules/statementOfMeans/priorityDebtsService.ts
  src/main/routes/features/response/statementOfMeans/priorityDebtsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/statementOfMeans/priority-debts.njk
  src/main/views/macro/conditional-checkBoxHTML.njk
  src/main/views/macro/error-block.njk
  src/main/views/question-template.njk
  src/main/views/webpack/income-expense-scripts.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/statementOfMeans/priorityDebts/priorityDebtDetails.test.ts
  src/test/unit/common/form/models/statementOfMeans/priorityDebts/priorityDebts.test.ts
  src/test/unit/routes/features/response/statementOfMeans/priorityDebtsController.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-297

#299 Feature/civ 1476 do you have loans or credit card debts
  src/main/common/form/models/form.ts
  src/main/common/form/models/statementOfMeans/debts/debtItems.ts
  src/main/common/form/models/statementOfMeans/debts/debts.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/atLeastOnePopulatedRow.ts
  src/main/common/form/validators/currencyValidator.ts
  src/main/common/models/statementOfMeans.ts
  src/main/routes/features/response/statementOfMeans/debts/debtsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/test/unit/common/form/models/form.test.ts
  src/test/unit/routes/features/response/statementOfMeans/debts/debtsController.test.ts
  src/test/utils/mockForm.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-299

#318 Upgrade Packages #2
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-318

#310 Civ 1853 calculate total
  sonar-project.properties
  src/main/assets/js/calculate-amount.js
  src/main/common/form/models/statementOfMeans/expenses/expenseSource.ts
  src/main/common/form/models/statementOfMeans/expenses/regularExpenses.ts
  src/main/common/form/models/statementOfMeans/priorityDebtDetails.ts
  src/main/common/utils/calculateMonthlyIncomeExpenses/amountSchedule.ts
  src/main/common/utils/calculateMonthlyIncomeExpenses/monthlyIncomeExpensesCalculator.ts
  src/main/index.js
  src/main/routes/calculateMonthlyIncomeExpense/monthlyExpenseIncomeCalculatorController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
  src/main/views/features/response/statementOfMeans/priority-debts.njk
  src/main/views/macro/conditional-checkBoxHTML.njk
  src/main/views/macro/expense-details.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/statementOfMeans/expenses/expense.test.ts
  src/test/unit/common/form/models/statementOfMeans/priorityDebts/priorityDebtDetails.test.ts
  src/test/unit/common/utils/calculateMonthlyIncomeExpenses/monthlyIncomeExpensesCalculator.test.ts
  src/test/unit/routes/calculateMonthlyExpense/monthlyExpenseIncomeCalculatorController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-310

#319 Fix vulnerability: https://github.com/advisories/GHSA-fwr7-v2mv-hh25
  package.json
  src/main/modules/draft-store/index.ts
  src/main/modules/statementOfMeans/dependants/childrenDisabilityService.ts
  src/main/routes/features/response/financialDetails/financialDetailsController.ts
  src/main/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.ts
  src/test/unit/modules/draft-store/draftStore.test.ts
  src/test/unit/modules/statementOfMeans/dependants/childrenDisabilityService.test.ts
  src/test/unit/routes/features/response/financial-details/financialDetailsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-319

#333 fix ioredis-mock
  jest.config.js
  jest.setup.redis-mock.js
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-333

#340 Upgrade Packages
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-340

#341 Set unemployment details only for relevant categories
  src/main/modules/statementOfMeans/unemployment/unemploymentService.ts
  src/main/views/features/response/statementOfMeans/unemployment.njk
  src/test/unit/routes/features/response/statementOfMeans/unemployment/unemploymentController.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseUnemploymentOtherMock.json
  src/test/utils/mocks/civilClaimResponseUnemploymentRetiredMock.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-341

#336 bugFix/CIV-1966/Update contact-us-for-help macro
  src/main/views/macro/contact-us-for-help.njk
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-336

#347 CIV-2039 -fix bug overriding statement of means
  src/main/modules/statementOfMeans/otherDependants/otherDependantsService.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-347

#360 Children disability data not loaded properly
  src/main/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-360

#348 TechDebt/CIV-1752/Remove code smells part2
  jest.a11y.config.js
  jest.config.js
  jest.functionaltest.config.js
  jest.routes.config.js
  jest.smoketest.config.js
  sonar-project.properties
  src/main/app.ts
  src/main/app/auth/user/oidc.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/response/ageEligibility/ageEligibilityController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.ts
  src/main/routes/homeController.ts
  src/main/routes/unauthorisedController.ts
  src/test/utils/mockForm.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-348

#361 CIV-2041 Tech Debt - Reusable Mocks
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/test/unit/modules/admission/fullAdmission/paymentOption/paymentOptionService.test.ts
  src/test/unit/modules/statementOfMeans/dependants/betweenSixteenAndNineteenService.test.ts
  src/test/unit/routes/features/response/admission/fullAdmission/paymentOption/paymentOptionController.test.ts
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/routes/features/response/citizenResponseType/citizenResponseTypeController.test.ts
  src/test/unit/routes/features/response/financial-details/financialDetailsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/bankAccounts/bankAccountsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/debts/debtsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/betweenSixteenAndNineteenController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/dependants/dependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerPensionController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/residenceController.test.ts
  src/test/unit/sample.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-361

#346 Civ 1815 task list model
  sonar-project.properties
  src/main/assets/scss/main.scss
  src/main/assets/scss/task-list.scss
  src/main/common/models/taskList/TaskStatus.ts
  src/main/common/models/taskList/task.ts
  src/main/common/models/taskList/taskList.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/confirmYourDetails.ts
  src/main/common/utils/taskList/tasks/needMoreTime.ts
  src/main/modules/taskListService.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/routes.ts
  src/main/views/features/response/task-list.njk
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-346

#365 Fix/civ 2038 add test coverage
  src/test/unit/routes/features/response/statementOfMeans/dependants/childrenDisabilityController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-365

#300 Civ 1135 what date pay on
  src/main/common/form/models/admission/fullAdmission/paymentOption/paymentDate.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/optionalDateFourDigitValidator.ts
  src/main/common/form/validators/optionalDateNotInPastValidator.ts
  src/main/common/models/claim.ts
  src/main/modules/admission/fullAdmission/paymentOption/paymentDateService.ts
  src/main/modules/admission/fullAdmission/paymentOption/paymentOptionService.ts
  src/main/routes/features/response/statementOfMeans/employment/admission/fullAdmission/paymentOption/paymentDateController.ts
  src/main/routes/features/response/statementOfMeans/employment/admission/fullAdmission/paymentOption/paymentOptionController.ts
  src/main/routes/routes.ts
  src/main/views/features/response/admission/fullAdmission/paymentOption/payment-date.njk
  src/test/unit/common/form/validators/optionalDateFourDigitValidator.test.ts
  src/test/unit/common/form/validators/optionalDateNotInPastValidator.test.ts
  src/test/unit/modules/admission/fullAdmission/paymentOption/paymentDateService.test.ts
  src/test/unit/routes/features/response/admission/fullAdmission/paymentOption/paymentDateController.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-300

#320 Feature/civ 1366 court orders
  .eslintignore
  package.json
  sonar-project.properties
  src/main/assets/js/conditionally-hide-add-button.js
  src/main/assets/js/jquery.js
  src/main/assets/js/mojAll.js
  src/main/assets/js/remove-error-content.js
  src/main/assets/scss/main.scss
  src/main/common/form/models/genericForm.ts
  src/main/common/form/models/statementOfMeans/courtOrders/courtOrder.ts
  src/main/common/form/models/statementOfMeans/courtOrders/courtOrders.ts
  src/main/common/form/models/statementOfMeans/dependants/numberOfChildren.ts
  src/main/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/atLeastOneRowIsPopulated.ts
  src/main/common/models/statementOfMeans.ts
  src/main/index.js
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/response/statementOfMeans/courtOrders/courtOrdersController.ts
  src/main/routes/features/response/statementOfMeans/debts/debtsController.ts
  src/main/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.ts
  src/main/routes/features/response/statementOfMeans/employment/whoEmploysYouController.ts
  src/main/routes/features/response/statementOfMeans/unemployment/unemploymentController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/statementOfMeans/courtOrders/courtOrdersService.ts
  src/main/views/features/response/statementOfMeans/courtOrders/court-order.njk
  src/main/views/features/response/statementOfMeans/courtOrders/court-orders.njk
  src/main/views/features/response/statementOfMeans/dependants/dependants.njk
  src/main/views/features/response/statementOfMeans/residence.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/statementOfMeans/employment/selfEmployed/onTaxPayments.test.ts
  src/test/unit/routes/features/response/statementOfMeans/courtOrders/courtOrdersController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/debts/debtsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/selfEmployed/onTaxPaymentsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/whoEmploysYouController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/unemployment/unemploymentController.test.ts
  src/test/unit/services/features/response/statementOfMeans/courtOrders/courtOrdersService.test.ts
  webpack/ministryOfJusticeFrontend.js
  yarn.lock
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-320

#339 Civ 1563 other expenses
  sonar-project.properties
  src/main/assets/js/append-row.js
  src/main/assets/js/calculate-amount.js
  src/main/assets/scss/main.scss
  src/main/common/form/models/statementOfMeans/expenses/expenseSource.ts
  src/main/common/form/models/statementOfMeans/expenses/otherTransaction.ts
  src/main/common/form/models/statementOfMeans/expenses/regularExpenses.ts
  src/main/common/utils/calculateMonthlyIncomeExpenses/monthlyIncomeExpensesCalculator.ts
  src/main/routes/features/response/statementOfMeans/expenses/regularExpensesController.ts
  src/main/views/features/response/statementOfMeans/expenses/regular-expenses.njk
  src/main/views/macro/expense-details.njk
  src/test/unit/common/utils/calculateMonthlyIncomeExpenses/monthlyIncomeExpensesCalculator.test.ts
  src/test/unit/routes/features/response/statementOfMeans/expenses/regularExpensesController.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-339

#363 Civ 1156 why do you disagree with
  src/main/common/form/models/admission/partialAdmission/whyDoYouDisagree.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/claim.ts
  src/main/common/models/partialAdmission.ts
  src/main/common/models/whyDoYouDisagreeForm.ts
  src/main/modules/admission/partialAdmission/whyDoYouDisagreeService.ts
  src/main/routes/features/response/statementOfMeans/employment/admission/partialAdmision/whyDoYouDisagreeController.ts
  src/main/routes/features/response/statementOfMeans/employment/whoEmploysYouController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/admission/partialAdmission/why-do-you-disagree.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/statementOfMeans/admission/partialAdmission/whyDoYouDisagree.test.ts
  src/test/unit/modules/admission/partialAdmission/whyDoYouDisagreeService.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/whyDoYouDisagreeController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-363

#345 Civ 1520 explain cant pay immediately
  src/main/common/form/models/statementOfMeans/explanation.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/statementOfMeans.ts
  src/main/modules/statementOfMeans/explanationService.ts
  src/main/routes/features/response/statementOfMeans/explanationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/statementOfMeans/explanation.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/modules/statementOfMeans/explanationService.test.ts
  src/test/unit/routes/features/response/statementOfMeans/explanationController.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-345

#323 Feature/CIV-1892/Part admit - how much do you admit you owe?
  src/main/common/form/models/admission/partialAdmission/howMuchDoYouOwe.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/form/validators/equalToOrLessThanPropertyValueValidator.ts
  src/main/common/models/partialAdmission.ts
  src/main/modules/admission/partialAdmission/howMuchDoYouOweService.ts
  src/main/routes/features/response/admision/partialAdmission/howMuchDoYouOweController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/admission/partialAdmisssion/how-much-do-you-owe.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/form/models/admission/partialAdmission/howMuchDoYouOwe.test.ts
  src/test/unit/modules/admission/partialAdmission/howMuchDoYouOweService.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/howMuchDoYouOweController.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-323

#324 Features/CIV-1122 - part admit have you paid claimant
  src/main/common/form/models/admission/partialAdmission/alreadyPaid.ts
  src/main/common/models/partialAdmission.ts
  src/main/modules/admission/partialAdmission/partialAdmissionService.ts
  src/main/routes/features/response/admision/partialAdmission/alreadyPaidController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/admission/partialAdmission/already-paid.njk
  src/main/views/macro/yesNoForm.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/modules/admission/partialAdmission/partialAdmissionService.test.ts
  src/test/unit/routes/features/response/admission/partialAdmission/alreadyPaidController.test.ts
  src/test/unit/routes/features/response/citizenResponseType/citizenResponseTypeController.test.ts
  src/test/unit/views/features/response/admission/partialAdmission/already-paid.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-324

#342 Feature/civ 1523 repayment plan
  sonar-project.properties
  src/main/assets/js/calculate-length-repayment.js
  src/main/common/form/models/repaymentPlan/repaymentPlanForm.ts
  src/main/common/form/validationErrors/errorMessageConstants.ts
  src/main/common/models/claim.ts
  src/main/common/models/repaymentPlan.ts
  src/main/common/utils/dateFormatter.ts
  src/main/index.js
  src/main/modules/repaymentPlan/repaymentPlanService.ts
  src/main/routes/features/response/repaymentPlan/repaymentPlanController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/modules/repaymentPlan/repaymentPlanService.test.ts
  src/test/unit/routes/features/response/repaymentPlan/repaymentPlanController.test.ts
  src/test/unit/views/features/response/repaymentPlan/repaymentPlan.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-342

#378 CIV-2114 fix the url where the user should go after court orders
  src/main/routes/features/response/statementOfMeans/courtOrders/courtOrdersController.ts
  src/test/unit/routes/features/response/statementOfMeans/courtOrders/courtOrdersController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-378

#376 fix error
  src/main/routes/features/response/admission/fullAdmission/paymentOption/paymentDateController.ts
  src/main/routes/features/response/admission/partialAdmission/alreadyPaidController.ts
  src/main/routes/features/response/admission/partialAdmission/howMuchDoYouOweController.ts
  src/main/routes/features/response/admission/partialAdmission/whyDoYouDisagreeController.ts
  src/main/routes/routes.ts
  src/test/unit/routes/features/response/admission/fullAdmission/paymentOption/paymentDateController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-376

#375 fix error
  src/main/routes/features/response/statementOfMeans/debts/debtsController.ts
  src/test/unit/routes/features/response/statementOfMeans/debts/debtsController.test.ts
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-375
