Repository hmcts/civil-citizen-ui, pull requests merged in 2023-06, with the labels that each got.

#1684 CIV-8562 implement disclosure sections for evidence upload
  src/main/assets/scss/citizen-ui-colours.scss
  src/main/assets/scss/main.scss
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/services/features/caseProgression/disclosureContentBuilder.ts
  src/main/services/features/caseProgression/disclosureService.ts
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/disclosureService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1684

#1627 CIV-6395 add email for judgement
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1627

#1705 CIV-1663 service unavailable
  src/main/app.ts
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/service-unavailable-layout.njk
  src/main/views/service-unavailable.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1705

#1716 CIV-8946 Accessibility urls added for CUI-CP
  src/main/modules/draft-store/redisData.json
  src/test/a11y/constants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1716

#1717 CIV-TASK Demo session logout issue investigation
  package.json
  src/main/app.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1717

#1706 CIV-8563 evidence upload part2
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/disclosureService.ts
  src/main/services/features/caseProgression/uploadDocumentsSection.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/disclosureService.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1706

#1695 CIV-7068 - CUI - Update Date entry fields on Timeline pages.
  src/main/common/form/models/timeLineOfEvents/claimantTimeline.ts
  src/main/common/form/models/timeLineOfEvents/defendantTimeline.ts
  src/main/common/form/models/timeLineOfEvents/timelineRow.ts
  src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
  src/main/services/features/claim/checkAnswers/claimSection/addTimeLine.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
  src/main/views/features/response/timelineOfEvents/defendant-timeline.njk
  src/main/views/macro/timeline-row.njk
  src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/addYourTimeLine.js
  src/test/unit/common/models/timeLineOfEvents/claimantTimeline.test.ts
  src/test/unit/routes/features/response/timlineOfEvents/defendantTimelineController.test.ts
  src/test/unit/services/features/claim/checkAnswers/claimSection/buildClaimSection.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
  src/test/unit/services/features/response/timelineOfEvents/defendantTimelineService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDAdmitPartRoute.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
  src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
  src/test/unit/services/translation/response/convertToCCDTimeLine.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1695

#1701 CIV-8434 Update SoT statement for org/company
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/macro/statement-of-truth.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1701

#1678 CIV-8591 welsh translations39
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1678

#1698 CIV-7531 - Restrict access extend response deadline
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/routes/features/response/incompleteSubmissionController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/guards/allResponseTasksCompletedGuard.ts
  src/main/services/features/common/responseDeadlineAgreedService.ts
  src/main/services/translation/convertToCUI/convertToCUIResponseDeadline.ts
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/response/checkAnswersController.test.ts
  src/test/unit/routes/features/response/taskListController.test.ts
  src/test/unit/routes/guards/allResponseTasksCompleteGuard.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIResponseDeadline.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1698

#1686 CIV-8629 welsh translations40
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1686

#1718 CIV-8564 Evidence upload - Fast Track : Upload documents Page - Part 3 - Expert Evidence section
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/expertService.ts
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/uploadDocumentsSectionBuilder.test.ts
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/expertService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1718

#1734 CIV-7582 - Part Admit and State Paid: Financial details in CYA
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/admission/partialAdmission/partialAdmissionService.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1734

#1739 CIV-8884 - Update add-roles.sh
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1739

#1723 CIV-7861 Defendant response Status Part Admit Accept
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1723

#1759 CIV-9219 redis cache version change
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  infrastructure/_main.tf
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1759

#1766 CIV-0000 Fix Yarn Audit Issue Security Check
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1766

#1770 CIV-0000 Fix: resolution semver
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1770

#1773 CIV-0000 FTFix
  src/test/config.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/courtLocation.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1773

#1775 CIV-9417 A few events are still not enabled in AAT (prod like)
  Jenkinsfile_CNP
  src/test/config.js
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantLatestUpdate.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/response_admitAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1775

#1726 CIV-8641 - Added method for uploading file and returning CaseDocument
  package.json
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/caseProgression/fileUpload.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/utils/errorMessageTestConstants.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1726

#1747 CIV-8881 - CUI to CCD translation for evidence upload.
  src/main/services/translation/caseProgression/convertToCCDEvidenceUpload.ts
  src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1747

#1782 CIV-7718 - Part admit claimant ITP, mediation successful added to automation
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/breathingSpace.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/liftBreathingSpace.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/mediation.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitClaimantResponse.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1782

#1781 CIV-9265 FunctionalTestforCaseProgression
  Jenkinsfile_CNP
  src/test/config.js
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/pages/uploadYourDocumentsIntroduction.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/features/caseProgression/util/DateUtilsComponent.js
  src/test/functionalTests/features/common/contactUs.js
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToHearingInitiated.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToSDOState.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createDefendantResponse.js
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1781

#1786 CIV-0000 update env condition to check if only preview run cp tests
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1786

#1780 CIV-7723 fast track automation functional test
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterCompanyDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterContactNumberDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/considerClaimantDocs.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/expertDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/expertEvidence.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/requestExtraFourWeeks.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/sentExpertReports.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/sharedExpert.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/triedToSettle.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/freeTelephoneMediation/freeTelephoneMediation.js
  src/test/functionalTests/features/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecFastTrack.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1780

#1789 CIV-0000 Notify on tech team channel
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1789

#1791 CIV-0000 Temporarily disabling accessibility tests on preview
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1791

#1765 CIV-9215 WelshTranslations41
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1765

#1792 CIV-0000 fix memory leak - test
  jest.config.js
  package.json
  sonar-project.properties
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1792

#1802 CIV-7721 reject all claimant response, sdo scenarios
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/admitAllClaimantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createSDO.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/notSuitableForSDO.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllClaimantResponse.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1802

#1804 CIV-0000 revert pipeline
  jest.config.js
  package.json
  sonar-project.properties
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1804

#1810 CIV-0000 Ignore DQ unit tests
  jest.config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1810
