Repository hmcts/civil-citizen-ui, pull requests merged in 2023-09, with the labels that each got.

#2113 CIV-10364 welsh regresion bug
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/eligibility/sendYourResponseByEmailController.ts
  src/main/services/features/response/checkAnswers/financialSection/answers/addEmploymentDetails.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/addSupportRequiredList.ts
  src/main/views/features/response/eligibility/send-your-response-by-email.njk
  src/test/unit/services/features/response/checkAnswers/financialDetails/addEmploymentDetails.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/addSupportRequiredList.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2113

#2114 CIV-10415 - UI - Defendant LatestUpdate screen is blank for FastTrack claim.
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2114

#2090 CIV-9649 WelshEligibilityChecker1
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2090

#2112 CIV-10126 Set Up Lip Claim Issue After Payment
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/models/events/eventDto.ts
  src/main/routes/features/claim/claimFeeController.ts
  src/main/routes/features/claim/claimSubmittedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/claimFeeController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2112

#2127 CIV-10438 - CUI-Latest update section empty for Fast Track claim when its FD and claimant intent to proceed.
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimResponseStatus.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2127

#2086 CIV-10313 Settle claim amount calculation
  src/main/routes/features/claimantResponse/settleClaimController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2086

#1987 CIV-4694 Disable Google Analytics
  src/main/assets/js/cookies-controller.js
  src/main/index.js
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/public/cookiesController.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/features/public/cookies/cookies-view.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1987

#1981 CIV-8199 Pay your claim fee - Front End
  sonar-project.properties
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/routes/routes.ts
  src/main/views/features/claim/payment/claim-fee-breakdown.njk
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1981

#2134 CIV-10293 Claim check box message change
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claim/check-answers.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2134

#2139 CIV-10507 bug fix
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/routes/urls.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2139

#2120 CIV-9729 claimant dashboard claim list
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/dashboard/dashboarddefendantresponse.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/services/features/dashboard/claimPaginationService.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
  src/test/unit/services/features/dashboard/claimPaginationService.test.ts
  src/test/utils/mocks/claimantClaimsMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2120

#2020 CIV-9015 Code for Claimant Intent: Task List - Full Defence Full Reject
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2020

#2121 CIV-9028 task list fa instalments set date
  src/main/common/models/claim.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2121

#1922 CIV-9030 claimant intent fa instalments
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/fullAdmissionPayInstallmentsDefendantResponseContent.ts
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1922

#2110 CIV-10367 add caseRoles and service to get the information from civil-service
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/form/models/caseRoles.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/routes/guards/responseSubmitDateGuard.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2110

#2149 CIV-0000 fix quality gate in master
  src/main/app/client/civilServiceClient.ts
  src/test/unit/app/client/civilServiceClient.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2149

#1980 CIV-8487 file format link download
  src/main/services/features/caseProgression/documentTableBuilder.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1980

#2115 CIV-9201 check your answers page for Trial arrangements
  src/main/app/client/civilServiceClient.ts
  src/main/assets/scss/main.scss
  src/main/common/models/ccdResponse/ccdTrialArrangementsHearingRequirements.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/utils/stringUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/routes/routes.ts
  src/main/services/features/caseProgression/trialArrangements/checkAnswersService.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
  src/main/services/translation/caseProgression/trialArrangements/convertToCCDTrialArrangements.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/main/views/features/caseProgression/trialArrangements/check-answers.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/utils/stringUtils.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/checkAnswersController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/checkAnswersService.test.ts
  src/test/unit/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmation.test.ts
  src/test/unit/services/translation/caseProgression/trialArrangements/convertToCCDTrialArrangements.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mocks/civilClaimResponseFastTrackMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2115

#2137 CIV-9934 Full Defence states Paid where paid amount is full amount
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/settleAdmittedController.ts
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2137

#2102 CIV-10128 Claimant Intent-CYA
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/statementOfTruth/statementOfTruthForm.ts
  src/main/common/models/ccdResponse/ccdDQExtraDetails.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/routes/features/mediation/companyTelephoneNumberController.ts
  src/main/routes/routes.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/submitClaimantResponse.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantMediation.ts
  src/main/services/translation/response/convertToCCDAgreedMediation.ts
  src/main/services/translation/response/convertToCCDDQExtraDetials.ts
  src/main/services/translation/response/convertToCCDExpert.ts
  src/main/services/translation/response/convertToCCDMediation.ts
  src/main/views/features/claimantResponse/check-answers.njk
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/routes/features/claimantResponse/claimantResponseCheckAnswersController.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/submitClaimantReponse.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
  src/test/utils/mocks/noRespondentTelephoneClaimantIntentionMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2102

#1888 CIV-9615 View the defendants response - Dispute + Full paid
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-1888

#2135 CIV-9665 WelshClaimantDetails
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2135

#2138 CIV-9687 WelshDDetailsandCAmount
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2138

#2125 CIV-9651 WelshEligibilityChecker3
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2125

#1952 CIV-6602 how they want to pay defendant is organisation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
  src/main/views/features/claimantResponse/accept-repayment-plan.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-1952

#2091 CIV-9650 WelshEligibilityChecker2
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2091

#2146 CIV-9716 Settle claim screen
  sonar-project.properties
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/settleClaimController.ts
  src/main/services/translation/convertToCUI/convertToCUIRespondToClaim.ts
  src/main/views/features/claimantResponse/settle-claim.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/claimantResponse/settleClaimController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIRespondToClaim.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2146

#2131 CIV-7844 - check your answers for evidence upload
  src/main/common/form/models/caseProgression/documentUploadSubmission.ts
  src/main/common/models/caseProgression/documentUploadSections.ts
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/models/summaryList/summaryList.ts
  src/main/common/utils/dateUtils.ts
  src/main/common/utils/formatDocumentURL.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildDisclosureSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadedSummaryRows.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildExpertEvidenceSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildTrialDocumentsSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildWitnessEvidenceSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/checkYourAnswers/titledSummaryRowValueBuilder.ts
  src/main/services/features/caseProgression/documentTableBuilder.ts
  src/main/services/translation/caseProgression/convertToCCDEvidenceUpload.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/main/views/features/caseProgression/check-answers.njk
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/test/unit/routes/features/caseProgression/checkYourAnswersController.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadSummaryRows.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/titledSummaryRowValueBuilder.test.ts
  src/test/unit/services/features/caseProgression/expertService.test.ts
  src/test/unit/services/features/caseProgression/trialService.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
  src/test/utils/caseProgression/mockEvidenceUploadSections.ts
  src/test/utils/caseProgression/mockEvidenceUploadSummaryRows.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2131

#1984 CIV-7302 Issue Automated Strike Out - LiP
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/claimDismissedHearingDueDateUploadContent.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1984

#2156 CIV-8382 update dependencies
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2156

#2140 CIV-6431 Debt Respite Translation
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccd/ccdBreathingSpace/ccdBreathingSpaceStartInfo.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/routes/features/claim/breathingSpace/checkAnswersController.ts
  src/main/services/features/breathingSpace/submission/submitBreathingSpace.ts
  src/main/services/translation/breathingSpace/ccdTranslation.ts
  src/main/services/translation/breathingSpace/convertToCCDBreathingSpaceStartInfo.ts
  src/test/unit/routes/features/breathingSpace/checkAnswersController.test.ts
  src/test/unit/services/features/breathingSpace/submission/submitBreathingSpace.test.ts
  src/test/unit/services/translation/breathingSpace/ccdTranslation.test.ts
  src/test/unit/services/translation/breathingSpace/convertToCCDBreathingSpaceStartInfo.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2140

#1937 CIV-8201 Claim submission hwf
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/claimSubmittedController.ts
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/convertToCUI/convertToCUIClaimDetails.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/views/external-urls.njk
  src/main/views/features/claim/claim-submitted.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIClaimDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1937

#2173 CIV-0000 remove enable relase helm
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2173

#1996 CIV-8784 Claimant Intent confirmation-PA Pay Immediately accepted
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseConfirmationController.ts
  src/main/routes/guards/claimantIntentGuard.ts
  src/main/routes/guards/claimantResponseConfirmationGuard.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/partAdmitConfirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/test/unit/routes/features/claimantResponse/claimantResponseConfirmationController.test.ts
  src/test/unit/routes/guards/claimantIntentGuard.test.ts
  src/test/unit/routes/guards/claimantResponseConfirmationGuard.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-1996

#2158 CIV-9921 Set expire time for draft claim
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  sonar-project.properties
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/routes/features/claim/claimTaskListController.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/routes/guards/claimIssueTaskListGuard.ts
  src/main/services/dashboard/draftClaimService.ts
  src/main/services/features/claim/taskListService.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
  src/test/unit/modules/draft-store/draftStore.test.ts
  src/test/unit/modules/draft-store/draftStoreService.test.ts
  src/test/unit/modules/health/health-down.test.ts
  src/test/unit/modules/health/health-up.test.ts
  src/test/unit/modules/i18n/i18n.test.ts
  src/test/unit/routes/features/claim/claimTaskListController.test.ts
  src/test/unit/routes/features/mediation/mediationDisagreementController.test.ts
  src/test/unit/routes/features/mediation/mediationIndividualPhoneController.test.ts
  src/test/unit/routes/features/response/ageEligibility/ageEligibilityController.test.ts
  src/test/unit/routes/features/response/evidence/evidenceController.test.ts
  src/test/unit/routes/features/response/financial-details/financialDetailsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/employment/whoEmploysYouController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/otherDependants/otherDependantsController.test.ts
  src/test/unit/routes/features/response/statementOfMeans/partner/partnerAgeController.test.ts
  src/test/unit/routes/guards/claimIssueTaskListGuard.test.ts
  src/test/unit/services/dashboard/draftClaimService.test.ts
  src/test/utils/mockDraftStore.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2158

#1941 CIV-8319 confirmation claim settled
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/events/caseEvent.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimSettledConfirmationController.ts
  src/main/routes/features/claimantResponse/paidInFull/datePaidController.ts
  src/main/routes/routes.ts
  src/main/views/features/response/claim-settled-confirmation.njk
  src/test/unit/routes/features/claimantResponse/paidInFull/claimSettledConfirmationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-1941

#2180 CIV-0000 enableFTsForPartAdmitInst
  src/test/functionalTests/features/home/steps/login.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/assignCasePinInPost.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/checkYourAnswers.js
  src/test/functionalTests/features/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2180

#2130 CIV-9018 Claimant Response Task list - Part Admit Paid
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseTasklistController.ts
  src/main/routes/features/claimantResponse/partPaymentReceivedController.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/claimantResponse/claimantResponseTasklistController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseClaimantIntentionMock.json
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2130

#2154 CIV-10324 code for check answers part admit immediately
  src/main/common/models/claimantResponse/checkAnswers.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2154

#2193 CIV-10513 Help with fees :no redirect change
  src/main/routes/features/claim/checkAnswersController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2193

#2178 CIV-10540 Cancel Trial Arrangements invalidates redis info
  src/main/routes/features/caseProgression/trialArrangements/cancelTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/caseProgression/trialArrangements/check-answers.njk
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/caseProgression/trialArrangements/hearing-duration-other-info.njk
  src/test/unit/routes/features/caseProgression/trialArrangements/cancelTrialArrangements.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2178

#2197 CIV-10694 Negative scenarios for optionsBeforeResponseDeadline
  src/test/functionalTests/features/response/pages/defendantLipResponse/viewYourOptionsBeforeDeadline/viewYourOptionsBeforeDeadline.js
  src/test/functionalTests/features/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2197

#2203 CIV-8382 Update dependencies
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2203

#2159 CIV-9962 joint experts file name tweak
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2159

#2177 CIV-9131 - added caseRole check for expert evidence other party name
  src/main/services/features/caseProgression/expertService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2177

#2174 CIV-9014 Claimant Intent: Task List
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2174

#2187 CIV-10536 fixing csp error Security Policy directive: "form-action 'self'".
  src/main/modules/helmet/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2187

#2157 CIV-8105 - Tile + File for Final order
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/viewFinalGeneralOrderContent.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/viewFinalGeneralOrderContent.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2157

#2126 CIV-9800 CIV-9803 CIV-9660 - Bundles pr to test
  src/main/common/models/caseProgression/TabSectionBuilder.ts
  src/main/common/models/caseProgression/bundles/bundle.ts
  src/main/common/models/caseProgression/bundles/ccdBundle.ts
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/caseProgression/uploadDocumentsTableSectionBuilder.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/tabs.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/bundles/bundlesFormatter.ts
  src/main/services/features/caseProgression/bundles/bundlesService.ts
  src/main/services/features/caseProgression/documentTableBuilder.ts
  src/main/services/features/caseProgression/uploadedEvidenceFormatter.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/viewBundleContent.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/main/views/features/dashboard/claim-summary.njk
  src/test/unit/common/models/caseProgression/TabSectionBuilder.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/common/utils/formatDocumentURL.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/caseProgression/bundles/bundlesFormatter.test.ts
  src/test/unit/services/features/caseProgression/bundles/bundlesService.test.ts
  src/test/unit/services/features/caseProgression/uploadedEvidenceFormatter.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/viewBundleContent.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
  src/test/utils/caseProgression/mockDocumentTypeNameMap.ts
  src/test/utils/mockDocument.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2126

#2162 CIV-5853 mediation navigation
  src/main/services/features/response/mediation/companyTelephoneNumberService.ts
  src/test/unit/services/features/response/mediation/companyTelephoneNumberService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2162

#2184 CIV-8912 Claim issue Incomplete Task Page
  sonar-project.properties
  src/main/common/models/caseProgression/trialArrangements/trialArrangements.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/document/caseDocument.ts
  src/main/common/models/document/documentType.ts
  src/main/routes/features/claim/incompleteClaimIssueSubmissionController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/taskListService.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/main/services/translation/convertToCUI/convertToCUITrialArrangements.ts
  src/main/views/features/response/incomplete-submission.njk
  src/test/unit/routes/features/claim/incompleteClaimIssueSubmissionController.test.ts
  src/test/unit/services/features/claim/taskListService.test.ts
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUITrialArrangements.test.ts
  src/test/utils/caseProgression/mockCaseProgressionHearing.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2184

#2192 CIV-10158 ClaimAmountBugs
  src/main/assets/js/calculate-total-amount.js
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/totalAmountController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2192

#2235 CIV-10811 - fix bundles text
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2235

#2231 CIV-10831 fix undefined on cp confirmation
  src/main/routes/features/caseProgression/documentsUploadedController.ts
  src/test/unit/routes/features/caseProgression/documentsUploadedController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2231
