Repository hmcts/civil-citizen-ui, pull requests merged in 2023-02, with the labels that each got.

#1307 CIV-6644 - Cleanup of helm releases regardless
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1307

#1303 CIV-6931 update chart dependencies._Snyk
  charts/civil-citizen-ui/Chart.yaml
  package.json
  src/test/unit/services/features/response/responseDeadlineService.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1303

#1334 Going back the version of ccd to avoid bug with multiple pods getting…
  charts/civil-citizen-ui/Chart.yaml
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1334

#1330 CIV-7000 - Update dependencies._Snyk
  package.json
  src/main/modules/helmet/index.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1330

#1287 CIV-6131 Claimant response task list-P1._Snyk
  src/main/assets/scss/main.scss
  src/main/common/models/claimantResponse.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/routes/features/claimantResponse/claimantResponseTasklistController.ts
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertCanStillExamineController.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertSmallClaimsController.ts
  src/main/routes/features/directionsQuestionnaire/experts/permissionForExpertController.ts
  src/main/routes/features/directionsQuestionnaire/welshLanguageRequirements/welshLanguageController.ts
  src/main/routes/features/response/incompleteSubmissionController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/guards/allResponseTasksCompletedGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/claimantHearingRequirementsSectionTasks.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/claimantResponseSubmitSectionTasks.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/howDefendantRespondSectionTaks.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/common/taskListService.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/hearingExportsReportBuilderSection.ts
  src/main/views/features/claimantResponse/claimant-response-task-list.njk
  src/main/views/features/directionsQuestionnaire/experts/expert-small-claims.njk
  src/test/unit/common/models/directionQuestionnaire/directionQuestionnaire.test.ts
  src/test/unit/routes/features/claimantResponse/claimantResponseTasklistController.test.ts
  src/test/unit/routes/features/claimantResponse/courProposedDateController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertCanStillExamineController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertSmallClaimsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/permissionForExpertController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/welshLanguageRequirements/welshLanguageController.test.ts
  src/test/unit/routes/features/mediation/mediationIndividualPhoneController.test.ts
  src/test/unit/routes/features/response/checkAnswersController.test.ts
  src/test/unit/routes/features/response/incompleteSubmissionController.test.ts
  src/test/unit/routes/guards/allResponseTasksCompleteGuard.test.ts
  src/test/unit/routes/guards/paidAdmitGurad.test.ts
  src/test/unit/routes/guards/partAdmitHowMuchHaveYouPaidGuard.test.ts
  src/test/unit/routes/guards/signSettlmentAgreementGuard.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/experts/expertDetailsService.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/utils/mockDraftStore.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1287

#1304 CIV-6816 validate phone numbers._Snyk
  src/main/common/form/models/citizenTelephoneNumber.ts
  src/main/common/form/validators/phoneUKValidator.ts
  src/main/common/models/PartyPhone.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/routes/features/response/citizenPhoneDetails/citizenPhoneController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1304

#1296 CIV-5449 Unused Imports
  src/test/unit/common/utils/taskList/tasks/whyDisagreeWithAmountClaimed.test.ts
  src/test/unit/routes/features/breathingSpace/checkAnswersController.test.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteOptionsController.test.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteReferenceNumberController.test.ts
  src/test/unit/routes/features/claim/amount/claimAmountBreakdownController.test.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/routes/features/claim/defendantPhoneController.test.ts
  src/test/unit/routes/features/claim/details/helpWithFeesController.test.ts
  src/test/unit/routes/features/claim/details/reasonController.test.ts
  src/test/unit/routes/features/claimantResponse/repaymentPlanAcceptedController.test.ts
  src/test/unit/routes/features/mediation/mediationDisagreementController.test.ts
  src/test/unit/routes/features/mediation/mediationIndividualPhoneController.test.ts
  src/test/unit/services/features/breathingSpace/buildDebtRespiteSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1296

#1342 CIV-0000 Remove ilbip terraform var as it's no longer used
  infrastructure/variables.tf
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, rel:civil-citizen-ui-pr-1342

#1278 CIV-5996 Create Idam Fields
  src/main/common/models/civilClaimResponse.ts
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/claimantIdamDetails.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/submission/submitClaim.test.ts
  src/test/unit/services/features/claim/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claim/submission/submitClaim.test.ts
  src/test/unit/services/features/claimantResponse/ccj/ccjCheckAnswersService.test.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
  src/test/unit/services/translation/response/claimIdamDetatils.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
  src/test/utils/UserDetails.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1278

#1335 CIV-6177 claimant response task list PA PI._Snyk
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/mediation/iDontWantFreeMediationController.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/views/features/mediation/i-dont-want-free-mediation.njk
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/routes/features/mediation/iDontWantFreeMediationController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1335

#1339 CIV-6874 - Missing values in claim summary
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/evidence/evidenceType.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/main/services/translation/convertToCUI/convertToCUIClaimDetails.ts
  src/main/services/translation/convertToCUI/convertToCUIEvidence.ts
  src/main/services/translation/response/convertToCCDEvidence.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIClaimDetails.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIEvidence.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1339

#1308 CIV-6891 fast track dq journey._Snyk
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/common/form/models/claimType.ts
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/modules/draft-store/redisData.json
  src/main/routes/features/directionsQuestionnaire/experts/expertEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/routes.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/claimantHearingRequirementsSectionTasks.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-evidence.njk
  src/test/unit/common/models/directionQuestionnaire/directionQuestionnaire.test.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1308

#1299 CIV-6434 assign claim to defendant
  sonar-project.properties
  src/main/app.ts
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/claimAssignment/assignClaimController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/firstContact/claim-summary.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/routes/features/claimAssignment/claimAssignmentController.test.ts
  src/test/unit/routes/features/public/firstContact/accessDeniedController.test.ts
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
  src/test/unit/routes/features/public/firstContact/signpostingController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1299

#1354 CIV-0000 Fix build errors
  src/test/unit/common/models/directionQuestionnaire/directionQuestionnaire.test.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/otherWitnessesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1354

#1345 CIV-6180 claimant intend pa p set._Snyk
  src/main/common/form/models/claimantResponse/chooseHowToProceed.ts
  src/main/common/models/chooseHowProceed.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claimantResponse/chooseHowToProceedController.ts
  src/main/routes/routes.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/response/submission/compareAddress.ts
  src/main/views/features/claimantResponse/choose-how-to-proceed.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1345

#1358 CIV-5433 - Correct Code Owners
  .github/CODEOWNERS
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1358

#1350 CIV-5408 Longer period of time
  src/main/common/form/validators/dateNotAfterReferenceDate.ts
  src/main/common/models/directionsQuestionnaire/hearing/hearing.ts
  src/main/common/models/directionsQuestionnaire/hearing/unavailableDates.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/directionsQuestionnaire/hearing/cantAttendHearingInNext12MonthsController.ts
  src/main/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.ts
  src/main/routes/features/directionsQuestionnaire/hearing/whyUnavailableForHearingController.ts
  src/main/routes/features/directionsQuestionnaire/witnesses/otherWitnessesController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesCalculation.ts
  src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesForHearingService.ts
  src/main/services/features/directionsQuestionnaire/whyUnavailableForHearingService.ts
  src/main/views/features/directionsQuestionnaire/hearing/unavailable-dates-for-hearing.njk
  src/main/views/macro/unavailable-date-row.njk
  src/test/unit/routes/features/directionsQuestionnaire/hearing/cantAttendHearingInNext12MonthsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/witnesses/otherWitnessesController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/hearing/unavailableDatesCalculation.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1350

#1344 CIV-5469 dates added calculation._Snyk
  sonar-project.properties
  src/main/app.ts
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/claimAssignment/assignClaimController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/firstContact/claim-summary.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/directionQuestionnaire/directionQuestionnaire.test.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/routes/features/claimAssignment/claimAssignmentController.test.ts
  src/test/unit/routes/features/public/firstContact/accessDeniedController.test.ts
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
  src/test/unit/routes/features/public/firstContact/signpostingController.test.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/otherWitnessesService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1344

#1365 CIV-0000 fix_node_version
  charts/civil-citizen-ui/Chart.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1365

#1349 CIV-5698 - Add CUI Infra and update Key Vaults used
  .gitignore
  infrastructure/README.md
  infrastructure/_main.tf
  infrastructure/_state.tf
  infrastructure/_variables.tf
  infrastructure/app-insights.tf
  infrastructure/key-vault-secrets-civil.tf
  infrastructure/key-vault-secrets-cmc.tf
  infrastructure/key-vault-secrets.tf
  infrastructure/key-vault.tf
  infrastructure/main.tf
  infrastructure/redis.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: destroy

#1367 CIV-5698 - Do not create MI in TF
  infrastructure/key-vault.tf
Labels: fullDeploy, add-or-update

#1370 CIV-5698 - Temp add back in secret
  infrastructure/key-vault-secrets-civil.tf
Labels: add-or-update

#1368 CIV-0000 fix build error._Snyk
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, rel:civil-citizen-ui-pr-1368

#1337 CIV-5511 - Check your answers - Fast Track - Hearing Requirements Pt1
  src/main/common/form/models/claimType.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/buildHearingRequirementSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1337

#1373 CIV-5698 - Grant Civil MI access to Vault
  infrastructure/key-vault.tf
Labels: add-or-update

#1376 CIV-0000 added start:redis on package.json
  package.json
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, rel:civil-citizen-ui-pr-1376

#1377 CIV-7187 bug adding row
  src/main/assets/js/append-row.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1377

#1386 CIV-0000 - Adding new Access Profiles
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1386

#1352 CIV-7081 Dependabot replaced by Renovate
  .github/dependabot.yml
  .github/renovate.json
Labels: ns:civil, prd:civil, fullDeploy, stale, destroy, rel:civil-citizen-ui-pr-1352

#1390 CIV-7328 failing unit tests
  src/main/common/form/validators/phoneUKValidator.ts
  src/main/routes/features/claimantResponse/chooseHowToProceedController.ts
  src/main/routes/urls.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/defendantPhoneController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantPhoneController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1390

#1393 CIV-0000 add languageService.ts
  src/main/app.ts
  src/main/modules/i18n/languageService.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1393

#1379 CIV-6601 claimant intent pi accept
  sonar-project.properties
  src/main/common/form/models/admission/repaymentPlanSummary.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
  src/main/routes/features/claimantResponse/fullAdmitSetDatePaymentController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/views/features/claimantResponse/accept-repayment-plan.njk
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/main/views/macro/repayment-plan-summary.njk
  src/test/unit/routes/features/claimantResponse/acceptRepaymentPlanController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1379
