Repository hmcts/civil-citizen-ui, pull requests merged in 2023-08, with the labels that each got.

#1991 CIV-0000 - Add vulnerabilities to known issues
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1991

#1949 CIV-6250 Defendant dashboard status
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1949

#1977 CIV-0000 - updated index.ts
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/AppRequest.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/document/document.ts
  src/main/modules/oidc/index.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1977

#1953 CIV-9534 create new claim link
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/services/dashboard/draftClaimService.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
  src/test/unit/services/dashboard/draftClaimService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1953

#1951 CIV-9524 update document section from ccd
  src/main/common/models/document/systemGeneratedCaseDocuments.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/caseDocuments/documentService.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/caseDocuments/documentService.test.ts
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1951

#1889 CIV-8197 claim issue tasklist
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/claimTaskListController.ts
  src/main/routes/features/claim/resolvingThisDisputeController.ts
  src/main/routes/features/public/eligibility/eligibleController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/resolvingDisputeService.ts
  src/main/services/features/claim/taskListService.ts
  src/main/views/features/claim/resolving-this-dispute.njk
  src/main/views/features/claim/task-list.njk
  src/main/views/features/public/eligibility/eligible.njk
  src/test/unit/routes/features/claim/claimTaskListController.test.ts
  src/test/unit/routes/features/claim/resolvingThisDisputeController.test.ts
  src/test/unit/services/features/claim/resolvingDisputeService.test.ts
  src/test/unit/services/features/claim/taskListService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1889

#1955 CIV-9841 Eligibility pages as public route
  src/main/modules/oidc/index.ts
  src/test/unit/routes/features/public/eligibility/applyForHelpWithFeesController.test.ts
  src/test/unit/routes/features/public/eligibility/claimAgainstGovernmentController.test.ts
  src/test/unit/routes/features/public/eligibility/claimTypeController.test.ts
  src/test/unit/routes/features/public/eligibility/claimantAddressEligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/claimantOver18EligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/defendantAddressEligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/defendantAgeEligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/eligibleController.test.ts
  src/test/unit/routes/features/public/eligibility/helpWithFeesEligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/helpWithFeesReferenceController.test.ts
  src/test/unit/routes/features/public/eligibility/notEligibleController.test.ts
  src/test/unit/routes/features/public/eligibility/singleDefendantController.test.ts
  src/test/unit/routes/features/public/eligibility/someUsefulInfoFeesController.test.ts
  src/test/unit/routes/features/public/eligibility/tenancyDepositController.test.ts
  src/test/unit/routes/features/public/eligibility/totalAmountController.test.ts
  src/test/unit/routes/features/public/eligibility/tryNewServiceController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1955

#1982 CIV-9718 Upload Documents - Date Validation error messages improved
  src/main/common/form/validators/dateDayValidator.ts
  src/main/common/form/validators/dateMonthValidator.ts
  src/main/common/form/validators/dateYearValidator.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1982

#1911 CIV-8200 CYA - Update content and Submit Function
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/common/form/models/statementOfTruth/qualifiedStatementOfTruthClaimIssue.ts
  src/main/common/form/models/statementOfTruth/statementOfTruthFormClaimIssue.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/services/features/claim/checkAnswers/checkAnswersService.ts
  src/main/views/features/claim/check-answers.njk
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/services/features/claim/checkAnswers/checkAnswersService.test.ts
  src/test/utils/mocks/claimDetailsMock.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1911

#1994 CIV-0000 added CUI URLs for Pally
  src/test/a11y/constants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1994

#1970 CIV-0000 CUI nightly
  Jenkinsfile_nightly
  package.json
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1970

#1992 CIV-9873 fix error message
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1992

#2000 CIV-0000 Update dependencies
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2000

#1940 CIV-9772 Defendant Response PDF and Screen Display
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/rejectClaimConfirmationContent.ts
  src/test/functionalTests/features/response/pages/defendantLipResponse/checkYourAnswers.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1940

#1950 CIV-8843 fix uploadFiles validation
  sonar-project.properties
  src/main/app.ts
  src/main/assets/js/fileValidator.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1950

#1990 CIV-5339 - Release 2 - LIP v LIP Update Access Profile JSON
  bin/add-roles.sh
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1990

#1597 CIV-7748 and CIV-7732 - Button to Hearing Notice in Dashboard
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/tabItem.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/document/systemGeneratedCaseDocuments.ts
  src/main/common/utils/downloadUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/document/documentViewController.ts
  src/main/routes/routes.ts
  src/main/routes/tabs.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/SystemDocumentInfoExtractor.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/hearingTrialLatestUploadContent.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/document/SystemGeneratedCaseDocuments.test.ts
  src/test/unit/common/utils/downloadUtils.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/document/documentViewController.test.ts
  src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
  src/test/unit/services/features/caseProgression/hearingDateTimeFormatter.test.ts
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/hearingTrialLatestUploadContent.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/SystemGeneratedCaseDocumentsMock.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1597

#2011 CIV-0000 Update dependencies
  charts/civil-citizen-ui/Chart.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2011

#2005 CIV-9997 Fix: hidden label pounds
  src/main/views/features/claimantResponse/instalments-plan.njk
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/main/views/features/response/statementOfMeans/courtOrders/court-order.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/main/views/macro/transaction-details.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2005

#1975 CIV-8453 - claim task list
  src/main/common/models/claim.ts
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/routes/features/claim/completingClaimController.ts
  src/main/routes/features/claim/yourDetails/claimantDoBController.ts
  src/main/routes/guards/checkYourAnswersGuard.ts
  src/main/services/features/claim/completingClaimService.ts
  src/main/services/features/claim/taskListService.ts
  src/main/views/features/claim/completing-claim.njk
  src/test/unit/routes/features/claim/completingClaimController.test.ts
  src/test/unit/routes/guards/checkYourAnswersGuard.test.ts
  src/test/unit/services/features/claim/completingClaimService.test.ts
  src/test/unit/services/features/claim/taskListService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1975

#2023 CIV-0000 fix wa issue
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.enableWA.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2023

#2009 CIV-9740 WelshBugFixes-clone
  src/main/common/models/taskList/TaskStatus.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/response/responseType/citizenResponseTypeController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/main/views/features/response/task-list.njk
  src/main/views/govukTemplate.njk
  src/main/views/macro/about-claim-widget.njk
  src/main/views/macro/new-line.njk
  src/main/views/macro/time-remaining.njk
  src/main/views/macro/timeline-summary.njk
  src/main/views/service-unavailable-layout.njk
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2009

#2047 CIV-000 Ignore accessibility test principle
  src/test/a11y/a11y.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2047

#1988 CIV-8202 - CIV-9831 - Claim task-list guard and eligibility cookie
  src/main/common/models/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/claim/claimTaskListController.ts
  src/main/routes/features/public/eligibility/eligibleController.ts
  src/main/routes/guards/claimIssueTaskListGuard.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/routes/guards/claimIssueTaskListGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1988

#2051 CIV-0000 Add security check to known issues
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2051

#2022 CIV-9935 Welsh UI bugs
  src/main/common/models/evidence/evidenceType.ts
  src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesCalculation.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/hearingExportsReportBuilderSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/views/macro/timeline-summary.njk
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2022

#1947 CIV-8213 claim submission payment requirement
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/claimSubmittedController.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/claim-submitted.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1947

#1881 CIV-9204 Trial Arrangements: Defendant LiP - Confirmation screen - Case ready for Trial
  src/main/common/form/models/claimSummarySection.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/isCaseReadyController.ts
  src/main/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationContent.ts
  src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationService.ts
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements-confirmation.njk
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/test/a11y/constants.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1881

#2033 Fix: tasklist status colors and translations
  src/main/common/models/taskList/TaskStatus.ts
  src/main/views/features/claim/task-list.njk
  src/main/views/features/claimantResponse/claimant-response-task-list.njk
  src/main/views/features/response/task-list.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2033

#2028 CIV-0000 addcuikeyintf
  infrastructure/key-vault-secrets-serviceauth.tf
Labels: ns:civil, prd:civil, fullDeploy, stale, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2028

#1983 CIV-9829 - added three quarters class to title row to prevent 'Remove button' overlap
  src/main/services/features/caseProgression/disclosureContentBuilder.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/trialContentBuilder.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1983

#2035 CIV-9629 Update hearing notice latest update defendant LiP
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/hearingTrialLatestUploadContent.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/hearingTrialLatestUploadContent.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2035

#2054 CIV-0000 Ignore accessibility test principle
  src/test/a11y/a11y.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2054

#1972 CIV-9830 Trial Arrangement - Error text Finalise Your Trial or Hearing Arrangements
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1972

#2039 CIV-9726 ClaimantIntentJourneyGaurd
  src/main/app.ts
  src/main/routes/guards/claimantIntentGuard.ts
  src/main/routes/urls.ts
  src/test/unit/routes/guards/claimantIntentGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2039

#2042 CIV-1068 - fix for text wrapping in table and text wrapping on tab.
  src/main/assets/scss/main.scss
  src/main/common/models/caseProgression/uploadDocumentsTableSectionBuilder.ts
  src/main/views/features/dashboard/claim-summary.njk
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2042

#2070 CIV-1135 - CUI - Defendant LatestUpdate does not have any content for RejectAll and DisputeAll
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2070

#2075 CIV-0000 Update main.yml to allow 5 digits
  .github/workflows/main.yml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2075

#2053 CIV-10127 Rename DQ URL
  src/main/routes/urls.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2053

#2052 CIV-8631 optional phone
  src/main/services/features/response/mediation/companyTelephoneNumberService.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2052

#1891 CIV-9613 Trial Arrangements - CTA “Finalise your Trial or Hearing Arrangements” - Latest Updates Screen
  src/main/common/models/claim.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/finaliseTrialArrangementsContent.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/finaliseTrialArrangementsContent.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values: enableHelm, pr-values:elasticsearch, pr-values:enableWA, rel:civil-citizen-ui-pr-1891

#2012 CIV-9972 refactor date validation for evidence upload
  src/main/assets/js/fileValidator.js
  src/main/assets/js/remove-error-content.js
  src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
  src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/disclosureContentBuilder.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/trialContentBuilder.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/uploadDocumentsSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2012

#2057 CIV-9910 create trial arragement page guard
  src/main/app.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/guards/caseProgression/trialArragement/trialArrangementsGuard.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/isCaseReadyController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.test.ts
  src/test/unit/routes/guards/caseProgression/trialArragement/trialArrangementsGuard.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseFastTrackMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2057

#2040 CIV-10028 - Defect fix/dashboard status latest updated
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimResponseStatus.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2040

#2025 CIV-8455 - Check your answers Guard Where Claim Submitted
  src/main/routes/guards/checkYourAnswersGuard.ts
  src/test/unit/routes/guards/checkYourAnswersGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2025

#2067 CIV-0010 Remove backlink on contact them page
  src/main/routes/features/dashboard/contactThemController.ts
  src/main/views/features/dashboard/contact-them.njk
  src/test/unit/routes/features/dashboard/contactThemController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2067

#2085 CIV-10302 WelshRegressionBugs
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/hearingExportsReportBuilderSection.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2085

#2065 CIV-0000 post code lookup is failing for adding correspondence address
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app.ts
  src/main/modules/ordance-survey-key/ordanceSurveyKey.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
  src/test/secretsConfig.js
  src/test/unit/modules/ordance-survey-key/ordanceSurveyKey.test.ts
  src/test/unit/routes/features/response/citizenDetails/postcodeLookupController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2065

#2076 CIV-10132 Pence value has single digit in confirmation screen
  src/main/common/utils/numberConverter.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2076

#2078 CIV-10133 Add pound symbol in defendant latest update monetary amounts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2078

#2084 CIV-10165 Getting Mediation screens for Fast Track claims
  src/main/common/utils/taskList/taskListBuilder.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2084

#2096 CIV-10145 Update latest update page content
  src/main/common/models/claim.ts
  src/main/common/models/claimResponseStatus.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2096

#2095 CIV-10139 CIV-10138 counter claim page fix
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/eligibility/send-your-response-by-email.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2095

#2013 CIV-6003 CCJ guard
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/routes/features/claimantResponse/ccj/ccjConfirmationController.ts
  src/main/routes/guards/ccjConfirmationGuard.ts
  src/test/unit/common/models/claimantResponse/ccj/ccjRequest.test.ts
  src/test/unit/routes/guards/ccjConfirmationGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2013

#2061 CIV-8109 Save documents to redis
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/disclosureService.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/expertService.ts
  src/main/services/features/caseProgression/trialService.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/caseProgressionService.test.ts
  src/test/unit/services/features/caseProgression/expertService.test.ts
  src/test/unit/services/features/caseProgression/trialService.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/utils/caseProgression/mockEvidenceUploadSections.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseDocumentUploadedMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2061

#2093 CIV-10097 - made evidence upload available at SDO stage
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, pr-values:enableWA, rel:civil-citizen-ui-pr-2093
