Repository hmcts/civil-citizen-ui, pull requests merged in 2023-07, with the labels that each got.

#1814 CIV-0000 fix memory issues
  jest.config.js
  package.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1814

#1806 CIV-7549 first contact links
  package.json
  src/main/app.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/document/documentDownloadController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/views/features/public/firstContact/claim-summary.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1806

#1805 CIV-9439 RemovingColumnsClaimantCaseList
  src/main/views/features/dashboard/dashboard.njk
  src/test/functionalTests/features/dashboard/pages/dashboard.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1805

#1774 CIV-9370 Fix: phone of undefined
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/functionalTests/features/dashboard/pages/dashboard.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1774

#1778 CIV-8368 added connection for redis testing
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  src/main/app.ts
  src/main/modules/utilityService.ts
  src/test/unit/modules/i18n/i18n.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1778

#1784 CIV-9334 Defendant Sole Trader Full Name Missing
  src/main/views/features/response/citizenDetails/citizen-details.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1784

#1746 CIV-8559 Evidence upload - Small Claims : Upload documents - All sections
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
  src/main/services/features/caseProgression/trialContentBuilder.ts
  src/main/services/features/caseProgression/trialService.ts
  src/main/views/features/caseProgression/upload-documents.njk
  src/test/unit/routes/features/caseProgression/uploadYourDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/trialService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1746

#1830 CIV-0000 bringing back accessibility tests
  Jenkinsfile_CNP
  jest.config.js
  package.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1830

#1812 CIV-9460 footer links
  src/main/modules/nunjucks/index.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/service-unavailable-layout.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1812

#1809 CIV-9482 corrected cancel page and expert name label
  src/main/views/features/caseProgression/cancel-your-upload.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1809

#1808 CIV-4449 Update survey link
  src/main/views/external-urls.njk
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1808

#1839 CIV-0000 FTFix
  src/test/functionalTests/tests/response_partAdmit_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1839

#1829 CIV-9597 Fix response deadline complete task
  src/main/services/features/common/responseDeadlineAgreedService.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1829

#1743 CIV-7500 pcq journey check and submit
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/app/client/pcq/generatePcqId.ts
  src/main/app/client/pcq/generatePcqToken.ts
  src/main/app/client/pcq/pcqClient.ts
  src/main/app/client/pcq/savePcqIdClaim.ts
  src/main/common/models/claim.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes/features/response/checkAnswersController.ts
  src/main/routes/guards/pcqGuard.ts
  src/test/functionalTests/features/response/pages/defendantLipResponse/checkYourAnswers.js
  src/test/secretsConfig.js
  src/test/unit/app/client/pcq/generatePcqId.test.ts
  src/test/unit/app/client/pcq/pcqClient.test.ts
  src/test/unit/app/client/pcq/savePcqIdClaim.test.ts
  src/test/unit/routes/features/response/checkAnswersController.test.ts
  src/test/utils/mocks/civilClaimResponseApplicanIndividualMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1743

#1749 CIV-6958 delete unnecesary expert data
  src/main/routes/features/directionsQuestionnaire/experts/expertSmallClaimsController.ts
  src/main/services/features/directionsQuestionnaire/expertRequiredValueService.ts
  src/test/config.js
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
  src/test/functionalTests/tests/dashboard_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertSmallClaimsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertRequiredValueService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1749

#1788 CIV-9393 Fix: not show financial section when organisation or company
  src/main/services/features/response/checkAnswers/checkAnswersService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1788

#1832 CIV-9218 enable extended response time test
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1832

#1859 CIV-0000 Update: add minimist and toough-cookie in resolutions
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1859

#1860 CIV-9218 revert
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1860

#1865 CIV-0000 Adding Elastic Search Limit
  charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1865

#1828 CIV-2695 - Reject - Reject all and Counterclaim - Court fees for Fast Track
  src/main/common/models/feeRange.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/eligibility/sendYourResponseByEmailController.ts
  src/test/unit/common/models/feeRange.test.ts
  src/test/unit/routes/features/response/eligibility/sendYourResponseByEmailController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1828

#1835 CIV-8405 Set Up Case Details Tab
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/services/translation/claim/moneyConversation.ts
  src/main/services/translation/convertToCUI/convertToCUICourtOrders.ts
  src/main/services/translation/convertToCUI/convertToCUIDebts.ts
  src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
  src/main/services/translation/convertToCUI/convertToCUIPriorityDebts.ts
  src/main/services/translation/convertToCUI/convertToCUIRecurringExpense.ts
  src/main/services/translation/convertToCUI/convertToCUIRecurringIncome.ts
  src/main/services/translation/convertToCUI/convertToCUISelfEmploymentDetails.ts
  src/main/services/translation/convertToCUI/convertToCUISelfEmploymentTaxPayment.ts
  src/main/services/translation/convertToCUI/convertToCUIStatementOfMeans.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDCourtOrders.ts
  src/main/services/translation/response/convertToCCDDebtDetails.ts
  src/main/services/translation/response/convertToCCDLoanCredit.ts
  src/main/services/translation/response/convertToCCDRecurringExpense.ts
  src/main/services/translation/response/convertToCCDRecurringIncome.ts
  src/main/services/translation/response/convertToCCDRepaymentPlan.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDSelfEmploymentDetails.ts
  src/test/unit/common/models/ccdResponse/ccdRepaymentPlan.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICourtOrders.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIDebts.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIMediation.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPriorityDebts.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIRecurringIncome.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIRespondentLipResponse.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUISelfEmploymentDetails.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUISelfEmploymentTaxPayment.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIStatementOfMeans.test.ts
  src/test/unit/services/translation/convertToCUI/converttoCUIRecurringExpenses.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDCourtOrders.test.ts
  src/test/unit/services/translation/response/convertToCCDDebtDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDLoanCredit.test.ts
  src/test/unit/services/translation/response/convertToCCDRecurringExpense.test.ts
  src/test/unit/services/translation/response/convertToCCDRecurringIncome.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
  src/test/unit/services/translation/response/convertToCCDSelfEmploymentDetails.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1835

#1737 CIV-9008 Added text input validation for remaining witness and expert…
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
  src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/disclosureContentBuilder.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/expertService.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/uploadDocumentsSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/disclosureService.test.ts
  src/test/unit/services/features/caseProgression/expertService.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1737

#1844 CIV-7160 Defendant Latest Update Screens
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimResponseStatus.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1844

#1831 CIV-9464 Adding all the Files the Case Progression Test Fast Track....
  src/test/functionalTests/features/caseProgression/pages/uploadYourDocument.js
  src/test/functionalTests/features/caseProgression/pages/uploadYourDocumentsIntroduction.js
  src/test/functionalTests/features/caseProgression/pages/whatTypeOfDocumentsDoYouWantToUpload.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/features/caseProgression/util/StringUtilsComponent.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createDefendantResponse.js
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1831

#1833 CIV-9608 Upload evidence fix
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/caseProgression/typeOfDocuments.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1833

#1845 CIV-7141 Dashboard status Part1
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/mediation/mediationAgreement.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/public/eligibility/notEligibleController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1845

#1760 CIV-7555 language preference guard
  src/main/routes/features/response/bilingualLangPreferenceController.ts
  src/main/routes/guards/languagePreferenceGuard.ts
  src/main/services/features/response/bilingualLangPreferenceService.ts
  src/test/unit/routes/guards/languagePreferenceGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1760

#1763 CIV-9369 Pence value in the amount is not displaying properly
  src/main/common/utils/taskList/tasks/whenWillYouPay.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/views/features/response/admission/payment-option.njk
  src/test/unit/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1763

#1848 CIV-0000 all_validation_tickets
  sonar-project.properties
  src/main/assets/js/fileValidator.js
  src/main/assets/scss/main.scss
  src/main/common/form/models/caseProgression/documentUploadSubmission.ts
  src/main/common/form/validators/dateDayValidator.ts
  src/main/common/form/validators/dateMonthValidator.ts
  src/main/common/form/validators/dateYearValidator.ts
  src/main/common/form/validators/isAllowedMimeType.ts
  src/main/common/form/validators/isFileSize.ts
  src/main/common/models/caseProgression/documentUploadSections.ts
  src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
  src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
  src/main/index.js
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/routes/features/caseProgression/uploadFileController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/TypeOfDocumentSectionMapper.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildDisclosureSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildExpertEvidenceSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildTrialDocumentsSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildWitnessEvidenceSection.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/disclosureContentBuilder.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/trialContentBuilder.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/views/features/caseProgression/check-answers.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/form/validators/isAllowedMimeType.test.ts
  src/test/unit/common/form/validators/isFileSize.test.ts
  src/test/unit/common/models/caseProgression/uploadDocumentsSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/routes/features/caseProgression/uploadFileController.test.ts
  src/test/unit/services/features/caseProgression/disclosureService.test.ts
  src/test/unit/services/features/caseProgression/expertService.test.ts
  src/test/unit/services/features/caseProgression/trialService.test.ts
  src/test/unit/services/features/caseProgression/typeOfDocumentMapperTest.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1848

#1795 CIV-7951 - Change documents tab to show Evidence Upload Documents
  src/main/common/models/caseProgression/TypesOfEvidenceUploadDocument.ts
  src/main/common/models/caseProgression/uploadDocumentsTableSectionBuilder.ts
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/models/summaryList/summaryList.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/caseProgression/documentTableBuilder.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/services/translation/convertToCUI/convertToCUIEvidenceUpload.ts
  src/main/views/features/dashboard/claim-summary.njk
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/caseProgression/caseProgressionService.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
  src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIEvidenceUpload.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1795

#1890 CIV-0000 FTFixForMaster
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecFastTrackLrvLR.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecLRvLR.js
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1890

#1904 CIV-0000 Adding memory to node js pod
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1904

#1887 CIV-0000 key vault name
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  infrastructure/_variables.tf
  infrastructure/key-vault.tf
Labels: fullDeploy, destroy, pr-values:elasticsearch

#1838 CIV-7954 - Adding update to dashboard if new evidence uploaded
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/urls.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/newUploadContent.ts
  src/main/services/translation/convertToCUI/convertToCUIEvidenceUpload.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIEvidenceUpload.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1838

#1907 CIV-9223 welsh translations42
  sonar-project.properties
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/addSupportRequiredList.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/hearingExportsReportBuilderSection.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1907

#1909 CIV-9513 remove duplication
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1909

#1877 CIV-9365 Adding Changes for Mediation
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/test/unit/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1877

#1871 CIV-8643 update c UI document download controller to use doc
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/FileResponse.ts
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/document/systemGeneratedCaseDocuments.ts
  src/main/common/utils/documentTypeConverter.ts
  src/main/common/utils/downloadUtils.ts
  src/main/common/utils/stringUtils.ts
  src/main/routes/features/claim/claimSubmittedController.ts
  src/main/routes/features/document/documentDownloadController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/SystemDocumentInfoExtractor.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
  src/test/unit/common/models/document/SystemGeneratedCaseDocuments.test.ts
  src/test/unit/common/utils/documentTypeConverter.test.ts
  src/test/unit/common/utils/downloadUtils.test.ts
  src/test/unit/common/utils/stringUtils.test.ts
  src/test/unit/routes/features/document/documentDownloadController.test.ts
  src/test/unit/services/features/caseProgression/SystemDocumentInfoExtractor.test.ts
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/utils/mocks/SystemGeneratedCaseDocumentsMock.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1871

#1932 CIV-0000 Update renovate json
  .github/renovate.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1932

#1867 CIV-9342 add defendant pdf tab docs
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/document/documentDownloadController.ts
  src/main/routes/features/response/submitConfirmationController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/response/task-list.njk
  src/main/views/macro/about-claim-widget.njk
  src/test/unit/routes/features/document/documentDownloadController.test.ts
  src/test/unit/services/features/dashboard/claimDocuments/claimDocumentContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/SystemGeneratedCaseDocumentsMock.ts
  src/test/utils/mocks/civilClaimResponsePDFTimelineMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1867

#1863 CIV-9124 Finalise trial start screen
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/caseProgression/trialArrangements/finaliseYourTrialSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/trialArrangements/finaliseYourTrialSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1863

#1930 CIV-3046 Display and dowload timeline pdf
  src/main/common/utils/downloadUtils.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
  src/main/routes/features/response/timelineOfEvents/theirPdfTimelineDownloadController.ts
  src/main/routes/urls.ts
  src/test/unit/common/utils/downloadUtils.test.ts
  src/test/unit/routes/features/response/timlineOfEvents/theirPdfTimelineDownloadController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1930

#1708 CIV-6241 p3 defendant dashboard status
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1708

#1910 CIV-9599 Remove error messages on new block with add another
  src/main/assets/js/remove-error-content.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1910

#1880 CIV-9127 Trial Arrangements - Has anything changed to the support
  src/main/common/models/caseProgression/trialArrangements/hasAnythingChangedForm.ts
  src/main/common/models/caseProgression/uploadYourDocumentsSectionBuilder.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/trialArrangements/hasAnythingChanged.ts
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/trialArrangements/hasAnythingChangedForm.test.ts
  src/test/unit/common/models/caseProgression/uploadYourDocumentsSectionBuilder.test.ts
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/hasAnythingChanged.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1880

#1912 CIV-9640 Update List of Claims to show CCD claims first then OCMC claims
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/dashboard/dashboarddefendantresponse.ts
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/services/features/dashboard/claimPaginationService.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
  src/test/unit/services/features/dashboard/claimPaginationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1912

#1916 CIV-9126 Is the case ready for trial?
  src/main/common/models/caseProgression/trialArrangements/isCaseReadyForm.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/isCaseReadyController.ts
  src/main/routes/routes.ts
  src/main/services/features/caseProgression/trialArrangements/isCaseReady.ts
  src/main/views/features/caseProgression/trialArrangements/is-case-ready.njk
  src/test/unit/common/models/caseProgression/trialArrangements/isCaseReadyForm.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/isCaseReadyController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/isCaseReady.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1916
