Repository hmcts/civil-citizen-ui, pull requests merged in 2023-12, with the labels that each got.

#2689 CIV-0000 Fix OCMC Pin
  src/main/modules/helmet/index.ts
  src/main/routes/features/public/firstContact/pinController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2689

#2660 CIV-7484 hearing fee pay hearing fee page 1
  src/main/common/models/caseProgression/hearingFee/hearingFee.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/payHearingFeeStartScreenController.ts
  src/main/routes/routes.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeStartPageContent.ts
  src/main/views/features/caseProgression/hearingFee/pay-hearing-fee-start.njk
  src/test/unit/routes/features/caseProgression/hearingFee/payHearingFeeStartScreenController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/heringFeeStartPageContent.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2660

#2693 CIV-11895 for merge
  src/main/routes/features/claim/yourDetails/claimantDoBController.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/test/unit/routes/features/claim/claimantDoBController.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2693

#2717 CIV-0000 update civil service chart to latest
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/test/config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2717

#2714 CIV-11821 pin notification banner
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/firstContact/claim-reference.njk
  src/main/views/features/public/firstContact/pin.njk
  src/main/views/features/public/firstContact/signposting.njk
  src/main/views/macro/pin-error-notification-banner.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2714

#2735 CIV-0000 -- unassign role assignments for the user from the case after testing
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_uploadevidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_uploadevidence_small_claims_tests.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_comp_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2735

#2736 CIV-11489 Pay-Hearing-Fee-Handle-Return-Url
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/feePayment/paymentInformation.ts
  src/main/routes/features/caseProgression/hearingFee/paymentConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
  src/main/services/features/feePayment/feePaymentService.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/paymentConfirmationController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/paymentConfirmationService.test.ts
  src/test/unit/services/features/feePayment/feePaymentService.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2736

#2743 CIV-0000 - Run nightly on aat
  Jenkinsfile_nightly
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2743

#2506 CIV-8997 Create draft claim form
  src/main/common/models/ccdResponse/ccdParty.ts
  src/main/routes/features/claim/yourDetails/claimantDoBController.ts
  src/main/services/translation/convertToCUI/convertToCUIParty.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterDateOfBirthDetails.js
  src/test/unit/routes/features/claim/claimantDoBController.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIParty.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2506

#2727 CIV-11846 CUI 'Respond to claim' page content Welsh update
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2727

#2748 CIV-11874 Defendant response document
  src/main/common/models/claim.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2748

#2738 CIV-0000 - added draft changes with new api.
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/main/views/features/public/firstContact/claim-reference.njk
  src/main/views/features/public/firstContact/pin.njk
  src/main/views/features/public/firstContact/signposting.njk
  src/main/views/macro/pin-error-notification-banner.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2738

#2656 CIV-9024 Claimant Intent: Judgement by admission RPA
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/services/features/claimantResponse/submitClaimantResponse.ts
  src/main/services/translation/claimantResponse/ccdRequestJudgementTranslation.ts
  src/test/unit/services/features/claimantResponse/submitClaimantReponse.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2656

#2672 CIV-11733 CCD translations for court calculator decision
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2672

#2333 CIV-10962 Claimant Intent – CYA: Manual Determination
  src/main/common/models/claimantResponse/checkAnswers.ts
  src/main/common/utils/checkYourAnswer/formatAnswer.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2333

#2788 CIV-11749 fix object error
  src/main/routes/features/claimantResponse/courtProposedDateController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2788

#2257 CIV-9675 - Allowed trial ready check for claimant
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccdResponse/ccdTrialArrangementsHearingRequirements.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaireType.ts
  src/main/common/models/document/systemGeneratedCaseDocuments.ts
  src/main/common/models/events/caseEvent.ts
  src/main/routes/features/caseProgression/trialArrangements/cancelTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
  src/main/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/routes/features/caseProgression/trialArrangements/isCaseReadyController.ts
  src/main/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/SystemDocumentInfoExtractor.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/main/services/features/caseProgression/trialArrangements/hasAnythingChanged.ts
  src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationContent.ts
  src/main/services/features/caseProgression/trialArrangements/trialArrangementsService.ts
  src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
  src/main/services/translation/caseProgression/trialArrangements/convertToCCDTrialArrangements.ts
  src/main/services/translation/convertToCUI/convertToCUITrialArrangements.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/checkAnswersController.test.ts
  src/test/unit/services/features/caseProgression/caseProgressionService.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/hasAnythingChanged.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationService.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/trialArrangementsService.test.ts
  src/test/unit/services/translation/caseProgression/trialArrangements/convertToCCDTrialArrangements.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUITrialArrangements.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mocks/civilClaimResponseFastTrackMock.json
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2257

#2787 CIV-0000 - CMC pin validate endpoint url renamed.
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2787

#2641 CIV-11485 confirmation business
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/claimantResponseConfirmationContentService.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/financialDetailsBuilder.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/convertToCUI/convertToCUICCJRequest.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2641

#2416 CIV-11186 PartAdmitPayBySetDateWelsh
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/getSetDatePaymentDetails.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/getSetDatePaymentDetails.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2416

#2567 CIV-7828 - Generic page for help with fees
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/claim.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.ts
  src/main/routes/features/helpWithFees/helpWithFeesController.ts
  src/main/routes/guards/helpWithFees/helpWithFeesGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/helpWithFees/applyHelpWithFeesService.ts
  src/main/views/features/dashboard/item-content.njk
  src/main/views/features/helpWithFees/help-fees-start.njk
  src/test/unit/common/models/caseProgression/trialArrangements/finaliseYourTrialSectionBuilder.test.ts
  src/test/unit/common/models/caseProgression/uploadYourDocumentsSectionBuilder.test.ts
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.test.ts
  src/test/unit/routes/features/helpWithFees/helpWithFeesController.test.ts
  src/test/unit/routes/guards/helpWithFees/helpWithFeesGuard.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/hearingDurationAndOtherInformation.test.ts
  src/test/unit/services/features/helpWithFees/applyHelpWithFeesService.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseWithFeeTypeMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2567

#2687 CIV-11333 CancelLinkForEvidenceUpload
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
  src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2687

#2782 CIV-8786 claimant intent confirmation screen county court judgement requested reject plan
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/ccjConfirmationBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2782

#2626 CIV-11614 PartAdmitPayInstalments
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/views/macro/repayment-plan-summary.njk
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2626

#2765 CIV-8950 The repayment plan screen" Claimant and Defendant
  src/main/common/form/models/admission/repaymentInformation.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryClaimantController.ts
  src/main/routes/features/claimantResponse/ccj/repaymentPlanSummaryDefendantController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/ccj/repaymentPlanSummaryService.ts
  src/main/views/features/claimantResponse/ccj/repayment-plan-summary-claimant.njk
  src/main/views/features/claimantResponse/ccj/repayment-plan-summary.njk
  src/test/unit/routes/features/claimantResponse/ccj/repaymentPlanSummaryCliamantController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/repaymentPlanSummaryDefendantController.test.ts
  src/test/unit/services/features/claimantResponse/ccj/repaymentPlanSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2765

#2453 CIV-11279 FullDefence+FullDisputeWelsh
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/disputeConfirmationContentBuilder.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmissionAlreadyPaidDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2453

#2544 CIV-8903 dashboard settlement agreement
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2544

#2710 CIV-11781 clicking welsh toggle redirects to preview page
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/routes/features/claimantResponse/reviewDefendantsResponseController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2710

#2709 CIV-11254 pay hearing fee redirect to gov pay
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/caseProgression/hearing.ts
  src/main/common/models/feePayment/paymentInformation.ts
  src/main/modules/helmet/index.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.ts
  src/main/routes/features/caseProgression/hearingFee/makePaymentAgainController.ts
  src/main/routes/features/caseProgression/hearingFee/paymentConfirmationController.ts
  src/main/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
  src/main/services/features/caseProgression/hearingFee/makePaymentAgainService.ts
  src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
  src/main/services/features/feePayment/feePaymentService.ts
  src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/makePaymentAgainController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/paymentConfirmationController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/makePaymentAgainService.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/paymentConfirmationService.test.ts
  src/test/unit/services/features/feePayment/feePaymentService.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2709

#2825 CIV-8903 dashboard settlement agreement-revert
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2825

#2803 CIV-11641 - Documents Referred added field
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadedSummaryRows.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadSummaryRows.test.ts
  src/test/unit/services/features/caseProgression/uploadedEvidenceFormatter.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
  src/test/utils/caseProgression/mockEvidenceUploadSections.ts
  src/test/utils/caseProgression/mockEvidenceUploadSummaryRows.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2803

#2806 CIV-11368 - Update documents tab so trial arrangements shows
  src/main/services/features/dashboard/claimSummaryService.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2806
