Repository hmcts/civil-citizen-ui, pull requests merged in 2023-04, with the labels that each got.

#1484 CIV-7613 - CCD to CUI Transform response data - Part Admit PT1
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/claim.ts
  src/main/services/translation/convertToCUI/convertToCUIAddress.ts
  src/main/services/translation/convertToCUI/convertToCUIParty.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIAddress.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIParty.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1484

#1498 CIV-7561 Remove empty Error:
  src/main/views/features/response/statementOfMeans/employment/who-employs-you.njk
  src/main/views/macro/employer.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1498

#1457 CIV-6238 - Welsh - Bilingual language preference
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/services/translation/convertToCUI/convertToCUIRespondentLiPResponse.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIRespondentLipResponse.test.ts
  src/test/unit/services/translation/response/convertToCCDRepondentResponseLanguage.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1457

#1482 CIV-7231 Enforcing conventions on branch names and commit messages
  .git-config/hooks/commit-msg
  .git-config/hooks/pre-commit
  .github/workflows/main.yml
  README.md
Labels: stale

#1445 CIV-6215 added additional excludes
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1445

#1502 CIV-7416 non text pounds
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claimantResponse/instalments-plan.njk
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/main/views/features/response/statementOfMeans/courtOrders/court-order.njk
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/on-tax-payments.njk
  src/main/views/features/response/statementOfMeans/employment/selfEmployed/self-employed-as.njk
  src/main/views/macro/bank-account.njk
  src/main/views/macro/transaction-details.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1502

#1507 CIV-7438 link purpose
  src/main/common/models/summaryList/summaryList.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/dashboard/dashboard.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1507

#1515 CIV-0000 Exclude hnl nonprod
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1515

#1503 CIV-7417 Labels for multi-row
  src/main/assets/js/append-row.js
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/mediation/can-we-use.njk
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/macro/bank-account.njk
  src/main/views/macro/employer.njk
  src/main/views/macro/telephone.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1503

#1511 CIV-7902 welsh translation28
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1511

#1509 CIV-7439 info and relationships
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
  src/main/views/features/claim/yourDetails/claimant-organisation-details.njk
  src/main/views/features/mediation/i-dont-want-free-mediation.njk
  src/main/views/features/mediation/mediation-disagreement.njk
  src/main/views/features/response/admission/payment-date.njk
  src/main/views/features/response/citizenDob/citizen-dob.njk
  src/main/views/features/response/citizenResponseType/details-content.njk
  src/main/views/features/response/financialDetails/financial-details.njk
  src/main/views/features/response/repaymentPlan/repaymentPlan.njk
  src/main/views/features/response/request-more-time.njk
  src/main/views/features/response/response-deadline-options.njk
  src/main/views/features/response/statementOfMeans/courtOrders/court-orders.njk
  src/main/views/features/response/statementOfMeans/debts/debts.njk
  src/main/views/features/response/statementOfMeans/dependants/dependants.njk
  src/main/views/features/response/statementOfMeans/residence.njk
  src/main/views/macro/address.njk
  src/test/a11y/a11y.test.ts
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterDateOfBirthDetails.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1509

#1523 CIV-0000 Add windows specific lint config (ignore CRLFs)
  package.json
  win.eslint.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1523

#1526 CIV-0000 Patch-issue Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0'
  yarn-audit-known-issue
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1526

#1520 CIV-0000 create latest update builder
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1520

#1528 CIV-0000 Use working version of definition-processor until it's fixed
  bin/utils/process-definition.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1528

#1529 CIV-0000 - Fixed build errors in CUI.
  src/test/unit/routes/guards/allResponseTasksCompleteGuard.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1529

#1533 CIV-7982 Initial yarn 3 migration changes
  .dockerignore
  .gitattributes
  .gitignore
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  Dockerfile
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1533

#1522 CIV-7618 CCD to CUI Common Part Admit
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/services/translation/convertToCUI/convertToCUIDQs.ts
  src/main/services/translation/convertToCUI/convertToCUIHearing.ts
  src/main/services/translation/convertToCUI/convertToCUIVulnerability.ts
  src/main/services/translation/convertToCUI/convertToCUIWelshLanguageRequirements.ts
  src/main/services/translation/convertToCUI/convertToCUIWitnesses.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIDQs.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIHearing.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIVulnerability.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIWelshLanguageRequirements.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIWitnesses.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1522

#1524 CIV-0000 Call yarn build from jenkins
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1524

#1535 CIV-8039 create green button
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1535

#1537 CIV-0000 Move back to using the latest definition-processor
  bin/utils/process-definition.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1537

#1417 CIV-5788 transform p2 for defendant response
  src/main/common/models/ccdResponse/ccdHowToAddTimeline.ts
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/ccdResponse/ccdResponseType.ts
  src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/response/evidence/evidenceController.ts
  src/main/services/features/response/evidence/evidenceService.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDEvidence.ts
  src/main/services/translation/response/convertToCCDPaymentOption.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
  src/main/views/webpack/js.njk
  src/test/unit/routes/features/response/evidence/evidenceController.test.ts
  src/test/unit/services/features/response/evidence/evidenceService.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDAdmitPartRoute.test.ts
  src/test/unit/services/translation/response/convertToCCDPaymentOptions.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondentLiPResponse.test.ts
  src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1417

#1547 CIV-0000 Updating idam url
  Jenkinsfile_CNP
  bin/add-roles.sh
  src/test/config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1547

#1531 CIV-8029 Find address accessibility
  src/main/modules/nunjucks/index.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1531

#1512 CIV-7615 Translate Uncommon DQ fields to CUI
  src/main/common/form/models/claimType.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/routes/urls.ts
  src/main/services/translation/convertToCUI/convertToCUIDQs.ts
  src/main/services/translation/convertToCUI/convertToCUIExperts.ts
  src/main/services/translation/convertToCUI/convertToCUIHearing.ts
  src/main/services/translation/response/convertToCCDExpert.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIDQs.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIExperts.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1512

#1541 CIV-0000 refactoredFTs
  src/test/functionalTests/features/response/pages/defendantLipResponse/bilingualLanguagePreference.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterContactNumberDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterDateOfBirthDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/confirmYourDetails/enterNameAndAddressDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/cantAttendHearing.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/courtLocation.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/defendantWitnesses.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/dqExpert.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/expertReportDetails.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/giveEvidenceYourself.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/phoneOrVideoHearing.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/supportRequired.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/vulnerability.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/welshLanguage.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantLatestUpdate.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/taskList.js
  src/test/functionalTests/features/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpec.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1541

#1501 CIV-6214 dahsboard status part2
  src/main/app.ts
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/views/features/breathingSpace/check-answers.njk
  src/test/unit/app/client/legacyDraftStoreClient.test.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1501

#1519 CIV-7972 welsh translation30
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1519

#1465 CIV-7614 CCD to CUI transform pt2
  src/main/common/form/models/genericForm.ts
  src/main/common/form/models/genericYesNo.ts
  src/main/common/form/models/statementOfMeans/expensesAndIncome/transactionSource.ts
  src/main/common/models/breathingSpace/debtRespiteStartDate.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/hearing/unavailableDates.ts
  src/main/routes/features/claim/interest/claimInterestController.ts
  src/main/routes/features/claim/interest/claimantInterestFromController.ts
  src/main/routes/features/claim/totalAmountController.ts
  src/main/routes/features/claim/yourDetails/defendantEmailController.ts
  src/main/routes/features/claimantResponse/courtProposedPlanController.ts
  src/main/services/features/response/admission/howMuchHaveYouPaidService.ts
  src/main/services/translation/convertToCUI/convertToCUIEvidence.ts
  src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/convertToCCDRecurringExpense.ts
  src/main/services/translation/response/convertToCCDRecurringIncome.ts
  src/test/unit/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1465

#1552 CIV-0000 WA changes
  charts/civil-citizen-ui/values.enableWA.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, pr-values:enableWA, rel:civil-citizen-ui-pr-1552

#1491 CIV-6668 add tenant-id to import-bpmn-diagram.sh
  bin/import-bpmn-diagram.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1491

#1561 CIV-TASK - fix build errors raised by new version of eslint (auto updated)
  package.json
  src/main/modules/draft-store/index.ts
  src/main/modules/helmet/index.ts
  src/main/routes/features/response/financialDetails/financialDetailsController.ts
  src/main/views/webpack/js.njk
  src/test/unit/modules/draft-store/draftStore.test.ts
  src/test/unit/routes/features/response/financial-details/financialDetailsController.test.ts
  src/test/utils/mockDraftStore.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1561

#1564 CIV-7712 includeRejectAll
  package.json
  src/test/functionalTests/features/response/pages/defendantLipResponse/checkYourAnswers.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/whyDoYouDisagree.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/whyDoYouDisagreeTheClaimAmount.js
  src/test/functionalTests/features/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1564

#1567 CIV-0000 Update WA_SUPPORTED_JURISDICTIONS not for civil as preview doesnt have WA setup
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1567

#1557 CIV-7493 CCD to CUI Translation Fields Full Admit
  src/main/services/translation/convertToCUI/convertToCUIFullAdmission.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIFullAdmission.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1557

#1543 CIV-7991 welsh translation31
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1543
