Repository hmcts/civil-citizen-ui, pull requests merged in 2023-11, with the labels that each got.

#2350 CIV-10809 Claimant Dashboard Status - Default Judgement
  src/main/common/models/dashboard/dashboardItem.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2350

#2391 CIV-10893 - Court Calculator Trigger and Navigation
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/claimantResponse/ClaimantProposedPlan.ts
  src/main/common/models/claimantResponse/RepaymentDecisionType.ts
  src/main/routes/features/claimantResponse/claimantSuggestedInstalmentsController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.ts
  src/main/services/translation/response/convertToCCDRepaymentPlan.ts
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedInstalmentsController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedPaymentDateController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.ts.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2391

#2337 CIV-10634 Added message for claimant reject confirmation
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/partAdmitConfirmationContentBuilder.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/models/claimantResponse.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2337

#2458 CIV-11335 - Scenario to Check the Latest Update Tab for the Trial Arrangements by the Other Party
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/steps/trialArrangementSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createATrialArrangement.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2458

#2471 CIV-10972 new scenario for the Trial Arrangements Journey.
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/isYourCaseReadyForTrial.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/trialArrangementsConfirmation.js
  src/test/functionalTests/features/caseProgression/steps/trialArrangementSteps.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2471

#2376 CIV-11180 Claimant Intention -Terms of agreement and Do you want to Settle screen bug fix
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/signSettlmentAgreementController.ts
  src/main/views/features/claimantResponse/settle-admitted.njk
  src/main/views/features/claimantResponse/sign-settlement-agreement.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2376

#2447 CIV-11318 fix logout button issue
  src/main/views/claim-details-tpl.njk
  src/main/views/features/public/claim/defendant-phone.njk
  src/main/views/features/public/cookies/cookies-view.njk
  src/main/views/features/public/eligibility/apply-for-help-with-fees.njk
  src/main/views/features/public/eligibility/claim-against-government.njk
  src/main/views/features/public/eligibility/claim-type.njk
  src/main/views/features/public/eligibility/claimant-address-eligibility.njk
  src/main/views/features/public/eligibility/defendant-age.njk
  src/main/views/features/public/eligibility/defendant-eligible-address.njk
  src/main/views/features/public/eligibility/eligible.njk
  src/main/views/features/public/eligibility/help-with-fees-reference.njk
  src/main/views/features/public/eligibility/help-with-fees.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-for-tenancy-deposit.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-on-behalf.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-value-not-known.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-value-over-25000.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claimant-address.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claimant-under-18.njk
  src/main/views/features/public/eligibility/not-eligible-includes/defendant-address.njk
  src/main/views/features/public/eligibility/not-eligible-includes/government-department.njk
  src/main/views/features/public/eligibility/not-eligible-includes/multiple-claimants.njk
  src/main/views/features/public/eligibility/not-eligible-includes/multiple-defendants.njk
  src/main/views/features/public/eligibility/not-eligible-includes/under-18-defendant.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/main/views/features/public/eligibility/over-18.njk
  src/main/views/features/public/eligibility/single-defendant.njk
  src/main/views/features/public/eligibility/some-useful-info-fees.njk
  src/main/views/features/public/eligibility/tenancy-deposit.njk
  src/main/views/features/public/eligibility/total-amount.njk
  src/main/views/features/public/eligibility/try-new-service.njk
  src/main/views/features/public/eligibility/you-can-use-service.njk
  src/main/views/features/public/firstContact/access-denied.njk
  src/main/views/features/public/firstContact/claim-reference.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/public/firstContact/pin.njk
  src/main/views/features/public/firstContact/signposting.njk
  src/main/views/macro/header.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2447

#2520 CIV-0000 Fix Functional Attempt
  src/main/services/features/caseProgression/SystemDocumentInfoExtractor.ts
  src/test/functionalTests/specClaimHelpers/fixtures/events/createAnAssistedOrder.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToSDOState.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createSDO.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2520

#2451 CIV-9528 Update LR Pay Immediately screen
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/response/submitConfirmationController.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdateService.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationService.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdateService.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/utils/mocks/fullAdmitPayByImmediatelyMock.json
  src/test/utils/mocks/partAdmitPayByImmediatelyMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2451

#2476 CIV-11384 Prevent storage of data when defendant changes their response part way through submission
  src/main/common/form/models/admission/paymentOption/paymentOption.ts
  src/main/services/features/response/admission/paymentOptionService.ts
  src/main/services/features/response/responseType/citizenResponseTypeService.ts
  src/test/unit/services/features/response/admission/paymentOptionService.test.ts
  src/test/unit/services/features/response/responseType/citizenResponseTypeService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2476

#2450 CIV-10441 Limit number of characters entered on the text boxes are not working as expected
  src/main/common/form/models/address.ts
  src/main/common/form/models/statementOfTruth/qualifiedStatementOfTruth.ts
  src/main/common/form/validators/validationConstraints.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/macro/address.njk
  src/main/views/macro/statement-of-truth.njk
  src/test/unit/common/form/validators/QualifiedStatementOfTruth.test.ts
  src/test/unit/common/form/validators/address.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2450

#2538 CIV-0000 Ft fix
  src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/addYourTimeLine.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2538

#2535 CIV-11517 Mediation content
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/fullDefenceConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/rejectClaimConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationService.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2535

#2519 CIV-11487 R1 - Welsh language preference - Content change
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/bilingual-language-preference.njk
  src/test/functionalTests/features/response/pages/defendantLipResponse/bilingualLanguagePreference.js
  src/test/unit/routes/features/response/bilingualLangPreferenceController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2519

#2532 CIV-11513 - Part/Full admit pay immediately - 5 working days calculation
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claim.ts
  src/main/routes/features/response/submitConfirmationController.ts
  src/main/services/features/response/responseDeadline/extendResponseDeadlineService.ts
  src/main/services/features/response/submission/submitResponse.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/submitConfirmationBuilder.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDPayBySetDate.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/services/features/response/responseDeadline/extendResponseDeadlineService.test.ts
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDPayBySetDate.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2532

#2529 CIV-11516 Content change for LiP Small Claims DQs
  sonar-project.properties
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/supportRequiredController.ts
  src/main/routes/features/directionsQuestionnaire/witnesses/otherWitnessesController.ts
  src/main/views/features/directionsQuestionnaire/support-required-list.njk
  src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
  src/test/config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-2529

#2555 CIV-0000 skipping test
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2555

#2552 CIV-11550 R1 welsh translations
  src/main/common/models/dashboard/tabItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/common/addSupportRequiredList.ts
  src/main/services/features/common/buildCommonHearingRequirements.ts
  src/main/services/features/common/buildFastTrackHearingRequirements.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseToClaimSection.ts
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
  src/main/views/features/claim/yourDetails/claimant-organisation-details.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/directionsQuestionnaire/experts/sent-expert-reports.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/response/admission/partialAdmission/already-paid.njk
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/main/views/macro/amount-breakdown.njk
  src/main/views/macro/statement-of-truth.njk
  src/main/views/macro/types-of-senior-position.njk
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseToClaimSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2552

#2473 CIV-11326 Claimant Intent - Part admit pay set by date - How they want to pay screen missing
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/routes/guards/signSettlmentAgreementGuard.ts
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
  src/main/views/features/claimantResponse/how-they-want-to-pay-response.njk
  src/test/unit/routes/features/claimantResponse/reviewDefendantsResponseController.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2473

#2396 CIV-11152 Fix Sign settlement agreement content
  sonar-project.properties
  src/main/common/models/claim.ts
  src/main/common/utils/repaymentUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/signSettlmentAgreementController.ts
  src/main/routes/guards/signSettlmentAgreementGuard.ts
  src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
  src/main/views/features/claimantResponse/sign-settlement-agreement.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/utils/repaymentUtils.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2396

#2566 CIV-11579 Welsh Bug Part 2
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/claimantResponse/checkAnswers/buildFreeTelephoneMediationSection.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/common/buildSmallClaimHearingRequirements.ts
  src/main/services/features/common/hearingExportsReportBuilderSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponsePaymentSection.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-report-details.njk
  src/main/views/features/mediation/mediation-disagreement.njk
  src/main/views/features/response/statementOfMeans/courtOrders/court-orders.njk
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/hearingExportsReportBuiderSection.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildSmallHearingRequirments.test.ts
  src/test/unit/services/features/response/checkAnswers/responseSection/buildFreeTelephoneMediationSection.test.ts
  src/test/utils/checkAnswersConstants.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2566

#2569 CIV-11576 welsh translation
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2569

#2570 CIV-11580 missing welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/views/features/public/firstContact/claim-summary.njk
  src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2570

#2508 CIV-11185 Apply for help with fees selection
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/form/models/helpWithFees/feeType.ts
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/caseProgression/hearingFee/hearingFee.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.ts
  src/main/routes/features/caseProgression/hearingFee/cancelHearingFeeJourneyController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionButtonContents.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionContents.ts
  src/main/services/translation/convertToCUI/convertToCaseProgressionHearing.ts
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-selection.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/caseProgressionHearing.test.ts
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/cancelHearingFeeJourneyController.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCaseProgressionHearing.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseHearingFeeMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2508

#2591 CIV-11208 Apply
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/caseProgression/hearingFee/apply-help-with-fees.njk
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2591

#2355 CIV-10636 Implement sign settlement agreement confirmation
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/signSettlementAgreementContentBuilder.ts
  src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: pr-values:elasticsearch

#2510 CIV-11351 - adding scenario for upload evidence check
  src/test/functionalTests/features/caseProgression/pages/documents.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/evidenceUpload.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2510

#2619 CIV-TASK Fixing FTs that are failing at doc upload
  src/test/functionalTests/features/caseProgression/pages/documents.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/evidenceUpload.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2619

#2354 CIV-8939 Adding ccd mapping for signSettlementAgreement
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2354

#2282 CIV-10370 Make available Claimant Lip
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/cancelYourUploadController.ts
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/caseProgression/documentsUploadedController.ts
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/disclosureService.ts
  src/main/services/features/caseProgression/expertService.ts
  src/main/services/features/caseProgression/trialService.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
  src/test/unit/routes/features/caseProgression/checkYourAnswersController.test.ts
  src/test/unit/routes/features/caseProgression/documentsUploadedController.test.ts
  src/test/unit/routes/features/caseProgression/typeOfDocumentsController.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/caseProgressionService.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/caseProgression/disclosureService.test.ts
  src/test/unit/services/features/caseProgression/expertService.test.ts
  src/test/unit/services/features/caseProgression/trialService.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseDefendantMock.json
  src/test/utils/mocks/civilClaimResponseDocumentUploadedClaimantMock.json
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2282

#2493 CIV-11235 create hearing section
  src/main/common/models/caseProgression/dashboard.ts
  src/main/common/models/claim.ts
  src/main/modules/draft-store/getDashboardCache.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/services/features/caseProgression/dashboardService.ts
  src/main/views/macro/task.njk
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2493

#2448 CIV-8147 Sign settlement agreement: Submit Function Back end
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claim.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/models/events/eventDto.ts
  src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2448

#2604 CIV-0000 Update dependencies
  charts/civil-citizen-ui/Chart.yaml
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2604

#2635 CIV-0000 Adding S2S auth services list
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2635

#2342 CIV-8785 -Claimant Intent – County Court Judgment requested
  src/main/common/models/ccdResponse/ccdApplicant1LiPResponse.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/ccjConfirmationBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/convertToCUI/convertToCUICCJRequest.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/models/claimantResponse.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2342

#2611 CIV-0000 Fix DQs & Claim Issue tests
  jest.config.js
  src/test/unit/routes/features/claim/amount/claimAmountBreakdownController.test.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/claimFeeController.test.ts
  src/test/unit/routes/features/claim/claimantDoBController.test.ts
  src/test/unit/routes/features/claim/claimantPartyTypeController.test.ts
  src/test/unit/routes/features/claim/completingClaimController.test.ts
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/routes/features/claim/defendantEmailController.test.ts
  src/test/unit/routes/features/claim/defendantPartyTypeController.test.ts
  src/test/unit/routes/features/claim/defendantPhoneController.test.ts
  src/test/unit/routes/features/claim/details/helpWithFeesController.test.ts
  src/test/unit/routes/features/claim/details/reasonController.test.ts
  src/test/unit/routes/features/claim/feeChangeController.test.ts
  src/test/unit/routes/features/claim/incompleteClaimIssueSubmissionController.test.ts
  src/test/unit/routes/features/claim/interest/claimInterestController.test.ts
  src/test/unit/routes/features/claim/interest/claimantInterestFromController.test.ts
  src/test/unit/routes/features/claim/interest/continueClaimingInterestController.test.ts
  src/test/unit/routes/features/claim/interest/howMuchContinueClaimingController.test.ts
  src/test/unit/routes/features/claim/interest/interestEndDateController.test.ts
  src/test/unit/routes/features/claim/interest/interestStartDateController.test.ts
  src/test/unit/routes/features/claim/interest/interestTypeController.test.ts
  src/test/unit/routes/features/claim/iterest/claimTotalInterestController.test.ts
  src/test/unit/routes/features/claim/iterest/claimantInterestRateController.test.ts
  src/test/unit/routes/features/claim/resolvingThisDisputeController.test.ts
  src/test/unit/routes/features/claim/totalAmountController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantEvidenceController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantIndividualDetailsController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantOrganisationDetailsController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantPhoneController.test.ts
  src/test/unit/routes/features/claim/yourDetails/timelineController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertGuidanceController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertSmallClaimsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2611

#2495 CIV-10440 claimant intent task list 2
  src/main/common/models/claim.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2495

#2503 CIV-11315 Check your answers Guard (Claimant Intent Journey)
  sonar-project.properties
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/routes/features/claimantResponse/incompleteClaimantResponseSubmissionController.ts
  src/main/routes/guards/claimantResponseCheckYourAnswersGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
  src/test/unit/routes/features/claimantResponse/incompleteClaimantResponseSubmissionController.test.ts
  src/test/unit/routes/guards/claimantResponsecheckYourAnswersGuard.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2503

#2675 CIV-TASK PR to fix the document upload FTs
  src/test/functionalTests/features/caseProgression/pages/documents.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/evidenceUpload.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2675

#2630 CIV-0000 - CCD translation
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2630

#2610 CIV-11531 - added URL for evidence upload application
  src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2610

#2605 CIV-8454 Generate service request
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/ccdResponse/ccdClaimFee.ts
  src/main/common/models/events/caseEvent.ts
  src/main/routes/features/claim/totalAmountController.ts
  src/main/services/features/claim/amount/checkClaimFee.ts
  src/main/services/features/claim/amount/claimFeesService.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/services/features/claim/amount/checkClaimFee.test.ts
  src/test/unit/services/features/claim/amount/claimFeesService.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2605

#2642 CIV-7824 Pay hearing fee payment unsuccessful screen
  src/main/assets/scss/main.scss
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/external-urls.njk
  src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
  src/test/unit/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2642

#2679 CIV-0000 Fix ClaimantResponse tests
  jest.config.js
  src/main/routes/features/claimantResponse/ccj/ccjPaymentOptionController.ts
  src/test/unit/routes/features/claimantResponse/ccj/ccjConfirmationController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/defendantDOBController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/paidAmountController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantResponseCheckAnswersController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedInstalmentsController.test.ts
  src/test/unit/routes/features/claimantResponse/paidInFull/datePaidController.test.ts
  src/test/unit/routes/features/claimantResponse/settleClaimController.test.ts
  src/test/utils/mocks/noRespondentTelephoneClaimantIntentionMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2679

#2621 CIV-8572 CYA: Court Calc - Court Decision and Your Response
  src/main/common/models/claimantResponse.ts
  src/main/common/models/claimantResponse/checkAnswers.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.ts
  src/main/services/features/claimantResponse/responseSection/buildCourtDecisionDetailsSection.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/builsCourtDecisionDetailsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2621

#2546 CIV-8241 Manual Determination - Lip Notifications
  src/main/common/models/ccdResponse/ccdClaimantPaymentOption.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/main/services/translation/convertToCUI/convertToCUICCJRequest.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICCJRequest.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2546
