Repository hmcts/civil-citizen-ui, pull requests merged in 2023-01, with the labels that each got.

#1245 Bump dependencies
  package.json
  src/main/common/form/models/claim/yourDetails/defendantEmail.ts
  src/main/common/models/Email.ts
  src/main/common/models/directionsQuestionnaire/experts/expertDetails.ts
  src/main/common/models/directionsQuestionnaire/witnesses/otherWitnessItems.ts
  src/test/functionalTests/features/response/pages/repaymentPlan.js
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1245

#1211 Civ 6392 debt respite scheme
  src/main/common/models/breathingSpace.ts
  src/main/common/models/breathingSpace/debtRespiteStartDate.ts
  src/main/common/models/ccd/ccdBreathingSpace/ccdBreathingSpace.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/breathingSpace/debtRespiteLiftedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/translation/breathingSpace/convertBreathingSpaceToCCD.ts
  src/main/views/features/breathingSpace/debt-respite-lift-date.njk
  src/test/unit/routes/features/breathingSpace/debtRespiteLiftedController.test.ts
  src/test/unit/services/translation/breathingSpace/convertBreathingSpaceToCCD.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1211

#1208 CIV-6384 Claim Intent confirmation
  src/main/common/form/models/claimSummarySection.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/claimantResponseConfirmationContentService.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/disputeConfirmationContentBuilder.ts
  src/main/views/features/claimantResponse/claimant-response-confirmation.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/routes/features/claimantResponse/claimantResponseConfirmationController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, rel:civil-citizen-ui-pr-1208

#1195 Feat/civ 5574 claim intent check answers
  src/main/common/form/models/admission/paymentIntention.ts
  src/main/common/models/fullAdmission.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/breathingSpace/debtRespiteReferenceNumberController.ts
  src/main/routes/features/claim/breathingSpace/checkAnswersController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/breathingSpace/checkAnswersService.ts
  src/main/services/features/breathingSpace/debtRespiteScheme/buildDebtRespiteSection.ts
  src/main/views/features/breathingSpace/check-answers.njk
  src/test/unit/routes/features/breathingSpace/checkAnswersController.test.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteReferenceNumberController.test.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/services/features/breathingSpace/buildDebtRespiteSection.test.ts
  src/test/unit/services/features/response/checkAnswers/checkAnswersService.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  yarn-audit-known-issue
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1195

#1256 Bump dependencies
  .nvmrc
  charts/civil-citizen-ui/Chart.yaml
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1256

#1247 CIV-5745: Claimant Intent - Not agree free mediation
  src/main/common/form/models/mediation/noMediationReason.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/mediation/mediationDisagreementController.ts
  src/main/services/features/response/mediation/mediationService.ts
  src/main/views/features/mediation/i-dont-want-free-mediation.njk
  src/main/views/features/mediation/mediation-disagreement.njk
  src/test/unit/routes/features/mediation/iDontWantFreeMediationController.test.ts
  src/test/unit/routes/features/mediation/mediationDisagreementController.test.ts
  src/test/unit/services/features/response/mediation/mediationService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1247

#1260 Fix: add debug to resolutions
  package.json
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1260

#1224 Civ 6582 defendant cant afford
  sonar-project.properties
  src/main/common/form/models/claimantResponse/courtProposedPlan.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/utils/dateUtils.ts
  src/main/common/utils/repaymentUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claimantResponse/courtProposedPlanController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/court-proposed-plan.njk
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/common/utils/repaymentUtils.test.ts
  src/test/unit/routes/features/claimantResponse/courtProposedPlanController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1224

#1259 Translation missing added
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1259

#1248 CIV-6591/Claimant Intent – DQs SC1
  Jenkinsfile_CNP
  src/main/common/models/claimantResponse.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
  src/main/services/features/directionsQuestionnaire/expertReportDetailsService.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-guidance.njk
  src/main/views/macro/report-detail.njk
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/otherWitnessesService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1248

#1222 Features/civ 6586 repayment plan accepted
  sonar-project.properties
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/repaymentPlanAcceptedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/repayment-plan-accepted.njk
  src/test/unit/routes/features/claimantResponse/repaymentPlanAcceptedController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1222

#1218 Features/civ 6375 settlement agreement
  sonar-project.properties
  src/main/common/form/models/claimantResponse/signSettlementAgreement.ts
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/signSettlmentAgreementController.ts
  src/main/routes/guards/signSettlmentAgreementGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/sign-settlement-agreement.njk
  src/test/unit/common/utils/repaymentUtils.test.ts
  src/test/unit/modules/nunjucks/filters/dateFilter.test.ts
  src/test/unit/routes/features/claimantResponse/signSettlmentAgreementController.test.ts
  src/test/unit/routes/guards/signSettlmentAgreementGuard.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, rel:civil-citizen-ui-pr-1218

#1272 enable cui import ccd definitions
  Jenkinsfile_CNP
  src/test/functionalTests/features/response/pages/checkYourAnswers.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1272

#1276 Update dependencies
  charts/civil-citizen-ui/Chart.yaml
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1276

#1258 Civ 6598 dq ft2
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/experts/sentExpertReportsController.ts
  src/main/routes/urls.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/sharedExpert.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1258

#1263 CIV-6596/Claimant Intent – DQs SC5
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/test/unit/services/features/directionsQuestionnaire/supportRequiredService.test.ts
  src/test/utils/mocks/civilClaimantIntentionMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1263

#1127 CIV-5602: Defendant Respones - Part admit already paid
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmissionAlreadyPaidDefendantsResponseContent.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1127

#1179 CIV:6054:Claimant Intent - Part admit + pay set by date - How they want to pay.
  sonar-project.properties
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/views/features/claimantResponse/how-they-want-to-pay-response.njk
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/routes/features/claimantResponse/reviewDefendantsResponseController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1179, add-or-update

#1261 CIV-6584 - Defendant cant pay proposed date
  sonar-project.properties
  src/main/common/form/models/claimantResponse/courtProposedDate.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/utils/repaymentUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claimantResponse/courtProposedDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claimantResponse/court-proposed-date.njk
  src/test/unit/common/utils/repaymentUtils.test.ts
  src/test/unit/routes/features/claimantResponse/courProposedDateController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1261

#1106 Civ 5572 dispute paid less
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1106, add-or-update

#1267 CIV-6597: DQs - ft1
  src/main/modules/i18n/locales/en.json
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
  src/test/unit/routes/features/directionsQuestionnaire/considerClaimantDocumentsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1267

#1264 reject the repayment plan screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/rejectionReasonController.ts
  src/main/views/features/claimantResponse/rejection-reason.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1264

#1257 Rapayment length to update when typing new value
  src/main/assets/js/calculate-length-repayment.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1257

#1290 Update: update chart dependencies
  charts/civil-citizen-ui/Chart.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1290

#1220 CIV-5337: Notification Email
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDParty.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1220

#1279 CIV-6806: PinInPost SecurityCode verification not working
  src/main/app/client/civilServiceClient.ts
  src/main/routes/features/public/firstContact/pinController.ts
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1279

#1202 Civ 4406 claim submitted screen
  sonar-project.properties
  src/main/assets/scss/main.scss
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/claimSubmittedController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/claim/claim-submitted.njk
  src/test/unit/routes/features/claim/claimSubmittedController.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1202

#1289 Ccd transformation
  Jenkinsfile_CNP
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccdResponse/ccdClaimAmountBreakup.ts
  src/main/common/models/ccdResponse/ccdEvidence.ts
  src/main/common/models/ccdResponse/ccdInterestType.ts
  src/main/common/models/ccdResponse/ccdSameRateInterestSelection.ts
  src/main/common/models/ccdResponse/ccdTimeLineOfEvents.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/routes/features/claim/interest/claimTotalInterestController.ts
  src/main/routes/features/claim/interest/claimantInterestFromController.ts
  src/main/routes/features/claim/interest/claimantInterestRateController.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildClaimAmountSection.ts
  src/main/services/features/claim/interest/claimInterestService.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/convertToCUI/convertToCUIParty.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDClaimAmount.ts
  src/main/services/translation/response/convertToCCDEvidence.ts
  src/main/services/translation/response/convertToCCDInterestType.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/main/services/translation/response/convertToCCDTimeLine.ts
  src/main/services/translation/response/convertToCCDYesNo.ts
  src/main/services/translation/response/convertToCCDtoSameRateInterestSelection.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/interest/claimantInterestFromController.test.ts
  src/test/unit/routes/features/claim/iterest/claimTotalInterestController.test.ts
  src/test/unit/routes/features/claim/iterest/claimantInterestRateController.test.ts
  src/test/unit/services/features/claim/checkAnswers/claimAmountSection/buildClaimAmountSection.test.ts
  src/test/unit/services/features/claim/submission/submitClaim.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIParty.test.ts
  src/test/unit/services/translation/response/convertToCCDClaimAmount.test.ts
  src/test/unit/services/translation/response/convertToCCDEvidence.test.ts
  src/test/unit/services/translation/response/convertToCCDInterestType.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
  src/test/unit/services/translation/response/convertToCCDTimeLine.test.ts
  src/test/unit/services/translation/response/convertToCCDYesNo.test.ts
  src/test/unit/services/translation/response/convertToCCDtoSameRateInterestSelection.test.ts
  src/test/utils/mocks/claimDetailsMock.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1289

#1294 Fix: delete ccd test branch and log
  Jenkinsfile_CNP
  src/main/app/client/civilServiceClient.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1294

#1250 CIV-5681 CCJ check answers
  sonar-project.properties
  src/main/common/form/models/claimantResponse/ccj/ccjPaymentOption.ts
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/ccjCheckAnswersController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildCcjTheirDetailsSection.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
  src/main/services/features/claimantResponse/ccj/ccjCheckAnswersService.ts
  src/main/views/features/claimantResponse/ccj/check-answers.njk
  src/main/views/macro/statement-of-truth.njk
  src/test/unit/routes/features/claimantResponse/ccj/ccjCheckAnswersController.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildCcjTheirDetailsSection.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.test.ts
  src/test/unit/services/features/claim/checkAnswers/financialSection/buildPaymentSection.test.ts
  src/test/unit/services/features/claimantResponse/ccj/ccjCheckAnswersService.test.ts
  src/test/utils/checkAnswersConstants.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, rel:civil-citizen-ui-pr-1250

#1136 CIV-5978: Defendant response - Part admit - Not paid scenarios
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1136

#1297 Feat/civ 6592
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
  src/main/services/features/directionsQuestionnaire/expertDetailsService.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/test/unit/modules/nunjucks/filters/dateFilter.test.ts
  src/test/unit/routes/features/claimantResponse/repaymentPlanAcceptedController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/experts/expertDetailsService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1297

#1295 CIV-5433 - Add PR Title validation and Code Owners
  .github/CODEOWNERS
  .github/workflows/main.yml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1295

#1283 CIV-6063 - part admit pay instalments how they want to pay
  src/main/common/utils/repaymentUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/views/features/claimantResponse/how-they-want-to-pay-response.njk
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/test/unit/common/utils/repaymentUtils.test.ts
  src/test/unit/routes/features/claimantResponse/reviewDefendantsResponseController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1283

#1306 CIV-6992 updated JenkinsCNP._Snyk
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1306

#1182 CIV-5668 - Claimant Intent - Request a CCJ - Judgement amount calculation
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/draft-store/redisData.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/totalAmountController.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/routes/routes.ts
  src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
  src/main/views/features/claimantResponse/ccj/judgement-amount-summary.njk
  src/test/unit/routes/features/claim/totalAmountController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.test.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1182, add-or-update
