Repository hmcts/civil-citizen-ui, pull requests merged in 2023-05, with the labels that each got.

#1554 CIV-7137 Part Admit States Paid - CYA and Submit
  src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
  src/main/services/translation/response/convertToCCDRespondToClaim.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
  src/test/unit/services/translation/response/convertToCCDAdmitPartRoute.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondToClaim.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1554

#1548 CIV-7730 added new dashboard status
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1548

#1583 CIV-0000 Update dependencies
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1583

#1565 CIV-8203 - Fix date validations
  src/main/common/form/models/admission/fullAdmission/paymentOption/paymentDate.ts
  src/main/common/form/validators/optionalDateFourDigitValidator.ts
  src/main/common/models/breathingSpace/debtRespiteEndDate.ts
  src/main/common/models/breathingSpace/debtRespiteStartDate.ts
  src/main/common/utils/numberConverter.ts
  src/main/views/features/breathingSpace/respite-start.njk
  src/test/unit/routes/features/breathingSpace/debtRespiteStartDateController.test.ts
  src/test/unit/routes/features/response/citizenDob/citizenDobController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1565

#1585 CIV-0000 Fix sonar errors
  src/main/routes/features/claim/interest/claimInterestController.ts
  src/main/routes/features/claim/interest/claimantInterestFromController.ts
  src/main/routes/features/claim/yourDetails/defendantEmailController.ts
  src/main/routes/features/response/evidence/evidenceController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1585

#1550 CIV-7836 Evidence upload latest update on claim summary
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/document/documentType.ts
  src/main/common/utils/documentTypeConverter.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/urls.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
  src/test/unit/common/utils/documentTypeConverter.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1550

#1588 CIV-0000 Update dependencies
  .github/workflows/stale.yml
  Dockerfile
  charts/civil-citizen-ui/Chart.yaml
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1588

#1590 CIV-0000 - Config changes to support WA.
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1590

#1596 CIV-8391 add days to paymentDay immediately
  src/main/common/utils/dateUtils.ts
  src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1596

#1586 CIV-0000 fix preview environment - enable more memory for ccd data store api
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1586

#1551 CIV-7839 evidence upload macro
  src/main/common/form/models/claimSummarySection.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/uploadDocumentsSection.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1551

#1587 CIV-8339 welsh translation34
  package.json
  src/main/modules/i18n/locales/cy.json
  yarn.lock
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1587

#1612 CIV-8115 Evidence upload Latest update Add bundle deadline
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/caseProgression/courtNameExtractor.ts
  src/main/services/features/caseProgression/hearingDateTimeFormatter.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/hearingTrialLatestUploadContent.ts
  src/main/services/translation/convertToCUI/convertToCaseProgressionHearing.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
  src/test/unit/common/models/caseProgression/caseProgressionHearing.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/caseProgression/courtNameExtractor.test.ts
  src/test/unit/services/features/caseProgression/hearingDateTimeFormatter.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/hearingTrialLatestUploadContent.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCaseProgressionHearing.test.ts
  src/test/utils/caseProgression/mockCaseProgressionHearing.ts
  src/test/utils/dateUtils.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1612

#1623 CIV-8073 Testing for pally based on the Redis Cache
  Jenkinsfile_CNP
  src/test/a11y/a11y.ts
  src/test/a11y/constants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1623

#1584 CIV-7729 hearing notice latest update to defendant lip
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1584

#1625 CIV-8073 Adding all of the relevant redis Data for a Case Progression Case
  src/main/modules/draft-store/redisData.json
  src/test/a11y/a11y.ts
  src/test/a11y/constants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1625

#1631 CIV-7498 SDO Latest Update for LIP Defendant.<New PR>
  src/main/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/document/documentDownloadController.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/models/LatestUpdateSectionBuilder/latestUpdateSectionBuilder.test.ts
  src/test/unit/routes/features/document/documentDownloadController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1631

#1460 CIV-7161 defendant latest update screens part 3
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/responseToClaimSection.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/dashboard/claimSummary/latestUpdateService.ts
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdateService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1460

#1632 CIV-0000 - Test WA
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.enableWA.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1632

#1643 CIV-TASK Fix camunda import
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1643

#1646 CIV-7139 Clone-Fixed the translation
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/services/translation/convertToCUI/convertToCUIPartialAdmission.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIPartialAdmission.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1646

#1626 CIV-8121 Welsh and English Deadline Extension Notification
  src/main/common/models/events/eventDto.ts
  src/main/services/features/response/responseDeadline/extendResponseDeadlineService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1626

#1650 CIV-7905 upload model
  src/main/views/features/caseProgression/upload-documents.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1650

#1621 CIV-7857 evidence upload ft types of document
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/models/claim.ts
  src/main/common/models/document/caseDocument.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/test/unit/routes/features/caseProgression/typeOfDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/caseProgressionService.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1621

#1655 CIV-0000 Changing SR callback url
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1655

#1653 CIV-8540 sdo document is not loading
  src/main/common/models/claim.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/evidenceUploadContent.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1653

#1674 CIV-8598 Bug Fixed for translation
  src/main/services/translation/response/convertToCCDHearingSupport.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1674

#1654 CIV-8554 cancel text size smaller
  src/main/views/features/caseProgression/typeOfDocuments.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1654

#1685 CIV-0000 Update Jenkins to Exclude import in AAT
  Jenkinsfile_CNP
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1685

#1649 CIV-8536 welsh translations38
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1649

#1703 CIV-8796 English and welsh correction
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1703

#1629 CIV-7838 - Small Claims page for Evidence Upload
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/views/features/caseProgression/typeOfDocuments.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1629
