Repository hmcts/civil-citizen-ui, pull requests merged in 2023-10, with the labels that each got.

#2160 CIV-9464 test
  src/test/functionalTests/features/caseProgression/data/fileUpload.txt
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocumentsConfirmation.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocumentsIntroduction.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/whatTypeOfDocumentsDoYouWantToUpload.js
  src/test/functionalTests/features/caseProgression/pages/uploadYourDocument.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/features/home/pages/login.js
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/SDOMidEventPayloads.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToSDOState.js
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2160

#2246 Adding await to the Login Code....for fix thes test failure...
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2246

#2262 CIV-0000 fixMaster
  src/test/functionalTests/tests/caseprogression_uploadevidence_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2262

#2240 CIV-10815 Check your Answers page Summary label to be replaced with Statement
  src/main/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadedSummaryRows.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadSummaryRows.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2240

#2216 CIV-9616 Defendant Latest Update Mediation Succesful PDF
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2216

#2251 CIV-8946 Adding the latest pa11y changes...
  src/test/a11y/constants.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2251

#2151 CIV-10460 AdditionalPartyDetails added
  src/main/common/models/ccdResponse/ccdAdditionalPartyDetails.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/test/unit/services/translation/response/ccdAdditionalPartyDetatils.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2151

#2227 CIV-10498 AmountClaimSummaryPageBug
  src/main/modules/claimDetailsService.ts
  src/main/views/macro/amount-breakdown.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2227

#2265 CIV-0000 increase memory for nodejs
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2265

#2188 CIV-9011 DJ Lip vs LiP Submission
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/routes/guards/ccjConfirmationGuard.ts
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/main/services/translation/convertToCUI/convertToCUICCJRequest.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/models/claimantResponse/ccdTranslation.test.ts
  src/test/unit/common/models/claimantResponse/ccj/ccjRequest.test.ts
  src/test/unit/routes/guards/ccjConfirmationGuard.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICCJRequest.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2188

#2272 CIV-0000 add_LipvLip_tests
  src/test/functionalTests/features/createClaim/pages/eligibilityCheck.js
  src/test/functionalTests/features/createClaim/steps/createLipvLipClaimSteps.js
  src/test/functionalTests/tests/createClaim_LipvLip_eligibilityCheck_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2272

#2275 CIV-0000 increase memory for nodejs The Second
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2275

#2222 CIV-8894 dashboard claimant
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/common/models/legacyDraftClaim/draftClaim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2222

#2209 CIV-10628 Clearing eligibility cookies after submit
  src/main/routes/features/claim/checkAnswersController.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2209

#2210 CIV-8607 CYA-claimant-response
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/checkAnswers/buildYourResponseSection.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2210

#2284 CIV-10950 - fix latestUpdate hasRespondent1NotAgreedMediation
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2284

#1986 CIV-9661 Set Up Fee Change Page
  sonar-project.properties
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/feeChangeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/draftClaimService.ts
  src/main/views/features/claim/fee-change.njk
  src/test/unit/routes/features/claim/feeChangeController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-1986

#2274 CIV-9464 sall clais
  src/test/functionalTests/features/caseProgression/data/TestBMP.bmp
  src/test/functionalTests/features/caseProgression/data/TestCSV.csv
  src/test/functionalTests/features/caseProgression/data/TestDOC.doc
  src/test/functionalTests/features/caseProgression/data/TestDOCX.docx
  src/test/functionalTests/features/caseProgression/data/TestJPEG.jpeg
  src/test/functionalTests/features/caseProgression/data/TestJPG.jpg
  src/test/functionalTests/features/caseProgression/data/TestPDF.pdf
  src/test/functionalTests/features/caseProgression/data/TestPNG.png
  src/test/functionalTests/features/caseProgression/data/TestPPT.ppt
  src/test/functionalTests/features/caseProgression/data/TestRTF.rtf
  src/test/functionalTests/features/caseProgression/data/TestTIF.tif
  src/test/functionalTests/features/caseProgression/data/TestTIFF.tiff
  src/test/functionalTests/features/caseProgression/data/TestTXT.txt
  src/test/functionalTests/features/caseProgression/data/TestXLS.xls
  src/test/functionalTests/features/caseProgression/data/TestXLSX.xlsx
  src/test/functionalTests/features/caseProgression/pages/documents.js
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocumentsIntroduction.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/whatTypeOfDocumentsDoYouWantToUpload.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/tests/cp_uploadevidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_uploadevidence_small_claims_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2274

#2236 CIV-7035 Breathing space guard
  src/main/common/models/claim.ts
  src/main/routes/features/breathingSpace/checkAnswersController.ts
  src/main/routes/features/breathingSpace/debtRespiteEndDateController.ts
  src/main/routes/features/breathingSpace/debtRespiteLiftedController.ts
  src/main/routes/features/breathingSpace/debtRespiteOptionController.ts
  src/main/routes/features/breathingSpace/debtRespiteReferenceNumberController.ts
  src/main/routes/features/breathingSpace/debtRespiteStartDateController.ts
  src/main/routes/guards/breathingSpaceGuard.ts
  src/main/routes/routes.ts
  src/test/unit/routes/guards/breathingSpaceGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2236

#2242 CIV-10829 DJ Spelling error
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2242

#2232 CIV-8198 Task list expired
  src/main/app.ts
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/routes/features/claim/yourDetails/claimantPartyTypeController.ts
  src/main/routes/features/claim/yourDetails/defendantPartyTypeController.ts
  src/main/routes/guards/claimIssueTaskListGuard.ts
  src/main/routes/urls.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2232

#2293 Adding the relevant tests for the Case Progression State Check on the…
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/tests/cp_latest_update_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_small_claims_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2293

#2260 CIV-8382 Update dependencies
  charts/civil-citizen-ui/Chart.yaml
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2260

#2295 CIV-0000 change redis sku from premium to basic in non-prod envs
  infrastructure/_variables.tf
  infrastructure/key-vault.tf
  infrastructure/prod.tfvars
  infrastructure/redis.tf
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2295

#2271 CIV-10497 Fix by a set date - accept repayment plan
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
  src/main/services/features/claimantResponse/getSetDatePaymentDetails.ts
  src/main/views/features/claimantResponse/accept-repayment-plan.njk
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService.test.ts
  src/test/unit/services/features/claimantResponse/fullAdmitSetDatePaymentService.test.ts
  src/test/unit/services/features/claimantResponse/getSetDatePaymentDetails.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2271

#2309 CIV-000 Update azurerm version
  charts/civil-citizen-ui/Chart.yaml
  infrastructure/_state.tf
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2309

#2313 CIV-10695 Negative scenarios
  src/test/functionalTests/features/response/pages/defendantLipResponse/bilingualLanguagePreference.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/chooseAResponse/respondType.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchDoYouOwe.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/whyDoYouDisagreeTheClaimAmount.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/repaymentPlan.js
  src/test/functionalTests/features/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/response_negativeScenarios_comp_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2313

#2317 CIV-10998 auth bypass
  package.json
  src/main/common/models/claim.ts
  src/main/common/models/pinToPost.ts
  src/main/routes/features/claimAssignment/assignClaimController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
  src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2317

#2321 CIV-8382 Update dependencies
  charts/civil-citizen-ui/Chart.yaml
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2321

#2306 CIV-10959 CIV-10960 CIV-10968 - R1 Bug fix.
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/rejectClaimConfirmationContent.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-2306

#2319 CIV-10951 fix documentary evidence literal
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/features/caseProgression/pages/documents.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/whatTypeOfDocumentsDoYouWantToUpload.js
  src/test/functionalTests/tests/cp_uploadevidence_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2319

#2325 CIV-11014 Remove erroneous whitespace from cy.json
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2325

#2255 CIV-10391 Respondent1 response deadline date update
  src/main/routes/features/claim/claimFeeController.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2255

#2343 CIV-11068 - CCD translation
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2343

#2344 CIV-100 Change redis sku in aat/ithc envs
  infrastructure/aat.tfvars
  infrastructure/ithc.tfvars
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2344

#2349 CIV-0000 Avoid the claim issue guard on the pay claim fee screen.
  src/main/routes/guards/claimIssueTaskListGuard.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2349

#2332 CIV-11028 Terms of agreement screen is not appearing
  src/main/common/models/claim.ts
  src/main/routes/features/claimantResponse/signSettlmentAgreementController.ts
  src/main/routes/guards/signSettlmentAgreementGuard.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/guards/signSettlmentAgreementGuard.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2332

#2303 CIV-10830 fix bug
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2303

#2298 CIV-10849 dashboard design structure
  src/main/assets/scss/main.scss
  src/main/common/models/taskList/TaskStatus.ts
  src/main/common/models/taskList/task.ts
  src/main/common/models/taskList/taskListBuilder.ts
  src/main/common/utils/dashboard/notificationBuilder.ts
  src/main/common/utils/dashboard/notifications.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/macro/notifications.njk
  src/main/views/macro/task-list.njk
  src/main/views/macro/task.njk
  src/test/unit/common/utils/dashboard/notifications.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2298

#2371 CIV-10849 dashboard design structure Revert
  src/main/assets/scss/main.scss
  src/main/common/models/taskList/TaskStatus.ts
  src/main/common/models/taskList/task.ts
  src/main/common/models/taskList/taskListBuilder.ts
  src/main/common/utils/dashboard/notificationBuilder.ts
  src/main/common/utils/dashboard/notifications.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/macro/notifications.njk
  src/main/views/macro/task-list.njk
  src/main/views/macro/task.njk
  src/test/unit/common/utils/dashboard/notifications.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2371

#1914 CIV-9409 Trial Arrangements: Defendant LiP – Latest Updates Tile Notification for Defendant LiP
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/viewTrialArrangementsContent.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/services/translation/convertToCUI/convertToCUITrialArrangements.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/viewTrialArrangementsContent.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUITrialArrangements.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCaseProgressionHearing.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1914

#2351 CIV-11129 Misspelled word corrected.
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2351

#2305 CIV-10903 claim fee and timeline added
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/ccdResponse/ccdClaimFee.ts
  src/main/common/models/ccdResponse/ccdTimeLine.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/routes/features/claim/totalAmountController.ts
  src/main/services/features/claim/amount/claimFeesService.ts
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/test/unit/routes/features/claim/totalAmountController.test.ts
  src/test/unit/services/features/claim/amount/claimFeesService.test.ts
  src/test/unit/services/translation/response/ccdClaimFee.test.ts
  src/test/unit/services/translation/response/ccdTimeLine.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2305

#2400 CIV-0000 Update username
  src/test/config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2400

#2386 CIV-11187 remove space before to .
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2386

#2426 CIV-10972 test
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/pages/noticesAndOrders.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/hasAnythingChanged.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/isYourCaseReadyForTrial.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/trialArrangementsConfirmation.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/trialArrangementsIntroduction.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/trialDuration.js
  src/test/functionalTests/features/caseProgression/steps/trialArrangementSteps.js
  src/test/functionalTests/features/caseProgression/util/DateUtilsComponent.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToHearingInitiated.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2426

#2431 CIV-10792 Adding the caveat for the CUI tests to be fixed.....
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2431

#2259 CIV-10516 CYA-Judgment request
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/routes/features/claimantResponse/ccj/paidAmountController.ts
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2259

#2381 CIV-10849 dashboard-design-structure
  src/main/assets/scss/main.scss
  src/main/common/models/taskList/TaskStatus.ts
  src/main/common/models/taskList/task.ts
  src/main/common/models/taskList/taskListBuilder.ts
  src/main/common/utils/dashboard/notificationBuilder.ts
  src/main/common/utils/dashboard/notifications.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/macro/notifications.njk
  src/main/views/macro/task-list.njk
  src/main/views/macro/task.njk
  src/test/unit/common/utils/dashboard/notifications.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2381

#2215 CIV-10774 fix bug with expert required
  src/main/services/features/directionsQuestionnaire/expertRequiredValueService.ts
  src/test/unit/services/features/directionsQuestionnaire/expertRequiredValueService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2215

#2403 CIV-11056 Trial Arrangements tile showing and working for a Hearing Date Listed under 3 weeks
  src/main/common/models/claim.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2403

#2314 CIV-10964 Add conditional message to court offered radios
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claimantResponse/court-proposed-date.njk
  src/main/views/features/claimantResponse/court-proposed-plan.njk
Labels: ns:civil, prd:civil, fullDeploy, stale, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2314

#2304 CIV-9023 Claimant Intent: CCJ after Part Admit or Full Admit Pay Immediately - Submit Function
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/events/caseEvent.ts
  src/main/services/features/claimantResponse/submission/submitClaimantResponse.ts
  src/main/services/translation/claimantResponse/ccdRequestJudgementTranslation.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/features/claimantResponse/submission/submitReponse.test.ts
  src/test/unit/services/translation/claimantResponse/ccdRequestJudgementTranslation.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2304

#2417 CIV-11206 cancel button
  src/main/common/models/AppRequest.ts
  src/main/routes/features/caseProgression/cancelYourUploadController.ts
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, enable_keep_helm, pr-values:enable-release-helm, rel:civil-citizen-ui-pr-2417

#2286 CIV-8904 - Claimant Dashboard Status - Any Defence, CCJ, Offline, Part Admit Pay Immediately
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2286

#2393 CIV-10458 Unable to create claim with amount having decimal places
  src/main/services/translation/response/convertToCCDClaimAmount.ts
  src/test/unit/services/translation/response/convertToCCDClaimAmount.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2393
