Repository hmcts/civil-citizen-ui, pull requests merged in 2023-03, with the labels that each got.

#1387 CIV-6581 Claimant suggested repayment plan
  sonar-project.properties
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/claimantResponse/ccj/ccjPaymentOptionController.ts
  src/main/routes/features/claimantResponse/ccj/defendantPaymentDateController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedInstalmentsController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.ts
  src/main/routes/features/response/admission/fullAdmission/paymentOption/paymentDateController.ts
  src/main/routes/features/response/admission/fullAdmission/paymentOption/paymentOptionController.ts
  src/main/routes/features/response/admission/partialAdmission/partialAdmissionPaymentOptionController.ts
  src/main/routes/features/response/admission/partialAdmission/paymentDateController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.ts
  src/main/views/features/claimantResponse/instalments-plan.njk
  src/main/views/features/response/admission/payment-date.njk
  src/main/views/features/response/admission/payment-option.njk
  src/test/unit/common/models/claimantResponse.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/ccjPaymentOptionController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedInstalmentsController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedPaymentDateController.test.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/claimantResponse/src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1387

#1415 CIV-0000 - Upgrading elastic search version
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values: enableHelm, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1415

#1366 CIV-5829 CCD Translation
  src/main/common/models/ccdResponse/ccdBankAccount.ts
  src/main/common/models/ccdResponse/ccdCourtOrders.ts
  src/main/common/models/ccdResponse/ccdDebtDetails.ts
  src/main/common/models/ccdResponse/ccdEmployerDetails.ts
  src/main/common/models/ccdResponse/ccdEmploymentOption.ts
  src/main/common/models/ccdResponse/ccdFinancialDetailsLiP.ts
  src/main/common/models/ccdResponse/ccdHomeDetails.ts
  src/main/common/models/ccdResponse/ccdLoanCredit.ts
  src/main/common/models/ccdResponse/ccdPartnerAndDependent.ts
  src/main/common/models/ccdResponse/ccdPaymentFrequency.ts
  src/main/common/models/ccdResponse/ccdRecurringExpenses.ts
  src/main/common/models/ccdResponse/ccdRecurringIncome.ts
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/ccdResponse/ccdSelfEmploymentDetails.ts
  src/main/common/models/ccdResponse/ccdUnemploymentDetails.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDBankAccount.ts
  src/main/services/translation/response/convertToCCDCarerAllowanceCredit.ts
  src/main/services/translation/response/convertToCCDCourtOrders.ts
  src/main/services/translation/response/convertToCCDDebtDetails.ts
  src/main/services/translation/response/convertToCCDEmployerDetails.ts
  src/main/services/translation/response/convertToCCDEmploymentSelection.ts
  src/main/services/translation/response/convertToCCDHomeDetails.ts
  src/main/services/translation/response/convertToCCDLoanCredit.ts
  src/main/services/translation/response/convertToCCDPartnerAndDependent.ts
  src/main/services/translation/response/convertToCCDPaymentFrequency.ts
  src/main/services/translation/response/convertToCCDRecurringExpense.ts
  src/main/services/translation/response/convertToCCDRecurringIncome.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDResponseLiPFinancialDetails.ts
  src/main/services/translation/response/convertToCCDSelfEmploymentDetails.ts
  src/main/services/translation/response/convertToCCDUnemploymentDetails.ts
  src/main/services/translation/response/convertToCCDYesNo.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDBankAccount.test.ts
  src/test/unit/services/translation/response/convertToCCDCarerAllowanceCredit.test.ts
  src/test/unit/services/translation/response/convertToCCDCourtOrders.test.ts
  src/test/unit/services/translation/response/convertToCCDDebtDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDEmployerDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDEmploymentSelection.test.ts
  src/test/unit/services/translation/response/convertToCCDHomeDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDLoanCredit.test.ts
  src/test/unit/services/translation/response/convertToCCDPartnerAndDependent.test.ts
  src/test/unit/services/translation/response/convertToCCDPaymentFrequency.test.ts
  src/test/unit/services/translation/response/convertToCCDRecurringExpense.test.ts
  src/test/unit/services/translation/response/convertToCCDRecurringIncome.test.ts
  src/test/unit/services/translation/response/convertToCCDResponseLiPFinancialDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDSelfEmploymentDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDUnemploymentDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDYesNo.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, rel:civil-citizen-ui-pr-1366, pr-values:elasticsearch

#1374 CIV-5797 - Transform Mediation model - CCD
  src/main/common/models/ccdResponse/ccdMediation.ts
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/mediation/mediationIndividualPhoneController.ts
  src/main/routes/features/response/bilingualLangPreferenceController.ts
  src/main/services/features/response/bilingualLangPreferenceService.ts
  src/main/services/translation/response/convertToCCDMediation.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDYesNo.ts
  src/main/views/features/mediation/can-we-use.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/services/features/response/bilingualLangPreferenceService.test.ts
  src/test/unit/services/translation/response/convertToCCDMediation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1374, pr-values:elasticsearch

#1426 CIV-0000 - update: civil-service charts and env var
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1426

#1292 CIV-4969 add download claim link
  src/main/app/client/civilServiceClient.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/views/features/public/firstContact/claim-summary.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1292, pr-values:elasticsearch

#1438 CIV-0000 get user details from app.locals rather than request session
  src/main/modules/oidc/index.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1438

#1437 CIV-7123 welsh UI translations
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1437

#1431 CIV-5454 Improve test coverage
  src/main/common/form/models/timeLineOfEvents/claimantTimeline.ts
  src/test/unit/common/form/validators/atLeastOneCheckboxSelectedValidator.test.ts
  src/test/unit/common/models/claim/amount/amountBreakdown.test.ts
  src/test/unit/common/models/claim/amount/claimAmountRow.test.ts
  src/test/unit/common/models/claim/details/helpWithFees.test.ts
  src/test/unit/common/models/claim/interest/claimantInterestRate.test.ts
  src/test/unit/common/models/claim/interest/interestClaimFromSelection.test.ts
  src/test/unit/common/models/claim/interest/interestClaimOption.test.ts
  src/test/unit/common/models/claim/partyTypeSelection.test.ts
  src/test/unit/common/models/claimantResponse/chooseHowToProceed.test.ts
  src/test/unit/common/models/claimantResponse/courtProposedDate.test.ts
  src/test/unit/common/models/claimantResponse/courtProposedPlan.test.ts
  src/test/unit/common/models/claimantResponse/dateOfBirth.test.ts
  src/test/unit/common/models/claimantResponse/defendantDOB.test.ts
  src/test/unit/common/models/claimantResponse/signSettlementAgreement.test.ts
  src/test/unit/common/models/interest/howMuchContinueClaiming.test.ts
  src/test/unit/common/models/interest/interestEndDate.test.ts
  src/test/unit/common/models/timeLineOfEvents/claimantTimeline.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1431

#1413 CIV-6095 - Correspondence address error messages
  src/main/common/form/models/address.ts
  src/main/common/form/models/citizenCorrespondenceAddress.ts
  src/main/common/form/models/partyDetails.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
  src/main/views/features/claim/yourDetails/claimant-organisation-details.njk
  src/main/views/features/response/citizenDetails/citizen-details-company.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/main/views/macro/address.njk
  src/main/views/macro/postcode-address-form.njk
  src/test/functionalTests/features/response/pages/enterNameAndAddressDetails.js
  src/test/unit/routes/features/claim/yourDetails/claimantIndividualDetailsController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantOrganisationDetailsController.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1413

#1359 CIV-6145 dashboard status
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/services/translation/convertToCUI/convertToCUIParty.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDPaymentOption.ts
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/common/models/ccdResponse/ccdPaymentOption.test.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIParty.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-1359, pr-values:elasticsearch

#1427 CIV-0000 Add language file validation test
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/modules/i18n/languageFileValidation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1427

#1454 CIV-0000 Start CUI from Windows
  package.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1454

#1458 CIV-7616 - CCD to CUI - Part 4
  .nvmrc
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/services/translation/convertToCUI/convertToCUIMediation.ts
  src/main/services/translation/convertToCUI/convertToCUIYesNo.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIMediation.test.ts
  src/test/unit/services/translation/response/convertToCCDMediation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1458

#1433 CIV-5195 Full Reject Fields to CCD
  src/main/common/models/ccdResponse/ccdRejectAllOfClaimType.ts
  src/main/common/models/ccdResponse/ccdRespondToClaim.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDRejectAllOfClaimType.ts
  src/main/services/translation/response/convertToCCDRespondToClaim.ts
  src/test/unit/services/translation/response/convertToCCDRejectAllOfClaimType.test.ts
  src/test/unit/services/translation/response/convertToCCDRespondToClaim.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1433

#1409 CIV-5789 - ccd translation for DQ common screens.
  src/main/common/models/ccdResponse/ccdDQExtraDetails.ts
  src/main/common/models/ccdResponse/ccdFastClaimHearing.ts
  src/main/common/models/ccdResponse/ccdHearingSupport.ts
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/ccdResponse/ccdSmallClaimHearing.ts
  src/main/common/models/ccdResponse/ccdSpecificCourtLocations.ts
  src/main/common/models/ccdResponse/ccdVulnerability.ts
  src/main/common/models/ccdResponse/ccdWelshLanguageRequirements.ts
  src/main/common/models/ccdResponse/ccdWitnesses.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDDQExtraDetials.ts
  src/main/services/translation/response/convertToCCDFastClaimHearing.ts
  src/main/services/translation/response/convertToCCDHearingSupport.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDSmallClaimHearing.ts
  src/main/services/translation/response/convertToCCDSpecificCourtLocations.ts
  src/main/services/translation/response/convertToCCDVulenrabilityQuestions.ts
  src/main/services/translation/response/convertToCCDWelshLanguageRequirements.ts
  src/main/services/translation/response/convertToCCDWitnesses.ts
  src/main/services/translation/response/convertToCCDYesNo.ts
  src/test/unit/services/translation/response/convertToCCDDQExtraDetails.test.ts
  src/test/unit/services/translation/response/convertToCCDHearingSupport.test.ts
  src/test/unit/services/translation/response/convertToCCDSmallClaimHearing.test.ts
  src/test/unit/services/translation/response/convertToCCDSupportedCourtLocations.test.ts
  src/test/unit/services/translation/response/convertToCCDVulenrabilityQuestions.test.ts
  src/test/unit/services/translation/response/convertToCCDWelshLanguageRequirments.test.ts
  src/test/unit/services/translation/response/convertToCCDWitnesses.test.ts
  src/test/unit/services/translation/response/convertToFastClaimHearing.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1409

#1478 CIV-7603 add warnings to a11y test
  src/test/a11y/a11y.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1478

#1384 CIV-7032 specific court, telephone hearing, hearing support
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/directionsQuestionnaire/hearing/phone-or-video-hearing.njk
  src/main/views/features/directionsQuestionnaire/hearing/specific-court.njk
  src/main/views/features/directionsQuestionnaire/support-required-list.njk
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1384, pr-values:elasticsearch

#1483 CIV-0000 Added values to values.preview only for civil service
  charts/civil-citizen-ui/values.preview.template.yaml
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpec.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1483

#1495 CIV-0000 fixed date issue on unit test
  src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-1495

#1394 CIV-5985 check your answers fast track hearing requirements part 3
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/ccjPaymentOptionController.ts
  src/main/routes/features/claimantResponse/ccj/defendantPaymentDateController.ts
  src/main/routes/urls.ts
  src/main/services/features/directionsQuestionnaire/hearing/unavailableDatesCalculation.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.ts
  src/main/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.ts
  src/main/views/features/response/admission/payment-option.njk
  src/test/unit/routes/features/claimantResponse/ccj/ccjPaymentOptionController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/defendantPaymentDateController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/hearing/cantAttendHearingInNext12MonthsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
  src/test/unit/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildCommonHearingRequirements.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildFastTrackHearingRequirements.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, rel:civil-citizen-ui-pr-1394, pr-values:elasticsearch
