Repository hmcts/civil-citizen-ui, pull requests merged in 2024-08, with the labels that each got.

#4274 CIV-14282 - Court response - request more information - upload/confirmation/cya
  src/main/app/client/gaServiceClient.ts
  src/main/common/models/gaEvents/applicationEvent.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/modules/draft-store/draftGADocumentService.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/additionalInfoUpload/checkAnswerController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/moreInfoSubmittedConfirmationController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/uploadDocumentsForRequestMoreInfoController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/additionalInfoUpload/uploadDocumentsForReqMoreInfoService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/additionalInfoUpload/checkYourAnswer.njk
  src/main/views/features/generalApplication/additionalInfoUpload/confirmation-screen.njk
  src/main/views/features/generalApplication/additionalInfoUpload/upload-documents.njk
  src/test/unit/routes/features/claim/generalApplication/additionalInfoUpload/checkAnswerController.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalInfoUpload/moreInfoSubmittedConfirmationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalInfoUpload/uploadDocumentsForRequestMoreInfoController.test.ts
  src/test/unit/services/features/generalApplication/additionalInfoUpload/uploadDocumentsForReqMoreInfoService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-upload-documents-for-addln-info-check-and-send.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-upload-documents-for-addln-info-confirmation.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-upload-documents-for-addln-info.html
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4274

#4277 CIV-14017 Pay application fee button on view my screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/routes/urls.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/routes/features/claim/generalApplication/viewApplicationController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-view-application.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4277

#4245 CIV-14334 Submit function for Hwf - GA for Lips
  src/main/app/client/gaServiceClient.ts
  src/main/common/models/gaEvents/applicationEvent.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeContinueController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithFeesContentController.ts
  src/main/routes/features/generalApplication/applicationFee/payApplicationFeeConfirmationController.ts
  src/main/services/features/generalApplication/applicationFee/generalApplicationFeePaymentService.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/services/features/generalApplication/applicationFee/helpWithFeeReferenceContents.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeContinueController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithFeesContentController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/payApplicationFeeConfirmationController.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithFeeReferenceContents.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4245

#4317 CIV-0000 Update: ws package
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4317

#4285 CIV-14644 application status
  src/main/common/models/generalApplication/applicationSummary.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/macro/generalApplication/application-summary.njk
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4285

#4308 CIV-14835 Fix labels and error message positioning
  src/main/views/features/claim/amount/claim-amount-breakdown.njk
  src/main/views/features/claim/yourDetails/timeline.njk
  src/main/views/macro/claim-amount.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4308

#4310 CIV-11811 Accept payment method page has wrong content when Defendant response is PartAdmit
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4310

#4319 CIV-14073 fix bug
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/test/unit/routes/features/caseProgression/checkYourAnswersController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4319

#4330 CIV-14701 Click on Pay link after submit the claim gives an error
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/views/features/claim/payment/claim-fee-breakdown.njk
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4330

#4332 CIV-14702 update status
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/dashboardController.ts
  src/main/views/features/dashboard/dashboard.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4332

#4269 CIV-14168 Navigation for make application
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
  src/main/routes/features/generalApplication/applicationFeePaymentSuccessfulController.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/applicationFeePaymentConfirmationContent.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFeePaymentSuccessfulController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-application-submitted.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4269

#4309 CIV-14339 - Use 1 template for Case Progression confirmation pages
  src/main/routes/features/caseProgression/documentsUploadedController.ts
  src/main/routes/features/caseProgression/hearingFee/payHearingFeeConfirmationController.ts
  src/main/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/commentsConfirmationController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/confirmationController.ts
  src/main/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.ts
  src/main/routes/features/claim/paymentSuccessfulController.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/features/caseProgression/documents-uploaded.njk
  src/main/views/features/caseProgression/hearingFee/pay-hearing-fee-confirmation.njk
  src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
  src/main/views/features/caseProgression/requestForReconsideration/comments-confirmation.njk
  src/main/views/features/caseProgression/requestForReconsideration/confirmation.njk
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements-confirmation.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4309

#4315 CIV-13928 fixed: case number not appearing in hearing fee
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeReferenceContents.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionContents.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpWithFeesPageContent.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeStartPageContent.ts
  src/main/services/features/helpWithFees/applyHelpWithFeesService.ts
  src/test/unit/services/features/caseProgression/hearingFee/heringFeeStartPageContent.test.ts
  src/test/unit/services/features/helpWithFees/applyHelpWithFeesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4315

#4320 CIV-14320 GA - Upload additional documents - Judge/Party access CIV-14326 CIV-14328
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationAddlDocument.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/response/view-application.njk
  src/main/views/features/generalApplication/view-applications.njk
  src/main/views/macro/create-table-documents.njk
  src/test/unit/routes/features/claim/generalApplication/response/viewApplicationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/viewApplicationController.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4320

#4171 CIV-14538 -Permissive Content Security Policy (CSP)
  sonar-project.properties
  src/main/app.ts
  src/main/app/auth/user/oidc.ts
  src/main/index.js
  src/main/modules/helmet/index.ts
  webpack/govukFrontend.js
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4171

#4294 CIV-14388 Court Response - Judge's directions
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationDirectionsOrderDocument.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/routes/features/claim/generalApplication/viewApplicationController.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4294

#4301 CIV-14714 RTL compatibility changes
  src/main/common/form/models/address.ts
  src/main/common/form/models/partyDetails.ts
  src/main/common/form/validators/fullNameValidator.ts
  src/main/common/form/validators/maxLengthValidator.ts
  src/main/common/form/validators/postcodeValidator.ts
  src/main/common/form/validators/specialCharValidator.ts
  src/main/common/form/validators/validationConstraints.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/defendant/defendantDetailsController.ts
  src/main/routes/features/claim/yourDetails/claimantDetailsController.ts
  src/main/routes/features/response/citizenDetails/citizenDetailsController.ts
  src/test/unit/common/form/validators/address.test.ts
  src/test/unit/common/form/validators/fullNameValidator.test.ts
  src/test/unit/common/form/validators/maxLengthValidator.test.ts
  src/test/unit/common/form/validators/partyDetails.test.ts
  src/test/unit/common/form/validators/postcodeValidator.test.ts
  src/test/unit/common/form/validators/specialCharValidator.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4301

#4323 CIV-14005 respondent application summary
  src/main/routes/features/generalApplication/response/applicationResponseSummaryController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseSummaryController.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-summary.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4323

#4333 CIV-14855 Lip Respondent expert case flags
  src/main/common/models/directionsQuestionnaire/experts/experts.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertReportDetailsController.ts
  src/main/services/features/common/hearingExportsReportBuilderSection.ts
  src/main/services/features/directionsQuestionnaire/expertReportDetailsService.ts
  src/main/services/translation/response/convertToCCDExpert.ts
  src/main/services/translation/response/convertToCCDLiPExpert.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-report-details-claimant.njk
  src/main/views/features/directionsQuestionnaire/experts/expert-report-details.njk
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/expertReportDetails.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertReportDetailsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/hearingExportsReportBuiderSection.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIDQs.test.ts
  src/test/unit/services/translation/response/convertToCCDDQExtraDetails.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4333

#4313 CIV-11758 change track
  src/main/common/form/models/claimType.ts
  src/main/common/models/claim.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/requestForReviewCommentsController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/requestForReviewController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/routes/features/caseProgression/trialArrangements/isCaseReadyController.ts
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
  src/main/routes/features/claimantResponse/ccj/ccjCheckAnswersController.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
  src/main/services/features/caseProgression/hearingFee/makePaymentAgainService.ts
  src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
  src/main/services/features/claimantResponse/ccj/ccjCheckAnswersService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/features/caseProgression/checkYourAnswersController.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/services/features/caseProgression/caseProgressionService.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4313

#4342 CIV-14762 Updates to screen content
  src/main/routes/features/generalApplication/additionalFee/additionalFeeController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/additionalFee/additional-fee.njk
  src/test/unit/routes/features/claim/generalApplication/additionalFee/additionalFeeController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4342

#4367 CIV-14120 Status update on Application detail screen - Additional fee paid
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4367

#4331 CIV-14851 GA for LiPs - back button navigation and fee amount in HWF journey
  src/main/routes/features/generalApplication/additionalFee/payAdditionalFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeContinueController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithFeesContentController.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/main/services/features/generalApplication/feeDetailsService.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeContinueController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
  src/test/unit/services/features/generalApplication/feeDetailsService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4331

#4382 CIV-0000 testpr for rtf file
  src/main/common/form/validators/isAllowedMimeType.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4382

#4224 DTSCCI-313 check defendant is linked for civil claims
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/DefendantLinkStatus.ts
  src/main/routes/features/public/firstContact/claimReferenceController.ts
  src/test/functionalTests/citizenFeatures/citizenDashboard/pages/citizenDashboard.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/assignCasePinInPost.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/commonFeatures/home/pages/login.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/common/LRvLip_response_rejectAll_DisputeAll_tests.js
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4224

#4358 CIV-14813 Defendant Dashboard - Application section
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4358

#4389 DTSCCI-796 - Removing 10 second waits
  src/test/functionalTests/commonFeatures/home/steps/login.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4389

#4387 CIV-14980 Bug Fix
  src/main/routes/features/caseProgression/requestForReconsideration/cancelRequestForReconsiderationController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/checkAnswersCommentsController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/checkAnswersController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/requestForReviewCommentsController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/requestForReviewController.ts
  src/main/routes/features/caseProgression/trialArrangements/cancelTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
  src/main/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/routes/features/caseProgression/trialArrangements/isCaseReadyController.ts
  src/main/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4387

#4249 CIV-0000 Enable dashboard notification content check
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4249

#4356 CIV-14858 Welsh translations for confirm paid page
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4356

#4338 CIV-14514 link ga pages to the application being paid for
  src/main/routes/features/generalApplication/additionalFee/payAdditionalFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeContinueController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithFeesContentController.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/submitGeneralApplicationConfirmationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/services/features/generalApplication/applicationFee/helpWithFeeReferenceContents.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/submitApplication.ts
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/test/unit/routes/features/claim/generalApplication/checkAnswersController.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithFeeReferenceContents.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-apply-help-fee-selection.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-apply-help-with-fees-reference-number.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-apply-help-with-fees-start.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-apply-help-with-fees.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4338

#4386 CIV-14978 Unable to submit defendant sole trader response
  src/main/common/utils/taskList/tasks/taskListHelpers.ts
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaimDefendantSoleTrader.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantResponseCarm.js
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4386

#4347 CIV-14880 change statement of truth
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claim/check-answers.njk
  src/main/views/features/claimantResponse/ccj/check-answers.njk
  src/main/views/macro/statement-of-truth.njk
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4347

#4337 CIV-14274 Adding Request More Info to Response From Court Section
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
  src/test/utils/mocks/applicationMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4337

#4369 DTSCCI-753 update packages and fix audit issues
  .eslintignore
  package.json
  src/main/assets/js/jquery.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4369

#4412 DTSCCI-753 update packages and fix audit issues REVERT
  .eslintignore
  package.json
  src/main/assets/js/jquery.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4412

#4344 CIV-14338 - Trial ready & final order on Notices and Orders page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/ordersAndNoticesController.ts
  src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationContent.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationService.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4344

#4366 CIV-14311 Navigation for Make application journey - Settle or Dismiss by consent and Set aside judgment
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/guards/generalApplication/addAnotherApplicationGuard.ts
  src/main/routes/guards/generalApplication/agreementFromOtherPartyGuard.ts
  src/main/routes/guards/generalApplication/orderJudgeGuard.ts
  src/main/routes/guards/generalApplication/requestReasonControllerGuard.ts
  src/test/unit/routes/features/claim/generalApplication/orderJudgeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/requestingReasonController.test.ts
  src/test/unit/routes/guards/generalApplication/agreementFromOtherPartyGuard.test.ts
  src/test/unit/routes/guards/generalApplication/orderJudgeGuard.test.ts
  src/test/unit/routes/guards/generalApplication/requestingReasonControllerGuard.test.ts
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4366

#4371 CIV-14849 unavailability dates radio button labelling
  src/main/assets/js/append-row.js
  src/main/modules/i18n/locales/en.json
  src/main/views/macro/unavailable-date-row.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4371

#4416 CIV-15012 court documents opened in new tab
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4416

#4357 CIV-13865 Response application navigation
  src/main/common/models/generalApplication/response/gaResponse.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeContinueController.ts
  src/main/routes/features/generalApplication/respondentAgreeToOrderController.ts
  src/main/routes/features/generalApplication/respondentRequestChangeInformationController.ts
  src/main/routes/features/generalApplication/response/acceptDefendantOfferController.ts
  src/main/routes/features/generalApplication/response/checkAnswersResponseController.ts
  src/main/routes/features/generalApplication/response/hearingArrangementResponseController.ts
  src/main/routes/features/generalApplication/response/hearingContactDetailsResponseController.ts
  src/main/routes/features/generalApplication/response/hearingSupportResponseController.ts
  src/main/routes/features/generalApplication/response/respondentAgreementController.ts
  src/main/routes/features/generalApplication/response/respondentHearingPreferenceController.ts
  src/main/routes/features/generalApplication/response/respondentUploadEvidenceDocmentsController.ts
  src/main/routes/features/generalApplication/response/respondentWantToUploadDocumentsController.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesResponseController.ts
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/test/unit/routes/features/claim/generalApplication/response/checkAnswersResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingSupportResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/respondentAgreementController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/respondentUploadEvidenceDocumentsController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/respondentWantToUploadDocController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/unavailableHearingDatesResponseController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4357

#4378 CIV-14901 Data issues for HwF
  src/main/common/models/generalApplication/gaHelpWithFees.ts
  src/main/modules/draft-store/gaHwFeesDraftStore.ts
  src/main/routes/features/generalApplication/additionalFee/payAdditionalFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeContinueController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithFeesContentController.ts
  src/main/routes/features/generalApplication/applicationFee/payApplicationFeeConfirmationController.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/test/unit/modules/draft-store/gaHwFeesDraftStore.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalFee/payAdditionalFeeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeContinueController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithFeesContentController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/payApplicationFeeConfirmationController.test.ts
  src/test/unit/routes/guards/generalAplicationGuard.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseStoreService.test.ts
  src/test/unit/services/features/generalApplication/uploadN245FormService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-pay-application-fee-confirmation.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4378

#4384 CIV-14892 Re-direct/Alert message
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeController.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4384

#4398 CIV-14475 Court Response - Hearing Order
  src/main/common/models/document/documentType.ts
  src/main/common/models/generalApplication/CourtResponseSummary.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/additionalDocuments/uploadAdditionalDocumentsController.ts
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/response/view-application.njk
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/routes/features/claim/generalApplication/response/viewApplicationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/viewApplicationController.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4398
