Repository hmcts/civil-citizen-ui, pull requests merged in 2024-04, with the labels that each got.

#3483 CIV-00000 Fix jq issue
  bin/pull-latest-release-asset.sh
  bin/utils/idam-lease-user-token.sh
Labels: fullDeploy, pr-values:elasticsearch

#3490 fix flaky functional tests
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/tests/wa/welshResponse_caseworker_request_translation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3490

#3472 CIV-12989 Dashboard notification- Claimant rejects repayment plan
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-3472

#3495 CIV-0000 fix login test
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/commonFeatures/home/pages/login.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecFastTrack.js
  src/test/functionalTests/tests/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3495

#3475 CIV-11302 Trial Arrangements Notify Other Party
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3475

#3304 CIV-11402 Defendant response case flags
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/services/translation/response/ccdTranslation.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3304

#3522 CIV-13035 Added Property in dashboardInterpolationService for dashboard notifications
  src/main/services/dashboard/dashboardInterpolationService.ts
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3522

#3534 CIV-000 fix yarn audit known issues
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3534

#3520 CIV-13260 Hearing Fee Required
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, pr-values:enableNotifyEmails, rel:civil-citizen-ui-pr-3520

#3484 CIV-11301 dashboard notification trial arrangements
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3484

#3414 CIV-13281 Fields disappears when the enter button has been pressed
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-details.njk
  src/main/views/features/directionsQuestionnaire/experts/expert-report-details.njk
  src/main/views/features/directionsQuestionnaire/hearing/unavailable-dates-for-hearing.njk
  src/main/views/features/directionsQuestionnaire/support-required-list.njk
  src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witness.njk
  src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
  src/main/views/features/response/statementOfMeans/income/regular-income.njk
  src/main/views/macro/expert-details-row.njk
  src/main/views/macro/report-detail.njk
  src/main/views/macro/support-required.njk
  src/main/views/macro/transaction-details.njk
  src/main/views/macro/unavailable-date-row.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3414

#3536 CIV-12929 Claim status is not correct when claim is waiting for Case…
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3536

#3407 CIV-13234 Timeline missing from defendant response
  src/main/common/form/models/rejectAllOfClaim.ts
  src/main/routes/features/response/timelineOfEvents/defendantTimelineController.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/response/timelineOfEvents/defendantTimelineService.ts
  src/main/services/translation/convertToCUI/convertToCUIRejectAllOfClaim.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDResponseTimelineOfEvents.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/unit/services/features/response/timelineOfEvents/defendantTimelineService.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDResponseTimelineOfEvents.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3407

#3552 CIV-12912 fix task list translations
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/claim/claimTaskListController.ts
  src/main/services/features/claim/taskListService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3552

#3528 CIV-11710 - bundles page
  src/main/common/models/caseProgression/bundles/bundle.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/bundlesController.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/caseProgression/bundles/bundlesService.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/features/caseProgression/bundles.njk
  src/main/views/macro/newDashboarBack.njk
  src/test/unit/routes/features/caseProgression/bundlesController.test.ts
  src/test/unit/services/features/caseProgression/bundles/bundlesService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-bundle-overview.html
Labels: fullDeploy

#3569 CIV-12460 ClaimantIntent Reject the Defendant response PartAdmit pay by instalments
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/createClaim/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3569

#3342 CIV-12545 Upload mediation docs UI automation
  src/test/functionalTests/citizenFeatures/response/pages/claimantLiPResponse/checkYourAnswers.js
  src/test/functionalTests/citizenFeatures/response/pages/claimantLiPResponse/claimantUpdate.js
  src/test/functionalTests/citizenFeatures/response/pages/uploadMediationDocuments/checkYourAnswers.js
  src/test/functionalTests/citizenFeatures/response/pages/uploadMediationDocuments/confirmation.js
  src/test/functionalTests/citizenFeatures/response/pages/uploadMediationDocuments/typeOfDocuments.js
  src/test/functionalTests/citizenFeatures/response/pages/uploadMediationDocuments/uploadDocuments.js
  src/test/functionalTests/citizenFeatures/response/steps/lipClaimantResponseSteps.js
  src/test/functionalTests/citizenFeatures/response/steps/uploadDocSteps.js
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/mediation.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3342

#3591 CIV-0000 Dashboard update
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  src/test/config.js
  src/test/functionalTests/citizenFeatures/response/pages/claimantLiPResponse/claimantUpdate.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantLatestUpdate.js
  src/test/functionalTests/citizenFeatures/response/steps/lipClaimantResponseSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/hwfPayloads.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_Api_FullAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_upload_evidence_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_trial_arrangements_fasttrack_notReadyForTrial_tests.js
  src/test/functionalTests/tests/nonprod/cp_trial_arrangements_fasttrack_readyForTrial_tests.js
  src/test/functionalTests/tests/nonprod/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3591

#3471 CIV-13248 typo error
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3471

#3473 CIV-13206 deadline pay immediately
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/partAdmitConfirmationContentBuilder.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3473

#3563 CIV-13368 Claim status - determination where defendant is individual/sole trader
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3563

#3564 CIV-13262 content changes for defendant request more time
  jest.config.js
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/requestMoreTimeController.ts
  src/main/routes/features/response/responseDeadline/agreedResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/newResponseDeadlineController.ts
  src/main/routes/features/response/responseDeadline/responseDeadlineOptionsController.ts
  src/main/routes/features/response/understandingYourOptionsController.ts
  src/main/views/features/response/request-more-time.njk
  src/main/views/features/response/response-deadline-options.njk
  src/main/views/features/response/responseDeadline/agreed-response-deadline.njk
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/main/views/features/response/understanding-your-options.njk
  src/test/unit/routes/features/response/responseDeadline/agreedResponseDeadlineController.test.ts
  src/test/unit/routes/features/response/responseDeadline/newResponseDeadlineController.test.ts
  src/test/unit/routes/features/response/responseDeadlineOptionsController.test.ts
  src/test/unit/routes/features/response/understandingYourOptionsController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3564

#3410 CIV-13236 Full Defence States Paid (Not Paid In Full) - CYA Page content incorrect
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3410

#3540 CIV-13252 validation over 18
  src/main/common/form/models/claim/claimant/citizenDate.ts
  src/main/common/utils/dateUtils.ts
  src/main/routes/features/claim/yourDetails/claimantDoBController.ts
  src/main/views/features/response/citizenDob/citizen-dob.njk
  src/test/unit/routes/features/claim/claimantDoBController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3540

#3456 CIV-13324 Eligibility Page
  src/main/routes/features/public/eligibility/claimantOver18EligibilityController.ts
  src/main/routes/features/public/eligibility/someUsefulInfoFeesController.ts
  src/test/functionalTests/citizenFeatures/createClaim/pages/eligibilityCheck.js
  src/test/functionalTests/citizenFeatures/createClaim/steps/createLipvLipClaimSteps.js
  src/test/unit/routes/features/public/eligibility/claimantOver18EligibilityController.test.ts
  src/test/unit/routes/features/public/eligibility/someUsefulInfoFeesController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3456

#3383 CIV-13055 Fix missing CCJ details and Welsh translation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/responseSection/buildCourtDecisionDetailsSection.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildCourtDecisionDetailsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3383

#3549 CIV-13267 fix page title
  src/main/views/features/claimantResponse/settle-admitted.njk
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm

#3553 CIV-13361 CCJ selected to formalise remove settlement agreement
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm

#3541 CIV-13203 Update contact-them page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/contactThemController.ts
  src/main/routes/features/dashboard/viewClaimantInformationController.ts
  src/main/routes/features/dashboard/viewDefendantInformationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/views/features/dashboard/contact-them-new.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/dashboard/viewClaimantInformationController.test.ts
  src/test/unit/routes/features/dashboard/viewDefendantInformationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3541

#3561 CIV-12450 Claimant Intent for FullAdmit scenarios
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/createClaim/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitSmallClaimsDefendantResponse.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_NotFull_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3561

#3630 CIV-13292 Dashboard support links
  sonar-project.properties
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/dashboard/taskList/dashboardTaskStatus.ts
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/macro/support-links.njk
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/utils/externalURLs.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3630

#3629 CIV-13570 Updated scenario key for draft claims
  src/main/app/client/civilServiceClient.ts
  src/test/unit/app/client/civilServiceClient.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3629

#3568 CIV-12908 Claimant Dashboard Status - Payment
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3568

#3618 CIV-11844 Evidence Upload page new Dashboard
  src/main/common/form/models/alignText.ts
  src/main/common/utils/formatDocumentURL.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/evidenceUploadDocumentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/documentTableBuilder.ts
  src/main/services/features/caseProgression/uploadedEvidenceFormatter.ts
  src/main/services/features/dashboard/evidenceUploadDocumentsService.ts
  src/main/views/features/caseProgression/evidence-upload-documents.njk
  src/test/unit/routes/features/dashboard/evidenceUploadDocumentsController.test.ts
  src/test/unit/services/features/dashboard/evidenceUploadDocumentsService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-evidence-upload-documents.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3618

#3571 CIV-11709 view the hearing
  src/main/common/models/summaryList/summaryList.ts
  src/main/common/utils/formatDocumentURL.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/viewTheHearingController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/caseProgression/hearing/hearingService.ts
  src/main/views/features/caseProgression/view-the-hearing.njk
  src/main/views/macro/dashboard-accordion.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/utils/formatDocumentURL.test.ts
  src/test/unit/routes/features/caseProgression/viewTheHearingControllerTest.ts
  src/test/unit/services/features/caseProgression/hearing/hearingService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3571

#3529 CIV-11304 Order Made
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/dashboardNotification.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantClaimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-evidence-upload-documents
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3529

#3566 CIV-13207 Content changes to the view the claim screen
  src/main/common/models/claim.ts
  src/main/common/models/evidence/evidence.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/views/features/response/claimDetails/claim-details-new.njk
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3566

#3588 CIV-13142 View Response to the claim page creation
  src/main/common/mappers/documentViewMapper.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/viewResponseToClaimController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/views/features/dashboard/view-response-to-claim.njk
  src/main/views/macro/create-table-documents.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/common/mappers/documentViewMapper.test.ts
  src/test/unit/routes/features/dashboard/viewResponseToClaimController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3588

#3643 CIV-13416 - Dashboard - HWF claim issue -Content changes/Welsh translations
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3643

#3655 CIV-0000 Test pr
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_DefaultJudgment_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3655

#3538 CIV-11305 url for upload hearing documents
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3538

#3606 CIV-13157 CIV-13159 Unsuccessful mediation non attendance notifications
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3606

#3589 CIV-13533 Date of birth in CCJ check your answers
  src/main/services/features/claim/checkAnswers/detailsSection/buildCcjTheirDetailsSection.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildCcjTheirDetailsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3589

#3626 CIV-13543 space is needed between the text and actual name
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3626

#3596 CIV-13401 SettlementAgreement is not updated on the Defendant side
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/services/features/settlementAgreement/respondSettlementAgreementService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3596

#3559 CIV-13251 add check for NI and Scot
  src/main/common/form/validators/postcodeValidator.ts
  src/test/unit/common/form/validators/postcodeValidator.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3559

#3687 CIV-0000 fix date issue
  src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3687

#3557 CIV-13261 Settlement agreement displaying inconsistent dates
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
  src/main/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.ts
  src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
  src/main/services/features/settlementAgreement/respondSettlementAgreementService.ts
  src/main/services/features/settlementAgreement/settlementAgreementConfirmationBuilder/confirmationContentBuilder.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/features/claimantResponse/signSettlmentAgreementController.test.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementConfirmationController.test.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
  src/test/unit/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3557

#3658 CIV-0000 Dashboard changes
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/common/mappers/documentViewMapper.ts
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/dashboardNotification.ts
  src/main/common/models/evidence/evidence.ts
  src/main/common/models/summaryList/summaryList.ts
  src/main/common/utils/formatDocumentURL.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/viewTheHearingController.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/routes/features/dashboard/viewResponseToClaimController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/features/caseProgression/hearing/hearingService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/views/features/caseProgression/view-the-hearing.njk
  src/main/views/features/dashboard/view-response-to-claim.njk
  src/main/views/features/response/claimDetails/claim-details-new.njk
  src/main/views/macro/create-table-documents.njk
  src/main/views/macro/dashboard-accordion.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/common/mappers/documentViewMapper.test.ts
  src/test/unit/common/utils/formatDocumentURL.test.ts
  src/test/unit/routes/features/caseProgression/viewTheHearingControllerTest.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantClaimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/routes/features/dashboard/viewResponseToClaimController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/caseProgression/hearing/hearingService.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-evidence-upload-documents
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3658

#3572 CIV-9120 Add dashboard statuses
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3572

#3694 CIV-0000 Carm changes CIV-13345 and CIV-13378
  src/main/common/mappers/documentViewMapper.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/document/mediation/viewMediationDocumentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/document/mediation/mediationDocumentService.ts
  src/main/views/features/common/viewDocuments.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/document/mediation/viewMediationDocumentsController.test.ts
  src/test/unit/services/features/document/mediation/mediationDocumentService.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/Mediation/uploadFilesMediationMocks.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3694

#3628 CIV-13427 Confirmation screen for claimant response - defendant business - proposed new repayment plan
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/financialDetailsBuilder.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3628
