Repository hmcts/civil-citizen-ui, pull requests merged in 2024-09, with the labels that each got.

#4456 CIV-15167 Fix functional test: Create LipvLip claim and defendant response as FullAdmit and pay immediately
  src/test/functionalTests/tests/nonprod/LiPvLiP_Api_FullAdmit_PayImmediately_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4456

#4422 DTSCCI-753 update packages and fix CVEs
  .eslintignore
  .sass-lint.yml
  .stylelintrc.json
  README.md
  package.json
  src/main/assets/js/jquery.js
  src/main/assets/scss/main.scss
  src/main/assets/scss/task-list.scss
  yarn-audit-known-issues
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4422

#4470 CIV-0000 Ip Vulnerability suppress
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4470

#4414 CIV-14960 Displaying Without Notice or Consent Cases Created by Defendants
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4414

#4363 CIV-14276 provide more information screen
  src/main/common/form/validators/respondAddInfoValidator.ts
  src/main/common/models/generalApplication/response/gaResponse.ts
  src/main/common/models/generalApplication/response/respondAddInfo.ts
  src/main/modules/draft-store/draftGADocumentService.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/additionalInfoUpload/checkAnswerController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/respondController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/uploadDocumentsForRequestMoreInfoController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/additionalInfoUpload/uploadDocumentsForReqMoreInfoService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/views/features/generalApplication/additionalInfoUpload/additional-info.njk
  src/test/unit/routes/features/claim/generalApplication/additionalInfoUpload/checkAnswerController.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalInfoUpload/respondAddInfoController.test.ts
  src/test/unit/services/features/generalApplication/additionalInfoUpload/uploadDocumentsForReqMoreInfoService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-respond-addln-info.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4363

#4376 CIV-14919 Displaying applications time
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/routes/features/generalApplication/response/applicationResponseSummaryController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationSummaryController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseSummaryController.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4376

#4362 CIV-14088 Error message for GA screens - upload documents
  src/main/routes/features/generalApplication/response/respondentUploadEvidenceDocmentsController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/test/unit/routes/features/claim/generalApplication/response/respondentUploadEvidenceDocumentsController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4362

#4455 CIV-15127 change-a-hearing-date
  src/main/common/models/generalApplication/applicationType.ts
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/guards/generalApplication/orderJudgeGuard.ts
  src/main/routes/guards/generalApplication/requestReasonControllerGuard.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/unit/routes/features/claim/generalApplication/applicationTypeController.test.ts
  src/test/unit/routes/guards/generalApplication/orderJudgeGuard.test.ts
  src/test/unit/routes/guards/generalApplication/requestingReasonControllerGuard.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4455

#4399 CIV-14353 Court response - request written representations - provide more information screen
  src/main/common/models/generalApplication/response/gaResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFeePaymentSuccessfulController.ts
  src/main/routes/features/generalApplication/writtenRepresentationDocs/checkAnswerController.ts
  src/main/routes/features/generalApplication/writtenRepresentationDocs/respondToWrittenRepController.ts
  src/main/routes/features/generalApplication/writtenRepresentationDocs/uplodWrittenRepresentationDocsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/writtenRepresentation/writtenRepresentationDocsService.ts
  src/main/views/features/generalApplication/additionalInfoUpload/respondToWrittenRepInfo.njk
  src/test/unit/routes/features/claim/generalApplication/writtenRepresentationDocs/checkAnswerController.test.ts
  src/test/unit/routes/features/claim/generalApplication/writtenRepresentationDocs/respondWrittenRepControllerTest.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/writtenRepresentation/writtenRepresentationDocsService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4399

#4441 CIV-13999 View all application link and upload link on dashboard page
  src/main/app/client/gaServiceClient.ts
  src/main/common/models/dashboard/iWantToLinks.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/routes/features/generalApplication/response/applicationResponseSummaryController.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/main/views/features/generalApplication/response/view-application.njk
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4441

#4451 CIV-14872 changed-doc-named-for-lips
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/views/features/generalApplication/response/view-application.njk
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4451

#4457 CIV-15163 - notificationRedirectController calls to civil service
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4457

#4327 CIV-14011 ga response submitted
  src/main/app/client/gaServiceClient.ts
  src/main/app/client/gaServiceUrls.ts
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationHearingDetails.ts
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationRespondentResponse.ts
  src/main/common/models/gaEvents/applicationEvent.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/routes/features/generalApplication/response/checkAnswersResponseController.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesResponseController.ts
  src/main/services/features/generalApplication/response/checkAnswersResponseService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseStoreService.ts
  src/main/services/features/generalApplication/response/submitApplicationResponse.ts
  src/main/services/translation/claim/moneyConversation.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/app/client/gaServiceClient.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/checkAnswersResponseController.test.ts
  src/test/unit/services/features/generalApplication/response/checkAnswersResponseService.test.ts
  src/test/unit/services/features/generalApplication/response/submitApplicationResponse.test.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4327

#4481 CIV-15197 Changes to retrieve GA dashboard notifications
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/CaseLink.ts
  src/main/common/models/generalApplication/claimGeneralApplication.ts
  src/main/common/models/partyType.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4481

#4492 DTSCCI-745 - Update Dynatrace URL
  config/default.yaml
  config/production.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4492

#4501 CIV-0000 supressed security issues
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4501

#4324 CIV-14602 General order
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationAddlDocument.ts
  src/main/common/models/claim.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4324

#4406 CIV-15015 view application back button fixed
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4406

#4472 CIV-15053 Refactor Vary Judgement CYA Guard
  src/main/routes/guards/checkYourAnswersGAGuard.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4472

#4488 CIV-15206 Unable to submit GA Something thats not on this list
  src/main/common/models/generalApplication/applicationType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/services/features/generalApplication/orderJudgePageBuilder.ts
  src/main/views/features/generalApplication/application-type.njk
  src/test/unit/routes/features/claim/generalApplication/applicationTypeController.test.ts
  src/test/unit/services/features/generalApplication/orderJudgePageBuilder.test.ts
  src/test/unit/services/features/generalApplication/requestingReasonPageBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4488

#4502 DTSCCI-745 - Split dynatrace url prod - non-prod
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4502

#4521 CIV-15259 Set inform other party for SET_ASIDE_JUDGMENT
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationInformOtherParty.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4521

#4498 CIV-14239 Response section - LiP View Applications
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationRespondentResponse.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/response/submitApplicationResponse.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4498

#4494 CIV-14109 - move full stop out of hyperlinks
  src/main/common/form/models/claimSummarySection.ts
  src/main/common/utils/pageSectionBuilder.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionContents.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/main/services/features/caseProgression/trialArrangements/hasAnythingChanged.ts
  src/main/services/features/generalApplication/additionalFee/helpWithAdditionalFeeContent.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/services/features/helpWithFees/applyHelpWithFeesService.ts
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
  src/main/views/features/dashboard/item-content.njk
  src/main/views/features/generalApplication/applicationFee/help-with-application-fee-reference.njk
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFeesReferenceNumber.js
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/services/features/generalApplication/additionalFee/helpWithAdditionalFeeContent.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4494

#4538 CIV-15294 Change link text for settling claim
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/views/features/claimantResponse/paidInFull/date-paid.njk
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-paid-in-full-date-paid.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4538

#4558 CIV-0000 Ref data location name change
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpec.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimSpecLRvLR.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createSmallTrackClaimSpec.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantResponseCarm.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitSmallClaimsDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllFastTrackDefendantResponse.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4558

#4532 CIV-15277 Unable to make an Application as it is looping back to Make an application page
  src/main/routes/guards/checkYourAnswersGAGuard.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4532

#4467 DTSCCI-812 add preview dev env
  README.md
  bin/setup-devuser-preview-env.sh
  bin/variables/load-dev-user-preview-environment-variables.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4467

#4524 DTSCCI-577 - Add Warning Banner for CUI R2
  src/main/assets/scss/main.scss
  src/main/views/features/dashboard/dashboard.njk
  src/main/views/macro/banner.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4524

#4551 CIV-15240 fix Application submitted date comes as Invalid DateTime
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/claimGeneralApplication.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/features/claim/generalApplication/applicationSummaryController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseSummaryController.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4551

#4429 CIV-15013 lowest fee displayed in payingForYourApplication screen
  src/main/routes/features/generalApplication/payingForApplicationController.ts
  src/test/unit/routes/features/claim/generalApplication/payingForApplicationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4429

#4426 CIV-15010 multiple apps abandoned
  src/main/app.ts
  src/main/common/models/generalApplication/applicationType.ts
  src/main/modules/draft-store/draftStoreService.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/features/generalApplication/wantToUploadDocuments.ts
  src/main/routes/guards/caseProgressionGuard.ts
  src/main/routes/guards/checkYourAnswersGAGuard.ts
  src/main/routes/guards/deleteGAGuard.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/unit/modules/draft-store/draftStoreService.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationTypeController.test.ts
  src/test/unit/routes/guards/deleteGAGuard.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4426

#4500 CIV-15189 Free text entered in the text box is missing
  src/main/views/features/generalApplication/additionalInfoUpload/respondToWrittenRepInfo.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4500

#4483 CIV-14987 Without notice application becomes available for respondent
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4483

#4553 CIV-14790 - Case states for make an application GA for LiPs
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4553

#4519 CIV-15212 - Documents not accessible from 'View my application' screen
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4519

#4552 CIV-15185 added cya changes for response
  src/main/common/models/gaEvents/eventDto.ts
  src/main/services/features/generalApplication/response/checkAnswersResponseService.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/services/features/generalApplication/response/checkAnswersResponseService.test.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4552

#4574 CIV-15287 Fix missing application details
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/test/unit/routes/features/claim/generalApplication/response/viewApplicationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4574

#4444 CIV-14829 remove link to create applications when case is dismissed
  src/main/common/models/claim.ts
  src/main/services/dashboard/dashboardService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4444

#4580 CIV-15810 82 83 84 86 87 88 Welsh Amends
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4580

#4607 CIV-0000 Add skip provider registration
  infrastructure/_state.tf
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:civil-citizen-ui-pr-4607

#4490 CIV-13605 replacing the placeholders
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4490

#4602 CIV-0000 changes doubleclick to wildcard, added GTM main url to CSP policies
  src/main/modules/helmet/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4602

#4509 CIV-15216 change the location of 'Response from the court' section
  src/main/views/features/generalApplication/response/view-application.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4509

#4623 CIV-0000 Csp issue on googletagmanager
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/claim-details-tpl.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4623

#4248 CIV-0000 Add GA tests
  src/test/config.js
  src/test/functionalTests/citizenFeatures/GA/pages/addAnotherApplication.js
  src/test/functionalTests/citizenFeatures/GA/pages/agreementFromOtherParty.js
  src/test/functionalTests/citizenFeatures/GA/pages/applicationCosts.js
  src/test/functionalTests/citizenFeatures/GA/pages/applicationType.js
  src/test/functionalTests/citizenFeatures/GA/pages/applyHelpFeeSelection.js
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/functionalTests/citizenFeatures/GA/pages/claimApplicationCost.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingArrangement.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingArrangementsGuidance.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingContactDetails.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingSupport.js
  src/test/functionalTests/citizenFeatures/GA/pages/informOtherParties.js
  src/test/functionalTests/citizenFeatures/GA/pages/orderJudge.js
  src/test/functionalTests/citizenFeatures/GA/pages/payingForApplication.js
  src/test/functionalTests/citizenFeatures/GA/pages/requestingReason.js
  src/test/functionalTests/citizenFeatures/GA/pages/submitGAConfirmation.js
  src/test/functionalTests/citizenFeatures/GA/pages/unavailableDates.js
  src/test/functionalTests/citizenFeatures/GA/pages/wantToUploadDocuments.js
  src/test/functionalTests/citizenFeatures/response/steps/createGAAppSteps.js
  src/test/functionalTests/tests/common/LRvLip_response_rejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsCompany.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/OrgVsSoleTrader.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4248

#4616 CIV-15389 - Default Judgment RPA
  src/main/common/models/claim.ts
  src/main/common/utils/dateUtils.ts
  src/main/common/utils/interestUtils.ts
  src/main/services/translation/claimantResponse/ccdRequestJudgementTranslation.ts
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/test/unit/common/models/claimantResponse/ccdTranslation.test.ts
  src/test/unit/common/utils/interestUtils.test.ts
  src/test/unit/services/translation/claimantResponse/ccdRequestJudgementTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4616

#4568 CIV-15073 ask for proof of debt payment guidance
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.ts
  src/main/routes/routes.ts
  src/main/views/external-urls.njk
  src/main/views/features/generalApplication/certOfSorC/ask-proof-debtPayment-guidance.njk
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4568

#4621 CIV-15381 Remove Quote Mark - Welsh Amends
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4621

#4615 CIV-15077 CoSC: New Screen (Evidence Upload)
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-cosc-upload-documents.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4615

#4637 CIV-15079 CoSc submit comfirmation page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/test/unit/routes/features/claim/generalApplication/submitGeneralApplicationConfirmationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4637

#4638 CIV-13319 Add FeeOutcome events for HWF scenarios
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/hwfPayloads.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/SoleTraderVsIndividual.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4638

#4649 CIV-0000 - fixed unit tests.
  src/main/common/utils/interestUtils.ts
  src/test/unit/common/utils/interestUtils.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4649

#4603 CIV-15178 Content updates required for LiP and LR application screens
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/payApplicationFeeConfirmationController.ts
  src/main/services/features/generalApplication/applicationFeePaymentConfirmationContent.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4603

#4609 CIV-15361 Incorrect screens
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4609

#4563 CIV-15155 change behaviour of the close
  src/main/routes/features/caseProgression/hearingFee/payHearingFeeConfirmationController.ts
  src/main/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.ts
  src/main/routes/features/claim/paymentSuccessfulController.ts
  src/main/services/features/claim/paymentSuccessfulContents.ts
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements-confirmation.njk
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFeesConfirmation.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/paymentSuccessful.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/trialArrangementsConfirmation.js
  src/test/functionalTests/citizenFeatures/caseProgression/steps/hearingFeeSteps.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/unit/services/features/claim/paymentSuccessfulContents.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4563

#4639 CIV-15076 Certificate of Satisfaction evidence of the debt payment
  src/main/common/models/generalApplication/CertificateOfSatisfactionOrCanceled.ts
  src/main/common/models/generalApplication/debtPaymentEvidence.ts
  src/main/common/models/generalApplication/debtPaymentOptions.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/certOfSorC/debtPaymentEvidenceController.ts
  src/main/routes/features/generalApplication/certOfSorC/defendantFinalPaymentDateController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
  src/main/views/features/generalApplication/certOfSorC/debt-payment-evidence.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/debtPaymentEvidenceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:civil-citizen-ui-pr-4639

#4656 CIV-0000 fix sprint p135 4 cosc
  src/main/common/models/claim.ts
  src/main/common/models/generalApplication/CertificateOfSatisfactionOrCanceled.ts
  src/main/common/models/generalApplication/CertificateOfSatisfactionOrCancellation.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.ts
  src/main/routes/features/generalApplication/certOfSorC/debtPaymentEvidenceController.ts
  src/main/routes/features/generalApplication/certOfSorC/defendantFinalPaymentDateController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/certOfSorC/certificateOfSatisfactionOrCancellationService.ts
  src/main/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.ts
  src/main/services/features/generalApplication/certOfSorC/defendantFinalPaymentDateService.ts
  src/main/views/features/generalApplication/certOfSorC/ask-proof-debtPayment-guidance.njk
  src/main/views/features/generalApplication/certOfSorC/debt-payment-evidence.njk
  src/main/views/features/generalApplication/certOfSorC/final-payment-date.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/debtPaymentEvidenceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/defendantFinalPaymentDateController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/services/features/generalApplication/certOfSorC/certificateOfSatisfactionOrCancellationService.test.ts
  src/test/unit/services/features/generalApplication/certOfSorC/debtPaymentEvidenceService.test.ts
  src/test/unit/services/features/generalApplication/certOfSorC/defendantFinalPaymentDateService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, aat/add-or-update, prod/no-changes, rel:civil-citizen-ui-pr-4656
