Repository hmcts/civil-citizen-ui, pull requests merged in 2024-03, with the labels that each got.

#3251 CIV-0000 Add db15 secrets
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3251

#3189 CIV-0000 HWF Bulk Branch
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3189

#3258 CIV-11970 CUIR2 automation Defendant Response FullAdmit
  src/test/functionalTests/features/createClaim/pages/responseToDefence.js
  src/test/functionalTests/features/createClaim/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createDefendantResponse.js
  src/test/functionalTests/tests/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fasttrack_notReadyForTrial_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fasttrack_readyForTrial_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/createLiPvLiPClaim_tests.js
  src/test/functionalTests/tests/createLiPvLiP_FullAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/createLipvLip_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/createLipvLip_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/createLipvLip_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/createLipvLip_RejectAll_DisputeAll_Mediation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3258

#3168 CIV-12060 Prevent creation of DJ Spec form for LR V LiP claims
  src/main/common/models/businessProcess.ts
  src/main/common/models/claim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3168

#3214 CIV-12795 Remove Banner
  src/main/views/features/directionsQuestionnaire/support-required-list.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3214

#3256 CIV-1197: Defendant response - Api functional tests for part admit and reject all
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/admitAllDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitFastTrackDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitSmallClaimsDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllFastTrackDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllSmallClaimsDefendantResponse.js
  src/test/functionalTests/tests/LiPvLiP_Api_FullAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/LipvLip_Api_RejectAll_AlreadyPaid_tests.js
  src/test/functionalTests/tests/LipvLip_Api_RejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/LipvLip_Api_partAdmit_PayBySetDate_tests.js
  src/test/functionalTests/tests/LipvLip_Api_partAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
  src/test/functionalTests/tests/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fasttrack_notReadyForTrial_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fasttrack_readyForTrial_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3256

#3273 CIV-1511 Add different party types scenarios for claim creation
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/createClaim/pages/createClaim.js
  src/test/functionalTests/features/createClaim/steps/createLipvLipClaimSteps.js
  src/test/functionalTests/helpers/browser_helper.js
  src/test/functionalTests/tests/LipvLip_Api_RejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/createClaim/OrgVsSoleTrader.js
  src/test/functionalTests/tests/createClaim/SoleTraderVsIndividual.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3273

#3272 CIV-11605 TRACK NON-JAVASCRIPT VISITS IN GOOGLE ANALYTICS
  src/main/views/claim-details-tpl.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3272

#3275 CIV-13099 - remove dashboard cache
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/dashboard/dashboard.ts
  src/main/common/models/dashboard/dashboardNotification.ts
  src/main/common/models/dashboard/dashboardNotificationList.ts
  src/main/common/models/dashboard/taskList/civilServiceDashboardTask.ts
  src/main/common/models/dashboard/taskList/dashboardTask.ts
  src/main/common/models/dashboard/taskList/dashboardTaskList.ts
  src/main/modules/draft-store/getDashboardCache.ts
  src/main/routes/features/dashboard/claimantClaimSummaryController.ts
  src/main/routes/routes.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/modules/utilityService.test.ts
  src/test/unit/routes/features/dashboard/claimantClaimSummaryController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3275

#3296 CIV-000 hide S2S_SECRET
  src/test/config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3296

#3291 CIV-0000 - claim id payment
  src/main/modules/utilityService.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-3291

#3310 CIV-0000 Add camunda checks
  src/test/functionalTests/features/createClaim/pages/createClaim.js
  src/test/functionalTests/features/createClaim/steps/createLipvLipClaimSteps.js
  src/test/functionalTests/tests/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
  src/test/functionalTests/tests/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/createClaim/OrgVsSoleTrader.js
  src/test/functionalTests/tests/createClaim/SoleTraderVsIndividual.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3310

#3197 CIV-12815 Assign claim is passing undefined claimid to civil-service causing issues in prod and aat
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/AppRequest.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/claimAssignment/assignClaimController.ts
  src/main/routes/features/public/firstContact/claimReferenceController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/main/services/firstcontact/firstcontactService.ts
  src/main/views/features/public/firstContact/claim-summary.njk
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/routes/features/claimAssignment/claimAssignmentController.test.ts
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3197

#3245 CIV-12879 Fix translations on some pages
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/services/features/claim/checkAnswers/claimSection/addEvidence.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/common/claimTimelineService.ts
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/main/views/macro/timeline-summary.njk
  src/test/unit/services/features/claim/checkAnswers/claimSection/buildClaimSection.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3245

#3287 CIV-12901 Trial arrangements and evidence upload scenarios for Claimant Lip
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/hasAnythingChanged.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/isYourCaseReadyForTrial.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/trialArrangementsIntroduction.js
  src/test/functionalTests/features/caseProgression/pages/trialArrangements/trialDuration.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/checkYourAnswers.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocumentsIntroduction.js
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/whatTypeOfDocumentsDoYouWantToUpload.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/features/caseProgression/steps/trialArrangementSteps.js
  src/test/functionalTests/tests/cp_LiPvLiP_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_LiPvLiP_upload_evidence_trial_arrangements_fast_track_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3287

#3293 CIV-12959 - Dashboard notification action filter
  src/main/app/auth/user/oidc.ts
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/AppRequest.ts
  src/main/common/models/dashboard/dashboardNotification.ts
  src/main/common/models/dashboard/dashboardNotificationAction.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/oidc/index.ts
  src/test/unit/app/auth/user/oidc.test.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/modules/oidc/index.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3293

#3219 CIV-12614 payment ccd update
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
  src/main/services/features/feePayment/feePaymentService.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
  src/test/unit/services/features/feePayment/feePaymentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3219

#3352 CIV-00000 Fix unit test
  package.json
  src/main/routes/features/claim/checkAnswersController.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3352

#3358 CIV-12457 ClaimantIntent Accept/Reject the Defendant response PartAdmit payImmediately
  src/test/functionalTests/features/createClaim/pages/responseToDefence.js
  src/test/functionalTests/features/createClaim/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/helpers/browser_helper.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitFastTrackDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitSmallClaimsDefendantResponse.js
  src/test/functionalTests/tests/LipvLip_Api_partAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3358

#3366 CIV-0000 Added Pally urls for R2
  src/test/a11y/constants.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3366

#3374 CIV-12791 - In Mediation Dashboard Scenario
  src/main/common/models/claim.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3374

#3387 CIV-13119 - Dashboard response url change
  src/main/routes/guards/languagePreferenceGuard.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3387

#3413 CIV-0000 change gateway to latest
  charts/civil-citizen-ui/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3413

#3336 CIV-12895 CCJ url for settlement
  src/main/common/models/document/documentType.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3336

#3398 CIV-0000 FT's for Dashboard
  src/test/functionalTests/features/createClaim/pages/responseToDefence.js
  src/test/functionalTests/features/createClaim/steps/createLipvLipClaimSteps.js
  src/test/functionalTests/features/response/pages/claimantLiPResponse/judgment.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/bilingualLanguagePreference.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantAdmission_SSA.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/defendantLatestUpdate.js
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
  src/test/functionalTests/tests/LRvLip_response_deadlineExtension_tests.js
  src/test/functionalTests/tests/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
  src/test/functionalTests/tests/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/createClaim/OrgVsSoleTrader.js
  src/test/functionalTests/tests/createClaim/SoleTraderVsIndividual.js
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3398

#3224 CIV-12914 HWF No answer not displaying in CYA page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claim/checkAnswers/financialSection/buildClaimAmountSection.ts
  src/test/functionalTests/features/createClaim/pages/createClaim.js
  src/test/unit/services/features/claim/checkAnswers/claimAmountSection/buildClaimAmountSection.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3224

#3429 CIV-0000 bilingual screens are added as part of CIV-13119
  src/test/functionalTests/features/response/pages/defendantLipResponse/bilingualLanguagePreference.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3429

#3425 CIV-13073 Dashboard notification - Judgment Requested (where court ag…
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/default.yaml
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3425

#3373 CIV-13111 Defendant response org/com installments
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3373
