Repository hmcts/civil-citizen-ui, pull requests merged in 2024-12, with the labels that each got.

#5168 DTSCCI-000 fix date methods in error tests
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/viewYourOptionsBeforeDeadline/viewYourOptionsBeforeDeadline.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5168

#5149 CIV-15944 - remove optional
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/GA/pages/wantToUploadDocuments.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5149

#5165 CIV-15931 upload a file is mandatory
  src/main/common/models/generalApplication/uploadN245GAFiles.ts
  src/main/routes/features/generalApplication/uploadN245FormController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5165

#5174 CIV-15955 Remove unnecessary data based on the type of application.
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5174

#5057 CIV-15113 Add EM_CCD_ORCHESTRATOR_URL env var
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5057

#5176 CIV-16013 only app can view
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5176

#5185 CIV-16247 Display correct payment reference
  src/main/routes/features/generalApplication/applicationFeePaymentSuccessfulController.ts
  src/main/services/features/generalApplication/applicationFeePaymentConfirmationContent.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5185

#5153 CIV-15852 GA Lip - In the Response draft document, not all the informations are captured
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5153

#5160 CIV-16031 Case offline FTs
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/steps_noc.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/caseProceedsInCaseman.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/tests/common/LRvLiP_case_offline_tests.js
  src/test/functionalTests/tests/common/LiPvLiP_case_offline_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5160

#4984 CIV-15377 - Configure Role Assignments Url
  charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4984

#5215 DTSCCI-00000 remove failing test for now as PRs are blocked
  src/test/e2eTests/tests/generalApplication/LipvsLipStrikeOut.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5215

#4410 DTSCCI-313 check defendant is linked for civil claims
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/routes/features/public/firstContact/claimReferenceController.ts
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/assignCasePinInPost.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/prod/LRvLip_response_admitAll_pininpost_tests.js
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:civil-citizen-ui-pr-4410

#4954 DTSCCI-1078 DQ value not being retrieved correctly
  src/main/services/features/common/buildHearingRequirementsSection.ts
  src/main/services/features/common/buildSmallClaimHearingRequirements.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4954

#5226 DTSCCI-00000 fix failing e2e test
  src/test/functionalTests/citizenFeatures/citizenDashboard/pages/citizenDashboard.js
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/commonFeatures/home/steps/login.js
  src/test/functionalTests/tests/prod/LRvLip_response_admitAll_pininpost_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5226

#5233 CIV-16318 fixing CI
  wiremock/mappings/civil-service-mapping.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5233

#5198 CIV-16269 - Defendant party PCQ questions are not being invoked
  src/main/app/client/pcq/savePcqIdClaim.ts
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/claim.ts
  src/main/routes/guards/pcqGuard.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/test/unit/routes/features/response/checkAnswersController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5198

#5207 CIV-16227 refresh data in redis For DJ
  src/main/common/models/claim.ts
  src/main/routes/features/claimantResponse/ccj/defendantDOBController.ts
  src/main/routes/guards/redisDataFlushForDJGuard.ts
  src/test/unit/modules/draft-store/draftStoreService.test.ts
  src/test/unit/routes/guards/redisDataFlushForDJGuardTest.ts
  src/test/unit/services/features/claim/details/claimDetailsService.test.ts
  src/test/unit/services/features/claim/interest/interestService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/directionQuestionnaireService.test.ts
  src/test/unit/services/features/mediation/uploadDocuments/mediationCheckAnswersService.test.ts
  src/test/utils/mocks/civilClaimResponseDocumentUploadedMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5207

#5229 CIV-16298 No fee only if with consent
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/test/unit/routes/features/claim/generalApplication/checkAnswersController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5229

#5234 CIV-16042 display ADDITIONAL_RESPONSE_TIME_EXPIRED
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5234

#5244 CIV-16228 fixed Welsh translation
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5244

#5239 CIV-16285 removed redundant question
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5239

#5245 CIV-16264 contact us
  src/main/views/features/generalApplication/additionalDocuments/submitted.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5245

#5225 CIV-0000 - fix ga strikeout e2e
  src/test/e2eTests/tests/generalApplication/LipvsLipStrikeOut.js
  wiremock/__files/generalApplication/strikeout/gaApplicationData_1732194111758649.json
  wiremock/mappings/civil-service-mapping.json
  wiremock/mappings/generalApplication/strike-out-mapping.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5225

#5228 CIV-16240 change XLS/XLSM' to 'XLS/XLSX
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5228

#5247 CIV-16223 add Without a hearing option
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationHearingDetails.ts
  src/main/common/models/generalApplication/hearingArrangement.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationRows.test.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5247

#5246 CIV-15855 CIV-16222 remove evidence section from ga summary
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5246

#5236 DTSCCI-1334 - Add hint text paid amount
  package.json
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claimantResponse/ccj/paid-amount.njk
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5236

#5252 CIV-16232 Fix Welsh doc types
  src/main/common/models/generalApplication/gaDocumentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5252

#5283 CIV-16245 added reason on application Response and fix unit test
  src/main/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5283

#5268 CIV-15922 added word wrap.
  src/main/views/macro/generalApplication/application-summary.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5268

#5275 CIV-16270 Upload documents text wrong on response journey CYA
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/response/checkAnswersResponseService.ts
  src/test/unit/services/features/generalApplication/response/checkAnswersResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5275

#5273 CIV-16038 added caption
  src/main/views/features/generalApplication/response/accept-defendant-offer.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5273

#5290 CIV-16293 - GA Lip - After Main case goes offline, defendant can use ViewApplications link
  src/main/services/features/generalApplication/generalApplicationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-5290

#5199 CIV-15576 EA courts whitelisted for general apps for Lips
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/claim.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5199

#5300 DTSCCI-1369 defence summary char limit changed 400 to 800
  src/main/common/form/models/defence.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5300
