Repository hmcts/civil-citizen-ui, pull requests merged in 2024-02, with the labels that each got.

#3034 CIV-6268 CCJ - Confirmation page content update
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claimantResponse/ccj/ccj-confirmation.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3034

#2822 CIV-11745 welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
  src/main/views/features/claimantResponse/court-proposed-date.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2822

#2976 CIV-12208 Conformation page CC accepted
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/signSettlementAgreementContentBuilder.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2976

#2886 CIV-12100 - CUI R2 - Claimant dob screen has incorrect date
  src/main/views/features/response/citizenDob/citizen-dob.njk
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2886

#3046 CIV-11085 CCJ Flows
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/claim.ts
  src/main/common/utils/interestUtils.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
  src/main/services/features/claimantResponse/submission/submitClaimantResponse.ts
  src/main/services/translation/claimantResponse/ccdRequestJudgementTranslation.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
  src/test/unit/services/translation/claimantResponse/ccdRequestJudgementTranslation.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3046

#2854 CIV-11812 Fix part admit admitted claim amount
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
  src/main/routes/features/claimantResponse/ccj/paidAmountController.ts
  src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
  src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.ts
  src/test/unit/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2854

#2918 CIV-12079 confirmation pages are not right when case moves to in mediation
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claimantResponse.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/disputeConfirmationContentBuilder.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2918

#3042 CIV-12336 Welsh language preference
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3042

#3037 CIV-11502 Fill DQ support dropdown menu
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/views/features/directionsQuestionnaire/support-required-list.njk
  src/main/views/features/directionsQuestionnaire/witnesses/otherWitnesses/other-witnesses.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3037

#3054 CIV-5663 Refactor Claim Properties Checks Into Functions
  src/main/common/models/claim.ts
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
  src/main/services/features/common/buildSmallClaimHearingRequirements.ts
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildSmallHearingRequirments.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3054

#3051 CIV-12501 WELSH translation 7
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3051

#3028 CIV-12433 Full Defence Not Settle Journey
  src/main/common/models/ccdResponse/ccdApplicant1LiPResponse.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/main/services/translation/convertToCUI/convertToCUIClaimantMediation.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/convertToCCDYesNo.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/models/claimantResponse.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIClaimantMediation.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDYesNo.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3028

#3084 CIV-11411 Logout button problem
  src/main/modules/nunjucks/index.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/features/public/claim/defendant-phone.njk
  src/main/views/features/public/cookies/cookies-view.njk
  src/main/views/features/public/eligibility/apply-for-help-with-fees.njk
  src/main/views/features/public/eligibility/claim-against-government.njk
  src/main/views/features/public/eligibility/claim-type.njk
  src/main/views/features/public/eligibility/claimant-address-eligibility.njk
  src/main/views/features/public/eligibility/defendant-age.njk
  src/main/views/features/public/eligibility/defendant-eligible-address.njk
  src/main/views/features/public/eligibility/eligible.njk
  src/main/views/features/public/eligibility/help-with-fees-reference.njk
  src/main/views/features/public/eligibility/help-with-fees.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-for-tenancy-deposit.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-on-behalf.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-value-not-known.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claim-value-over-25000.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claimant-address.njk
  src/main/views/features/public/eligibility/not-eligible-includes/claimant-under-18.njk
  src/main/views/features/public/eligibility/not-eligible-includes/defendant-address.njk
  src/main/views/features/public/eligibility/not-eligible-includes/government-department.njk
  src/main/views/features/public/eligibility/not-eligible-includes/multiple-claimants.njk
  src/main/views/features/public/eligibility/not-eligible-includes/multiple-defendants.njk
  src/main/views/features/public/eligibility/not-eligible-includes/under-18-defendant.njk
  src/main/views/features/public/eligibility/not-eligible.njk
  src/main/views/features/public/eligibility/over-18.njk
  src/main/views/features/public/eligibility/single-defendant.njk
  src/main/views/features/public/eligibility/some-useful-info-fees.njk
  src/main/views/features/public/eligibility/tenancy-deposit.njk
  src/main/views/features/public/eligibility/total-amount.njk
  src/main/views/features/public/eligibility/try-new-service.njk
  src/main/views/features/public/eligibility/you-can-use-service.njk
  src/main/views/features/public/firstContact/access-denied.njk
  src/main/views/features/public/firstContact/claim-reference.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/public/firstContact/pin.njk
  src/main/views/features/public/firstContact/signposting.njk
  src/main/views/macro/header.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3084

#3068 CIV-12555 Why did you reject the repayment plan screen missing
  src/main/routes/features/claimantResponse/rejectionReasonController.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3068

#3026 CIV-12435 Claimant settle confirmation page
  src/main/common/models/claim.ts
  src/main/common/models/events/eventDto.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/claimSettleConfirmationBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3026

#3062 CIV-12539 Do not set default CCD PaymentOptionType to IMMEDIATELY
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/test/unit/services/translation/claimantResponse/ccdRequestJudgementTranslation.test.ts
  src/test/unit/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3062

#3080 CIV-5663 Refactor part 2
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/routes/features/mediation/mediationDisagreementController.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildCcjTheirDetailsSection.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildClaimAmountSection.ts
  src/main/services/features/claimantResponse/checkAnswers/buildFreeTelephoneMediationSection.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationService.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/common/models/claimantResponse.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/builsCourtDecisionDetailsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3080

#3101 CIV-12541 Cancel Payment
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
  src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3101

#3119 CIV-0000 redirection to ocmc eligibility
  src/main/app.ts
  src/main/modules/oidc/index.ts
  src/main/views/claim-details-tpl.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3119

#3120 CIV-12200 FT changes
  package.json
  src/test/config.js
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/tests/carm/carm_company_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/carm/carm_individual_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_comp_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, enableHelm, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3120

#3024 CIV-6114 Refactor partyDetails
  sonar-project.properties
  src/main/common/form/models/partyDetails.ts
  src/main/common/models/claim.ts
  src/main/modules/draft-store/redisData.json
  src/main/services/features/claim/yourDetails/claimantDetailsService.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/main/services/translation/convertToCUI/convertToCUIParty.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
  src/main/views/features/claim/yourDetails/claimant-individual-details.njk
  src/main/views/features/response/citizenDetails/citizen-details.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/utils/taskList/tasks/taskListHelpers.test.ts
  src/test/unit/routes/features/claim/defendant/defendantDetailsController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantIndividualDetailsController.test.ts
  src/test/unit/routes/features/claim/yourDetails/claimantOrganisationDetailsController.test.ts
  src/test/unit/routes/features/mediation/uploadDocuments/startMediationUploadDocumentsController.test.ts
  src/test/unit/routes/features/mediation/uploadDocuments/typeOfDocumentsController.test.ts
  src/test/unit/routes/features/mediation/uploadDocuments/uploadDocumentsController.test.ts
  src/test/unit/routes/features/response/citizenDetails/citizenDetailsController.test.ts
  src/test/unit/routes/features/response/financial-details/claimIndividualMock.json
  src/test/unit/routes/features/response/financial-details/claimIndividualMockNoType.json
  src/test/unit/routes/features/response/financial-details/claimOrganisationMock.json
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claim/claimantAndDefendantPhoneService.test.ts
  src/test/unit/services/features/claim/defendantEmailService.test.ts
  src/test/unit/services/features/claim/taskListService.test.ts
  src/test/unit/services/features/claim/yourDetails/claimantDetailsService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/response/rejectAllOfClaimService.test.ts
  src/test/unit/services/features/response/taskListService.test.ts
  src/test/unit/services/features/response/yourDefenceService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIParty.test.ts
  src/test/unit/services/translation/response/ccdAdditionalPartyDetatils.test.ts
  src/test/unit/services/translation/response/convertToCCDParty.test.ts
  src/test/utils/mockClaim.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mocks/civilClaimResponseApplicantIndividualMock.json
  src/test/utils/mocks/civilClaimResponseRespondentIndividualWithCcdPhoneNumberFalseMock.json
  src/test/utils/mocks/civilClaimResponseRespondentIndividualWithPhoneNumberMock.json
  src/test/utils/mocks/civilClaimResponseRespondentIndividualWithoutPhoneNumberMock.json
  src/test/utils/mocks/civilClaimResponseTimelineAndEvidenceMock.json
  src/test/utils/mocks/civilClaimResponseUnemploymentRetiredMock.json
  src/test/utils/mocks/mockDefendantResponseSmallClaimRejectClaimMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3024

#3126 CIV-0000 code for make -claim
  src/main/app.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/public/eligibility/tryNewServiceController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/claim-details-tpl.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/public/eligibility/tryNewServiceController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3126

#2995 CIV-12360 welsh 4
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2995

#3127 CIV-12700 Fix claimant intention
  src/main/common/models/claimantResponse.ts
  src/main/services/features/claimantResponse/checkAnswers/buildFreeTelephoneMediationSection.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/test/unit/common/models/claim.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3127

#3086 CIV-11212 Title added
  src/main/views/features/response/your-defence.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3086

#3125 CIV-12154 welsh part 3
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/claimantResponse/courtProposedPlanController.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/partAdmitConfirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/signSettlementAgreementContentBuilder.ts
  src/main/services/features/settlementAgreement/settlementAgreementConfirmationBuilder/confirmationContentBuilder.ts
  src/main/views/features/claimantResponse/part-payment-received.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3125

#3133 CIV-12200 Flaky test
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3133

#3139 CIV-0000 Maximise use of parallel threads
  package.json
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/run-functional-tests.sh
  src/test/functionalTests/tests/carm/carm_company_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/carm/carm_individual_defendant_response_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3139

#3110 CIV-10058 No remission Hwf
  src/main/common/form/models/claimDetails.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeService.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDHelpWithFees.ts
  src/test/unit/services/features/caseProgression/hearingFee/hearingFeeService.test.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3110

#2966 CIV-11989 Fix Task List - Full Defence Full Dispute
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2966

#3137 CIV-12200 - FT timing and flaky check
  src/test/config.js
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/steps/trialArrangementSteps.js
  src/test/functionalTests/features/common/contactUs.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/smokeTest.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3137

#3153 CIV-12200 Run unit tests in multiple threads
  package.json
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/features/home/steps/login.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3153

#3069 CIV-6587 Update claimant intention submission date
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/disputeConfirmationContentBuilder.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3069

#3109 CIV-12629 welsh part 8
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3109

#3170 CIV-0000 Fix staging build
  src/main/routes/features/claimAssignment/assignClaimController.ts
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/assignCasePinInPost.js
  src/test/functionalTests/specClaimHelpers/api/caseRoleAssignmentHelper.js
  src/test/functionalTests/specClaimHelpers/api/idamHelper.js
  src/test/functionalTests/tests/carm/carm_company_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/carm/carm_individual_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_comp_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3170

#3187 CIV-12562 Part remission HwF - granted - Claimant notifications
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3187

#2937 CIV-12143 QuickLipClaimCreationTesting
  src/main/modules/csrf/index.ts
  src/main/modules/draft-store/draftClaimCache.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/claim/createDraftClaim.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/claim-details-tpl.njk
  src/main/views/features/claim/create-draft.njk
  src/test/a11y/ignored-urls.ts
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
  src/test/functionalTests/tests/createLiPvLiPClaim_tests.js
  src/test/unit/routes/features/claim/createClaimDraft.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2937

#3195 CIV-0000 Update cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/features/caseProgression/steps/trialArrangementSteps.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3195

#3132 CIV-12630 Welsh part 9
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3132

#3004 CIV-12361 WELSH translation 5
  src/main/common/utils/interestUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/settlementAgreement/respondSettlementAgreementService.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3004

#3055 CIV-12512 Judgment amount page AlreadyPaid amount fix
  src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3055

#3083 CIV-6019 Refactor date models to use a generic date model
  src/main/common/form/models/admission/fullAdmission/baseDate.ts
  src/main/common/form/models/admission/fullAdmission/paymentOption/paymentDate.ts
  src/main/common/form/models/admission/howMuchHaveYouPaid.ts
  src/main/common/form/models/admission/partialAdmission/defendantPaymentDate.ts
  src/main/common/form/models/agreedResponseDeadline.ts
  src/main/common/models/breathingSpace/debtRespiteEndDate.ts
  src/main/common/models/claimantResponse/ccj/instalmentFirstPaymentDate.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
  src/test/unit/services/features/response/admission/partialAdmission/howMuchHaveYouPaidService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3083

#3036 CIV-12465 - Claimant Intention Confirmation Page not showing correct msg for CCJ journey.
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3036

#3091 CIV-5798 Refactor directionQuestionnaireService to use generic function
  src/main/routes/features/directionsQuestionnaire/defendantYourselfEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertEvidenceController.ts
  src/main/routes/features/directionsQuestionnaire/experts/permissionForExpertController.ts
  src/main/routes/features/directionsQuestionnaire/experts/sharedExpertController.ts
  src/main/routes/features/directionsQuestionnaire/hearing/cantAttendHearingInNext12MonthsController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/features/directionsQuestionnaire/triedToSettleController.ts
  src/main/services/features/directionsQuestionnaire/directionQuestionnaireService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3091

#3159 CIV-12632 welsh part 10
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3159

#3015 CIV-12438 hearing response to type
  src/main/app/client/civilServiceClient.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3015

#3010 CIV-5452 Lint errors/warnings
  src/main/app/client/pcq/generatePcqToken.ts
  src/main/app/client/pcq/pcqClient.ts
  src/main/app/client/pcq/pcqParameters.ts
  src/main/common/form/models/caseProgression/documentUploadSubmission.ts
  src/main/common/form/validators/isAllowedMimeType.ts
  src/main/common/form/validators/isFileSize.ts
  src/main/common/models/caseProgression/documentUploadSections.ts
  src/main/common/models/caseProgression/uploadDocumentsSectionBuilder.ts
  src/main/modules/helmet/index.ts
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.ts
  src/main/routes/features/caseProgression/hearingFee/cancelHearingFeeJourneyController.ts
  src/main/routes/features/caseProgression/hearingFee/makePaymentAgainController.ts
  src/main/routes/features/caseProgression/hearingFee/paymentConfirmationController.ts
  src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
  src/main/routes/features/claim/paymentSuccessfulController.ts
  src/main/routes/features/claimantResponse/courtProposedDateController.ts
  src/main/routes/features/helpWithFees/helpWithFeesController.ts
  src/main/routes/features/mediation/uploadDocuments/checkAnswersController.ts
  src/main/services/features/breathingSpace/submission/submitBreathingSpace.ts
  src/main/services/features/breathingSpace/submission/submitBreathingSpaceLifted.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/disclosureContentBuilder.ts
  src/main/services/features/caseProgression/expertContentBuilder.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeService.ts
  src/main/services/features/caseProgression/trialArrangements/checkAnswersService.ts
  src/main/services/features/caseProgression/trialContentBuilder.ts
  src/main/services/features/caseProgression/trialService.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/services/features/claim/checkAnswers/claimSection/buildClaimSection.ts
  src/main/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/caseProgressionLatestUpdateService.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContent/claimDismissedHearingDueDateUploadContent.ts
  src/main/services/features/mediation/uploadDocuments/documentsForDocumentsReferredContentBuilder.ts
  src/main/services/features/mediation/uploadDocuments/yourStatementContentBuilder.ts
  src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
  src/test/unit/common/models/caseProgression/uploadDocumentsSectionBuilder.test.ts
  src/test/unit/common/models/claimantResponse/ccdTranslation.test.ts
  src/test/unit/common/utils/pageSectionBuilder.test.ts
  src/test/unit/modules/ordance-survey-key/ordanceSurveyKey.test.ts
  src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
  src/test/unit/routes/features/caseProgression/documentsUploadedController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/submission/submitClaim.test.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementController.test.ts
  src/test/unit/routes/guards/claimantIntentGuard.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.test.ts
  src/test/unit/services/features/claimantResponse/getDecisionOnClaimantProposedPlan.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/mediation/uploadDocuments/documentsForDocumentsReferredContentBuilder.test.ts
  src/test/unit/services/features/mediation/uploadDocuments/yourStatementContentBuilder.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIRecurringIncome.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3010

#3212 CIV-0000 supress security issues
  yarn-audit-known-issues
Labels: fullDeploy, pr-values:elasticsearch

#3205 CIV-12876 Fix claim not in draft store on fee breakdown
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3205

#3203 CIV-12804 adding express-async-error to handle async errors
  package.json
  src/main/app.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3203

#3131 CIV-11885 hearing fee scenarios
  src/test/config.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/applyHelpFeeSelection.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/applyHelpWithFees.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/applyHelpWithFeesConfirmation.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/applyHelpWithFeesReferenceNumber.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/applyHelpWithFeesStart.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/payHearingFee.js
  src/test/functionalTests/features/caseProgression/pages/hearingFee/paymentSuccessful.js
  src/test/functionalTests/features/caseProgression/steps/hearingFeeSteps.js
  src/test/functionalTests/features/caseProgression/util/DateUtilsComponent.js
  src/test/functionalTests/features/common/govPay.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
  src/test/functionalTests/tests/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/createLiPvLiPClaim_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3131

#3216 CIV-12717 Dashboard status translate
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3216

#3182 CIV-12804 clean up of civilServiceClient
  package.json
  src/main/app.ts
  src/main/app/client/civilServiceClient.ts
  src/main/modules/error/index.ts
  src/main/routes/features/claimAssignment/assignClaimController.ts
  src/main/routes/features/mediation/uploadDocuments/uploadDocumentsController.ts
  src/main/routes/features/public/firstContact/pinController.ts
  src/test/unit/routes/features/claimAssignment/claimAssignmentController.test.ts
  src/test/unit/routes/features/dashboard/dashboardController.test.ts
  src/test/unit/routes/features/response/submitComfirmationController.test.ts
  src/test/unit/routes/guards/responseSubmitDateGuard.test.ts
  src/test/unit/services/features/response/submission/submitReponse.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3182

#3220 CIV-10982 update hearing info scheduler handler 2
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3220

#3221 CIV-12906 Claim issue hwf dashboard status
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3221

#3222 CIV-0000 Test notification emails
  Jenkinsfile_CNP
  README.md
  package.json
  src/test/functionalTests/specClaimHelpers/api/steps.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3222

#3196 CIV-12653 - Draft claim dashboard
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/claim.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/common/models/dashboard/taskList/civilServiceDashboardTask.ts
  src/main/common/models/dashboard/taskList/dashboardTask.ts
  src/main/common/models/dashboard/taskList/dashboardTaskStatus.ts
  src/main/common/models/taskList/TaskStatus.ts
  src/main/modules/utilityService.ts
  src/main/routes/features/claim/bilingualLangPreferenceController.ts
  src/main/routes/features/claim/claimTaskListController.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/dashboard/draftClaimService.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
  src/test/unit/modules/utilityService.test.ts
  src/test/unit/routes/features/claim/bilingualLangPreferenceController.test.ts
  src/test/unit/routes/features/claim/claimTaskListController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/routes/guards/claimIssueTaskListGuard.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3196

#3243 CIV-0000 remove ga spec
  Jenkinsfile_CNP
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/repaymentPlan.js
  src/test/unit/common/utils/ageEligibilityVerification.test.ts
  src/test/unit/routes/features/breathingSpace/debtRespiteEndDateController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/hearing/unavailableDatesForHearingController.test.ts
  src/test/utils/dateUtils.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3243
