Repository hmcts/civil-citizen-ui, pull requests merged in 2024-07, with the labels that each got.

#4103 DTSCCI-005 - fix js tag
  config/default.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4103

#4115 DTSCCI-490 remove deprecated property volume lib
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4115

#4043 CIV-13827 - dashboard status for struck out cases
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4043

#4130 DTSCCI-490 remove deprecated property volume lib
  bin/pull-latest-release-asset.sh
  bin/utils/idam-lease-user-token.sh
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4130

#4107 CIV-14158 - Welsh Translation Review : Claim Issue screens (3)
  src/main/common/form/models/claim/details/helpWithFees.ts
  src/main/common/form/models/interest/interestStartDate.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claim/details/help-with-fees.njk
  src/main/views/features/claim/interest/claim-interest.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4107

#4145 update docker image hmctspublic.azurecr.io/imported/toolbelt/oathtool
  bin/import-bpmn-diagram.sh
  bin/import-dmn-diagram.sh
  bin/import-wa-bpmn-diagram.sh
  bin/utils/ccd-add-role.sh
  bin/utils/ccd-import-definition.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4145

#4011 CIV-9458 View application screen
  src/main/app/client/gaServiceClient.ts
  src/main/app/client/gaServiceUrls.ts
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationAddlDocument.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/utils/stringUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/app/client/gaServiceClient.test.ts
  src/test/unit/routes/features/claim/generalApplication/viewApplicationController.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-view-application.html
  src/test/utils/mocks/applicationMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4011

#4116 CIV-14159 Fix Welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/common/hearingExportsReportBuilderSection.ts
  src/main/views/features/claimantResponse/claimant-intention-to-proceed.njk
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/hearingExportsReportBuiderSection.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4116

#4125 CIV-14492 test PR for 14492
  Jenkinsfile_CNP
  package.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-4125

#4131 CIV-14447 fixed decimal formatting
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4131

#4151 CIV-14133 Bug/civ 14133
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/guards/claimFeePaymentGuard.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4151

#4123 CIV-14446 - CUI R2 - Text colour is different on Claim Details page
  src/main/views/features/response/claimDetails/claim-details-new.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4123

#4165 CIV-14292 PR
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/views/macro/external-link.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4165

#4168 CIV-14344 Debt respite link Case Progression states
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4168

#4100 CIV-14124 - add translated order document
  src/main/common/models/claim.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4100

#4150 CIV-14342 - Bug Fix
  src/main/common/models/claim.ts
  src/main/routes/features/settlementAgreement/respondSettlementAgreementConfirmationController.ts
  src/main/routes/features/settlementAgreement/respondSettlementAgreementController.ts
  src/main/services/features/settlementAgreement/settlementAgreementConfirmationBuilder/confirmationContentBuilder.ts
  src/test/unit/routes/features/settlementAgreement/respondSettlementAgreementConfirmationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4150

#4170 CIV-14556 Not showing the error messages at the top of the screen CIV-14564
  src/main/views/features/claim/check-answers.njk
  src/main/views/features/claimantResponse/ccj/check-answers.njk
  src/main/views/macro/statement-of-truth.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4170

#3986 CIV-13686 application summary
  src/main/app/client/gaServiceClient.ts
  src/main/app/client/gaServiceUrls.ts
  src/main/assets/scss/task-list.scss
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/models/generalApplication/applicationSummary.ts
  src/main/common/utils/dateUtils.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/applications-summary.njk
  src/main/views/macro/generalApplication/application-summary.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationSummaryController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-summary.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3986

#4121 CIV-14163 Added welsh translation for CCJ and JBA scenarios
  src/main/common/models/claimantResponse/ccj/paidAmount.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
  src/main/views/features/claimantResponse/ccj/defendant-dob.njk
  src/main/views/features/claimantResponse/ccj/paid-amount.njk
  src/test/unit/services/features/claim/checkAnswers/financialSection/buildPaymentSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4121

#4128 CIV-14414 GDS Version update need fix in warning component
  src/main/modules/i18n/locales/en.json
  src/main/views/features/dashboard/item-content.njk
  src/main/views/features/directionsQuestionnaire/request-extra-4weeks.njk
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/utils/mocks/a11y/mock-case-1645882162449409-directions-questionnaire-request-extra-4-weeks.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4128

#4174 CIV-14365 - Request for reconsideration comments
  src/main/common/models/caseProgression/requestForReconsideration/requestForReviewCommentsForm.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/requestForReconsideration/checkAnswersCommentsController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/commentsConfirmationController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/requestForReviewCommentsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/caseProgression/requestForReconsideration/requestForReviewCommentsContent.ts
  src/main/services/features/caseProgression/requestForReconsideration/requestForReviewCommentsService.ts
  src/main/services/features/caseProgression/requestForReconsideration/requestForReviewService.ts
  src/main/services/features/response/checkAnswers/caseProgression/requestForReconsideration/buildRequestForReconsiderationConfirmationSection.ts
  src/main/views/features/caseProgression/requestForReconsideration/comments-confirmation.njk
  src/test/unit/routes/features/caseProgression/requestForReconsideration/checkAnswersCommentsController.test.ts
  src/test/unit/routes/features/caseProgression/requestForReconsideration/commentsConfirmationController.test.ts
  src/test/unit/routes/features/caseProgression/requestForReconsideration/requestForReviewCommentsController.test.ts
  src/test/unit/services/features/caseProgression/requestForReconsideration/requestForReviewCommentsService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-comments-for-reconsideration-check-your-answers.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-comments-for-reconsideration-confirmation.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-comments-for-reconsideration.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4174

#4173 CIV-14348 disable link case offline defendant
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4173

#4122 CIV-14162 Claim intention full admit Welsh translations
  src/main/common/form/models/claimantResponse/courtProposedDate.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/acceptRepaymentPlanController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedInstalmentsController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentOptionController.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/claimantSuggestedInstalmentsService.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/views/features/claimantResponse/ccj/paid-amount.njk
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/claimantResponse/claimantSuggestedInstalmentsService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4122

#4176 CIV-14497 bug link
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/public/contactUsController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/public/privacyPolicyController.ts
  src/main/routes/features/public/termsAndConditionsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/claim-details-tpl.njk
  src/main/views/external-urls.njk
  src/main/views/features/public/contact-us.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/public/privacy-policy.njk
  src/main/views/features/public/terms-and-conditions.njk
  src/main/views/service-unavailable-layout.njk
  src/test/unit/routes/features/public/contactUsController.test.ts
  src/test/unit/routes/features/public/privacyPolicyController.test.ts
  src/test/unit/routes/features/public/termsAndConditionsController.test.ts
  src/test/utils/mocks/a11y/mock-contact-us.html
  src/test/utils/mocks/a11y/mock-privacy-policy.html
  src/test/utils/mocks/a11y/mock-terms-and-conditions.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4176

#4164 CIV-13549 - Respondent can view applicant's application
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/models/generalApplication/applicationType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/response/view-application.njk
  src/test/unit/routes/features/claim/generalApplication/applicationSummaryController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/viewApplicationController.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-view-application.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4164

#4192 CIV-14435 - fixed the deault value for PaymentOption.
  src/main/services/translation/response/convertToCCDPaymentOption.ts
  src/test/unit/services/translation/response/convertToCCDPaymentOptions.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4192

#4193 CIV-14063 Fixed explain briefly question on respondent CYA screen
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponsePaymentSection.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4193

#4194 CIV-14164 Updated welsh text for VALID_DAY error message
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4194

#4144 CIV-13798 accessibility focus dashboard link
  src/main/assets/scss/main.scss
  src/main/views/features/dashboard/dashboard.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4144

#4166 CIV-14537 CUI R2 - GA Lip section is visible in the Dashboard even though GA lip toggle is disabled
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4166

#4210 DTSCCI-005 - Add dynatrace domain to connectSrc whitelist
  src/main/modules/helmet/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4210

#4218 DTSCCI-592 - Update dynatrace tag to prod version
  config/default.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4218

#4186 DTSCCI-005 - add tag to other base
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/service-unavailable.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4186

#4208 CIV-14062 action caption on APPLICATION_ADD_PAYMENT status
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4208

#4233 DTSCCI-318 adding id to footer component
  src/main/views/macro/contact-us-for-help.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4233

#4196 CIV-14636 CUI R2 - View and Response link not working intermittently
  src/main/routes/guards/claimantIntentGuard.ts
  src/test/unit/routes/features/claimantResponse/repaymentPlanAcceptedController.test.ts
  src/test/unit/routes/features/claimantResponse/signSettlmentAgreementController.test.ts
  src/test/unit/routes/guards/claimantIntentGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4196

#4213 CIV-13440 Changing Trial Arrangements Date To 4 weeks Before The Hearing
  src/main/common/models/claim.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/test/unit/common/models/claim.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4213

#4219 CIV-14675 Incorrect claim list status
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4219

#4228 CIV-13642 modify redirect link documents uploaded
  src/main/routes/features/caseProgression/documentsUploadedController.ts
  src/main/views/features/caseProgression/documents-uploaded.njk
  src/test/unit/routes/features/caseProgression/documentsUploadedController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4228

#4147 CIV-14451 added code for status after DJ issued
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4147

#4079 CIV-14063 view application court section
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/models/generalApplication/response/gaResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/additionalFee/additionalFeeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFeePaymentSuccessfulController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationSummaryController.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4079

#4229 CIV-14708 accessibility support links
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/dashboard/dashboardService.ts
  src/main/views/macro/external-link.njk
  src/main/views/macro/support-links.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4229

#4259 CIV-14738 pdate wording on the repayment plan screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claimantResponse/ccj/repayment-plan-summary-claimant.njk
  src/test/utils/mocks/a11y/mock-case-1645882162449409-ccj-repayment-plan-summary-CLAIMANT.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-ccj-repayment-plan-summary-DEFENDANT.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4259

#4268 CIV-14761 accessibility texts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/accessibility-statement.njk
  src/test/unit/routes/features/public/accessibilityStatementController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4268

#4273 CIV-14787 welsh texts
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4273

#4167 CIV-14228 GA Upload additional documents
  src/main/common/models/gaEvents/applicationEvent.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/UploadAdditionalDocument.ts
  src/main/common/utils/urlFormatter.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/additionalDocuments/checkAnswersController.ts
  src/main/routes/features/generalApplication/additionalDocuments/submittedController.ts
  src/main/routes/features/generalApplication/additionalDocuments/uploadAdditionalDocumentsController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/additionalDocumentService.ts
  src/main/views/features/generalApplication/additionalDocuments/check-answers.njk
  src/main/views/features/generalApplication/additionalDocuments/submitted.njk
  src/main/views/features/generalApplication/additionalDocuments/upload-additional-documents.njk
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/routes/features/claim/generalApplication/additionalDocuments/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalDocuments/submittedController.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalDocuments/uploadAdditionalDocumentsController.test.ts
  src/test/unit/services/features/generalApplication/additionalDocumentService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-upload-additional-documents-check-and-send.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-upload-additional-documents-submitted.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-upload-additional-documents.html
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4167

#4282 DTSCCI-005 - Put different tag in prod
  config/default.yaml
  config/production.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4282

#4272 CIV-14656 Welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/contact-us.njk
  src/main/views/features/public/terms-and-conditions.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4272

#4234 CIV-14127 Court Response Document - Without notice becomes with notice
  src/main/common/models/ccdGeneralApplication/ccdGAMakeWithNoticeDocument.ts
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationAddlDocument.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/utils/urlFormatter.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4234

#4255 CIV-0000 - Fix claim fee details based on the claim amount we pass
  src/test/functionalTests/specClaimHelpers/fixtures/events/claimAmountAndFee.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaimDefendantCompany.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaimDefendantSoleTrader.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaimForCompany.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaimIndVOrg.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaimSoleTraderVCompany.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4255
