Repository hmcts/civil-citizen-ui, pull requests merged in 2024-06, with the labels that each got.

#3839 CIV-13670 Claimant List for Support Hearing
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3839

#3882 CIV-13608 Error messages for additional application
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/unit/routes/features/claim/generalApplication/applicationTypeController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3882

#3827 CIV-13854 task list flights
  src/main/common/models/claim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3827

#3860 CIV-13703 Stitch DQ and defendant response doc
  src/main/common/mappers/documentViewMapper.ts
  src/test/unit/common/common/mappers/documentViewMapper.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3860

#3854 CIV-9476 Response to application screens
  src/main/app.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/response/gaResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/respondentAgreeToOrderController.ts
  src/main/routes/features/generalApplication/response/hearingArrangementResponseController.ts
  src/main/routes/features/generalApplication/response/hearingContactDetailsResponseController.ts
  src/main/routes/features/generalApplication/response/hearingSupportResponseController.ts
  src/main/routes/features/generalApplication/response/respondentAgreementController.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesResponseController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseConfirmationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingArrangementResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingContactDetailsResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingSupportResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/unavailableHearingDatesResponseController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-agree-to-order.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-hearing-arrangement.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-hearing-contact-details.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-hearing-support.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-unavailable-dates.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3854

#3818 CIV-13636 New govuk front version
  package.json
  src/main/assets/scss/main.scss
  src/main/common/form/models/bankAndSavings/bankAccount.ts
  src/main/common/form/models/bankAndSavings/bankAccountTypeValues.ts
  src/main/common/form/models/bankAndSavings/bankAccountTypes.ts
  src/main/modules/nunjucks/index.ts
  src/test/functionalTests/tests/nonprod/carm_LR_mediation_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_mediation_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_small_claims_tests.js
  webpack/govukFrontend.js
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3818

#3942 CIV-8351 Update claimType method name
  src/main/common/models/claim.ts
  src/test/unit/common/models/claim.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3942

#3872 CIV-14026 Enabling HWF full remission functional tests
  src/test/functionalTests/specClaimHelpers/fixtures/events/admitAllClaimantResponse.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3872

#3939 CIV-13988 Include call charge url for welsh
  src/main/modules/nunjucks/index.ts
  src/main/views/external-urls.njk
  src/main/views/features/response/ageEligibility/under-18.njk
  src/main/views/macro/contact-us-for-help.njk
  src/main/views/macro/contact-us.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3939

#3912 CIV-13684 - updating cp tests
  src/test/functionalTests/citizenFeatures/caseProgression/steps/hearingFeeSteps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3912

#3934 CIV-9478 responds vary judgement application
  src/main/common/models/generalApplication/response/acceptDefendantOffer.ts
  src/main/common/models/generalApplication/response/gaResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/generalApplication/response/acceptDefendantOfferController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/external-urls.njk
  src/main/views/features/generalApplication/response/accept-defendant-offer.njk
  src/test/unit/routes/features/claim/generalApplication/response/acceptDefendantOfferController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-accept-defendant-offer.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3934

#3926 CIV-9457 LiP Application Confirmation Screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/submitGeneralApplicationConfirmationController.ts
  src/main/routes/routes.ts
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/main/views/features/generalApplication/submit-general-application-confirmation.njk
  src/test/unit/routes/features/claim/generalApplication/submitGeneralApplicationConfirmationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3926

#3957 CIV-13768 - Breathing space : Extend the states the 'Get debt respite' link is visible in
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3957

#3953 CIV-13916 def li p assign claim spec mt
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/claimType.ts
  src/main/common/models/claim.ts
  src/main/services/translation/convertToCUI/convertToCUIDQs.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/form/models/claimType.test.ts
  src/test/unit/common/models/claim.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3953

#3948 CIV-13692 - Navigation for make an application journey Gen Apps for LiPs
  src/main/app/client/civilServiceClient.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/features/generalApplication/applicationCostsController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/claimApplicationCostController.ts
  src/main/routes/features/generalApplication/hearingArrangementController.ts
  src/main/routes/features/generalApplication/hearingArrangementsGuidanceController.ts
  src/main/routes/features/generalApplication/hearingContactDetailsController.ts
  src/main/routes/features/generalApplication/hearingSupportController.ts
  src/main/routes/features/generalApplication/informOtherPartiesController.ts
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/features/generalApplication/payingForApplicationController.ts
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/features/generalApplication/unavailableHearingDatesController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/features/generalApplication/uploadN245FormController.ts
  src/main/routes/features/generalApplication/wantToUploadDocuments.ts
  src/main/routes/guards/generalApplication/addAnotherApplicationGuard.ts
  src/main/routes/guards/generalApplication/agreementFromOtherPartyGuard.ts
  src/main/routes/guards/generalApplication/claimApplicationCostGuard.ts
  src/main/routes/guards/generalApplication/informOtherPartiesGuard.ts
  src/main/routes/guards/generalApplication/orderJudgeGuard.ts
  src/main/routes/guards/generalApplication/requestReasonControllerGuard.ts
  src/main/routes/guards/generalApplication/uploadN245FormControllerGuard.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/feeDetailsService.ts
  src/main/services/features/generalApplication/uploadEvidenceDocumentService.ts
  src/main/views/features/generalApplication/application-costs.njk
  src/main/views/features/generalApplication/hearing_arrangements_guidance.njk
  src/main/views/features/generalApplication/paying-for-application.njk
  src/test/unit/routes/features/claim/generalApplication/agreementFromOtherPartyController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingArrangementsGuidanceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/informOtherPartiesController.test.ts
  src/test/unit/routes/features/claim/generalApplication/payingForApplicationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/routes/features/claim/generalApplication/wantToUploadDocumentsController.test.ts
  src/test/unit/routes/guards/generalApplication/addAnotherApplicationGuard.test.ts
  src/test/unit/routes/guards/generalApplication/agreementFromOtherPartyGuard.test.ts
  src/test/unit/routes/guards/generalApplication/claimApplicationCostGuard.test.ts
  src/test/unit/routes/guards/generalApplication/informOtherPartiesGuard.test.ts
  src/test/unit/routes/guards/generalApplication/orderJudgeGuard.test.ts
  src/test/unit/routes/guards/generalApplication/requestingReasonControllerGuard.test.ts
  src/test/unit/routes/guards/generalApplication/uploadN245FormControllerGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3948

#3883 CIV-13966 Add feature flag case-progression to the base.
  src/main/app.ts
  src/main/routes/guards/caseProgressionGuard.ts
  src/main/routes/urls.ts
  src/test/a11y/a11y-README.md
  src/test/a11y/constants.ts
  src/test/a11y/ignored-urls.ts
  src/test/functionalTests/specClaimHelpers/fixtures/events/hwfPayloads.js
  src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
  src/test/unit/routes/features/caseProgression/checkYourAnswersController.test.ts
  src/test/unit/routes/features/caseProgression/documentsUploadedController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/cancelHearingFeeJourneyController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/makePaymentAgainController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/payHearingFeeConfirmationController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/payHearingFeeStartScreenController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/paymentUnsuccessfulController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/checkAnswersController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/isCaseReadyController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.test.ts
  src/test/unit/routes/features/caseProgression/typeOfDocumentsController.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/routes/features/caseProgression/uploadYourDocumentsController.test.ts
  src/test/unit/routes/features/claim/paymentSuccessfulController.test.ts
  src/test/unit/routes/features/helpWithFees/helpWithFeesController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-apply-help-with-fees-reference-number.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-apply-help-with-fees-start.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-apply-help-with-fees.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3883

#3974 CIV-11358 Dashboard Task List
  sonar-project.properties
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/AppRequest.ts
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/app/client/generalApplicationClient.test.ts
  src/test/unit/routes/features/caseProgression/checkYourAnswersController.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3974

#4002 CIV-9465 LiP Pay for Application
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/app/client/gaServiceClient.ts
  src/main/app/client/gaServiceUrls.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/CaseLink.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/services/features/generalApplication/applicationFee/generalApplicationFeePaymentService.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeService.ts
  src/test/unit/app/client/gaServiceClient.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/generalApplicationFeePaymentService.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4002

#4001 CIV-13917 Assign to INT track
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/claimType.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/utils/mintiToggleUtils.ts
  src/main/services/translation/convertToCUI/convertToCUIDQs.ts
  src/main/services/translation/convertToCUI/convertToCUIExperts.ts
  src/main/services/translation/convertToCUI/convertToCUIHearing.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/nonprod/minti_LiPvLiP_intermediate_track_tests.js
  src/test/functionalTests/tests/nonprod/minti_LiPvLiP_multi_track_tests.js
  src/test/unit/common/form/models/claimType.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIDQs.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4001

#4014 CIV-13935 Fixed recoverable costs screen 1
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/models/directionsQuestionnaire/fixedRecoverableCosts/FixedRecoverableCosts.ts
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/frcBandAgreedController.ts
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/subjectToFRCController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/commons/detailContents.ts
  src/main/views/features/directionsQuestionnaire/fixedRecoverableCosts/frc-band-agreed.njk
  src/main/views/features/directionsQuestionnaire/fixedRecoverableCosts/subject-to-frc.njk
  src/test/unit/routes/features/directionsQuestionnaire/fixedRecoverableCosts/frcBandAgreedController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/fixedRecoverableCosts/subjectToFRCController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-directions-questionnaire-frc-band-agreed.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-directions-questionnaire-subject-to-frc.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4014

#4022 CIV-0000 all stitch screens
  src/main/app.ts
  src/main/common/models/AppRequest.ts
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/routes/common/backController.ts
  src/main/routes/features/directionsQuestionnaire/mintiMultitrack/agreementReachedController.ts
  src/main/routes/features/directionsQuestionnaire/mintiMultitrack/claimantDocumentsConsideredDetailsController.ts
  src/main/routes/features/directionsQuestionnaire/mintiMultitrack/claimantDocumentsTobeConsideredController.ts
  src/main/routes/features/directionsQuestionnaire/mintiMultitrack/disclosureNonElectronicDocumentsController.ts
  src/main/routes/features/directionsQuestionnaire/mintiMultitrack/disclosureOfDocumentsController.ts
  src/main/routes/features/directionsQuestionnaire/mintiMultitrack/disclosureOfElectronicDocumentsIssuesController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/guards/trackHistory.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/common/backController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/mintiMultitrack/agreementReachedController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/mintiMultitrack/claimantDocumentsTobeConsideredController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/mintiMultitrack/disclosureOfDocumentsController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/mintiMultitrack/disclosureOfElectronicDocumentsIssuesController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/requestExtra4WeeksController.test.ts
  src/test/unit/routes/guards/trackHistory.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-directions-questionnaire-agreement-reached.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-directions-questionnaire-claimant-documents-to-be-considered.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4022

#4013 CIV-14105 FlightDelayTest
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsCompany.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4013

#4031 CIV-0000 - Update css.njk
  src/main/views/webpack/css.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4031

#4038 CIV-0000 Minti fix task status
  src/main/common/models/directionsQuestionnaire/directionQuestionnaire.ts
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/common/utils/taskList/tasks/giveUsDetailsHearing.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/guards/allResponseTasksCompletedGuard.ts
  src/main/services/features/common/taskListService.ts
  src/test/unit/common/utils/taskList/taskListBuilder.test.ts
  src/test/unit/common/utils/taskList/tasks/giveUsDetailsHearing.test.ts
  src/test/unit/routes/features/response/taskListController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4038

#4030 CIV-14094 Amending notification text for FTs
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4030

#3990 CIV-9441 GA task list
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/common/models/claim.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3990

#4015 CIV-14122 welsh accessibility statement
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/accessibility-statement.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4015

#4007 CIV-14114 Claimant must complete expert screen
  src/main/common/models/directionsQuestionnaire/experts/expertReportDetails/expertReportDetails.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertReportDetailsController.ts
  src/main/services/features/common/hearingExportsReportBuilderSection.ts
  src/main/services/features/directionsQuestionnaire/expertReportDetailsService.ts
  src/main/services/translation/convertToCUI/convertToCUIExperts.ts
  src/main/services/translation/response/convertToCCDExpert.ts
  src/main/views/features/directionsQuestionnaire/experts/expert-report-details-claimant.njk
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/expertReportDetails.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertReportDetailsController.test.ts
  src/test/unit/services/features/directionsQuestionnaire/expertReportDetailsService.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementSection/hearingExportsReportBuiderSection.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUIExperts.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4007

#4042 CIV-0000 Fix tests
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantClaimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/functionalTests/citizenFeatures/caseProgression/steps/hearingFeeSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/unit/routes/features/caseProgression/cancelYourUploadController.test.ts
  src/test/unit/routes/features/claim/generalApplication/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/generalApplication/claimApplicationCostController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingArrangementController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingArrangementsGuidanceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingContactDetailsController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseConfirmationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/checkAnswersResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingArrangementResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingContactDetailsResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/routes/features/claim/generalApplication/wantToUploadDocumentsController.test.ts
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantClaimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4042

#4035 CIV-14092 Claim update for claimant after Noc
  src/main/common/models/dashboard/dashboardItem.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4035

#4060 CIV-0000 - fix secure issue ajv
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4060

#4067 CIV-14308 delete duplications
  src/main/app/client/gaServiceClient.ts
  src/main/app/client/gaServiceUrls.ts
  src/main/app/client/generalApplicationClient.ts
  src/main/app/client/generalApplicationUrls.ts
  src/test/unit/app/client/gaServiceClient.test.ts
  src/test/unit/app/client/generalApplicationClient.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4067

#3998 CIV-14099 accept offer response data displayed in check your answers
  src/main/common/models/summaryList/summaryList.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/response/checkAnswersResponseController.ts
  src/main/services/features/generalApplication/response/checkAnswersResponseService.ts
  src/main/views/features/generalApplication/check-answers.njk
  src/main/views/features/generalApplication/response/check-answers.njk
  src/test/unit/services/features/generalApplication/response/checkAnswersResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3998

#3952 CIV-14087 LiP Respondent Hearing Preferences - Multiple applications
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/response/hearingArrangementResponseController.ts
  src/main/routes/features/generalApplication/response/hearingContactDetailsResponseController.ts
  src/main/routes/features/generalApplication/response/hearingSupportResponseController.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesResponseController.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3952

#4048 CIV-14155 Claim Issue screen - Defendant details screen
  src/main/views/features/claim/defendant/defendant-details-company-or-organisation.njk
  src/main/views/features/claim/defendant/defendant-details-individual-or-sole-trader.njk
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4048

#4017 DTSCCI-005 - Add dynatrace JS script to base page
  config/default.yaml
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/views/claim-details-tpl.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4017

#3927 CIV-13767 GA for LiPs - Fee & Pay integration - POST payment status API and navigation
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/routes/features/generalApplication/applicationFeePaymentSuccessfulController.ts
  src/main/routes/features/generalApplication/applicationPaymentUnsuccessfulController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/payment/applicationFeePaymentConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/applicationFee/generalApplicationFeePaymentService.ts
  src/main/services/features/generalApplication/applicationFeePaymentConfirmationContent.ts
  src/main/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFeePaymentSuccessfulController.test.ts
  src/test/unit/routes/features/claim/generalApplication/payment/applicationFeePaymentConfirmationController.test.ts
  src/test/unit/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3927

#4064 CIV-13383 INT track screens stitch for defendant
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app.ts
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/utils/mintiToggleUtils.ts
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/chooseComplexityBandController.ts
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/frcBandAgreedController.ts
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/reasonForChoosingComplexityBandController.ts
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/subjectToFRCController.ts
  src/main/routes/features/directionsQuestionnaire/fixedRecoverableCosts/whyNotSubjectToFRCController.ts
  src/main/routes/features/directionsQuestionnaire/requestExtra4WeeksController.ts
  src/main/routes/features/response/taskListController.ts
  src/main/routes/guards/allResponseTasksCompletedGuard.ts
  src/test/unit/common/utils/mintiToggleUtils.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/fixedRecoverableCosts/frcBandAgreedController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/fixedRecoverableCosts/reasonForChoosingComplexityBandController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/fixedRecoverableCosts/subjectToFRCController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/fixedRecoverableCosts/whyNotSubjectToFRCController.test.ts
  src/test/unit/routes/features/directionsQuestionnaire/requestExtra4WeeksController.test.ts
  src/test/unit/routes/features/response/taskListController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4064

#4037 CIV-13756 Check your answer GA Guard
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/guards/checkYourAnswersGAGuard.ts
  src/test/unit/routes/features/claim/generalApplication/checkAnswersController.test.ts
  src/test/unit/routes/guards/checkYourAnswersGAGuard.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4037

#4026 CIV-13715 Add request for reconsideration document
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/caseProgression/requestForReconsideration/requestForReviewForm.ts
  src/main/common/models/ccdResponse/ccdRequestForReconsideration.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/events/caseEvent.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/requestForReconsideration/cancelRequestForReconsiderationController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/checkAnswersController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/confirmationController.ts
  src/main/routes/features/caseProgression/requestForReconsideration/requestForReviewController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/caseProgression/requestForReconsideration/requestForReviewContent.ts
  src/main/services/features/caseProgression/requestForReconsideration/requestForReviewService.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/features/response/checkAnswers/caseProgression/requestForReconsideration/buildRequestForReconsiderationConfirmationSection.ts
  src/main/services/translation/caseProgression/requestForReconsideration/convertToCCDRequestForReconsideration.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/main/views/features/caseProgression/requestForReconsideration/check-answers.njk
  src/main/views/features/caseProgression/requestForReconsideration/confirmation.njk
  src/main/views/features/caseProgression/requestForReconsideration/request-for-review.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/caseProgression/requestForReconsideration/cancelRequestForReconsiderationController.test.ts
  src/test/unit/routes/features/caseProgression/requestForReconsideration/checkAnswersController.test.ts
  src/test/unit/routes/features/caseProgression/requestForReconsideration/confirmationController.test.ts
  src/test/unit/routes/features/caseProgression/requestForReconsideration/requestForReviewController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/utils/mockClaimForCheckAnswers.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-request-for-reconsideration-check-your-answers.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-request-for-reconsideration-confirmation.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-case-progression-request-for-reconsideration.html
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4026

#4039 CIV-13717 - dashboard interpolation for reconsideration decision
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/routes/features/dashboard/ordersAndNoticesController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4039

#4097 CIV-14121 Amending notifications on FTs according to notifications changed in batch 5
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4097

#4085 CIV-13784 Claimant lip minti cya + CCD translation
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/routes/features/claimantResponse/claimantResponseTasklistController.ts
  src/main/routes/features/claimantResponse/incompleteClaimantResponseSubmissionController.ts
  src/main/routes/guards/claimantResponseCheckYourAnswersGuard.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/claimantHearingRequirementsSectionTasks.ts
  src/main/services/features/common/buildFastTrackHearingRequirements.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDDisclosureOfDocuments.ts
  src/main/services/translation/response/convertToCCDDocumentsToBeConsidered.ts
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/tests/nonprod/minti_LiPvLiP_intermediate_track_tests.js
  src/test/functionalTests/tests/nonprod/minti_LiPvLiP_multi_track_tests.js
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService.test.ts
  src/test/unit/services/translation/response/convertToCCDDisclosureOfDocuments.test.ts
  src/test/unit/services/translation/response/convertToCCDDocumentsToBeConsidered.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4085
