Repository hmcts/civil-citizen-ui, pull requests merged in 2024-05, with the labels that each got.

#3613 CIV-13466 - Claimant intention 'Check your answers' page showing 'Yes' in the intention to proceed field when the user selected 'No'
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3613

#3616 CIV-13224 - CUI R2 - Claimant Intent CYA page, without agreeing hearing requirements and submit gives an incorrect error
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3616

#3642 CIV-13350 Welsh translations
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3642

#3674 CIV-13635 incorrect error message
  src/main/common/form/models/claim/claimant/citizenDate.ts
  src/main/common/form/models/claim/claimant/dobDate.ts
  src/main/common/utils/dateUtils.ts
  src/main/routes/features/claim/yourDetails/claimantDoBController.ts
  src/test/unit/routes/features/claim/claimantDoBController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3674

#3654 CIV-13340 Welsh Translation
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3654

#3650 CIV-13557 - CUI R2 - Welsh Translations needed for request More Time screens
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3650

#3663 CIV-13616 added translation changes
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3663

#3577 CIV-12459 Claimant_Accept_PartAdmit_Instalments
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/createClaim/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitFastTrackDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitSmallClaimsDefendantResponse.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3577

#3640 CIV-12976 Welsh Translation
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/response/checkAnswers/financialSection/answers/addEmploymentDetails.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/test/unit/services/features/response/checkAnswers/financialDetails/addEmploymentDetails.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3640

#3598 DTSCCI-195 - send log messages to appinsights
  src/main/modules/appinsights/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3598

#3689 CIV-13454 Add Welsh translations to CYA court decision
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3689

#3669 CIV-13631 Welsh translation-Payment unsuccessful screen
  src/main/routes/features/claim/payment/claimFeeMakePaymentAgainController.ts
  src/main/routes/features/claim/payment/claimFeePaymentUnsuccessfulController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/payment/claimFeeMakePaymentAgainService.ts
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/payment/claimFeeMakePaymentAgainController.test.ts
  src/test/unit/routes/features/claim/payment/claimFeePaymentUnsuccessfulController.test.ts
  src/test/unit/services/features/claim/payment/claimFeeMakePaymentAgainService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3669

#3695 CIV-9446 LiP Has the other party agreed to the application
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/applicationType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/agreement-from-other-party.njk
  src/main/views/features/generalApplication/application-type.njk
  src/main/views/macro/heading-with-caption.njk
  src/test/unit/routes/features/claim/generalApplication/agreementFromOtherPartyController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-agreement-from-other-party.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3695

#3705 CIV-13575 Fixing View Orders And Notices Redirect Issue
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3705

#3700 CIV-13455 Hearing support page
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/hearingSupport.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/hearingSupportController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/external-urls.njk
  src/main/views/features/generalApplication/application-type.njk
  src/main/views/features/generalApplication/hearing-support.njk
  src/test/unit/routes/features/claim/generalApplication/hearingSupportController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-hearing-support.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3700

#3671 CIV-13572 Set payment date for court decision pay immediately
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3671

#3698 CIV-13398 Gen Apps - Application Costs screen
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/claimApplicationCostController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/claim-application-cost.njk
  src/test/unit/routes/features/claim/generalApplication/claimApplicationCostController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-claim-application-cost.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3698

#3713 CIV-0000 Bulking branch to master
  src/main/assets/js/language-toggle.js
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3713

#3612 CIV-0000 Add environment in LD user
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3612

#3715 CIV-13741 Dashboard notifications automated tests
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3715

#3710 CIV-13456 paying for application
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/payingForApplicationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/generalApplication/paying-for-application.njk
  src/test/unit/routes/features/claim/generalApplication/payingForApplicationController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-paying-for-application.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3710

#3724 CIV-9446 Fixed typo in word siders to sides
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3724

#3668 CIV-13514 Fix a11y link descriptions
  src/main/common/models/summaryList/summaryList.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.ts
  src/main/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.ts
  src/main/services/features/claimantResponse/checkAnswers/buildFreeTelephoneMediationSection.ts
  src/main/services/features/common/addSupportRequiredList.ts
  src/main/services/features/common/hearingExportsReportBuilderSection.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildTheirDetailsSection.test.ts
  src/test/unit/services/features/claim/checkAnswers/detailsSection/buildYourDetailsSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3668

#3717 CIV-13551 Respondent agree to order
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/respondentAgreeToOrderController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/agree-to-order.njk
  src/test/unit/routes/features/claim/generalApplication/respondentAgreeToOrderController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-agree-to-order.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3717

#3746 CIV-0000 Update GA pods in cui chart
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  bin/add-roles.sh
  bin/import-ga-ccd-definition.sh
  bin/variables/load-preview-environment-variables.sh
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3746

#3755 CIV-0000 CARM tests are skipped due to CIV-13832 and adding ga roles
  bin/add-roles.sh
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3755

#3745 CIV-13706 eligibility broken links fixed
  src/main/common/utils/externalURLs.ts
  src/main/views/external-urls.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3745

#3738 CIV-13407 Requesting reason - GA
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/requestingReason.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/requestingReasonPageBuilder.ts
  src/main/views/features/generalApplication/requesting-reason.njk
  src/test/unit/routes/features/claim/generalApplication/requestingReasonController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/requestingReasonPageBuilder.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-requesting-reason.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3738

#3714 CIV-13739 Add feature flag to General Application Page
  src/main/app.ts
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/routes/guards/generalAplicationGuard.ts
  src/test/unit/routes/features/claim/generalApplication/agreementFromOtherPartyController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationTypeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/claimApplicationCostController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingSupportController.test.ts
  src/test/unit/routes/features/claim/generalApplication/informOtherPartiesController.test.ts
  src/test/unit/routes/features/claim/generalApplication/payingForApplicationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/respondentAgreeToOrderController.test.ts
  src/test/unit/routes/guards/generalAplicationGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3714

#3735 DTSCCI-060 Reduce numbers of CVEs
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3735

#3743 CIV-13669 Evidence Upload changes
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/checkAnswersController.ts
  src/main/routes/features/caseProgression/typeOfDocumentsController.ts
  src/main/routes/features/caseProgression/uploadDocumentsController.ts
  src/main/routes/features/caseProgression/uploadYourDocumentsController.ts
  src/main/services/features/caseProgression/cancelDocumentUpload.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/evidenceUploadDocumentsContent.ts
  src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
  src/main/views/features/caseProgression/cancel-your-upload.njk
  src/main/views/features/caseProgression/check-answers.njk
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/caseProgression/upload-your-documents.njk
  src/test/unit/routes/features/caseProgression/typeOfDocumentsController.test.ts
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/routes/features/caseProgression/uploadYourDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3743

#3730 CIV-9451 order judge
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/orderJudge.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/guards/orderJudgeGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/orderJudgePageBuilder.ts
  src/main/views/features/generalApplication/order-judge.njk
  src/test/unit/routes/features/claim/generalApplication/orderJudgeController.test.ts
  src/test/unit/routes/guards/orderJudgeGuard.test.ts
  src/test/unit/services/features/generalApplication/orderJudgePageBuilder.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-order-judge.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3730

#3771 CIV-13475 Config Charts for GA service
  Jenkinsfile_nightly
  bin/import-ga-ccd-definition.sh
  charts/civil-citizen-ui/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/test/config.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3771

#3757 CIV-13650 - reformatting Dashboard page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/features/dashboard/claim-summary-redesign.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3757

#3725 CIV-13741 Dashboard notification test
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/createClaim/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_Api_FullAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3725

#3782 CIV-0000 Update values.yaml
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3782

#3789 CIV-13832 Fix carm api
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_company_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3789

#3768 CIV-13577 Welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/caseProgression/cancelDocumentUpload.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/evidenceUploadDocumentsContent.ts
  src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
  src/main/services/features/dashboard/evidenceUploadDocumentsService.ts
  src/main/views/webpack/css.njk
  src/test/unit/services/features/caseProgression/checkYourAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/dashboard/evidenceUploadDocumentsService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3768

#3791 CIV-000 remove-cookies-banner
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  src/test/config.js
  src/test/functionalTests/commonFeatures/home/pages/login.js
  src/test/functionalTests/commonFeatures/home/steps/login.js
  src/test/functionalTests/specClaimHelpers/fixtures/cookies/cmcCookies.js
  src/test/functionalTests/specClaimHelpers/fixtures/cookies/cuiCookies.js
  src/test/functionalTests/specClaimHelpers/fixtures/cookies/exuiCookies.js
  src/test/functionalTests/specClaimHelpers/fixtures/cookies/idamCookies.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3791

#3784 CIV-13649 Fix bug draft claims
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3784

#3741 CIV-13311 Create View orders and notices page
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/models/document/document.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/ordersAndNoticesController.ts
  src/main/routes/features/dashboard/viewResponseToClaimController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationContent.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/views/features/dashboard/orders-and-notices.njk
  src/main/views/features/dashboard/view-response-to-claim.njk
  src/main/views/features/response/claimDetails/claim-details-new.njk
  src/main/views/macro/create-table-documents.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/dashboard/ordersAndNoticesController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/trialArrangementsConfirmationService.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-view-orders-and-notices.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3741

#3774 CIV-13657 change design for trial
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/checkAnswersController.ts
  src/main/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/routes/features/caseProgression/trialArrangements/isCaseReadyController.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/main/services/features/caseProgression/trialArrangements/hasAnythingChanged.ts
  src/main/services/features/caseProgression/trialArrangements/hearingDurationAndOtherInformation.ts
  src/main/services/features/caseProgression/trialArrangements/isCaseReady.ts
  src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
  src/main/views/features/caseProgression/trialArrangements/check-answers.njk
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements-confirmation.njk
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements.njk
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/caseProgression/trialArrangements/hearing-duration-other-info.njk
  src/main/views/features/caseProgression/trialArrangements/is-case-ready.njk
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/test/unit/routes/features/caseProgression/trialArrangements/checkAnswersController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/hasAnythingChanged.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/hearingDurationAndOtherInformation.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/isCaseReady.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3774

#3750 CIV-13417 Implement Welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/macro/amount-breakdown.njk
  src/main/views/macro/interest-snippet.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3750

#3777 CIV-9442 Implement application costs page
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationCostsController.ts
  src/main/routes/features/generalApplication/hearingSupportController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/applicationCostsService.ts
  src/main/views/features/generalApplication/application-costs.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationCostsController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingSupportController.test.ts
  src/test/unit/services/features/generalApplication/applicationCostsService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-application-costs.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3777

#3723 CIV-13685 change the design
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.ts
  src/main/routes/features/caseProgression/hearingFee/payHearingFeeStartScreenController.ts
  src/main/routes/features/helpWithFees/helpWithFeesController.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeReferenceContents.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionContents.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpWithFeesPageContent.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeStartPageContent.ts
  src/main/services/features/helpWithFees/applyHelpWithFeesService.ts
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-selection.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-with-fees.njk
  src/main/views/features/caseProgression/hearingFee/pay-hearing-fee-start.njk
  src/main/views/features/claim/payment-successful.njk
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/features/helpWithFees/help-fees-start.njk
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/heringFeeStartPageContent.test.ts
  src/test/unit/services/features/helpWithFees/applyHelpWithFeesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3723

#3775 CIV-9455 Application Hearing Preferences and contact details
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/hearingArrangement.ts
  src/main/common/models/generalApplication/hearingContactDetails.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/generalApplication/hearingArrangementController.ts
  src/main/routes/features/generalApplication/hearingContactDetailsController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/views/features/generalApplication/hearing-arrangement.njk
  src/main/views/features/generalApplication/hearing-contact-details.njk
  src/test/unit/routes/features/claim/generalApplication/hearingArrangementController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingContactDetailsController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-hearing-arrangement.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-hearing-contact-details.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3775

#3760 CIV-13830 - fix hearing pay urls in notification
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
  src/main/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.ts
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/utils/mocks/civilClaimResponseNoAdmittedPaymentAmountMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3760

#3786 CIV-13741 More Tests
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/nonprod/carm_LiPvLiP_Individual_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3786

#3834 CIV-0000 Update README.md
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_NotFull_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3834

#3799 CIV-11832 Adding Link To View Evidence Upload Documents
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3799

#3734 CIV-13684 Amending CP FTs
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpFeeSelection.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFees.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFeesReferenceNumber.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFeesStart.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/payHearingFee.js
  src/test/functionalTests/citizenFeatures/caseProgression/steps/hearingFeeSteps.js
  src/test/functionalTests/citizenFeatures/common/govPay.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/dashboardTasklistConstants.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3734

#3829 CIV-9474 GA LiP Respondent Information Screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/respondentRequestChangeInformationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/generalApplication/respondent-request-change-information.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/respondentRequestChangeInformationController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-respondent-information.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3829

#3828 CIV-13893 contact us should shift if errors
  bin/import-bpmn-diagram.sh
  bin/import-dmn-diagram.sh
  bin/pull-latest-camunda-files.sh
  bin/pull-latest-dmn-files.sh
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/features/caseProgression/check-answers.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-selection.njk
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/caseProgression/trialArrangements/is-case-ready.njk
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/claim/payment-successful.njk
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/features/generalApplication/add-another-application.njk
  src/main/views/features/generalApplication/agree-to-order.njk
  src/main/views/features/generalApplication/agreement-from-other-party.njk
  src/main/views/features/generalApplication/application-type.njk
  src/main/views/features/generalApplication/claim-application-cost.njk
  src/main/views/features/generalApplication/hearing-support.njk
  src/main/views/features/generalApplication/inform-other-parties.njk
  src/main/views/features/generalApplication/order-judge.njk
  src/main/views/features/generalApplication/paying-for-application.njk
  src/main/views/features/generalApplication/requesting-reason.njk
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFees.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFeesConfirmation.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/paymentSuccessful.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/admitAllClaimantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/partAdmitClaimantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllClaimantResponse.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3828

#3840 CIV-13815 Welsh Translations
  src/main/modules/i18n/locales/cy.json
  src/test/unit/routes/features/response/responseDeadlineOptionsController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3840

#3739 CIV-13370 Pagination elements have the same hidden text
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/claimPaginationService.ts
  src/test/unit/services/features/dashboard/claimPaginationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3739

#3667 CIV-0000 DTSCCI-208: Multiple Incidents: Defendant Can't link claim
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/routes/features/public/firstContact/claimReferenceController.ts
  src/test/unit/routes/features/public/firstContact/claimReferenceController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3667

#3754 CIV-12893 Defendant LiP dashboard notifications: Default judgment issued
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3754

#3891 CIV-0000 Fix flaky cp tests
  src/test/functionalTests/citizenFeatures/caseProgression/steps/hearingFeeSteps.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3891

#3764 CIV-10455 Claimant LiP screen: mark Judgment as Paid in Full
  src/main/app/client/civilServiceClient.ts
  src/main/common/form/models/judmentOnline/confirmYouHaveBeenPaidForm.ts
  src/main/common/models/claim.ts
  src/main/common/models/events/caseEvent.ts
  src/main/common/models/judgmentOnline/ccdJudgmentPaidInFull.ts
  src/main/common/models/judgmentOnline/cuiJudgmentPaidInFull.ts
  src/main/common/models/judgmentOnline/judgmentOnline.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationController.ts
  src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationContents.ts
  src/main/services/translation/judgmentOnline/convertToCCDjudgmentPaidInFull.ts
  src/main/views/features/judgmentOnline/confirm-you-have-been-paid.njk
  src/main/views/features/judgmentOnline/judgment-online-confirmation-page.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/judgmentOnline/confirmYouHaveBeenPaidConfirmationController.test.ts
  src/test/unit/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.test.ts
  src/test/unit/services/translation/judgmentOnline/convertToCCDjudgmentPaidInFull.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-judgment-online-confirm-you-have-been-paid-confirmation.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-judgment-online-confirm-you-have-been-paid.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3764

#3731 CIV-8154 flight delay
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/airlines/flights.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/flightDetails.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/airlines/delayedFlightController.ts
  src/main/routes/features/claim/airlines/flightDetailsController.ts
  src/main/routes/features/claim/yourDetails/defendantPartyTypeController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/delayedFlightService.ts
  src/main/services/features/claim/partyTypeService.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDFlightDetails.ts
  src/main/views/features/claim/airlines/delayed-flight.njk
  src/main/views/features/claim/airlines/flight-details.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/airlines/delayedFlightController.test.ts
  src/test/unit/routes/features/claim/airlines/flightDetailsController.test.ts
  src/test/unit/routes/features/claim/defendantPartyTypeController.test.ts
  src/test/unit/services/features/claim/delayedFlightService.test.ts
  src/test/utils/mocks/a11y/mock-claim-delayed-flight.html
  src/test/utils/mocks/a11y/mock-claim-flight-details.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3731

#3826 CIV-13450 Unavailable hearing dates page
  sonar-project.properties
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/unavailableDatesGaHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/unavailableHearingDatesController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/unavailableHearingDatesService.ts
  src/main/views/features/directionsQuestionnaire/hearing/unavailable-dates-for-hearing.njk
  src/main/views/features/generalApplication/unavailable-dates-hearing.njk
  src/main/views/features/mediation/unavailable-dates-mediation.njk
  src/main/views/macro/unavailable-date-row.njk
  src/test/unit/routes/features/claim/generalApplication/hearingSupportController.test.ts
  src/test/unit/routes/features/claim/generalApplication/unavailableHearingDatesController.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/unavailableHearingDatesService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-unavailable-dates.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3826

#3871 CIV-9453 - LiP upload evidence to application
  src/main/common/models/AppRequest.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/uploadGAFiles.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/routes/features/generalApplication/hearingArrangementsGuidanceController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/features/generalApplication/wantToUploadDocuments.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/uploadEvidenceDocumentService.ts
  src/main/views/features/claimantResponse/check-answers.njk
  src/main/views/features/generalApplication/hearing_arrangements_guidance.njk
  src/main/views/features/generalApplication/upload_documents.njk
  src/main/views/features/generalApplication/want-to-upload-documents.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingArrangementsController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/routes/features/claim/generalApplication/wantToUploadDocumentsController.test.ts
  src/test/unit/services/features/generalApplication/uploadEvidenceDocumentService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-hearing-arrangements-guidance.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-upload-documents.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-want-to-upload-documents.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3871

#3815 CIV-13619 GA payment failure screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationPaymentUnsuccessfulController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/generalApplication/application-payment-unsuccessful.njk
  src/test/unit/routes/features/claim/generalApplication/applicationPaymentUnsuccessfulController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-payment-unsuccessful.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3815

#3740 CIV-13448 reduced margin-bottom to zero for notification content
  src/main/assets/scss/main.scss
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3740

#3825 CIV-13864 Application Response Confirmation Screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/response/applicationResponseConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/generalApplication/response/application-response-confirmation.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseConfirmationController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-general-application-confirmation.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3825

#3888 CIV-13708 - Welsh translations for trial readiness
  src/main/common/models/caseProgression/trialArrangements/finaliseYourTrialSectionBuilder.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/services/features/caseProgression/trialArrangements/finaliseYourTrialStartScreenContent.ts
  src/main/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmationSection.ts
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/caseProgression/trialArrangements/is-case-ready.njk
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/checkYourAnswers.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/hasAnythingChanged.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/isYourCaseReadyForTrial.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/trialArrangementsConfirmation.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/trialArrangementsIntroduction.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/trialArrangements/trialDuration.js
  src/test/functionalTests/citizenFeatures/caseProgression/steps/trialArrangementSteps.js
  src/test/unit/common/models/caseProgression/trialArrangements/finaliseYourTrialSectionBuilder.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/checkAnswersController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/finaliseTrialArrangementsController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hasAnythingChangedController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/isCaseReadyController.test.ts
  src/test/unit/routes/features/caseProgression/trialArrangements/trialArrangementsConfirmationController.test.ts
  src/test/unit/services/features/caseProgression/trialArrangements/checkAnswersService.test.ts
  src/test/unit/services/features/response/checkAnswers/caseProgression/trialArrangements/buildTrialReadyConfirmation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3888

#3783 CIV-13676 View The Judgement Page
  src/main/common/models/claim.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/viewTheJudgementController.ts
  src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/judgement/judgementService.ts
  src/main/views/features/caseProgression/view-the-judgement.njk
  src/main/views/macro/dashboard-accordion.njk
  src/main/views/macro/page-information.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/caseProgression/viewTheJudgementControllerTest.ts
  src/test/unit/services/features/caseProgression/judgement/judgementService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-view-the-judgment.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3783

#3837 CIV-13704 welsh translation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpWithFeeController.ts
  src/main/routes/features/claim/paymentSuccessfulController.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpWithFeesPageContent.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeStartPageContent.ts
  src/main/services/features/claim/paymentSuccessfulContents.ts
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-selection.njk
  src/main/views/features/helpWithFees/help-fees-start.njk
  src/test/functionalTests/citizenFeatures/caseProgression/pages/hearingFee/applyHelpWithFeesReferenceNumber.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/unit/routes/features/claim/paymentSuccessfulController.test.ts
  src/test/unit/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/heringFeeStartPageContent.test.ts
  src/test/unit/services/features/claim/paymentSuccessfulContents.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3837

#3851 CIV-13607 Applicant Defendant upload N245 form
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/uploadGAFiles.ts
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/uploadN245FormController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/uploadN245FormService.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/features/generalApplication/upload-n245-form.njk
  src/main/views/features/mediation/uploadDocuments/upload-documents.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadN245FormController.test.ts
  src/test/unit/services/features/generalApplication/uploadN245FormService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-upload-n245-form.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3851

#3868 CIV-13863 accessibility statement
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/oidc/index.ts
  src/main/routes/features/public/accessibilityStatementController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/claim-details-tpl.njk
  src/main/views/external-urls.njk
  src/main/views/features/public/accessibility-statement.njk
  src/main/views/service-unavailable-layout.njk
  src/test/unit/routes/features/public/accessibilityStatementController.test.ts
  src/test/utils/mocks/a11y/mock-accessibility-statement.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3868
