Repository hmcts/civil-citizen-ui, pull requests merged in 2024-10, with the labels that each got.

#4646 CIV-15073 CIV-15074 CIV-15075 CIV-15076 CIV-15077 CIV-15079 Sprint branch for CosC
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/form/models/certOfSorC/defendantFinalPaymentDate.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse/ccj/ccjRequest.ts
  src/main/common/models/generalApplication/CertificateOfSatisfactionOrCancellation.ts
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/common/models/generalApplication/applicationType.ts
  src/main/common/models/generalApplication/debtPaymentEvidence.ts
  src/main/common/models/generalApplication/debtPaymentOptions.ts
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/features/generalApplication/applicationCostsController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.ts
  src/main/routes/features/generalApplication/certOfSorC/debtPaymentEvidenceController.ts
  src/main/routes/features/generalApplication/certOfSorC/defendantFinalPaymentDateController.ts
  src/main/routes/features/generalApplication/claimApplicationCostController.ts
  src/main/routes/features/generalApplication/informOtherPartiesController.ts
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/generalApplication/certOfSorC/certificateOfSatisfactionOrCancellationService.ts
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/translation/convertToCUI/convertToCUIYesNo.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/views/external-urls.njk
  src/main/views/features/generalApplication/application-type.njk
  src/main/views/features/generalApplication/certOfSorC/ask-proof-debtPayment-guidance.njk
  src/main/views/features/generalApplication/certOfSorC/debt-payment-evidence.njk
  src/main/views/features/generalApplication/certOfSorC/final-payment-date.njk
  src/test/a11y/ignored-urls.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/debtPaymentEvidenceController.test.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/defendantFinalPaymentDateController.test.ts
  src/test/unit/routes/features/claim/generalApplication/submitGeneralApplicationConfirmationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/services/features/generalApplication/certOfSorC/certificateOfSatisfactionOrCancellationService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/utils/errorMessageTestConstants.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-cosc-ask-proof-of-debt-payment-guidance.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-cosc-final-payment-date.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-cosc-upload-documents.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4646

#4675 Nonce value for data layer script
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4675

#4699 CIV-15493 - Fix for draft claim dashboard
  src/main/modules/utilityService.ts
  src/main/routes/features/claim/createDraftClaim.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/test/unit/routes/features/claim/createClaimDraft.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4699

#4698 CIV-15490 Breakdown interest option
  src/main/routes/features/claim/interest/claimTotalInterestController.ts
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
  src/test/unit/routes/features/claim/iterest/claimTotalInterestController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4698

#4694 CIV-15484 - Fix to prevent interest from incorrectly accumulating once claim is submitted
  src/main/common/utils/dateUtils.ts
  src/main/common/utils/interestUtils.ts
  src/test/unit/common/utils/dateUtils.test.ts
  src/test/unit/common/utils/interestUtils.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4694

#4708 CIV-15495 - Amendment to content on the 'Try the new online service' screen
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/eligibility/tryNewServiceController.ts
  src/main/views/features/public/eligibility/try-new-service.njk
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4708

#4661 CIV-15220 welsh part 1
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/generalApplication/agreement-from-other-party.njk
  src/main/views/features/generalApplication/claim-application-cost.njk
  src/main/views/features/generalApplication/inform-other-parties.njk
  src/main/views/features/generalApplication/upload-n245-form.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:civil-citizen-ui-pr-4661

#4610 DTSCCI-000 updating readme to facilitate the elasticsearch chart trigger
  README.md
  bin/setup-devuser-preview-env.sh
  bin/utils/ccd-import-definition.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4610

#4726 CIV-000 remove field defenceAdmitPartPaymentTimeRouteRequired from reject all payloads
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllClaimantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllFastTrackDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllSmallClaimsDefendantResponse.js
  src/test/functionalTests/tests/nonprod/minti_LiPvLiP_intermediate_track_tests.js
  src/test/functionalTests/tests/nonprod/minti_LiPvLiP_multi_track_tests.js
  src/test/functionalTests/tests/nonprod/mt_it_LiPvLiP_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4726

#4727 CIV-15516 calculate total amount based on the rows
  src/main/services/features/claim/amount/claimAmountBreakdownService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4727

#4745 CIV-15545 testing support for prod
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/claim-details-tpl.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4745

#4746 CIV-0000 roundoffissue
  src/main/app/client/civilServiceClient.ts
  src/main/common/utils/dateUtils.ts
  src/main/routes/guards/checkYourAnswersGuard.ts
  src/main/services/features/claim/amount/claimAmountBreakdownService.ts
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/response/convertToCCDClaimAmount.ts
  src/test/unit/routes/features/claim/totalAmountController.test.ts
  src/test/unit/routes/guards/checkYourAnswersGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4746

#4735 CIV-15226 changes to conetnt for payment unsucessful screen
  src/main/routes/features/claim/payment/claimFeePaymentUnsuccessfulController.ts
  src/main/views/features/caseProgression/hearingFee/payment-unsuccessful.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4735

#4748 CIV-15517 Email validation for >40 characters
  src/main/common/form/validators/emailValidator.ts
  src/main/common/form/validators/phoneUKValidator.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/test/unit/routes/features/claim/defendantEmailController.test.ts
  src/test/unit/routes/features/claim/defendantPhoneController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4748

#4754 CIV-0000 fix for e2e test
  src/main/common/form/validators/emailValidator.ts
  src/main/services/features/claim/submission/submitClaim.ts
  src/main/services/translation/response/convertToCCDParty.ts
  src/test/e2eTests/response/steps/response.js
  src/test/unit/routes/features/claim/defendantEmailController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4754

#4757 DTSCCI-813 amending config for definitions caseType id extension
  bin/utils/process-definition.sh
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4757

#4758 CIV-15564 fix for updating with latest payment reference
  src/main/services/features/claim/payment/claimFeeMakePaymentAgainService.ts
  src/test/unit/services/features/claim/payment/claimFeeMakePaymentAgainService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4758

#4719 DTSCCI-843 Remove banner from CUI following CUI R2
  src/main/views/features/dashboard/dashboard.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4719

#4765 CIV-15569 Change email check to >320 chars
  src/main/common/form/validators/emailValidator.ts
  src/test/unit/routes/features/claim/defendantEmailController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4765

#4770 CIV-15573 logs added to analyse the payment failure issues
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4770

#4772 CIV-0000 remove log statement
  src/main/modules/draft-store/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4772

#4782 CIV-0000 added code for handling 401 errors
  src/main/modules/error/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4782

#4743 CIV-0000 Enable R2 tests to run in AAT
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/common/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_RejectAll_DisputeAll_Intention_UI_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/common/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/common/OCMC_tests.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_Api_FullAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_AlreadyPaid_NotFull_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_RejectAll_DisputeAll_Intention_UI_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_Api_partAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_DefaultJudgment_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_JudgmentByAdmissions_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsCompany.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/OrgVsSoleTrader.js
  src/test/functionalTests/tests/nonprod/createClaim/SoleTraderVsIndividual.js
  src/test/functionalTests/tests/prod/LiPvLiP_Api_FullAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_RejectAll_AlreadyPaid_NotFull_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/prod/LipvLip_UI_DefaultJudgment_tests.js
  src/test/functionalTests/tests/prod/LipvLip_UI_JudgmentByAdmissions_tests.js
  src/test/functionalTests/tests/prod/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4743

#4784 CIV-15587 fix validation on cya
  src/main/common/form/models/EmailValidationWithMessage.ts
  src/main/common/form/models/PhoneValidationWithMessage.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/checkAnswersController.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4784

#4787 DTSCCI-1022 - Update Time Extension Wording
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/viewYourOptionsBeforeDeadline/viewYourOptionsBeforeDeadline.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4787

#4799 CIV-15599 - Payment gateway return url get call is ignored when user session expires
  src/main/modules/oidc/index.ts
  src/test/unit/modules/oidc/index.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4799

#4786 CIV-15481 and CIV-10790 View Bundle Micro Heading And Text Changes
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/bundlesController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4786

#4829 CIV-13684: CP tests move some of them to nightly
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_orders_fast_small_claims.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_upload_evidence_trial_arrangements_fast_track_tests.js
Labels: fullDeploy, pr-values:elasticsearch

#4832 CIV-0000 Bulk SP5
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationAddlDocument.ts
  src/main/common/models/dashboard/dashboardNotification.ts
  src/main/common/models/document/documentType.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/models/generalApplication/response/acceptDefendantOffer.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/additionalFee/payAdditionalFeeController.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
  src/main/routes/features/generalApplication/applicationFeePaymentSuccessfulController.ts
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/routes/features/generalApplication/hearingSupportController.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesResponseController.ts
  src/main/routes/features/generalApplication/unavailableHearingDatesController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/features/generalApplication/applicationFeePaymentConfirmationContent.ts
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/main/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.ts
  src/main/services/features/generalApplication/submitGeneralApplicationConfirmationContent.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/add-another-application.njk
  src/main/views/features/generalApplication/additionalDocuments/upload-additional-documents.njk
  src/main/views/features/generalApplication/additionalInfoUpload/upload-documents.njk
  src/main/views/features/generalApplication/applicationFee/help-with-application-fee.njk
  src/main/views/features/generalApplication/check-answers.njk
  src/main/views/features/generalApplication/directionsOrderUpload/upload-documents.njk
  src/main/views/features/generalApplication/response/accept-defendant-offer.njk
  src/main/views/features/generalApplication/upload_documents.njk
  src/main/views/features/generalApplication/want-to-upload-documents.njk
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/features/claim/generalApplication/additionalFee/payAdditionalFeeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpApplicationFeeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFeePaymentSuccessfulController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/unavailableHearingDatesResponseController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4832

#4838 CIV-0000 increased session time out
  src/main/app.ts
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4838

#4692 CIV-0000 GA welsh tests
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllSmallClaimsDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/translatedDocUpload.js
  src/test/functionalTests/tests/common/LRvLip_response_rejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LIPvLiP_ClaimantWelsh_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LIPvLiP_DefendantWelsh_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LRvLiP_DefendantWelsh_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4692

#4810 CIV-15293 CoSc Welsh translation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/generalApplication/certOfSorC/ask-proof-debtPayment-guidance.njk
  src/main/views/features/generalApplication/certOfSorC/final-payment-date.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4810

#4531 CIV-15152 removed ambiguity from some states
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, aat/add-or-update, prod/no-changes, rel:civil-citizen-ui-pr-4531

#4853 CIV-15448 CoSC - Add guidelines link
  src/main/routes/features/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4853

#4839 CIV-15084 Added COSC document link on CUI dashboard
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4839

#4847 CIV-15622 fix Cannot read properties of undefined (reading 'date') at buildClaimAmountSection and CYA Page
  src/main/services/features/claim/checkAnswers/financialSection/buildClaimAmountSection.ts
  src/main/services/features/claim/interest/interestService.ts
  src/test/unit/services/features/claim/checkAnswers/claimAmountSection/buildClaimAmountSection.test.ts
  src/test/unit/services/features/claim/interest/interestService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4847

#4828 CIV-15623 - TypeError: Cannot read properties of (reading 'status') at postcodeLookupController
  src/main/modules/ordance-survey-key/ordanceSurveyKeyService.ts
  src/main/routes/features/response/citizenDetails/postcodeLookupController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4828

#4850 CIV-15639 typo accessibility
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4850

#4874 DTSCCI-0000 Bump civil service chart version
  charts/civil-citizen-ui/Chart.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4874

#4861 CIV-15648 invalid csrf token
  src/main/modules/csrf/index.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4861

#4887 CIV-0000 Sprint - CIV-15448
  src/main/routes/features/generalApplication/certOfSorC/askProofOfDebtPaymentGuidanceController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4887

#4885 DTSCCI-1058 Fixing Nightly tests
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/viewYourOptionsBeforeDeadline/viewYourOptionsBeforeDeadline.js
  src/test/functionalTests/tests/prod/wa/welshResponse_caseworker_request_translation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4885

#4595 CIV-15314 back link
  src/main/routes/features/generalApplication/response/respondentWantToUploadDocumentsController.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4595
