Repository hmcts/civil-citizen-ui, pull requests merged in 2024-11, with the labels that each got.

#4808 CIV-15369 redirect to claimant/defendant dashboard
  src/main/routes/features/generalApplication/response/applicationResponseConfirmationController.ts
  src/main/views/features/generalApplication/response/application-response-confirmation.njk
  src/test/unit/routes/features/claim/generalApplication/response/applicationResponseConfirmationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4808

#4926 CIV-15666 disable submit button
  sonar-project.properties
  src/main/assets/js/disable-submit.js
  src/main/index.js
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
  src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4926

#4966 CIV-15350 Accessibility Issue - Adding Header Only If Title Is Available
  src/main/views/features/caseProgression/check-answers.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4966

#4647 CIV-15373 GA Lip Response - Vary a judgement
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4647

#4878 CIV-15281 View Orders And Notices - Multiple SDO Documents
  src/main/services/features/dashboard/ordersAndNoticesService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4878

#4937 CIV-15508 CIV-15370 Fix GA statuses
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4937

#4923 CIV-15654 CoSc- View application
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/models/generalApplication/applicationType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4923

#4779 CIV-15368 CYA bug 2
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/response/checkAnswersResponseService.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/test/unit/services/features/generalApplication/response/checkAnswersResponseService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationRows.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4779

#4761 CIV-5366 cya bug
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/unit/services/features/generalApplication/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4761

#4974 CIV-15384 fix N245 upload
  src/main/common/models/gaEvents/eventDto.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4974

#4762 CIV-15501 welsh translations
  src/main/common/models/generalApplication/applicationType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4762

#4812 CIV-15530 Welsh Translation View Your Application
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/test/unit/routes/features/claim/payment/claimFeePaymentUnsuccessfulController.test.ts
  src/test/unit/routes/features/mediation/uploadDocuments/confirmationController.test.ts
  src/test/unit/routes/features/public/cookiesController.test.ts
  src/test/unit/routes/features/public/firstContact/accessDeniedController.test.ts
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
  src/test/unit/routes/features/public/firstContact/signpostingController.test.ts
  src/test/unit/routes/features/response/ageEligibility/ageEligibilityController.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4812

#4964 CIV-15698 CYA statement of truth
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-check-and-send.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4964

#4940 CIV-15645 Translate document type
  src/main/common/models/generalApplication/gaDocumentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4940

#4848 CIV-15565 fix names for companies or organization
  src/main/services/features/caseProgression/requestForReconsideration/requestForReviewContent.ts
  src/test/functionalTests/tests/nonprod/cp_request_for_reconsideration_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4848

#4941 CIV-15680 change SUMMARY_JUDGMENT to SUMMARY_JUDGEMENT
  src/main/common/models/generalApplication/applicationType.ts
  src/main/services/features/generalApplication/orderJudgePageBuilder.ts
  src/main/services/features/generalApplication/requestingReasonPageBuilder.ts
  src/main/views/features/generalApplication/application-type.njk
  src/test/unit/routes/guards/checkYourAnswersGAGuard.test.ts
  src/test/unit/services/features/generalApplication/orderJudgePageBuilder.test.ts
  src/test/unit/services/features/generalApplication/requestingReasonPageBuilder.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4941

#4927 DTSCCI-1079 remove court list cache
  src/main/modules/draft-store/courtLocationCache.ts
  src/main/services/features/directionsQuestionnaire/hearing/specificCourtLocationService.ts
  src/test/a11y/a11y.scrape.ts
  src/test/unit/routes/features/claim/generalApplication/certOfSorC/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/generalApplication/checkAnswersController.test.ts
  src/test/unit/routes/features/claim/generalApplication/hearingArrangementController.test.ts
  src/test/unit/routes/features/claim/generalApplication/response/hearingArrangementResponseController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/makePaymentAgainService.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/paymentConfirmationService.test.ts
  src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
  src/test/unit/services/features/directionsQuestionnaire/hearing/specificCourtLocationService.test.ts
  src/test/unit/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4927

#4997 CIV-15786 do not display 'reconsider an order' as a bullet point
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/generalApplication/agreement-from-other-party.njk
  src/test/functionalTests/citizenFeatures/GA/pages/agreementFromOtherParty.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4997

#4771 CIV-15431 CIV-15434 CIV-15433 CIV-15418
  package.json
  src/test/config.js
  src/test/functionalTests/citizenFeatures/GA/pages/addAnotherApplication.js
  src/test/functionalTests/citizenFeatures/GA/pages/agreementFromOtherParty.js
  src/test/functionalTests/citizenFeatures/GA/pages/applicationCosts.js
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/functionalTests/citizenFeatures/GA/pages/claimApplicationCost.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingArrangement.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingArrangementsGuidance.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingContactDetails.js
  src/test/functionalTests/citizenFeatures/GA/pages/hearingSupport.js
  src/test/functionalTests/citizenFeatures/GA/pages/informOtherParties.js
  src/test/functionalTests/citizenFeatures/GA/pages/orderJudge.js
  src/test/functionalTests/citizenFeatures/GA/pages/payingForApplication.js
  src/test/functionalTests/citizenFeatures/GA/pages/paymentGAConfirmation.js
  src/test/functionalTests/citizenFeatures/GA/pages/requestingReason.js
  src/test/functionalTests/citizenFeatures/GA/pages/submitGAConfirmation.js
  src/test/functionalTests/citizenFeatures/GA/pages/unavailableDates.js
  src/test/functionalTests/citizenFeatures/GA/pages/wantToUploadDocuments.js
  src/test/functionalTests/citizenFeatures/response/steps/createGAAppSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createDefendantResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/rejectAllSmallClaimsDefendantResponse.js
  src/test/functionalTests/tests/gaWelsh/GA_LIPvLiP_ClaimantWelsh_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LIPvLiP_DefendantWelsh_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LRvLiP_DefendantWelsh_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4771

#4904 CIV-14297 Changing Application Type CYA
  src/main/common/utils/urlFormatter.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/features/generalApplication/applicationCostsController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/claimApplicationCostController.ts
  src/main/routes/features/generalApplication/hearingArrangementController.ts
  src/main/routes/features/generalApplication/hearingArrangementsGuidanceController.ts
  src/main/routes/features/generalApplication/hearingContactDetailsController.ts
  src/main/routes/features/generalApplication/hearingSupportController.ts
  src/main/routes/features/generalApplication/informOtherPartiesController.ts
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/features/generalApplication/payingForApplicationController.ts
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/features/generalApplication/unavailableHearingDatesController.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/features/generalApplication/wantToUploadDocuments.ts
  src/main/routes/guards/generalApplication/agreementFromOtherPartyGuard.ts
  src/main/routes/guards/generalApplication/informOtherPartiesGuard.ts
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/checkAnswers/checkAnswersService.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/upload_documents.njk
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/services/features/generalApplication/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/generalApplication/generalApplicationService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4904

#5000 CIV-15702 Case states - Ga for LiPs
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5000

#4985 CIV-15687 Update wording on claimant LiP postal address eligibility question
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/claimant-address-eligibility.njk
  src/test/functionalTests/citizenFeatures/createClaim/pages/eligibilityCheck.js
  src/test/utils/mocks/a11y/mock-eligibility-claimant-address.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4985

#5032 CIV-15364 Add missing additional fee amount
  src/main/common/models/generalApplication/gaHelpWithFees.ts
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeContinueController.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5032

#4747 CIV-15545 flag testing support enabled
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/nunjucks/index.ts
  src/main/views/claim-details-tpl-dashboard.njk
  src/main/views/claim-details-tpl.njk
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-4747

#5034 CIV-15825 - Judge dismisses application - document does not appear in 'Documents from court' section
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationDirectionsOrderDocument.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5034

#5023 CIV-15647 Skipping the FRF FTs
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_request_for_reconsideration_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5023

#4938 CIV-15585 Crossbrowser tests
  Jenkinsfile_nightly
  package.json
  src/test/crossbrowser/helpers/saucelabsReportingHelper.js
  src/test/crossbrowser/supportedBrowsers.js
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
  src/test/functionalTests/citizenFeatures/createClaim/pages/eligibilityCheck.js
  src/test/functionalTests/commonFeatures/home/pages/login.js
  src/test/functionalTests/helpers/browser_helper.js
  src/test/functionalTests/run-crossbrowser-tests.sh
  src/test/functionalTests/saucelabs.conf.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/steps_noc.js
  src/test/functionalTests/tests/prod/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-4938

#5026 CIV-15773 Show same view as applicant after response
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationResponseRows.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5026

#5041 CIV-15719 Hearing Fee Prevent Duplicate Payments
  src/main/assets/js/disable-submit.js
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.ts
  src/main/services/features/caseProgression/hearingFee/makePaymentAgainService.ts
  src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
  src/main/services/features/caseProgression/hearingFee/paymentServiceUtils.ts
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeSelectionController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/applyHelpFeeSelectionService.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/makePaymentAgainService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5041

#5045 CIV-15500 HWF application type of fee not showing correctly in dashboard notification
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5045

#5055 CIV-15817 Welsh HWF Error Message
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-5055

#5056 CIV-15625 Accessibility Hearing Support
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/generalApplication/hearing-support.njk
  src/test/functionalTests/citizenFeatures/GA/pages/hearingSupport.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5056

#5076 CIV-5659 - Confirm your payment screen not translated to Welsh
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.ts
  src/test/unit/services/features/generalApplication/payment/applicationFeePaymentConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5076

#5064 CIV-15720 Display Stay Notifications First
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5064

#5067 CIV-15842 - GA Lip - Incorrect question appears in CYA page when application type is SetAsideJudgment
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/test/unit/services/features/generalApplication/checkAnswers/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5067

#5044 CIV-15802 Update General AppRespondent list
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5044

#5080 CIV-15705 Welsh Translations for Make Application Journey
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5080

#5063 CIV-15840 Additional text when in CP
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/routes/features/claim/generalApplication/response/viewApplicationController.test.ts
  src/test/unit/routes/features/claim/generalApplication/viewApplicationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5063

#5008 CIV-15781 added code e2e test for ga creation
  .github/workflows/ci.yml
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/modules/e2eConfiguration/gaRedisData.json
  src/main/modules/e2eConfiguration/index.ts
  src/main/modules/e2eConfiguration/redisData.json
  src/test/e2eTests/genralApplication/createGAApplication.js
  src/test/e2eTests/genralApplication/respondentResponse.js
  src/test/e2eTests/genralApplication/responseApplicationSummary.js
  src/test/e2eTests/tests/generalApplication/LipVsLipVaryOrderConsent.js
  wiremock/__files/generalApplication/application-submission.json
  wiremock/__files/generalApplication/claimantDashboardNotifications.json
  wiremock/__files/generalApplication/claimantDashboardTasks.json
  wiremock/__files/generalApplication/fee-select.json
  wiremock/__files/generalApplication/gaApplication-afterpayment.json
  wiremock/__files/generalApplication/gaApplications.json
  wiremock/__files/generalApplication/mainCaseForGA.json
  wiremock/__files/generalApplication/payment-redirect.json
  wiremock/__files/generalApplication/payment-status.json
  wiremock/__files/generalApplication/respondent-response.json
  wiremock/mappings/generalApplication/claimant-dashboard-mapping.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5008

#5113 CIV-15794 N245 at Ga CYA
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/checkAnswers/checkAnswersService.ts
  src/test/unit/services/features/generalApplication/checkAnswers/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5113

#5114 CIV-15807 agreement from other parties
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/GA/pages/agreementFromOtherParty.js
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-agreement-from-other-party.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5114

#5093 CIV-15818 Welsh Translation for Type of Response
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5093

#5087 CIV-15805 Welsh Translations for Upload Documents
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5087

#5035 DTSCCI-1149 Round value to avoid floating point error
  src/main/services/translation/claim/moneyConversation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDRespondToClaim.ts
  src/test/unit/services/translation/claim/moneyConversation.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5035

#5141 CIV-0000 fixed functional tests
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/courtLocation.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5141

#5124 CIV-15853 ga multiple types
  src/main/common/models/generalApplication/GeneralApplication.ts
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/applicationSummaryController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5124

#5112 CIV-15846 Fix unavailable dates error messages
  src/main/common/models/generalApplication/unavailableDatesGaHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/routes/features/claim/generalApplication/response/unavailableHearingDatesResponseController.test.ts
  src/test/unit/routes/features/claim/generalApplication/unavailableHearingDatesController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5112

#5102 CIV-15650 Implement summary cards for GA CYA and view application
  src/main/common/models/ccdGeneralApplication/ccdGeneralAppRequestingReason.ts
  src/main/common/models/ccdGeneralApplication/ccdGeneralApplicationOrderJudge.ts
  src/main/common/models/gaEvents/eventDto.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/common/models/summaryList/summaryList.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/checkAnswers/addCheckAnswersRows.ts
  src/main/services/features/generalApplication/checkAnswers/checkAnswersService.ts
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/main/views/features/generalApplication/check-answers.njk
  src/main/views/features/generalApplication/response/view-application.njk
  src/main/views/features/generalApplication/view-applications.njk
  src/test/unit/services/features/generalApplication/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
  src/test/utils/mocks/applicationMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5102

#5140 CIV-15967 CUI Banner Implementation For CUI_CP Release
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/features/dashboard/dashboard.njk
  src/main/views/macro/banner.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5140

#5145 CIV-15839 Updating Welsh Translation
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5145

#5051 CIV-15116 - Translated document access on CUI
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5051
