Repository hmcts/civil-citizen-ui, pull requests merged in 2024-01, with the labels that each got.

#2856 CIV-0000 FixFTs
  src/test/functionalTests/features/response/pages/defendantLipResponse/howYouWillPay/howMuchYouHavePaid.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/whyDoYouDisagree/addYourTimeLine.js
  src/test/functionalTests/features/response/pages/defendantLipResponse/yourRepaymentPlan/dateToPayOn.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2856

#2861 CIV-00000 CUI team 2 Post Christmas Release
  src/main/common/models/caseProgression/uploadDocumentsType.ts
  src/main/common/models/caseProgression/uploadDocumentsUserForm.ts
  src/main/services/features/caseProgression/caseProgressionService.ts
  src/main/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadedSummaryRows.ts
  src/main/services/features/caseProgression/checkYourAnswers/checkAnswersService.ts
  src/main/services/features/caseProgression/witnessContentBuilder.ts
  src/main/services/features/caseProgression/witnessService.ts
  src/main/services/features/dashboard/claimSummaryService.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/test/functionalTests/features/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/unit/routes/features/caseProgression/uploadDocumentsController.test.ts
  src/test/unit/services/features/caseProgression/checkYourAnswers/buildEvidenceUploadSummaryRows.test.ts
  src/test/unit/services/features/caseProgression/uploadedEvidenceFormatter.test.ts
  src/test/unit/services/features/caseProgression/witnessService.test.ts
  src/test/unit/services/features/dashboard/claimSummaryService.test.ts
  src/test/unit/services/translation/caseProgression/convertToCCDEvidenceUpload.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
  src/test/utils/caseProgression/mockCCDClaimForEvidenceUpload.ts
  src/test/utils/caseProgression/mockEvidenceUploadSections.ts
  src/test/utils/caseProgression/mockEvidenceUploadSummaryRows.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2861

#2865 DTSPO-15909 - migrated Application Insights
  infrastructure/README.md
  infrastructure/app-insights.tf
  infrastructure/key-vault-secrets.tf
Labels: add-or-update

#2757 CIV-11603 Fast Track Claimant Intent
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2757

#2853 CIV-11364 Case Progression tests to Check the the Case Strike off Tile in the Latest Update Page.
  src/test/functionalTests/features/caseProgression/pages/documents.js
  src/test/functionalTests/features/caseProgression/pages/latestUpdate.js
  src/test/functionalTests/features/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2853

#2880 CIV-TASK skipping orders FTs
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2880

#2771 CIV-7343 Hearing Fee Dashboard components
  src/main/common/models/caseProgression/dashboard.ts
  src/main/common/models/caseProgression/notifications.ts
  src/main/common/models/dashboardContentType.ts
  src/main/common/models/taskList/TaskStatus.ts
  src/main/common/models/taskList/task.ts
  src/main/common/models/taskList/taskList.ts
  src/main/common/utils/dashboard/dashboardNotification.ts
  src/main/common/utils/dashboard/notificationBuilder.ts
  src/main/common/utils/dashboard/notifications.ts
  src/main/modules/draft-store/getDashboardCache.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/services/features/caseProgression/dashboardService.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/test/unit/common/utils/dashboard/notifications.test.ts
  src/test/unit/services/dashboard/getDashboardContent.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2771

#2885 CIV-0000 - Minor change in CreateSpecifiedClaim Test file.
  src/test/functionalTests/specClaimHelpers/api/steps.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2885

#2833 CIV-11986 Fix Task List bug - Part Admit Pay by set date
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2833

#2838 CIV-11896 Payment Successful
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/paymentSuccessfulController.ts
  src/main/routes/routes.ts
  src/main/services/features/caseProgression/hearingFee/paymentConfirmationService.ts
  src/main/services/features/claim/paymentSuccessfulContents.ts
  src/main/services/features/claim/paymentSuccessfulSectionBuilder.ts
  src/main/views/features/claim/payment-successful.njk
  src/test/unit/routes/features/claim/paymentSuccessfulController.test.ts
  src/test/utils/mocks/civilClaimResponseHearingFeeMock.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2838

#2897 CIV-00000 Suppress follow redirect for higher version
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2897

#2815 CIV-11938 bug task list
  src/main/common/models/claimantResponse.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2815

#2835 CIV-8903 dashboard status for sign settlement
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2835

#2841 CIV-11965 remove duplicate fields
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2841

#2686 CIV-11161 Docmosis: Manual Determination -"Claimant's Response"
  src/main/common/models/ccdResponse/ccdPayBySetDate.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/main/services/translation/response/convertToCCDPayBySetDate.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
  src/test/unit/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.test.ts
  src/test/unit/services/translation/response/convertToCCDPayBySetDate.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2686

#2817 CIV-11542 Bilingual claim creation
  src/main/common/models/ccdResponse/ccdWelshLanguageRequirements.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/bilingualLangPreferenceController.ts
  src/main/routes/features/public/eligibility/eligibleController.ts
  src/main/routes/guards/claimLanguagePreferenceGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/response/bilingualLangPreferenceService.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/views/features/claim/claim-bilingual-language-preference.njk
  src/test/unit/common/models/ccdResponse/ccdWelshLanguageRequirements.test.ts
  src/test/unit/routes/features/claim/bilingualLangPreferenceController.test.ts
  src/test/unit/routes/guards/claimLanguagePreferenceGuard.test.ts
  src/test/unit/services/features/response/bilingualLangPreferenceService.test.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2817

#2786 CIV-11260 Judge decide repayment plan - CCJ confirmation screen
  src/main/common/models/claimantResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/ccjConfirmationBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2786

#2805 CIV-11969 Fast Track Mediation CYA
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2805

#2753 CIV-11828 Choose how to formalise repayment" task is not showing up after choosing a new repayment plan
  src/main/common/models/claimantResponse.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2753

#2733 CIV-11747 JudgmentAmountNaN
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2733

#2916 CIV-0000 Add new keys in the TF
  infrastructure/key-vault-secrets-civil.tf
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2916

#2624 CIV-11209 Help with fees reference number
  src/main/common/form/models/caseProgression/hearingFee/applyHelpFeesReferenceForm.ts
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/events/caseEvent.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.ts
  src/main/routes/features/caseProgression/hearingFee/payHearingFeeConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/caseProgression/hearingFee/applyHelpFeeReferenceContents.ts
  src/main/services/features/caseProgression/hearingFee/hearingFeeService.ts
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
  src/test/unit/routes/features/caseProgression/hearingFee/applyHelpFeeReferenceController.test.ts
  src/test/unit/routes/features/caseProgression/hearingFee/payHearingFeeConfirmationController.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/hearingFeeService.test.ts
  src/test/utils/mocks/civilClaimResponseHearingFeeMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2624

#2876 CIV-0000 Sprint pi32 s5 t4 to master
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/common/models/ccdResponse/ccdPayBySetDate.ts
  src/main/common/models/ccdResponse/ccdWelshLanguageRequirements.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/bilingualLangPreferenceController.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
  src/main/routes/features/public/eligibility/eligibleController.ts
  src/main/routes/guards/claimLanguagePreferenceGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/ccjConfirmationBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/confirmationContentBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.ts
  src/main/services/features/claimantResponse/responseSection/buildYourResponseSection.ts
  src/main/services/features/response/bilingualLangPreferenceService.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/main/services/translation/response/convertToCCDPayBySetDate.ts
  src/main/views/features/claim/claim-bilingual-language-preference.njk
  src/test/unit/common/models/ccdResponse/ccdWelshLanguageRequirements.test.ts
  src/test/unit/routes/features/claim/bilingualLangPreferenceController.test.ts
  src/test/unit/routes/guards/claimLanguagePreferenceGuard.test.ts
  src/test/unit/services/features/claim/checkAnswers/financialSection/buildPaymentSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/buildYourResponseSection.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseConfirmationContentService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseService.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistBuilder.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/whatToDoNextSectionTasks.test.ts
  src/test/unit/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasks/yourResponseSectionTasks.test.ts
  src/test/unit/services/features/response/bilingualLangPreferenceService.test.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
  src/test/unit/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.test.ts
  src/test/unit/services/translation/response/convertToCCDPayBySetDate.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2876

#2879 CIV-12104 removed logs
  src/main/app/client/civilServiceClient.ts
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch

#2952 CIV-12205 - Fixing functional tests
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2952

#2883 CIV-12106 - Fix of Final Orders test
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createAnAssistedOrder.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2883

#2663 CIV-9040 Redetermination - Interlocutory Judgement PDF (docmosis)
  src/main/common/models/ccdResponse/ccdPayBySetDate.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/common/utils/dateUtils.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/convertToCCDPayBySetDate.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDPayBySetDate.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2663

#2967 CIV-TASK fixing trial arrangements FTS
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createCaseProgressionToSDOState.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createClaimantResponseToDefence.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2967

#2914 CIV-00000 Add new keys in the TF
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
  config/default.yaml
  jest.setup.redis-mock.js
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/app/client/legacyDraftStoreClient.ts
  src/main/modules/properties-volume/index.ts
  src/main/services/features/claimantResponse/submission/submitClaimantResponse.ts
  src/main/services/features/claimantResponse/submitClaimantResponse.ts
  src/main/services/features/response/submission/submitResponse.ts
  src/test/secretsConfig.js
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2914

#2923 CIV-7707 CUI Automation: Create a citizen user on the fly to assign a case
  src/test/config.js
  src/test/functionalTests/specClaimHelpers/api/idamHelper.js
  src/test/functionalTests/tests/carm/carm_company_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/carm/carm_individual_defendant_response_small_claims_tests.js
  src/test/functionalTests/tests/cp_document_upload_fast_track_tests.js
  src/test/functionalTests/tests/cp_document_upload_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/cp_latest_update_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_latest_update_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/cp_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_comp_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2923

#2933 CIV-11878 fixing the contact us position bug
  src/main/views/features/caseProgression/trialArrangements/check-answers.njk
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements-confirmation.njk
  src/main/views/features/caseProgression/trialArrangements/finalise-trial-arrangements.njk
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/caseProgression/trialArrangements/hearing-duration-other-info.njk
  src/main/views/features/caseProgression/trialArrangements/is-case-ready.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2933

#2921 CIV-12122 update upload documents start button
  src/main/services/features/caseProgression/uploadYourDocumentsContents.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2921

#2851 CIV-8792 Fee & Pay integration - POSTPayment Status API and Navigation
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/common/form/models/helpWithFees/feeType.ts
  src/main/routes/features/claim/claimFeeController.ts
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/routes/features/claim/payment/claimFeePaymentConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
  src/main/views/features/claim/payment/claim-fee-breakdown.njk
  src/test/unit/routes/features/claim/claimFeeController.test.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
  src/test/unit/routes/features/claim/payment/claimFeePaymentConfirmationController.test.ts
  src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2851

#2760 CIV-11866 Welsh translations
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/modules/i18n/locales/cy.json
  src/main/routes/features/caseProgression/hearingFee/payHearingFeeConfirmationController.ts
  src/main/routes/features/caseProgression/trialArrangements/hearingDurationAndOtherInformationController.ts
  src/main/services/features/caseProgression/hearingDurationFormatter.ts
  src/main/services/features/caseProgression/trialArrangements/hearingDurationAndOtherInformation.ts
  src/main/services/features/claim/checkAnswers/claimSection/addEvidence.ts
  src/main/services/features/claim/checkAnswers/claimSection/addTimeLine.ts
  src/main/services/features/claim/checkAnswers/claimSection/buildClaimSection.ts
  src/main/views/features/caseProgression/trialArrangements/check-answers.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/dashboard/claim-summary.njk
  src/main/views/features/dashboard/item-content.njk
  src/test/unit/common/models/caseProgression/caseProgressionHearing.test.ts
  src/test/unit/services/features/caseProgression/hearingDurationFormatter.ts
  src/test/unit/services/features/caseProgression/trialArrangements/hearingDurationAndOtherInformation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2760

#2963 CIV-0000 Spring 6 team 4 feature branch
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/common/models/ccdResponse/ccdPayBySetDate.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/models/events/eventDto.ts
  src/main/common/utils/dateUtils.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
  src/main/routes/features/claimantResponse/claimantSuggestedPaymentDateController.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantPaymentOption.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/main/services/translation/response/convertToCCDPayBySetDate.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDPayBySetDate.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2963

#2987 CIV-5453 Session user id test
  charts/civil-citizen-ui/Chart.yaml
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/routes/guards/checkYourAnswersGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2987

#2971 CIV-11541 Bilingual check on state control
  src/main/routes/guards/claimantResponseConfirmationGuard.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/guards/claimantResponseConfirmationGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2971

#2929 CIV-11845 Court accepted claimants plan
  src/main/common/models/claim.ts
  src/main/common/utils/repaymentUtils.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/claimantResponse/signSettlmentAgreementService.ts
  src/test/unit/common/utils/repaymentUtils.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2929

#2990 CIV-12323 Fix part admit pay immediately tasklist
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2990

#2764 CIV-7829 Payment Succesful notifications
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/models/PaymentDetails.ts
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/caseProgression/hearing.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/taskList/TaskStatus.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/helpWithFees/helpWithFeesController.ts
  src/main/routes/urls.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/services/features/caseProgression/dashboardService.ts
  src/main/services/translation/convertToCUI/convertToCaseProgressionHearing.ts
  src/main/views/macro/task.njk
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2764

#2873 CIV-10294 payment success confirmation
  charts/civil-citizen-ui/values.preview.template.yaml
  package.json
  src/main/common/form/models/claim/details/claimDetails.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/payment/claimFeePaymentConfirmationController.ts
  src/main/routes/features/claim/payment/claimFeePaymentSuccessfulController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationContent.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
  src/main/services/features/claim/payment/claimFeePaymentSuccessfulSectionBuilder.ts
  src/main/views/features/claim/payment/claim-fee-payment-successful.njk
  src/test/unit/common/models/claim.test.ts
  src/test/unit/routes/features/claim/payment/claimFeePaymentSuccessfulController.test.ts
  src/test/utils/mockDraftStore.ts
  src/test/utils/mocks/civilClaimResponseApplicantIndividualMock.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, enable_keep_helm

#2991 CIV-11530 Evidence upload - contact us
  src/main/views/features/caseProgression/cancel-your-upload.njk
  src/main/views/features/caseProgression/check-answers.njk
  src/main/views/features/caseProgression/documents-uploaded.njk
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/main/views/features/caseProgression/upload-documents.njk
  src/main/views/features/caseProgression/upload-your-documents.njk
Labels: ns:civil, prd:civil, fullDeploy, add-or-update, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2991

#2827 CIV-11901 - hearing fee HwF dashboard changes
  src/main/common/models/civilClaimResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/urls.ts
  src/main/services/dashboard/getDashboardContent.ts
  src/main/services/features/caseProgression/dashboardService.ts
  src/main/services/translation/caseProgression/hearingFee/convertHearingFeeHelpWithFeesToCCD.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/test/unit/services/dashboard/getDashboardContent.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/caseProgression/hearingFee/hearingFeeService.test.ts
  src/test/unit/services/translation/caseProgression/hearingFee/convertHearingFeeHelpWithFeesToCCD.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2827

#2943 CIV-12119 back standard
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-reference.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-fee-selection.njk
  src/main/views/features/caseProgression/hearingFee/apply-help-with-fees.njk
  src/main/views/features/caseProgression/hearingFee/pay-hearing-fee-start.njk
  src/main/views/features/caseProgression/trialArrangements/check-answers.njk
  src/main/views/features/caseProgression/trialArrangements/has-anything-changed.njk
  src/main/views/features/caseProgression/trialArrangements/hearing-duration-other-info.njk
  src/main/views/features/caseProgression/trialArrangements/is-case-ready.njk
  src/main/views/features/helpWithFees/help-fees-start.njk
  src/main/views/features/response/responseDeadline/agreed-response-deadline.njk
  src/main/views/features/response/responseDeadline/new-response-deadline.njk
  src/main/views/macro/back.njk
  src/main/views/macro/contact-us-for-help-one-third.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2943

#2996 CIV-12258 Redirection to confirmation page on Payment cancelation by user
  src/main/routes/routes.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationService.ts
  src/test/unit/services/features/claim/payment/claimFeePaymentConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2996

#3019 CIV-12462 Enable CUI tests for AAT
  src/test/functionalTests/features/response/pages/defendantLipResponse/checkYourAnswers.js
  src/test/functionalTests/tests/response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/response_admitAll_tests.js
  src/test/functionalTests/tests/response_deadlineExtension_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_comp_tests.js
  src/test/functionalTests/tests/response_negativeScenarios_tests.js
  src/test/functionalTests/tests/response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/response_partAdmit_tests.js
  src/test/functionalTests/tests/response_rejectAll_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-3019

#2944 CIV-12067 Apply for help with fees content
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/public/eligibility/apply-for-help-with-fees.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2944

#2860 CIV-11746 Defendants response page content
  src/main/modules/i18n/locales/cy.json
  src/main/services/features/claimantResponse/defendantResponse/fullAdmissinionDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/fullAdmissionPayInstallmentsDefendantResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmissionAlreadyPaidDefendantsResponseContent.ts
  src/main/services/features/claimantResponse/defendantResponse/partAdmitNotPaidDefendantsResponseContent.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2860

#2893 CIV-12080 Mediation CYA
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/claimantResponseTasklistService/claimantResponseTasklistBuilder.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2893

#2849 CIV-11119 generate judgment by admission
  src/main/app/client/civilServiceClient.ts
  src/main/common/models/claimantResponse.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/common/utils/dateUtils.ts
  src/main/services/features/claimantResponse/submission/submitClaimantResponse.ts
  src/main/services/features/claimantResponse/submitClaimantResponse.ts
  src/main/services/translation/claimantResponse/ccdRequestJudgementTranslation.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/claimantResponse/convertToCCDClaimantLiPResponse.ts
  src/test/functionalTests/specClaimHelpers/fixtures/events/admitAllClaimantResponse.js
  src/test/unit/services/features/claimantResponse/submission/submitReponse.test.ts
  src/test/unit/services/features/claimantResponse/submitClaimantReponse.test.ts
  src/test/unit/services/translation/claimantResponse/ccdRequestJudgementTranslation.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2849

#2992 CIV-10295 payment unsuccessful
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/payment/claimFeePaymentUnsuccessfulController.ts
  src/main/routes/routes.ts
  src/main/services/features/claim/payment/claimFeePaymentConfirmationContent.ts
  src/main/services/features/claim/payment/claimFeePaymentSuccessfulSectionBuilder.ts
  src/main/services/features/claim/payment/claimFeePaymentUnsuccessfulSectionBuilder.ts
  src/main/views/features/claim/payment/claim-fee-payment-unsuccessful.njk
  src/test/unit/routes/features/claim/payment/claimFeePaymentUnsuccessfulController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2992

#3000 CIV-11311 Claimant Intention: Case Flags
  src/main/common/models/ccdResponse/ccdExpert.ts
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/response/convertToCCDHearingSupport.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-3000

#2866 CIV-12017 Welsh Translation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/guards/claimIssueTaskListGuard.ts
  src/main/services/features/caseProgression/bundles/bundlesService.ts
  src/main/services/features/caseProgression/documentTableBuilder.ts
  src/main/services/features/claim/taskListService.ts
  src/main/views/features/claim/interest/claimant-interest-rate.njk
  src/test/unit/services/features/caseProgression/bundles/bundlesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, destroy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-2866

#2653 CIV-11256 claimant dashboard status
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-2653
