Repository hmcts/civil-citizen-ui, pull requests merged in 2025-05, with the labels that each got.

#6028 DTSCCI-1977 pact service auth provider
  .gitignore
  Jenkinsfile_CNP
  jest.pact.config.js
  package.json
  src/test/contract/consumers/ServiceAuthProvider.test.ts
  src/test/contract/publish/publish.ts
  src/test/contract/utils.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6028

#6047 CIV-17092 Show defendant response doc for LiP vs LR
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6047

#6074 CIV-0000 fix Security Check
  yarn-audit-known-issues
Labels: fullDeploy

#6062 DTSCCI-2088 set settlement agreement option to feature toggle
  charts/civil-citizen-ui/values.aat.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/common/form/models/claimantResponse/chooseHowToProceed.ts
  src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6062

#6066 CIV-17121 - add banner for CUI ILA release
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/macro/banner.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6066

#6096 CIV-0000 - Fixed FT
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/welshLanguage.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6096

#5954 CIV-16980 Fix SOT on LIP Claim issue when Organization/Company
  src/main/common/models/ccdResponse/ccdResponse.ts
  src/main/common/models/ccdResponse/ccdStatementOfTruth.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDStatementOfTruth.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
  src/test/unit/services/translation/response/ccdTranslation.test.ts
  src/test/unit/services/translation/response/convertToCCDStatementOfTruth.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, rel:civil-citizen-ui-pr-5954

#6091 CIV-16861 Display translated interloc judgment
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6091

#6092 CIV-16867 - Delay notifications and visibility of Manual Determination document (includes show element)
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6092

#6131 CIV-0000 fix deadline dates
  src/test/unit/routes/features/response/responseDeadline/agreedResponseDeadlineController.test.ts
  src/test/unit/routes/features/response/taskListController.test.ts
  src/test/utils/mocks/civilClaimResponseFullAdmissionMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6131

#6118 DTSCCI-2069 eligibility guidance hwf
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/createClaim/pages/eligibilityCheck.js
  src/test/utils/mocks/a11y/mock-eligibility-information-about-help-with-fees.html
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6118

#6153 DTSCCI-2198 Fix for dashboard toggle fetching
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6153

#6090 CIV-16922 Query response dashboard notification
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/routes/features/queryManagement/qmViewQueriesController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/routes/features/queryManagement/qmViewQueriesController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6090

#6093 CIV-16865 Add translated settlement agreement to view
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6093

#6168 DTSCCI-2223 Implement Run Failed and Not Executed Test Files On Nightly
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  codecept.conf.js
  package.json
  src/test/e2eTests/caseProgression/caseProgressionSteps.js
  src/test/e2eTests/genralApplication/createGAApplication.js
  src/test/functionalTests/citizenFeatures/GA/pages/uploadN245Form.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/functionalTests/citizenFeatures/response/steps/uploadDocSteps.js
  src/test/functionalTests/codecept.conf.js
  src/test/functionalTests/plugins/failedAndNotExecutedTestFilesPlugin.js
  src/test/functionalTests/run-crossbrowser-tests.sh
  src/test/functionalTests/run-full-functional-tests.sh
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_orders_fast_track_tests.js
  src/test/functionalTests/tests/prod/wa/welshResponse_caseworker_request_translation_tests.js
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6168

#6191 CIV-0000 - Update package.json
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6191
