Repository hmcts/civil-citizen-ui, pull requests merged in 2025-04, with the labels that each got.

#5887 CIV-16976 - CUI Pipelines failing due to fee display issue in Gen Apps
  src/test/functionalTests/citizenFeatures/GA/steps/createGASteps.js
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5887

#5840 CIV-16699 level 2 send an update screens
  src/main/common/utils/externalURLs.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/qm/qmInformationController.ts
  src/main/views/features/generalApplication/application-type.njk
  src/test/unit/routes/features/qm/qmInformationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale

#5824 CIV-16706 lip send a message confirmation screen
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/qm/qmConfirmationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/qm/qm-confirmation-template.njk
  src/test/unit/routes/features/qm/qmConfirmationController.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-qm-confirmation.html
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5824

#5889 CIV-16786 added LipvLR e2e tests
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantLRResponse.js
  src/test/functionalTests/tests/nonprod/LipVLR_e2e_tests.js
Labels: ns:civil, prd:civil, enableHelm, fullDeploy

#5914 DTSCCI-1868 2 Add Case-Offline Tag and Turn Off Carm and LRvLIP Tests in Prod
  src/test/functionalTests/tests/common/LRvLiP_case_offline_tests.js
  src/test/functionalTests/tests/common/LiPvLiP_case_offline_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_admitAll_dateToPayOn_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_admitAll_repaymentPlan_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_dateToPayOn_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_repaymentPlan_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_rejectAll_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_company_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5914

#5855 DTSCCI-1799 remove after 4pm and additional days in calculation
  src/main/common/utils/dateUtils.ts
  src/main/common/utils/interestUtils.ts
  src/test/unit/common/utils/dateUtils.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5855

#5904 CIV-16952 Allow GA creation when GA for Welsh toggle enabled
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/routes/guards/checkYourAnswersGAGuard.ts
  src/main/routes/guards/generalAplicationGuard.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5904

#5920 CIV-16992 View the judgment screen
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5920

#5916 DTSCCI-1719 fixing phone number validation issue
  src/main/common/form/validators/phoneUKValidator.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, rel:civil-citizen-ui-pr-5916

#5974 CIV-17037 - Pre-requisite changes for work allocating to WLU
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5974

#5871 DTSCCI-1796 Judgment tab not including interest
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/test/unit/common/models/claimantResponse/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5871

#5956 CIV-16986 Show court response docs to respondent
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/routes/features/generalApplication/viewApplicationController.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/main/views/features/generalApplication/response/view-application.njk
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5956

#5945 CIV-16994 LiP able to make without notice application to set aside judgment
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/translation/generalApplication/ccdTranslation.ts
  src/test/unit/services/translation/generalApplication/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5945

#5955 CIV-16933 - Enhance flag to include English, Welsh and Bilingual variant
  src/main/common/models/ccdResponse/ccdRespondentLiPResponse.ts
  src/main/common/models/ccdResponse/ccdWelshLanguageRequirements.ts
  src/main/common/models/claimBilingualLanguagePreference.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/bilingualLangPreferenceController.ts
  src/main/routes/features/response/bilingualLangPreferenceController.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/features/response/bilingualLangPreferenceService.ts
  src/main/services/translation/convertToCUI/convertToCUIRespondentLiPResponse.ts
  src/main/services/translation/response/convertToCCDRespondentLiPResponse.ts
  src/main/views/features/claim/claim-bilingual-language-preference.njk
  src/main/views/features/response/bilingual-language-preference.njk
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/unit/services/features/response/bilingualLangPreferenceService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5955

#5990 DTSCCI-1746 improve unit tests
  .nvmrc
  jest.config.js
  jest.setup.js
  package.json
  src/main/routes/features/public/firstContact/pinController.ts
  src/test/unit/services/features/claimantResponse/getSetDatePaymentDetails.test.ts
  src/test/unit/services/features/response/checkAnswers/hearingRequirementsSection/buildHearingRequirementsSection.test.ts
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5990

#6021 CIV-17082 - CUI Pods in production are restarting frequently and on regular basis
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/routes/features/dashboard/viewDefendantInformationController.ts
  src/test/unit/routes/features/dashboard/viewDefendantInformationController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6021

#6025 test : fixing the nightly tests around the Fees Changes and the welsh…
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/availabilityForMediation/alternativeEmail.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/availabilityForMediation/nextThreeMonthsDate.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/availabilityForMediation/phoneConfirmation.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/availabilityDates.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/telephoneMediation/telephoneMediation.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/prod/wa/welshResponse_caseworker_request_translation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6025

#6017 CIV-0000 - WLU user changes
  bin/add-org-roles-to-users.sh
  charts/civil-citizen-ui/values.enableWA.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:enableWA, rel:civil-citizen-ui-pr-6017

#6033 CIV-16856 Show translated SDO in orders and notices
  src/main/common/models/document/documentType.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6033
