Repository hmcts/civil-citizen-ui, pull requests merged in 2025-09, with the labels that each got.

#6713 CIV-17660 fix accessibility
  src/main/views/features/queryManagement/qm-confirmation-template.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6713

#6709 CIV-17603 Added additional content on application details screen
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/response/viewApplicationController.ts
  src/main/views/features/generalApplication/response/view-application.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6709

#6702 DTSCCI-2639 change copy to HMCTS on moneyclaims terms and conditions page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/utils/mocks/a11y/mock-terms-and-conditions.html
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6702

#6594 DTSCCI-2384 Def Response - Content changes to payment option screen PA Additonal
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/response/admission/payment-option.njk
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6594

#6596 CIV-16912 Show doc created by user response
  src/main/common/models/document/documentType.ts
  src/main/common/models/generalApplication/applicationResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6596

#6454 CIV-17393 added changes wels functional tests
  codecept.conf.js
  src/test/config.js
  src/test/functionalTests/citizenFeatures/citizenDashboard/pages/citizenDashboard.js
  src/test/functionalTests/citizenFeatures/citizenDashboard/steps/citizenDashboard.js
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/bilingualLanguagePreference.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/confirmYourDetails/enterNameAndAddressDetails.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/welshLanguage.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/citizenFeatures/response/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/commonComponents/cButtons.js
  src/test/functionalTests/sharedData.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/uploadTranslatedDoc.js
  src/test/functionalTests/tests/mainClaimWelsh/LipVsLip_claimant_as_welsh.js
  src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation_Defendant_And_Claimant_Welsh_tests.js
  src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation_Defendant_Welsh_tests.js
  src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation__Claimant_English_document_welsh_tests.js
  src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation__defendant_English_document_welsh_tests.js
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6454

#6802 CIV-0000 - Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6802

#6805 DTSCCI-0000 renovate.json
  .github/renovate.json
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6805

#6642 CIV-17488 cui ga nro flag
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6642

#6811 CIV-17724 Update CUI 'Welsh' banner wording
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6811

#6662 DTSCCI-2371 Amendment to defendant payment deadline field
  sonar-project.properties
  src/main/common/models/claimantResponse/ccdClaimantResponse.ts
  src/main/services/features/claimantResponse/submitClaimantResponse.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationService.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/main/services/translation/response/ccdTranslation.ts
  src/main/services/translation/response/convertToCCDPayBySetDate.ts
  src/test/functionalTests/tests/mainClaimWelsh/LipVsLip_claimant_as_welsh.js
  src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation__defendant_English_document_welsh_tests.js
  src/test/unit/services/features/response/submitConfirmation/submitConfirmationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6662

#6864 DTSCCI-2369 fix for defendant response fully admits pay immediately notification not showing amount.
  src/test/functionalTests/tests/mainClaimWelsh/LipVsLip_claimant_as_welsh.js
  src/test/functionalTests/tests/mainClaimWelsh/LipvLip_UI_RejectAll_DisputeAll_Mediation__defendant_English_document_welsh_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6864
