Repository hmcts/civil-citizen-ui, pull requests merged in 2025-01, with the labels that each got.

#5259 CIV-16292 Defendant Lip Dashboard Notification-discontinued
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/common/models/document/documentType.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5259

#5022 CIV-15429 and CIV-15430
  src/test/functionalTests/citizenFeatures/GA/pages/applicationCosts.js
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/functionalTests/citizenFeatures/GA/pages/informOtherParties.js
  src/test/functionalTests/citizenFeatures/GA/pages/orderJudge.js
  src/test/functionalTests/citizenFeatures/GA/pages/requestingReason.js
  src/test/functionalTests/citizenFeatures/GA/pages/respondentAgreement.js
  src/test/functionalTests/citizenFeatures/GA/pages/respondentInformation.js
  src/test/functionalTests/citizenFeatures/GA/pages/responseCheckAndSend.js
  src/test/functionalTests/citizenFeatures/GA/pages/responseGAConfirmation.js
  src/test/functionalTests/citizenFeatures/GA/pages/responseHearingArrangementsGuidance.js
  src/test/functionalTests/citizenFeatures/GA/pages/responseUploadDocuments.js
  src/test/functionalTests/citizenFeatures/GA/pages/uploadN245Form.js
  src/test/functionalTests/citizenFeatures/GA/pages/viewApplication.js
  src/test/functionalTests/citizenFeatures/GA/steps/createGASteps.js
  src/test/functionalTests/citizenFeatures/GA/steps/respondGASteps.js
  src/test/functionalTests/citizenFeatures/response/steps/createGAAppSteps.js
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/api/testingSupport.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/makeAnOrderGA.js
  src/test/functionalTests/tests/common/LRvLip_response_rejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LIPvLiP_ClaimantWelsh_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LIPvLiP_DefendantWelsh_tests.js
  src/test/functionalTests/tests/gaWelsh/GA_LRvLiP_DefendantWelsh_tests.js
  src/test/functionalTests/tests/nonprod/LRvLiP_GA_creation_tests.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_GA_creation_tests.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsCompany.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
  src/test/functionalTests/tests/nonprod/createClaim/OrgVsSoleTrader.js
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5022

#5295 CIV-15984 added code to hide the applicant for claimant has respondet
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5295

#5311 CIV-16017 remove button response to request
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5311

#5304 CIV-16367 Zero fee journey
  src/main/services/features/generalApplication/feeDetailsService.ts
  src/test/unit/services/features/generalApplication/feeDetailsService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5304

#5313 DTSCCI-000 - Fixing CARM Part Admit Test
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/checkYourAnswers.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_Individual_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, stale, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5313

#5195 CIV-16029 Implement duplicate payment mitigation for GA
  src/main/assets/js/disable-submit.js
  src/main/modules/oidc/index.ts
  src/main/routes/features/generalApplication/payment/applicationFeePaymentConfirmationController.ts
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/test/unit/routes/features/claim/generalApplication/payment/applicationFeePaymentConfirmationController.test.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5195

#5345 DTSCCI-1364 upgrade ccd chart
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.aat.template.yaml
  charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5345

#5362 CIV-00000 Update enable Notify email
  charts/civil-citizen-ui/values.enableNotifyEmails.preview.template.yaml
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/tests/common/LiPvLiP_case_offline_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5362

#5334 CIV-16330 Amendments to Welsh translations for post court decision journeys
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/main/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.ts
  src/main/views/features/generalApplication/applicationFee/help-with-application-fee-reference.njk
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.test.ts
  src/test/unit/services/features/generalApplication/applicationFee/helpWithApplicationFeeContent.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5334

#5348 CIV-16035 added translation related to default judgment
  src/main/common/models/civilClaimResponse.ts
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/test/unit/common/models/claimantResponse/ccdTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5348

#5299 CIV-15991 Correct data not being pulled through into the Summary Cards for multiple applications
  src/main/services/features/generalApplication/viewApplication/addViewApplicationRows.ts
  src/test/unit/services/features/generalApplication/viewApplication/addViewApplicationRows.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5299

#5363 CIV-0000 Move cp tests to master and nightly
  src/test/functionalTests/tests/common/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_RejectAll_DisputeAll_Intention_UI_tests.js
  src/test/functionalTests/tests/common/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/common/OCMC_tests.js
  src/test/functionalTests/tests/common/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/common/cp_upload_evidence_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_orders_fast_small_claims.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_orders_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_trial_arrangements_tests_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/nonprod/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/nonprod/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_upload_evidence_trial_arrangements_fast_track_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_bundles_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_bundles_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_hearing_fee_tests_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_orders_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_orders_small_claims.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_trial_arrangements_tests_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_upload_evidence_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_bundles_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_case_struck_out_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/prod/cp_upload_evidence_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5363

#5237 CIV-15646 - Add court officer order to view orders and notices
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/unit/services/translation/convertToCUI/convertToCUICaseProgression.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5237

#5364 CIV-15626 add aria labels to documents
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/views/features/generalApplication/view-applications.njk
  src/main/views/macro/create-table-documents.njk
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5364

#5349 CIV-15966 - Update claimant LiP 'View info about the defendant' screen with defendant LR details.
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/dashboard/viewDefendantInformationController.ts
  src/main/services/features/response/contactThem/contactThemService.ts
  src/main/views/features/dashboard/contact-them-new.njk
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
  src/test/unit/routes/features/dashboard/viewDefendantInformationController.test.ts
  src/test/unit/services/features/response/contactThem/contactThemService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5349

#5384 CIV-16391 added code for correct notification
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5384

#5386 CIV-16251 - GA - Fix colour of the link 'View application'
  src/main/views/macro/generalApplication/application-summary.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5397 CIV-00000 Update ccbc url to CNBC
  src/main/common/utils/externalURLs.ts
  src/main/views/external-urls.njk
  src/test/utils/mocks/a11y/mock-first-contact-start.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5397

#5395 CIV-16405 ammend the welsh translations
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.ts
  src/test/unit/routes/features/claim/generalApplication/applicationFee/helpWithApplicationFeeReferenceController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5409 CIV-0000 fix nightly tests
  src/test/functionalTests/citizenFeatures/caseProgression/pages/viewBundle.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_orders_fast_track_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_orders_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch

#5336 CIV-16333 Welsh translation for response GA
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/main/views/features/generalApplication/unavailable-dates-hearing.njk
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
  src/test/unit/services/translation/convertToCUI/cuiTranslation.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5336

#5406 CIV-16006 GA Lip - Back button is not working on Upload additional document page
  src/main/routes/features/generalApplication/additionalDocuments/uploadAdditionalDocumentsController.ts
  src/main/routes/features/generalApplication/directionsOrderUpload/uploadDocumentsDirectionsOrderController.ts
  src/test/unit/routes/features/claim/generalApplication/additionalDocuments/uploadAdditionalDocumentsController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5365 CIV-16007 Implement toe/evidence links
  src/main/common/mappers/documentViewMapper.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claimantResponse/reviewDefendantsResponseController.ts
  src/main/services/features/caseProgression/SystemDocumentInfoExtractor.ts
  src/main/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.ts
  src/main/services/features/claimantResponse/defendantResponse/fullDisputeDefendantsResponseContent.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/common/common/mappers/documentViewMapper.test.ts
  src/test/unit/services/features/caseProgression/SystemDocumentInfoExtractor.test.ts
  src/test/unit/services/features/claimantResponse/defendantResponse/defendantResponseSummaryService.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/caseProgression/latestUpdateContentBuilderCaseProgression.test.ts
  src/test/unit/services/features/dashboard/claimSummary/latestUpdate/latestUpdateContentBuilder.test.ts
  src/test/utils/mocks/SystemGeneratedCaseDocumentsMock.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5365

#5413 CIV-16433 Translate "Unavailable hearing dates"
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5302 CIV-15750 Add JBA doc links to View orders and notices
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5302

#5375 DTSCCI-1402 Adjustment to the HWF guidance page.
  src/main/modules/i18n/locales/en.json
  src/test/functionalTests/citizenFeatures/createClaim/pages/eligibilityCheck.js
  src/test/utils/mocks/a11y/mock-eligibility-information-about-help-with-fees.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5169 DTSCCI-1224 CUI CNBC Webchat
  config/custom-environment-variables.yaml
  config/default.yaml
  src/main/modules/helmet/index.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/nunjucks/index.ts
  src/main/modules/oidc/index.ts
  src/main/routes/features/contact/contactCNBCController.ts
  src/main/routes/features/contact/contactMediationController.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/views/features/public/contact-service.njk
  src/test/unit/routes/features/contact/contactCNBCController.test.ts
  src/test/unit/routes/features/contact/contactMediationController.test.ts
  src/test/utils/mocks/a11y/mock-contact-cnbc.html
  src/test/utils/mocks/a11y/mock-contact-mediation.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5169

#5405 CIV-16271 updated the content in english
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/generalApplication/additionalDocuments/check-answers.njk
  src/main/views/features/generalApplication/additionalInfoUpload/checkYourAnswer.njk
  src/main/views/features/generalApplication/check-answers.njk
  src/main/views/features/generalApplication/directionsOrderUpload/check-answers.njk
  src/main/views/features/generalApplication/response/check-answers.njk
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/functionalTests/citizenFeatures/GA/pages/responseCheckAndSend.js
  src/test/unit/routes/features/claim/generalApplication/response/checkAnswersResponseController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch

#5403 DTSCCI-1440 Remove character limit for the Claim Summary and Defence Summary
  src/main/common/form/models/defence.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5454 CIV-16464 Added GALip e2e tests
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/makeAnOrderGA.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm

#5491 CIV-0000 Remove banner
  src/main/views/macro/banner.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5491

#5488 CIV-16280 - Revoke defendant LiP access to the claim
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/public/firstContact/pinController.ts
  src/main/views/features/public/firstContact/pin.njk
  src/test/unit/routes/features/public/firstContact/pinController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5488

#5492 DTSCCI-1494 Amend the interest from page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claim/interest/claimant-interest-from.njk
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
  src/test/utils/mocks/a11y/mock-claim-interest-date.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5492

#5502 CIV-0000 - Update values.enableWA.preview.template.yaml
  charts/civil-citizen-ui/values.enableWA.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5502

#5453 CIV-16444 add your payment is in progress screen
  src/main/services/features/generalApplication/fee/helpWithFeeService.ts
  src/test/unit/services/features/generalApplication/fee/helpWithFeeService.test.ts
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5453

#5472 CIV-15819 remove ignored urls
  src/test/a11y/ignored-urls.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-1720536653906339-provide-more-information.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-response-general-application-summary.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-general-application-submit-general-application-confirmation.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5472
