Repository hmcts/civil-citizen-ui, pull requests merged in 2025-07, with the labels that each got.

#6289 CIV-17322 - CUI Welsh - feature toggle changes
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
  src/main/routes/features/claim/bilingualLangPreferenceController.ts
  src/main/routes/features/response/bilingualLangPreferenceController.ts
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/views/features/claim/claim-bilingual-language-preference.njk
  src/main/views/features/response/bilingual-language-preference.njk
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6289

#6240 CIV-17259 undefined claimant phone
  src/main/app.ts
  src/main/common/form/models/mediation/ClaimantTelephone.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/claim/checkAnswersController.ts
  src/main/routes/features/mediation/claimantTelephoneMediationController.ts
  src/main/routes/guards/mediationClaimantPhoneRedirectionGuard.ts
  src/main/routes/routes.ts
  src/main/routes/urls.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/test/unit/routes/features/claim/checkAnswersController.test.ts
  src/test/unit/routes/features/mediation/claimantTelephoneMediationController.test.ts
  src/test/unit/routes/guards/mediationClaimantPhoneRedirectionGuard.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-mediation-claimant-phone.html
Labels: ns:civil, prd:civil, fullDeploy, runFailedTestFiles, rel:civil-citizen-ui-pr-6240

#6363 CIV-16916 - Re-trigger application flow after translation uploaded (Application summary documents) - enable state change
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6363

#6336 CIV-17210 Implement error message for document awaiting translation
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/features/dashboard/dashboard.njk
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, runFailedTestFiles, rel:civil-citizen-ui-pr-6336

#6291 CIV-17180 claim status code changes
  src/main/common/models/dashboard/dashboardItem.ts
Labels: ns:civil, prd:civil, fullDeploy, runFailedTestFiles, rel:civil-citizen-ui-pr-6291

#6421 DTSCCI-1888 notification retry
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6421

#6278 DTSCCI-1197 fix link format
  src/main/routes/features/public/eligibility/tryNewServiceController.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/admissionSubmitConfirmationContent.ts
  src/main/services/features/response/submitConfirmation/submitConfirmationBuilder/partAdmissionConfirmationContent.ts
  src/main/views/features/caseProgression/typeOfDocuments.njk
  src/main/views/features/claim/task-list.njk
  src/main/views/features/claimantResponse/ccj/paid-amount.njk
  src/main/views/features/claimantResponse/ccj/repayment-plan-summary-claimant.njk
  src/main/views/features/claimantResponse/ccj/repayment-plan-summary.njk
  src/main/views/features/claimantResponse/claimant-response-task-list.njk
  src/main/views/features/claimantResponse/review-defendants-response.njk
  src/main/views/features/dashboard/contact-them-new.njk
  src/main/views/features/dashboard/contact-them.njk
  src/main/views/features/dashboard/view-response-to-claim.njk
  src/main/views/features/mediation/mediation-disagreement.njk
  src/main/views/features/public/eligibility/claim-against-government.njk
  src/main/views/features/public/firstContact/access-denied.njk
  src/main/views/features/public/firstContact/claim-summary.njk
  src/main/views/features/public/firstContact/pin.njk
  src/main/views/features/response/ageEligibility/under-18.njk
  src/main/views/features/response/claimDetails/claim-details.njk
  src/main/views/features/response/financialDetails/financial-details.njk
  src/main/views/features/response/task-list.njk
  src/main/views/govukTemplate.njk
  src/main/views/macro/contact-us-for-help.njk
  src/main/views/macro/external-link.njk
  src/main/views/macro/new-line.njk
  src/main/views/macro/task.njk
  src/main/views/not-found.njk
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-6278

#6491 CIV-0000 fix security check
  yarn-audit-known-issues
Labels: fullDeploy

#6415 CIV-16897 Show label for translated dismissal order
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-6415

#6456 CIV-17443 Fix 404 issue
  src/main/routes/urls.ts
  src/main/services/commons/generalApplicationHelper.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/routes/features/claim/generalApplication/submitApplicationOfflineController.test.ts
  src/test/unit/services/commons/generalApplicationHelper.test.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/utils/mocks/a11y/mock-case-1645882162449409-submit-application-offline.html
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6456

#6333 CIV-17330 QM LIP Follow up tests
  codecept.conf.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/dashboard.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/getUpdateFromCourt.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/manageHearing.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/qmStart.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/sendUpdateToCourt.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/solveProblem.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/viewQuery.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/saucelabs.conf.js
  src/test/functionalTests/specClaimHelpers/api/apiRequest.js
  src/test/functionalTests/specClaimHelpers/api/steps_noc.js
  src/test/functionalTests/specClaimHelpers/api/steps_qm.js
  src/test/functionalTests/specClaimHelpers/fixtures/queryMessages.js
  src/test/functionalTests/specClaimHelpers/fixtures/queryTypes.js
  src/test/functionalTests/tests/nonprod/qm_Hearing_LiPvLiP_followUp_tests.js
  src/test/functionalTests/tests/nonprod/qm_Hearing_LiPvLiP_tests.js
  src/test/functionalTests/tests/nonprod/qm__LiPvLiP_ApplyToCourt_tests.js
  src/test/functionalTests/tests/nonprod/qm_noc_tests.js
  src/test/functionalTests/tests/nonprod/qm_nonHearing_LiPvLiP_tests.js
Labels: ns:civil, prd:civil, fullDeploy, Testing, rel:civil-citizen-ui-pr-6333

#6433 CIV-16906 - Translation of GA hearing order document - pause and unpause
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/viewApplicationService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-6433
