Repository hmcts/civil-citizen-ui, pull requests merged in 2025-10, with the labels that each got.

#6873 DTSCCI-0000 Removing fullDeploy label requirement
  .github/renovate.json
  Jenkinsfile_CNP
  README.md
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-6873

#6874 Update main.yml
  .github/workflows/main.yml
Labels: ns:civil, prd:civil, rel:civil-citizen-ui-pr-6874

#6880 update yarn
  .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
  .yarn/releases/yarn-3.5.0.cjs
  .yarn/releases/yarn-4.10.3.cjs
  .yarnrc.yml
  package.json
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantLRResponse.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantResponseCarm.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:civil, prd:civil, enable_keep_helm, rel:civil-citizen-ui-pr-6880
