Repository hmcts/civil-citizen-ui, pull requests merged in 2025-08, with the labels that each got.

#6455 CIV-16907 Pause and UnPause of GA during translation of hearing notice (GA)
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/main/services/features/generalApplication/viewApplication/viewApplicationService.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6455

#6553 Test fixes
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/whyDoYouDisagree/whyDoYouDisagreeTheClaimAmount.js
  src/test/functionalTests/tests/common/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_negativeScenarios_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_dateToPayOn_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_fastTrack_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_repaymentPlan_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_rejectAll_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_company_small_claims_tests.js
  src/test/functionalTests/tests/prod/minti_LiPvLiP_tests.js
  src/test/functionalTests/tests/prod/wa/welshResponse_caseworker_request_translation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6553

#6581 More test fixes
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/confirmation.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/tests/common/LRvLip_response_partAdmit_HaventPaid_immediatePay_tests.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_Individual_small_claims_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6581

#6557 CIV-17522 UI + API Automation Testing - LIP Close and WLU scenarios
  Jenkinsfile_CNP
  bin/add-org-roles-to-users.sh
  src/test/config.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/dashboard.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/queryManagement/viewQuery.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps_noc.js
  src/test/functionalTests/specClaimHelpers/api/steps_qm.js
  src/test/functionalTests/specClaimHelpers/fixtures/queryMessages.js
  src/test/functionalTests/tests/nonprod/qm_Hearing_LiPvLiP_followUp_tests.js
  src/test/functionalTests/tests/nonprod/qm_noc_tests.js
  src/test/functionalTests/tests/nonprod/qm_wlu_scenarios_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6557

#6591 DTSCCI-1746 increase unit test workers
  jest.config.js
  package.json
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6591

#6618 CIV-17479 GA EA remains in EA after NRO changes for main claim
  src/main/services/dashboard/dashboardService.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6618

#6552 DTSCCI-2457 Fix draftClaim SameRateInterestSelection NPE issue
  src/main/common/utils/interestUtils.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6552

#6602 CIV-17548 - WLU + Judge unable to see court officer order + translated version (Adding reverted changes with the fix)
  src/main/common/models/caseProgression/caseProgression.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/translation/convertToCUI/convertToCUICaseProgression.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:enableWA, enable_keep_helm, rel:civil-citizen-ui-pr-6602

#6484 CIV-16924 Directions Order - re-trigger notifications after document translation upload
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/generalApplication/viewApplication/responseFromCourtService.ts
  src/test/unit/services/features/generalApplication/viewApplication/responseFromCourtService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-6484

#6663 CIV-17625 CCJ Retrieve case data from CCD
  src/main/routes/features/claimantResponse/ccj/ccjPaymentOptionController.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:enableWA, rel:civil-citizen-ui-pr-6663
