Repository hmcts/civil-citizen-ui, pull requests merged in 2025-02, with the labels that each got.

#4990 DTSCCI-1136 upgrade terraform version inline with min version
  infrastructure/.terraform-version
  infrastructure/_state.tf
  infrastructure/_variables.tf
  infrastructure/app-insights.tf
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:civil-citizen-ui-pr-4990

#5523 CIV-16467 added GA e2e tests
  src/test/functionalTests/citizenFeatures/GA/pages/applyHelpFeeSelection.js
  src/test/functionalTests/citizenFeatures/GA/pages/paymentGAConfirmation.js
  src/test/functionalTests/citizenFeatures/GA/steps/createGASteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/makeAnOrderGA.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5523

#5516 CIV-0000 Add tribunal caseworker roles
  bin/add-org-roles-to-users.sh
  bin/add-roles.sh
  package.json
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5516

#5551 CIV-0000 removing playwright service access changes
  package.json
  src/test/functionalTests/codecept.conf.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5551

#5458 CIV-15986 Implement history for GA back button
  src/main/app.ts
  src/main/routes/features/generalApplication/addAnotherApplicationController.ts
  src/main/routes/features/generalApplication/additionalDocuments/checkAnswersController.ts
  src/main/routes/features/generalApplication/additionalDocuments/uploadAdditionalDocumentsController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/checkAnswerController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/respondController.ts
  src/main/routes/features/generalApplication/additionalInfoUpload/uploadDocumentsForRequestMoreInfoController.ts
  src/main/routes/features/generalApplication/agreementFromOtherPartyController.ts
  src/main/routes/features/generalApplication/applicationCostsController.ts
  src/main/routes/features/generalApplication/applicationTypeController.ts
  src/main/routes/features/generalApplication/checkAnswersController.ts
  src/main/routes/features/generalApplication/claimApplicationCostController.ts
  src/main/routes/features/generalApplication/directionsOrderUpload/checkAnswerController.ts
  src/main/routes/features/generalApplication/directionsOrderUpload/uploadDocumentsDirectionsOrderController.ts
  src/main/routes/features/generalApplication/hearingArrangementController.ts
  src/main/routes/features/generalApplication/hearingArrangementsGuidanceController.ts
  src/main/routes/features/generalApplication/hearingContactDetailsController.ts
  src/main/routes/features/generalApplication/hearingSupportController.ts
  src/main/routes/features/generalApplication/informOtherPartiesController.ts
  src/main/routes/features/generalApplication/orderJudgeController.ts
  src/main/routes/features/generalApplication/payingForApplicationController.ts
  src/main/routes/features/generalApplication/requestingReasonController.ts
  src/main/routes/features/generalApplication/respondentAgreeToOrderController.ts
  src/main/routes/features/generalApplication/response/checkAnswersResponseController.ts
  src/main/routes/features/generalApplication/response/hearingArrangementResponseController.ts
  src/main/routes/features/generalApplication/response/hearingContactDetailsResponseController.ts
  src/main/routes/features/generalApplication/response/hearingSupportResponseController.ts
  src/main/routes/features/generalApplication/response/respondentAgreementController.ts
  src/main/routes/features/generalApplication/response/respondentHearingPreferenceController.ts
  src/main/routes/features/generalApplication/response/respondentUploadEvidenceDocmentsController.ts
  src/main/routes/features/generalApplication/response/respondentWantToUploadDocumentsController.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesControllerResponseConfirmation.ts
  src/main/routes/features/generalApplication/response/unavailableHearingDatesResponseController.ts
  src/main/routes/features/generalApplication/unavailableHearingDatesController.ts
  src/main/routes/features/generalApplication/unavailableHearingDatesControllerConfirmation.ts
  src/main/routes/features/generalApplication/uploadEvidenceDocumentForApplication.ts
  src/main/routes/features/generalApplication/uploadN245FormController.ts
  src/main/routes/features/generalApplication/wantToUploadDocuments.ts
  src/main/routes/features/generalApplication/writtenRepresentationDocs/checkAnswerController.ts
  src/main/routes/features/generalApplication/writtenRepresentationDocs/respondToWrittenRepController.ts
  src/main/routes/features/generalApplication/writtenRepresentationDocs/uplodWrittenRepresentationDocsController.ts
  src/main/routes/guards/GaTrackHistory.ts
  src/main/routes/guards/generalApplication/addAnotherApplicationGuard.ts
  src/main/routes/guards/generalApplication/agreementFromOtherPartyGuard.ts
  src/main/routes/guards/generalApplication/informOtherPartiesGuard.ts
  src/main/routes/guards/generalApplication/orderJudgeGuard.ts
  src/main/routes/guards/generalApplication/requestReasonControllerGuard.ts
  src/main/services/features/generalApplication/generalApplicationService.ts
  src/test/unit/routes/features/claim/generalApplication/orderJudgeController.test.ts
  src/test/unit/routes/features/claim/generalApplication/requestingReasonController.test.ts
  src/test/unit/routes/features/claim/generalApplication/uploadEvidenceDocumentForApplication.test.ts
  src/test/unit/routes/guards/generalApplication/addAnotherApplicationGuard.test.ts
  src/test/unit/routes/guards/generalApplication/agreementFromOtherPartyGuard.test.ts
  src/test/unit/routes/guards/generalApplication/informOtherPartiesGuard.test.ts
  src/test/unit/routes/guards/generalApplication/orderJudgeGuard.test.ts
  src/test/unit/routes/guards/generalApplication/requestingReasonControllerGuard.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5458

#5531 CIV-15722 refresh session token
  src/main/app.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5531

#5366 CIV-16254 Accessible response docs
  src/main/common/mappers/documentViewMapper.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5366

#5481 CIV-16494 Fix month error on hint text
  charts/civil-citizen-ui/values.enableFlexiDb.preview.template.yaml
  src/main/views/features/claimantResponse/paidInFull/date-paid.njk
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, aat/add-or-update, prod/add-or-update, rel:civil-citizen-ui-pr-5481

#5460 CIV-16427 Default Judgment document link on LIP dashboard
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
  src/test/utils/mockClaim.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5460

#5497 DTSCCI-1486 fix timeline and evidence for full defence.
  src/main/common/models/evidence/evidenceType.ts
  src/main/services/features/response/checkAnswers/responseSection/buildYourResponseDetailsSection.ts
  src/test/unit/services/features/response/checkAnswers/responseDetails/buildYourResponseDetailsSection.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5497

#5532 CIV-16466 GA e2e tests
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/makeAnOrderGA.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5532

#5569 DTSCCI-1370 DTSCCI-1195 Update email address
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.yaml
  config/default.yaml
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/claimantResponse/claimantResponseConfirmation/confirmationContentBuilder/financialDetailsBuilder.ts
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-request-more-time.html
  src/test/utils/mocks/a11y/mock-case-1645882162449409-response-response-deadline-options.html
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5569

#5439 DTSCCI-1241 update phone number not empty validation check
  src/main/common/form/validators/mandatoryValidatorForParty.ts
  src/test/unit/routes/features/claim/yourDetails/claimantPhoneController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, aat/add-or-update, prod/add-or-update, rel:civil-citizen-ui-pr-5439

#5421 CIV-16353 fix hearing duration AHN
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/caseProgression/hearingDurationFormatter.ts
  src/main/services/features/caseProgression/trialArrangements/hearingDurationAndOtherInformation.ts
  src/main/services/translation/convertToCUI/convertToCaseProgressionHearing.ts
  src/test/unit/common/models/caseProgression/caseProgressionHearing.test.ts
  src/test/unit/services/features/caseProgression/hearingDurationFormatter.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, rel:civil-citizen-ui-pr-5421

#5573 CIV-15442 CIV16468 ga tests
  src/test/functionalTests/citizenFeatures/GA/pages/checkAndSend.js
  src/test/functionalTests/citizenFeatures/GA/steps/createGASteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/makeAnOrderGA.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_GA_creation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, enable_keep_helm, rel:civil-citizen-ui-pr-5573

#5485 CIV-16242 hearing document welsh
  src/main/common/models/caseProgression/caseProgressionHearing.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/routes/features/dashboard/notificationRedirectController.ts
  src/main/services/features/caseProgression/hearing/hearingService.ts
  src/main/services/translation/convertToCUI/convertToCaseProgressionHearing.ts
  src/test/unit/routes/features/dashboard/notificationRedirectController.test.ts
  src/test/unit/services/features/caseProgression/hearing/hearingService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, pr-values:elasticsearch, aat/add-or-update, prod/add-or-update, rel:civil-citizen-ui-pr-5485

#5584 DTSCCI-1444 cdam
  Jenkinsfile_CNP
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  charts/civil-citizen-ui/values.yaml
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5584

#5537 DTSCCI-1496 calculate claim interest endpoint
  charts/civil-citizen-ui/values.elasticsearch.preview.template.yaml
  charts/civil-citizen-ui/values.enableFlexiDb.preview.template.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
  src/main/app/client/civilServiceClient.ts
  src/main/app/client/civilServiceUrls.ts
  src/main/common/models/claim.ts
  src/main/common/utils/interestUtils.ts
  src/main/modules/claimDetailsService.ts
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/routes/features/claim/totalAmountController.ts
  src/main/routes/features/claimantResponse/ccj/ccjCheckAnswersController.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.ts
  src/main/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.ts
  src/main/routes/features/claimantResponse/claimantResponseCheckAnswersController.ts
  src/main/routes/features/public/firstContact/claimSummaryController.ts
  src/main/routes/features/response/claimDetails/claimDetailsController.ts
  src/main/services/dashboard/dashboardInterpolationService.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/features/claim/checkAnswers/financialSection/buildPaymentSection.ts
  src/main/services/features/claimantResponse/ccj/ccjCheckAnswersService.ts
  src/main/services/features/claimantResponse/ccj/judgmentAmountSummaryService.ts
  src/main/services/features/claimantResponse/checkAnswers/checkAnswersService.ts
  src/main/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.ts
  src/main/services/features/claimantResponse/submission/submitClaimantResponse.ts
  src/main/services/features/claimantResponse/submitClaimantResponse.ts
  src/main/services/translation/claim/ccdTranslation.ts
  src/main/services/translation/claimantResponse/ccdRequestJudgementTranslation.ts
  src/main/services/translation/claimantResponse/ccdTranslation.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
  src/test/functionalTests/citizenFeatures/createClaim/steps/createLipvLipClaimSteps.js
  src/test/functionalTests/tests/nonprod/createClaim/CompanyVsOrg.js
  src/test/functionalTests/tests/nonprod/createClaim/IndividualvsIndividual.js
  src/test/unit/app/client/civilServiceClient.test.ts
  src/test/unit/common/models/claimantResponse/ccdTranslation.test.ts
  src/test/unit/common/utils/interestUtils.test.ts
  src/test/unit/modules/claimDetailsService.test.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
  src/test/unit/routes/features/claim/totalAmountController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/judgmentAmountSummaryController.test.ts
  src/test/unit/routes/features/claimantResponse/ccj/judgmentAmountSummaryExtendedController.test.ts
  src/test/unit/routes/features/public/firstContact/claimSummaryController.test.ts
  src/test/unit/routes/features/response/claimDetails/claimDetailsController.test.ts
  src/test/unit/services/features/claimantResponse/ccj/judgmentAmountSummaryService.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswers/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/checkAnswersService.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildCourtDecisionDetailsSection.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildSettlementAgreementSection.test.ts
  src/test/unit/services/features/claimantResponse/responseSection/buildYourResponseSection.test.ts
  src/test/unit/services/features/dashboard/dashboardInterpolationService.test.ts
  src/test/unit/services/translation/claim/ccdTransaltion.test.ts
  src/test/unit/services/translation/claimantResponse/ccdRequestJudgementTranslation.test.ts
  src/test/utils/mocks/civilClaimResponseDocumentUploadedMock.json
  src/test/utils/mocks/civilClaimResponseFastTrackMock.json
  src/test/utils/mocks/civilClaimResponseMock.json
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5537

#5613 CIV-16647 fix pa11y issue with WCAG2AA.Principle1.Guideline1_1.1_1_1.H30.2
  src/test/utils/mocks/a11y/mock-contact-cnbc.html
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5613

#5627 DTSCCI-1499 Amend the How do you want to claim interest page
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claim/interest/interest-type.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5627

#5609 CIV-16594 take case offline
  src/main/services/features/generalApplication/generalApplicationService.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5609

#5581 CIV-16469 E2E GA Tests
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/makeAnOrderGA.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5581

#5192 DTSCCI-1154 checks business process before payment
  src/main/common/models/businessProcess.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/modules/utilityService.ts
  src/main/routes/features/claim/payment/claimFeeBreakDownController.ts
  src/main/views/features/claim/payment/claim-fee-breakdown.njk
  src/test/unit/common/models/businessProcess.test.ts
  src/test/unit/common/models/claim.test.ts
  src/test/unit/modules/utilityService.test.ts
  src/test/unit/routes/features/claim/payment/claimFeeBreakDownController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5192

#5587 CIV-16627 16634 DQ Expert Details Field Validations And Support Dropdown Error
  src/main/common/models/directionsQuestionnaire/experts/expertDetails.ts
  src/main/routes/features/directionsQuestionnaire/experts/expertDetailsController.ts
  src/main/services/features/directionsQuestionnaire/supportRequiredService.ts
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertDetailsController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5587

#5656 DTSCCI-1694 update deprecated charts
  charts/civil-citizen-ui/Chart.yaml
  package.json
  yarn.lock
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5656
