Repository hmcts/civil-citizen-ui, pull requests merged in 2025-03, with the labels that each got.

#5693 DTSCCI-1695 implement validation to stop users from selecting settlement agreement
  src/main/common/form/models/claimantResponse/chooseHowToProceed.ts
  src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayByInstallments_claimantResponse.js
  src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayBySetDate_claimantResponse.js
  src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayByInstallments_claimantResponse.js
  src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayBySetDate_claimantResponse.js
  src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5693

#5699 DTSCCI-1695 skip tests which select sign a settlement agreement as its temporarily unavailable
  src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayByInstallments_claimantResponse.js
  src/test/e2eTests/tests/claimantResponse/fullAdmit/fullAdmit_defendantPayBySetDate_claimantResponse.js
  src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayByInstallments_claimantResponse.js
  src/test/e2eTests/tests/claimantResponse/partAdmit/partAdmit_defendantPayBySetDate_claimantResponse.js
  src/test/functionalTests/tests/common/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5699

#5624 CIV-16652 DQ Expert Details Make First and Last Name Mandatory
  src/main/common/models/directionsQuestionnaire/experts/expertDetails.ts
  src/main/common/models/directionsQuestionnaire/witnesses/otherWitnessItems.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/macro/expert-details-row.njk
  src/test/unit/routes/features/directionsQuestionnaire/experts/expertDetailsController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5624

#5642 CIV-16607 amend welsh
  src/main/modules/i18n/locales/cy.json
Labels: ns:civil, prd:civil, fullDeploy, stale, rel:civil-citizen-ui-pr-5642

#5685 DTSCCI-1714 implementing requested cnbc changes
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/contact/contactCNBCController.ts
  src/main/routes/features/contact/contactMediationController.ts
  src/main/views/features/public/contact-cnbc.njk
  src/main/views/features/public/contact-mediation.njk
  src/test/utils/mocks/a11y/mock-contact-cnbc.html
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5685

#5688 CIV-16009 New text for docs being translated
  charts/civil-citizen-ui/values.enableWA.preview.template.yaml
  src/main/common/models/dashboard/dashboardItem.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/test/unit/common/models/dashboard/dashboardItem.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5688

#5682 CIV-16685 added feature toggle for query management cui
  src/main/app/auth/launchdarkly/launchDarklyClient.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5682

#5709 CIV-16008 Show DQ if bilingual and LiPvLR
  src/main/services/features/dashboard/ordersAndNoticesService.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5709

#5717 CIV-16567 added code to allow application for bilingual defendant
  src/main/routes/features/generalApplication/applicationSummaryController.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/services/features/generalApplication/response/generalApplicationResponseService.ts
  src/test/unit/services/features/caseProgression/dashboardService.test.ts
  src/test/unit/services/features/generalApplication/response/generalApplicationResponseService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5717

#5746 CIV-16623 noc e2e
  src/test/functionalTests/lrFeatures/noc/steps/nocSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/dashboardNotificationConstants.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantLRResponse.js
  src/test/functionalTests/tests/nonprod/LipVLR_e2e_tests.js
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5746

#5645 DTSCCI-1484 Amendment to the counter claim journey
  src/main/common/utils/taskList/taskListBuilder.ts
  src/main/services/features/common/taskListService.ts
  src/main/views/features/response/task-list.njk
  src/test/unit/services/features/response/taskListService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5645

#5769 DTSCCI-0000 Suppress Security Check
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5769

#5773 DTSCCI-1074 Add new doc removal role
  bin/add-roles.sh
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5773

#5778 DTSCCI-1781 test redoing the pr for the purpose of getting the fix in
  src/test/functionalTests/citizenFeatures/common/govPay.js
  src/test/functionalTests/specClaimHelpers/e2e/dashboardHelper.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5778

#5756 CIV-16770 Paid in full date validation against date of the judgment
  src/main/common/form/models/judmentOnline/confirmYouHaveBeenPaidForm.ts
  src/main/common/form/validators/dateNotBeforeReferenceDate.ts
  src/main/common/models/civilClaimResponse.ts
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.ts
  src/main/services/translation/convertToCUI/cuiTranslation.ts
  src/test/unit/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.test.ts
  src/test/utils/errorMessageTestConstants.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5756

#5671 CIV-16255 - fix the issue when is full defence
  src/main/common/models/claim.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5671

#5809 CIV-1781 test 1
  package.json
  src/test/functionalTests/citizenFeatures/createClaim/pages/createClaim.js
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5809

#5806 DTSCCI-1779 Make Accessibility Tests Run on Multiple Threads
  Jenkinsfile_CNP
  package.json
  src/test/a11y/a11y.mock-test.ts
  src/test/a11y/run-parallel-a11y-tests.sh
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5806

#5785 DTSCCI-1372 repayment amount validation issue
  src/main/services/translation/claim/moneyConversation.ts
  src/main/services/translation/claimantResponse/claimantResponseCCDTranslation.ts
  src/test/unit/services/translation/claim/moneyConversation.test.ts
  src/test/unit/services/translation/claimantResponse/ccdTransaltion.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5785

#5744 DTSCCI-1695 add content and error message
  src/main/common/form/models/claimantResponse/chooseHowToProceed.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/views/features/claimantResponse/choose-how-to-proceed.njk
  src/test/unit/routes/features/claimantResponse/chooseHowToProceedController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5744

#5837 CIV-16909 remove opens a new screen GA.
  src/main/common/models/dashboard/iWantToLinks.ts
  src/main/services/dashboard/dashboardService.ts
  src/main/views/macro/external-link.njk
  src/main/views/macro/support-links.njk
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5837

#5853 CIV-16786 Added LipvLR tests and enable GALip tests in Prod
  src/test/functionalTests/specClaimHelpers/fixtures/events/defendantLRResponse.js
  src/test/functionalTests/tests/common/LRvLip_response_rejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/nonprod/LRvLiP_GA_creation_tests.js
  src/test/functionalTests/tests/nonprod/LiPvLiP_GA_e2e_tests.js
  src/test/functionalTests/tests/nonprod/LipVLR_e2e_tests.js
  src/test/functionalTests/tests/nonprod/LipvLip_GA_creation_tests.js
  src/test/functionalTests/tests/prod/LRvLiP_GA_creation_tests.js
  src/test/functionalTests/tests/prod/LiPvLiP_GA_e2e_tests.js
  src/test/functionalTests/tests/prod/LipvLip_GA_creation_tests.js
  src/test/functionalTests/tests/prod/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5853

#5829 CIV-16844 - check for future date
  src/main/common/form/models/judmentOnline/confirmYouHaveBeenPaidForm.ts
  src/test/unit/routes/features/judgmentOnline/confirmYouHaveBeenPaidController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5829

#5852 CIV-0000 Update tests to use carm
  src/test/functionalTests/citizenFeatures/caseProgression/pages/uploadEvidence/checkYourAnswers.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/uploadEvidence/uploadYourDocument.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/uploadEvidence/uploadYourDocumentsIntroduction.js
  src/test/functionalTests/citizenFeatures/caseProgression/pages/viewDocuments.js
  src/test/functionalTests/citizenFeatures/caseProgression/steps/caseProgressionSteps.js
  src/test/functionalTests/citizenFeatures/common/contactUs.js
  src/test/functionalTests/citizenFeatures/createClaim/pages/responseToDefence.js
  src/test/functionalTests/citizenFeatures/response/pages/claimantLiPResponse/judgment.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/availabilityForMediation/phoneConfirmation.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/confirmYourDetails/enterContactNumberDetails.js
  src/test/functionalTests/citizenFeatures/response/pages/defendantLipResponse/defendantDQ/welshLanguage.js
  src/test/functionalTests/citizenFeatures/response/steps/lipDefendantResponseSteps.js
  src/test/functionalTests/citizenFeatures/response/steps/responseToDefenceLipvLipSteps.js
  src/test/functionalTests/specClaimHelpers/api/steps.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/createLiPClaim.js
  src/test/functionalTests/specClaimHelpers/fixtures/events/mediation.js
  src/test/functionalTests/tests/common/LRvLiP_case_offline_tests.js
  src/test/functionalTests/tests/common/LRvLip_response_partAdmit_HaventPaid_immediatePay_tests.js
  src/test/functionalTests/tests/common/LRvLip_response_rejectAll_DisputeAll_tests.js
  src/test/functionalTests/tests/common/LiPvLiP_case_offline_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_FullAdmit_PaySetDate_CCJ_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_RejectAll_AlreadyPaid_InFull_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_RejectAll_DisputeAll_Intention_UI_tests.js
  src/test/functionalTests/tests/common/LipvLip_Api_partAdmit_PayByInstallments_tests.js
  src/test/functionalTests/tests/common/LipvLip_UI_PartAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/common/carm_LR_mediation_tests.js
  src/test/functionalTests/tests/common/carm_LiPvLiP_mediation_tests.js
  src/test/functionalTests/tests/common/cp_LiPvLiP_hearing_fee_tests_small_claims_tests.js
  src/test/functionalTests/tests/nonprod/cp_LiPvLiP_orders_small_claims.js
  src/test/functionalTests/tests/prod/LRvLip_response_admitAll_pininpost_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_dateToPayOn_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_partAdmit_repaymentPlan_tests.js
  src/test/functionalTests/tests/prod/LRvLip_response_rejectAll_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PayInstalments_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_FullAdmit_PaySetDate_SSA_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_RejectAll_AlreadyPaid_NotFull_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_AlreadyPaid_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayBySetDate_tests.js
  src/test/functionalTests/tests/prod/LipvLip_Api_partAdmit_PayImmediately_tests.js
  src/test/functionalTests/tests/prod/LipvLip_UI_RejectAll_DisputeAll_Mediation_tests.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_Individual_small_claims_tests.js
  src/test/functionalTests/tests/prod/carm_LiPvLiP_company_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_bundles_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/prod/cp_LiPvLiP_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_bundles_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_case_struck_out_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_latest_update_orders_small_claims_tests.js
  src/test/functionalTests/tests/prod/cp_request_for_reconsideration_tests.js
  src/test/functionalTests/tests/prod/cp_upload_evidence_small_claims_tests.js
  src/test/functionalTests/tests/prod/minti_LiPvLiP_intermediate_track_tests.js
  src/test/functionalTests/tests/prod/minti_LiPvLiP_multi_track_tests.js
  src/test/functionalTests/tests/prod/mt_it_LiPvLiP_tests.js
  src/test/functionalTests/tests/prod/wa/welshResponse_caseworker_request_translation_tests.js
  yarn-audit-known-issues
Labels: ns:civil, prd:civil, fullDeploy, enable_keep_helm, rel:civil-citizen-ui-pr-5852

#5875 DTSCCI-1892 reduce em log
  charts/civil-citizen-ui/Chart.yaml
  charts/civil-citizen-ui/values.preview.template.yaml
Labels: ns:civil, prd:civil, fullDeploy, rel:civil-citizen-ui-pr-5875
