Repository hmcts/civil-citizen-ui, pull requests merged in 2025-06, with the labels that each got.

#6175 DTSCCI-2185 adding protection when trimming doctype
  .gitignore
  src/main/services/features/caseProgression/caseProgressionService.ts
Labels: ns:civil, prd:civil, fullDeploy, stale, enable_keep_helm, rel:civil-citizen-ui-pr-6175

#6220 CIV-16882 Delay notifications and visibility of 'Decision on Reconsid…
  src/main/common/models/document/documentType.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/services/features/dashboard/ordersAndNoticesService.ts
  src/test/unit/services/features/dashboard/ordersAndNoticesService.test.ts
Labels: ns:civil, prd:civil, fullDeploy, runFailedTestFiles, rel:civil-citizen-ui-pr-6220

#6274 CIV-17178 Implement Welsh party banner
  src/main/common/models/claim.ts
  src/main/modules/i18n/locales/cy.json
  src/main/modules/i18n/locales/en.json
  src/main/routes/features/dashboard/claimSummaryController.ts
  src/main/routes/features/dashboard/claimantDashboardController.ts
  src/main/views/features/dashboard/claim-summary-redesign.njk
  src/main/views/features/dashboard/dashboard.njk
  src/main/views/macro/welsh_party_banner.njk
  src/test/unit/routes/features/dashboard/claimSummaryController.test.ts
  src/test/unit/routes/features/dashboard/claimantDashboardController.test.ts
Labels: ns:civil, prd:civil, fullDeploy, runFailedTestFiles, rel:civil-citizen-ui-pr-6274
